### ISSUE TITLE
Allow/Deny fluidcontent elements for certain users/groups

### ISSUE THREAD

**Issue by mangopulp** [FluidTYPO3/flux#1011]
Using the "enable" argument of "FormViewHelper" dynamically with "{f:be.security.ifHasRole(role:6, then:1, else:0)}"  or "{v:security.allow(backendUserGroup:6,then:1,else:0)}" is not possible

EXAMPLE:
```html
<flux:form id="carousel" label="Carousel" enabled="{f:be.security.ifHasRole(role:6, then:1, else:0)}" options="{group:'Structure', icon:'{f:uri.resource(path:\'Icons/Content/Carousel.gif\')}', Fluidcontent: {sorting: 2}}"></flux:form>
```

**Comment by NamelessCoder** [comment]
Hi @mangopulp - this flag (and other options for flux:form) currently do not support dynamic values. The configurations get cached as TSconfig, PHP, TypoScript etc.

However, a solution is coming that allows you to restrict fluidcontent via user/group ACL.
