### ISSUE TITLE
[TYPO3 7] Grid Widget doesn't work

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#1018]
Hey,

I have the problem that the grid widget doesn't render my defined

    <flux:grid>
        <flux:grid.row>	
            <flux:grid.column colspan="12" colPos="0" name="Content" label="{f:translate(key: 'content')}" />   
        </flux:grid.row>
    </flux:grid>

inside the Configuration section. It only shows "***Fluid Content***" inside the content element in the backend.

In my Preview section I have

    <f:section name="Preview">
        <flux:widget.grid />
    </f:section>

Can someone reproduce this? I copied the example TwoColumns.html of the manual but it didn't work too.

**Comment by NamelessCoder** [comment]
Hi Marvin,

Please see https://fluidtypo3.org/blog/news/coming-changes-in-flux-72.html which explains all.

**Comment by MarvinRudolph** [comment]
Oh thanks! I didn't read it. So the grid of the content element should be rendered automatically if there is a grid in the template? I did that before and couldn't get any column of that content element in the backend. Or do I missunderstand something?

**Comment by toh82** [comment]
@NamelessCoder from the blog article I don't get what else I can use to have the backend grid. Would be cool if there is an explanation or a how to update/refactor

**Comment by TheNaderio** [comment]
@toh82 you don't Need `<flux:widget.grid />` any more. Define the grid in configuration and you are ready to go.

**Comment by toh82** [comment]
@TheNaderio Uhm, currently can't imagine what exactly that means, but thanks for the hint

**Comment by cedricziel** [comment]
In your Content/Page/$otherProvider templates, go through the `Preview` sections and remove the following tag: `<flux:widget.grid />`

Done. - If not, please open a new issue.

:)
