### ISSUE TITLE
flux:form.variable: allow dot-separated paths

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1025]
It'd be nice if I could use 

    <flux:form.variable name="Fluidcontent.allowedContentTypes" value="Vnd.Ext:File.html"/>

which is in my eyes more readable than

    <flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'Vnd.Ext:File.html'}"/>

what I currently have to use.

**Comment by NamelessCoder** [comment]
Makes sense. We would be directly assigning values in an ad-hoc created array because the parent array may or may not exist, but I don't see a problem with that approach.
