### ISSUE TITLE
Problem with flux:field.inline.fal when open a inline record panel in TYPO3 7.6

### ISSUE THREAD

**Issue by monosize** [FluidTYPO3/flux#1033]
Working with patch https://review.typo3.org/#/c/44914/.

if you try to open an inline fal record panel, then the content is not correctly loaded via ajax. 

Not OK: Using ```<flux:field.inline.fal .../>```

![image](https://cloud.githubusercontent.com/assets/1583746/11448597/b7dbdd5c-955b-11e5-9c6b-aadfe28927ed.png)

OK: standard image element with link, description and cropping

![image](https://cloud.githubusercontent.com/assets/1583746/11448586/980ace84-955b-11e5-878d-24f3e2e86218.png)

------

what I found out is...

![image](https://cloud.githubusercontent.com/assets/1583746/11448676/4b37d85c-955d-11e5-9901-14c84fb55f3d.png)

![image](https://cloud.githubusercontent.com/assets/1583746/11448758/f3af29c0-955f-11e5-8d9b-2db4e37cfb30.png)

the parent flexform configuration is not created.

The only known value is the uid of the tt_content record in the databaseRow array.
We need a dataProvider that can create the data based on the uid of the tt_content table.
The dataProvider must verify, that the record is a fluid content element.

@NamelessCoder: Is there such a function in the flux cosmos, that we can use?

**Comment by julianxhokaxhiu** [comment]
+1 having the same issue here on 7.6 LTS

Damn, what's wrong with T3 main Devs?

**Comment by cedricziel** [comment]
Calm down.

**Comment by NamelessCoder** [comment]
Omelet, eggs @julianxhokaxhiu ;)

**Comment by julianxhokaxhiu** [comment]
Btw with that patch anyway is not working. I though that would be the fix but it's not. Any suggestion rather than eggs to me? :P

**Comment by NamelessCoder** [comment]
@julianxhokaxhiu I do :)

Follow https://github.com/FluidTYPO3/flux/issues/1013 and https://review.typo3.org/#/c/44914/. The former is this same issue, already reported, but with a lot more information attached (so I will close this issue and keep the other open). The latter is the first of what I expect will be two or three patches total which fix the regression in TYPO3 itself. First to actually trigger the parent config resolving, second to retrieve the $row from database when it only contains a UID.

**Comment by monosize** [comment]
Problem is resolved with commit TYPO3/TYPO3.CMS@e6727c8e9ae4cb912bc2d59c79758fb32370641c
