### ISSUE TITLE
Redirects ignored

### ISSUE THREAD

**Issue by morinfa** [FluidTYPO3/flux#1039]
Hi,

In AbstractFluxController->callSubControllerAction(), the call to processRequest is ignoring an eventual StopActionException (thrown by \TYPO3\CMS\Extbase\Mvc\Controller\AbstractController\redirectToUri() function)
So a call to redirect function in the PageController doesn't work.
My current workaround is to wrap the call to processRequest in a try/catch in callSubControllerAction function :
```
		try {
			$potentialControllerInstance->processRequest($this->request, $response);
		} catch (\TYPO3\CMS\Extbase\Mvc\Exception\StopActionException $ignoredException) {
		}
```
But should it be fixed in Flux source ? (I'm using Flux 7.2.1)

Regards,
Fabrice

**Comment by NamelessCoder** [comment]
Hi Fabrice,

It's been a while but this exception is now caught and ignored. The fix will be included in the next TER release of Flux!

Thanks for your patience :)
