### ISSUE TITLE
Fatal error: Maximum function nesting level of XXX reached if sheet with name "options" exists

### ISSUE THREAD

**Issue by galoppi** [FluidTYPO3/flux#1041]
If you have a sheet named "options" then you get a fatal error due to an endless recursion in FluidTYPO3\Flux\Form\AbstractFormContainer->get() after clicking a page icon in TYPO3 BE.
Tested in TYPO3 7.6.0 with flux 7.3.0.

Form-Template:
```
   <f:section name="Configuration">
        <flux:form options="{group:'Struktur-Elemente'}"
                   id="gridElement"
                   label="Farbcontainer"
                   icon="/typo3conf/ext/sms_boilerplate/ext_icon.gif"
                   description="Vollbild-Container">

            <flux:form.sheet name="options" label="Optionen">
            </flux:form.sheet>
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column name="column" label="Containerinhalte" style="width:100%; font-weight: bold;">
                        <flux:form.content name="column" />
                    </flux:grid.column>
                </flux:grid.row>
            </flux:grid>
        </flux:form>
    </f:section>
```
If you rename the sheet f.e. to "options2" then everything is ok.

**Comment by jmverges** [comment]
I can confirm this, Iirc maybe there is another closed issue adverting about this.

**Comment by NamelessCoder** [comment]
I'm not sure why, but I still cannot reproduce this. I copy @galoppi's example 1:1, put it in a new FCE template and use that in any way I can think of; add new, edit, copy, edit that, move it, delete it, undelete it... all works, no recursion detected.

This is indeed on the development branch of Flux?

**Comment by NamelessCoder** [comment]
PS: a note about the example template above, it contains a now redundant `flux:form.content`. This ViewHelper no longer is required to define content areas in content elements like it was before; it is changed to be a shortcut that creates a grid with a single row and column (so you can avoid the `flux:grid` when you only have one area to define). In your template you can simply remove it without problem - or you can replace the entire `flux:grid` with a single `flux:form.content` with the name, label etc. you want.

This should *not* be related in any way to the recursion issue. I just thought I'd mention it ;)

**Comment by jmverges** [comment]
Ah, sure, maybe was because of that

**Comment by galoppi** [comment]
I tested this now with current development branch and there the behaviour is also reproducible.
It seems to be a conflict with flux/Classes/Form.php:96 where a default sheet with name="options" is defined.
Removing the deprecated `flux:form.content` doesn't change the behaviour.

Here is the full template:
```
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
{namespace flux=FluidTYPO3\Flux\ViewHelpers}

<f:layout name="Content" />
<div xmlns="http://www.w3.org/1999/xhtml"
        xmlns:flux="http://fedext.net/ns/flux/ViewHelpers"
        xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

    <f:section name="Configuration">
        <flux:form options="{group:'Struktur-Elemente'}"
                   id="gridElement"
                   label="Farbcontainer"
                   icon="/typo3conf/ext/sms_boilerplate/ext_icon.gif"
                   description="Vollbild-Container">

            <flux:form.sheet name="options" label="Optionen">
            </flux:form.sheet>
            <flux:form.sheet name="grid" label="Container">
                <flux:field.checkbox name="hasbow" label="Zeige Bogen">
                    <!-- tag content - may be ignored! -->
                </flux:field.checkbox>
                <flux:field.select
                    label="Hintergrundfarbe"
                    name="bgcolorclass"
                    items="{
                        1: {0: 'Weiß',1: 'u-brandBgColor-tertiary'},
                        2: {0: 'Blau (#EDF3FB)',1: 'u-brandBgColor-secondary'},
                        8: {0: 'Grau (#A8A8A8)',1: 'u-brandBgColor-quaternary'},
                        9: {0: 'Dunkelgrau (#848484)',1: 'u-brandBgColor-quinery'}
                    }"
                    />
            </flux:form.sheet>
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column name="column" label="Containerinhalte" style="width:100%; font-weight: bold;">
                    </flux:grid.column>
                </flux:grid.row>
            </flux:grid>
        </flux:form>
    </f:section>

    <f:section name="Preview">
        <b>Farbcontainer</b>
        <p>Hat Bogen: <f:if condition="{hasbow} == 1"><f:then>Ja</f:then><f:else>Nein</f:else></f:if></p>
        <flux:widget.grid />
    </f:section>

    <f:section name="Main">
        <div class="contentStage <f:if condition='{hasbow} == 1'>hasBow</f:if> {bgcolorclass}">
            <f:if condition="{hasbow} == 1">
                <div class="bluebow">
                    <img src="typo3conf/ext/sms_boilerplate/Resources/Public/Images/bow.png" alt="Bogen">
                </div>
            </f:if>
            <div class="g">
                <div class="gi u-w1/1">
                    <flux:content.render area="column" />
                </div>
            </div>
        </div>
    </f:section>
</div>
```

**Comment by NamelessCoder** [comment]
Thanks for the template Alex! Finally helped me reproduce the problem and put an end to it ;)

**Comment by NamelessCoder** [comment]
FYI, in order to reproduce this, the template had to be viewed in a way that caused Form data transformation to take place, which is why I did not detect it to begin with. It sounds obvious now, but it would not manifest unless the record has actually been saved with some values.
