### ISSUE TITLE
Delete object not work in 6.2.16 

### ISSUE THREAD

**Issue by mhirdes** [FluidTYPO3/flux#1045]
Hey I update a website with flux 7.2.3 from TYPO3 6.2.15 to 6.2.16. Now I can't delete an object in a flux flexform beacuse of an JS error.

**Comment by NamelessCoder** [comment]
Hi @mhirdes - you need to report this one to the TYPO3 bug tracker. Flux does not change the object deletion javascript so if that errors out after a core update, it's the fault of the core update, not Flux.

**Comment by mhirdes** [comment]
https://forge.typo3.org/issues/72325 thanks
