### ISSUE TITLE
FluidcontentCore form render is different with 7.3.0 or development

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#1052]
FluidcontentCore with Flux 7.3.0:
![image](https://cloud.githubusercontent.com/assets/2902073/12078409/7e2e5cec-b211-11e5-8474-69c08be3fc3a.png)

FluidcontentCore with Flux development:
![image](https://cloud.githubusercontent.com/assets/2902073/12078414/b93934ba-b211-11e5-9eb9-6e68398c42c2.png)
![image](https://cloud.githubusercontent.com/assets/2902073/12078416/d0ad85b0-b211-11e5-8977-600dd05b0115.png)

The checkboxes are missing, any clue?

**Comment by NamelessCoder** [comment]
Fixed with https://github.com/FluidTYPO3/flux/commit/cf06c0fd10f55865c7780395cbf47a5e1aab4495
