### ISSUE TITLE
FAL image saving

### ISSUE THREAD

**Issue by kersten** [FluidTYPO3/flux#1055]
Sorry for opening another issue for this. I already commented here on a closed issue: #1013 

I don't know if this has something todo with this issue, but after applying the patch, selecting an image works. But when I save the element, the fal element is empty again and the image was not saved.

**Comment by DenisMir** [comment]
So am I correct that there is no solution at the moment? (except patching TYPO3 core and fluidpages)

**Comment by NamelessCoder** [comment]
No patch is required for fluidpages. It's only the core regression preventing this.

**Comment by robsonrobi** [comment]
What must i do, do get it working, can someone provide the patch for the core, please

**Comment by kersten** [comment]
@robsonrobi I think this issue will help you  #1013

**Comment by NamelessCoder** [comment]
Will close this issue since #1013 contains all the relevant information. We *still* need a patch for the core regression for this one. Such a patch would solve the entire issue.
