### ISSUE TITLE
Plugin options are not shown ???

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#1056]
Hi guys, 

I just found this working with ext:news

![image](https://cloud.githubusercontent.com/assets/2902073/12141459/b14ce7aa-b46f-11e5-9d7e-8e7889254e53.png)

cms: ~7.6
FluidTYPO3 development
ext news dev-master

if any of you can confirm or deny it I could appreciate it

**Comment by NamelessCoder** [comment]
Do you have flux_capacitor installed by any chance?

**Comment by NamelessCoder** [comment]
I think I may have found the reason - https://github.com/FluidTYPO3/flux/commit/6a7a98bb85dc4ada26b533ec165429c5604f9773. Please confirm if that solves it ;)

**Comment by jmverges** [comment]
I didn't get the time to "capacite" a fresh install by now :(.
After pulling the commit (clearing caches even rm -r temp) nothing changes

**Comment by jmverges** [comment]
closed via #1059
