### ISSUE TITLE
[BUG] flux:form.sheet

### ISSUE THREAD

**Issue by grimmcreative** [FluidTYPO3/flux#1064]
If i want to use more then 1 flux:form.sheet and put in some text inside a simple flux:form.field
the page configuration is no more access able.

Error:
PHP Warning: Illegal string offset 'testinput' in /var/www/.../typo3_src-7.6.2/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaFlexProcess.php line 466

**Comment by Lirrec** [comment]
I have a similiar issue and have tracked down some more details.
I use the latest fluidpages, flux and vhs from the extension repository on t3 7.6.2.

The Error Message is:
```
Warning: Illegal string offset 'settings.columncount' in .../typo3/typo3_src-7.6.2/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaFlexProcess.php on line 466

Fatal error: Cannot use string offset as an array in .../typo3/typo3_src-7.6.2/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaFlexProcess.php on line 466
```

This seems to happen under some very strange circumstances:
I have a second flux:form.sheet in my configuration, which contains multiple values.
If **all** fields in the sheet are left unchanged they will inherit their values from the parent page.
This will create the following content in the database ( 'tx_fed_page_flexform' column of the 'pages' table ):
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="columns">
            <language index="lDEF">
            </language>
        </sheet>
    </data>
</T3FlexForms>
```
This configuration produces the error mentioned above when the sheet is about to be rendered.
Workaround for now: If i add a single field with *inherit* set to *false* this field will always be saved in the database. The resulting *tx_fed_page_flexform* will look like this:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="columns">
            <language index="lDEF">
                <field index="dummy">
                    <value index="vDEF">empty..</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```xml

**Comment by grimmcreative** [comment]
can confirm this

**Comment by mirkokaufmann** [comment]
I run into the same issue while upgrading a project from 6.2 to 7.6.3: Older pages longer not updated with missing flexform options in database throw the error which can be read above.

Flux: 7.3.0
Fluidpages: 3.4.0

**Comment by MaxGTR** [comment]
Same problem for me, if fields are not filled I have an error when I save the page properties:
"Cannot use string offset as an array"

Because in database "sheet" element is empty:
<sheet index="ctc.desktop">
            <language index="lDEF">
            </language>
</sheet>

Is there a fix for this ?

**Comment by typo3ua** [comment]
Same problem for me

`< flux:form.sheet name="n1" label="n1" >    < flux:field.input name="l1" label="l1" />< /flux:form.sheet >< flux:form.sheet name="n2" label="n2" >    < flux:field.input name="l2" label="l2" />< /flux:form.sheet >< flux:form.sheet name="n3" label="n3" >    < flux:field.input name="l3" label="l3" />< /flux:form.sheet >`

**Comment by typoworx-de** [comment]
Still having the same problem here for Migration zu TYPO3 8!!!

> 	<f:section name="Configuration">
> 		<flux:form id="standard" label="Standard page" options="{icon:'EXT:fluidtemplates/Resources/Public/Icons/Page/Standard.gif'}">
> 			**<flux:field.checkbox name="startpage" label="Startpage" />**
> 		</flux:form>
> 		<flux:grid>
> 			<flux:grid.row>
> 				<flux:grid.column colPos="1" name="top" label="Top" />
> 			</flux:grid.row>
> 			<flux:grid.row>
> 				<flux:grid.column colPos="0" name="main" label="Content" />
> 			</flux:grid.row>
> 		</flux:grid>
> 	</f:section>

Removing this part "removes" the Exception:
> <flux:field.checkbox name="startpage" label="Startpage" />

Exception due to editing page-properties:

Uncaught TYPO3 Exception
Cannot use string offset as an array 
> Error thrown in file
> [...]/public/typo3_src/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaFlexProcess.php in line 560.

Anyone knows how to fix this?!

**Comment by typoworx-de** [comment]
I was able to fix the issue for my case (migration to TYPO3 v.8 with Flux)

MySQL Fix FLUX-FlexForms in DB
> UPDATE `pages` SET tx_fed_page_flexform="" WHERE tx_fed_page_flexform REGEXP "<data>[\n \t]*</data>";
> UPDATE `pages` SET tx_fed_page_flexform_sub="" WHERE tx_fed_page_flexform_sub REGEXP "<data>[\n \t]*</data>";

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/93abfaf043a6dbf5b491e55c103b8757540e4415 - FlexForm data in handled record types will be truncated to remove empty wrappers / remove the entire value if data array is empty. No leftover XML will be present, except for variables which are not specified in DS (standard TYPO3 variable retention takes place).
