### ISSUE TITLE
Backend performance issue

### ISSUE THREAD

**Issue by almirbi** [FluidTYPO3/flux#1068]
When there are flux content elements added to the page, the loading of the page view gets really slow. When there are only few elements it's not that noticeable, but we have pages with 10-20 flux content elements per page, and some of them take more than 7 seconds to load.

http://pokit.org/get/?1f5e9f86006875a1c8db4e8e5a3f9fdd.jpg

The first call is with a flux content element ( just one ) and the second call is without any flux elements ( same page ).

I compared the pages where there are a lot of flux CE and pages where there are only the default CE ( text, text with pics etc. ). Pages with only default CEs, load much faster even though the number of CEs is higher or the same as on the pages with flux CEs.

I tried to make the preview of the CE smaller ( plain, hardcoded text ), but it does not change anything.

e.g.: 

```html
<f:section name="Preview">
  TEST
</f:section>
```

**Comment by marctusch** [comment]
Hi there, 

any news or hints on this? 

We've got a client's page with 50+ Flux-CEs (Grids, Accordions etc.)... backend loading takes up to 45 seconds in page view, pretty ugly and no idea where to start debugging :-1: 

Best regards
Marc

**Comment by NamelessCoder** [comment]
Pull request merged - thanks @almirbi!
