### ISSUE TITLE
TYPO3[7.6.2] Inline FAL image wrong in backend

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#1069]
Hey,

I tried to use the inline FAL image field of flux inside my FCE.
My code looks like: 
`<flux:field.inline.fal name="backgroundImage" multiple="true" maxItems="1" collapseAll="true" />`

But in my backend form it gets rendered like this and I can't upload any image.
![wrong-fal-field](https://cloud.githubusercontent.com/assets/6840287/12828398/dd23f5fe-cb84-11e5-8021-3f43baed6c0b.jpg)

Do I need anything else like a attribute or do I need a TYPO3 core patch to fix this?

Thanks in advance!

**Comment by NamelessCoder** [comment]
Nearly certain you face https://github.com/FluidTYPO3/flux/issues/1013 and will have errors in your XHR console debug log in your browser after clicking the button. Yes, we await a core patch for this one.
