### ISSUE TITLE
unable to leave flux:field.relation as empty

### ISSUE THREAD

**Issue by moger-xx** [FluidTYPO3/flux#1070]
When using a flux:field.relation viewhelper, for example:

`<flux:field.relation name="featuredDownload" table="tx_myext_domain_model_download" maxItems="1"> `

the resulting dropdown always shows the first possible option as default, instead of an "empty" value. So it is impossible to leave the field empty when saving the page properties. As a side effect, the user can't tell if it's not set or if the first option is actually selected (stored in DB).

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin vom Freitag, 4. Februar 2016 bis und mit Dienstag, 9. Februar 2016 Skiferien und Fasnachts bedingt abwesend und gerne am Mittwoch, 10. Februar 2016 wieder für Sie da.
 
Die Nachricht wird nicht weiter geleitet! In ganz dringenden Fällen bin ich auf dem Mobile zeitweise erreichbar.


Einen guten Tag wünscht

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by moger-xx** [comment]
One Addition: the `<flux:field.select>` allows an empty option. However, I miss a good example for using a query for the "items" option. Also see #679

**Comment by NamelessCoder** [comment]
See `emptyOption` argument for `flux:field.select` - I think `flux:field.relation` with `renderMode="selectSingle"` also supports that one, so we could add that to `flux:field.relation` with a note that it only applies to selectSingle.

**Comment by NamelessCoder** [comment]
Regarding using a query to fill values in `flux:field.select` that's not intended, but you could write a ViewHelper that returns the items and use that inline in `items` attribute. However, you are supposed to use `flux:field.relation` or `flux:field.multiRelation` with various conditions and matching fields as supported by the `select` TCA type in various rendering modes.

**Comment by moger-xx** [comment]
Yes, adding an emptyOption to flux.field.relation would be a safe and easy solution. Unfortunately I was not able to archive that on my own, so I'd highly appreciate a patch for flux 7.2.
