### ISSUE TITLE
Cannot add / save more child-objects (flux:form.object)

### ISSUE THREAD

**Issue by christianbaer** [FluidTYPO3/flux#1072]
I have a fluidcontent-Element containing a flux:form.object.

I only can save a certain number of child-elements (32), after that is produces an error: "Validating the security token of this form has failed"

Even when I suppress the FormValidation (override function validateToken() in typo3/typo3/sysext/core/Classes/FormProtection/AbstractFormProtection.php ) the new child-elements are not saved.

Maybe there is a limitation of the according field (pi_flexform)?

**Comment by christianbaer** [comment]
I have TYPO3 6.2.15, flux 7.2.3, fluidcontent 4.3.3

the strange thing is: I cloned the page for debugging to my local system (db & files), there is no such error and I can an more childs... °_° ???

has anyone an idea?

**Comment by NamelessCoder** [comment]
It's very likely your post data size exceeds `MAX_POST_SIZE` - see https://github.com/FluidTYPO3/flux#known-issues

**Comment by NamelessCoder** [comment]
Will close this one on a huge hunch that max post size and/or max post fields limits is the problem as described in the link above. If that's not the case, as always, let me know and I'll reopen.
