### ISSUE TITLE
Resolve to custom flux controller without matching action

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/flux#1081]
I have a custom ContentController in my extension that should provide data for **all** my content elements. For this I created an initializeAction (which extbase always calls). But flux ignores my CustomController because I don't have a specific action for all of my content elements.

Two suggestions:
1. Remove the check for a matching action method completely from the Resolver.
or
2. Resolve the custom ContentController if it contains an initializeAction

**Comment by NamelessCoder** [comment]
This sounds like a fair enough suggestion - I can see the use case for overriding various initialize methods on the controller without necessarily needing an action. If you create a patch please make one for the first option above - use the foreign controller if detecting the class exists, drop check for matching action ;)
