### ISSUE TITLE
Images resize not working in Preview, thumbnails not working, file reference - to store images

### ISSUE THREAD

**Issue by vinayn** [FluidTYPO3/flux#1083]
I am facing the following issues:

1) In the Preview section I am not able to resize the image . I have tried image resize as below. PHP extension 'gd' is also enabled.

`<f:image src="{object.image}" treatIdAsReference="1"  alt="{object.imagealt}" width="100" height="100" minWidth="100" minHeight="100" maxWidth="100" maxHeight="100" /> 	`

2) Using the below code I am able to upload images but the thumbnail is not shown. The reason might be that I am using localhost/{projectname}. The thumbnail preview has to work as there are lot of intranet based projects ( {IP}/{projectname})
```
 <flux:field.file name="foo" label="NULL" showThumbnails="1">
</flux:field.file>
```
3) The physical path of the images are stored as per the below tag . File reference has to used to store the images and not the physical path of the image. The reason is that in future if I have to generate mobile based images or getting the list of all the images used in the website(for clean up activity) the file reference will be handy.

```
 <flux:field.file name="foo" label="NULL" showThumbnails="1">
</flux:field.file>

```

**Comment by NamelessCoder** [comment]
The native image ViewHelper suffers from limited support in backend mode - you could have more luck with v:image. Yes, your hostname must be a proper hostname for back-reference detection to work (or you must have manually configured every aspect of the TYPO3 site to run from a subfolder - that's not supported by us but it is possible). The flux:field.file will always store filenames (it's a legacy type). Use flux:field.inline.fal instead.
