### ISSUE TITLE
Content area linking to the fields in the flux field

### ISSUE THREAD

**Issue by vinayn** [FluidTYPO3/flux#1084]
In the below code each **tab title** is linked to the **content area** and shown in the preview. The problem starts if one of the **tab title** is deleted in the fluid content element. The order of the content area changes and the content of the deleted **tab title** title will be there and the last content area will be removed. To solve this issue I am planning to use the id of object field as `<flux:grid.column name="{object.id}" />`. I tested it and its working fine .Is this the correct way or is there any other better way.
```
<flux:grid>
			<flux:grid.row>
				<f:if condition="{tabs}">
					<f:for each="{tabs}" as="tab" iteration="iteration">
						<flux:grid.column name="content.{iteration.index}" label="{tab.tab.title} Tab {iteration.cycle}" style="width: {v:math.division(b: '{tabs -> f:count()}', a: 100)}%">
							
						</flux:grid.column>
					</f:for>
				</f:if>
			</flux:grid.row>
		</flux:grid>
```

**Comment by NamelessCoder** [comment]
Use `{object.id}` as (part of) the column name and the related elements will "stick" to the area in which they were created. That's the only way to achieve what you want.
