### ISSUE TITLE
colPos 18181 after moving localized element

### ISSUE THREAD

**Issue by EnzephaloN** [FluidTYPO3/flux#1087]
Installed FLUX 7.2.3 on TYPO3 6.2.19

1.) localize an element ("copy default content") => colPos=0
2.) open new localized element => colPos=0
3.) move new localized element to other position and re-open it => colPos=18181

**Comment by DenisMir** [comment]
I can not confirm this error with 7.6.4 LTS and the latest developement version of flux.

**Comment by NamelessCoder** [comment]
Please see my comment on https://github.com/FluidTYPO3/flux/issues/1078#issuecomment-208099964 for how to approach reports/fixes that concern unsupported versions of TYPO3. And keep track of currently open issues because this one had around a handful duplicates ;)
