### ISSUE TITLE
Fatal error while clearing caches in the install tool with TYPO3 7.6

### ISSUE THREAD

**Issue by sascha-schieferdecker** [FluidTYPO3/flux#1088]
TYPO3: 7.6.4
flux: cc384df

After clicking on "clear all caches", the following error occurs:

Detected Fatal Error
Call to undefined method TYPO3\CMS\Extbase\Configuration\ConfigurationManager::getCurrentPageId() in /xxx/xxx/typo3conf/ext/flux/Classes/Service/FluxService.php on line 355

**Comment by NamelessCoder** [comment]
Indicates that extension configuration files were not properly cleared, causing our required configuration manager implementation to not be registered. Clear all caches from inside the install tool and the problem should go away (you sometimes need to do this when updating Extbase-based extensions) - if it doesn't, please make sure you don't use any extensions which force another configuration manager implementation!

Improvements in TYPO3 may allow us to remove this required implementation at some point, but currently it is required and must not be overridden.

**Comment by sascha-schieferdecker** [comment]
This happens within the install tool. I have uninstalled all 3rd party extensions except flux, vhs, fluidcontent, fluidpages and the provider extension. The error still occurs.

**Comment by NamelessCoder** [comment]
Please try this one again with an updated Flux repository and most recent fluidpages/fluidcontent. I'm unfortunately not able to reproduce this issue so I have to assume it's solved since then (a failure with this method should fail on *any* site, php version etc).
