### ISSUE TITLE
[TYPO3 7.6.4] No auto translation?

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#1090]
Hey,

I updated all extensions (flux, fluidcontent, fluidpages & vhs), TYPO3 to 7.6.4 and created a new provider extension. Now my whole language labels don't get translated automatically with the path "flux.XYZ". 
Only the path is shown f.e. "LLL:EXT:provider/Resources/Private/Language/locallang.xlf:flux.fceMain.columns.content".

Before my update it worked fine. Did I miss something or is this a bug?

Thanks in advance!

**Comment by NamelessCoder** [comment]
To make sure I understand the issue - before, you were using `label="flux.foobar"` and expecting that to be expanded to `LLL:EXT:yourext/Resources/Private/Language/locallang.xlf:flux.foobar`?

If that is correct then there is one bug solved and another performance related task that could affect you:

* Labels must now contain `LLL:` as prefix to be considered actual prefixes.
* Both directly specified and automatic LLL paths are no longer translated before being passed to TCA and other functions (which already understand the LLL format).

Could be that you're affected by the first item - in which case you've been relying on a bug. To fix it, prefix `LLL:` to your shorthand label reference and you should be good to go again ;)

**Comment by MarvinRudolph** [comment]
Nope I didn't use `label="flux.foobar"`. I only used `name="foobar"` and this worked fine before because the auto path thing. 

Do I have to use `label` now with the whole path and `LLL:` before it?

**Comment by fspeckmaier** [comment]
Hey,

we're using flux from the dev-development-branch and experience quite the same trouble on Typo 7.6.3. 

`    <flux:grid>
                <flux:grid.row>
                    <flux:grid.column name="content" label="LLL:boxEmpty.content" />
                </flux:grid.row>
            </flux:grid>
`

boxEmpty.content does not longer resolve to the string of the langfile, it only shows the complete path like described above.

**Comment by NamelessCoder** [comment]
When you fill a label that *is not* prefixed with `LLL:` you should see that label appear directly - e.g. no attempts to build an automatic reference. It would appear there's a bug in that area but I wasn't able to tell what it is by reading the code. Need to do some further debugging.

**Comment by MarvinRudolph** [comment]
Problem in the content area is fixed but same thing exists f.e. in page layouts tab of a page. 
Or is this a fluidpages problem?
