### ISSUE TITLE
flux:field.inline.fal: In case of using "collapseAll" link field is gone

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/flux#1092]
Hi,

I use `<flux:field.inline.fal name="settings.images" multiple="TRUE" maxItems="10" label="Sliderbilder" />` for small slider FCE. Everything is fine but when I change it to `<flux:field.inline.fal name="settings.images" multiple="TRUE" maxItems="10" label="Sliderbilder" collapseAll="1" />` the input-fields for image links and alt are gone. Is that on purpose? I tried to use the collapseAll option to have less scroll action and a better overview. That is working but then I can't put a link to the images... 

I use TYPO3 7.6.4 and the patched fluidcontent version (error 500 patch from Monosize)

Thank you and greetz

**Comment by NamelessCoder** [comment]
Hi Markus,

Please report this on the TYPO3 issue tracker. It would be an issue with any FlexForm source when using `collapseAll` on an IRRE.

Note that this could be an issue related to https://github.com/FluidTYPO3/flux/issues/1013 (see bottom responses for connections to known issues in TYPO3).
