### ISSUE TITLE
Flux Controller Pipe Example

### ISSUE THREAD

**Issue by oliverbeck** [FluidTYPO3/flux#1095]
Hi all

I've just read about the pipes in flux and try to understand them. Are there any examples about controller pipes? 

Kind regards, Oliver

**Comment by NamelessCoder** [comment]
Although I'm a bit late to the party here: the Outlet/Pipe feature has been restored and cleaned up a bit by https://github.com/FluidTYPO3/flux/pull/1837. An example implementation will be added to https://github.com/FluidTYPO3/test_provider_extension.
