### ISSUE TITLE
Documentation: link displayCond attribute to typo3 docs

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1096]
It would be helpful if the `displayCond` attribute documentation would link to https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Index.html#displaycond

Example: https://fluidtypo3.org/viewhelpers/flux/master/Field/TextViewHelper.html

But I have no idea how to achieve this

**Comment by NamelessCoder** [comment]
Thanks Christian - if you want to do this for other properties too that would be most appreciated. I'm sure you can use the linked commit as all the guide you need, but if not, feel free to ask me anytime ;)
