### ISSUE TITLE
several provider extensions on a multi domain site

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#1097]
hi there,
i urgently search a solution for the problem, that on a multi momain site always ALL page layouts and fces from ALL providerextensions  are shown in a single domain tree.

i read this issue, but id didn't work for me.
https://github.com/FluidTYPO3/flux/issues/839

any suggestions?

best regards blueamerican

**Comment by cedricziel** [comment]
What did you try and what didnt work?

**Comment by blueamerican** [comment]
i have a two domain website (two separate trees).

i have two provider extensions, one for each tree.

in each tree the specific provider extension is inludes as a static template. 

my problem is, that all fces and all page layouts are shown in each tree.

Therefore i tried the following things, with no sucess.

i removed the static include template and wrote the Template/Partial/Layout pathes in TS.

i tried georgs solution:
in ext_localconf.php of providerextension_2 i wrote:

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScript($_EXTKEY, 'setup', '
    plugin.tx_providerextension_2.view {
        templateRootPaths.10 = EXT:flux/Resources/Private/Templates/
        partialRootPaths.10 = EXT:flux/Resources/Private/Partials/
        layoutRootPaths.10 = EXT:flux/Resources/Private/Layouts/
    }
');
```

The same in providerextension_2/Configuration/TypoScript/setup.txt

no reaction in the backend.

**Comment by cedricziel** [comment]
@NamelessCoder am I right the mentioned workaround is just for the typoscript and respectively just for the frontend views so a manual intervention with PageTS should solve it?

**Comment by NamelessCoder** [comment]
PageTSconfig manipulation can take care of the content elements' availability - but for page templates you have to set the `enabled` property via `plugin.tx_yourext.forms.$formId.enabled = 0` when you do not want a template to be available.

**Comment by blueamerican** [comment]
is there an example/explanation for the syntax?

**Comment by NamelessCoder** [comment]
For the pageTSconfig you can check the string the cache stores in the `cf_fluidcontent` table (or the official TYPO3 pageTSconfig reference), for the TypoScript to disable just use the syntax from my previous comment.

**Comment by NamelessCoder** [comment]
Closing the issue - hope you found the right settings for your site! If not, please drop by the support chat for a more realtime Q-and-A about the settings :)
