### ISSUE TITLE
My styling does not work in backend layout

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/flux#1098]
I have the flux 7.3.0 and TYPO3 7.6.4 but my styling does not work in backend layout.
~~~
<flux:grid.column colPos="0" colspan="3" style="width: 100%; background-color: green; border-top: 10px solid green;" name="section" label="Label name" />
~~~
A similar problem ... #553 

Can anybody help me?

**Comment by NamelessCoder** [comment]
`style` on `flux:grid.column` is only supported for nested content areas (not page columns) and may at some point be removed there, too. To implement custom styles for your backend you should use the TYPO3 core feature of substituting or appending to the default stylesheet (which is shipped in the `t3skin` extension).

Check the docs for that - there are a lot of other things you can style this way!
