### ISSUE TITLE
Language Keys of Page Templates don't render

### ISSUE THREAD

**Issue by gradinarufelix** [FluidTYPO3/flux#1101]
Hello!

I've got an issue in my system: the language fields of the page templates don't render. I checked it out with a earlier version of flux, and then it works, but with the latest 7.3.0 export from GitHub, it doesn't render.

<img width="548" alt="bildschirmfoto 2016-03-15 um 09 45 49" src="https://cloud.githubusercontent.com/assets/4405087/13772204/36c4bada-ea93-11e5-9527-fbf879136341.png">

This is how I have written my labels down in the locallang.xlf:

<img width="377" alt="bildschirmfoto 2016-03-15 um 09 49 41" src="https://cloud.githubusercontent.com/assets/4405087/13772217/483db7e4-ea93-11e5-80e7-51f211af53b6.png">

Flux-Version: 7.3.0

Thanks for any help!

**Comment by NamelessCoder** [comment]
Hi Felix - thanks for reporting! Confirmed, a pull request is currently open for it:

https://github.com/FluidTYPO3/fluidpages/pull/314

We have another issue for this:

https://github.com/FluidTYPO3/fluidpages/issues/313

I don't know if you or Christian created their issue first but I'm taking the liberty of closing this one - you're very welcome to both test the pull request and add any info you think is missing from the other issue.
