### ISSUE TITLE
Column Error FluxGrid in Content Element

### ISSUE THREAD

**Issue by gradinarufelix** [FluidTYPO3/flux#1102]
Hello!

I get an error with an content element in a flux grid in a parent content element. It shows me, that the column of the CE is 'Invalid Value 18181'. If I save the CE, it will turn into an text element.
Does anybody know what the problem could be?

<img width="229" alt="bildschirmfoto 2016-03-15 um 17 07 15" src="https://cloud.githubusercontent.com/assets/4405087/13784740/b306b57a-ead0-11e5-9566-c10b4ad0cb22.png">

**Comment by Shupal** [comment]
maybe related https://github.com/FluidTYPO3/flux/issues/1087

**Comment by NamelessCoder** [comment]
See this search result for some history of the "Invalid value" issue: https://github.com/issues?q=is%3Aissue+user%3AFluidTYPO3+18181+is%3Aclosed

The content element turning into a text element is not related to this - you can test that out by temporarily installing the `fluidpages` extension which should make the "Invalid value" disappear but should have no effect on the type changing. A few things that *could* cause that:

* Incompletely updated DB schema causing row to not be saved if missing field is included in POST.
* Third-party hooks listening for record updates changing the type

If you do narrow it down to Flux being the cause please submit a more detailed error report with more information about your system, extension versions, other installed extensions etc. and we may be able to reproduce it.
