### ISSUE TITLE
[BUG][TYPO3-7.6] Wrong preview markup (sys_language_uid) enables d&d between languages

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/flux#1103]
When creating the page-preview markup a wrong sys_language_uid is used in the languages-view.

Setup:

Extension | Version
------------ | -------------
flux | development branch (2016-03-13; aff30de)
fluidpages | 3.5.0 (5cbb73f)
TYPO3 | 7.6.4 (bd0c7f6)

## Steps to reproduce the issue
1) Create a page with alternative language and open the Page > Languages view.
2) When dragging a ce, all drop areas inside flux-grids in all languages are activated.
## Expected outcome
Only drop areas in the current languages are activated.

**Comment by BenjaminBeck** [comment]
fixed with #1104

**Comment by NamelessCoder** [comment]
Great - thanks for keeping track Benjamin!
