### ISSUE TITLE
Content Element disappears after Drag & Drop into Container content element (but only the FIRST one)

### ISSUE THREAD

**Issue by rhartlein** [FluidTYPO3/flux#1106]
Scenario: When moving a standard content element - using drag & drop -  into another "container" content element featuring a grid, the moved content element disappears in the backend. This only happens when moving a standard content element into an empty "container" element.

When executing the following steps, the moved content element disappears:

1. Create a "Container" content element featuring a grid in Backend
2. Create a standard content element (e.g. Header) next to the "Container" content element (not inside)
3. Move the standard content element into the "Container" content element using Drag & Drop

=> The standard content element disappears in the backend

in the tt_content database table, the following fields are incorrectly set:
tx_flux_column: is NULL
tx_flux_parent: is NULL

4. Fill the database fields manually (e.g. phpMyAdmin) with the right value for column and parent

=> The standard content element appears in the backend as expected

5. Create a second standard content element (e.g. Header) next to the "Container" element (not inside)
6. Move the second standard content element into the "Container" content element using Drag & Drop

=> The second standard content element appears as expected

This has been observed using:
typo3 7.6.4

And the following extensions from the typo3 repository
flux 7.3.0
fluidcontent 4.4.1
fluidpages 3.5.0
vhs 2.4.0

I also tested this using the 4 extensions downloaded from GitHub today (29-03-2016), but the result is the same.

**Comment by BenjaminBeck** [comment]
Hello rhartlein,
i can not reproduce the bug you describe.
Do you have any javascript errors in the backend when using d&d?
What is the column name/id of the  container element?
Maybe you can make a gist?

**Comment by DenisMir** [comment]
I can not confirm this bug with 7.6.4 LTS and the flux development version.

**Comment by NamelessCoder** [comment]
It's possible that this one is caused by naming the content area something containing a hyphen which then causes the DOM ID that D&D sadly depends on to be incorrectly parsed. If that's the case, avoid the issue by avoiding anything other than characters `/[a-z0-9\.]/i` as name of your content area.

If that is *not* the case you may be affected by one or more known issues with drag and drop and nested content. Please refer to the list of open issues if the first suggestion doesn't allow you to work around it.
