### ISSUE TITLE
[BUG][TYPO3-7.6]Possible wrong {settings} in a flux element inside the f:section name="Configuration"

### ISSUE THREAD

**Issue by guelzow** [FluidTYPO3/flux#1108]
Hi everybody.

**Description**
When creating a new flux element directly inside a typo3 page, the flux configuration manager loads the wrong plugin `{settings}`. Nesting elements works well. Editing old elements also works well.

**Typo3 version**
Typo3 7.6.4

**Extensions**
builder 1.1.1
vhs 2.4.0
fluidpages 3.5.0
fluidcontent 4.4.1
flux 7.3.0

**How to reproduce**
1. ) Setup a new typo3 7.6.
2. ) Install the extensions above.
3. ) Create a page (uid 1) and a subpage (uid 2) in the page treeview.
4. ) Use Builder to kickstart a contentprovider.
5. ) Create a new template on the first page (uid 1), activate the extension and include it's typoscript setup.
6. ) Add some settings to your extension setup.txt so it will be asigned to your flux elements.
7. ) Add an extension template to the subpage (uid 2), overwriting the already existing plugin settings (step 6).
8. ) Add two new tt_content elements on your first page. They will get the uid 1 and 2.
9. ) Edit the Example.html flux template and add a debug-feedback inside the `<f:section name="Configuration">`, displaying the `{settings}`.
10.) Add a new Example.html element directly to the second page, but don't save it. It is important, that this element is not inside another flux element.

The debug-feedback from the settings should show the data from the subpage, where it is located.
But it actually shows the stuff from the setup.txt.
When saving and then editing the element, the correct `{settings}` are loaded, and everything is fine.

**What is happening inside the code**
--> `FluidTYPO3\Flux\Configuration\BackendConfigurationManager`
--> `protected function getPageIdFromRecordIdentifiedInEditUrlArgument()`
This function tries to get the page uid via url parameters. The Problem here is, that it gets the uid 2 from the parameters, which is the actual page uid.
It then loads the tt_content record uid 2 and gets the pid 1 from it. The `BackendConfigurationManager` then loads the typoscript of the page with the uid 1.

Our (very dirty) workaround so far
With a very simple viewhelper inside the `<f:section name="Configuration">`, we correct the page id inside the `BackendConfigurationManager` via `setCurrentPageUid` when it is needed.
This only works, because the configuration is rendered twice, giving the viewhelper the opportunity to correct the page uid.

Tobi

**Comment by NamelessCoder** [comment]
Hi Tobi,

Thanks for an excellent bug report! Correct resolving of TypoScript in the backend is a known grey area - it's possible to cover *some* but probably not all of the possible conditions that may apply (there are quite literally dozens of methods that the page UID may be defined, as well as multiple ways that it may be formatted - negative UID, relative element and so on). Our implementation of the BackendConfigurationManager is exactly an attempt to get around this problem - by adding more internal methods that can resolve the page UID, and by adding a public method that allows the page UID to be overridden (which is as you've already found out a very nice "I need this working NOW!" solution).

It should be fairly easy to track this one down using your reproduction steps. You've identified the correct suspect method in the ConfigurationManager but I'm not sure how to fix it (in a way that works on both 7.6 and 8.0) so unfortunately can't give any hints about that right now.

**Comment by guelzow** [comment]
Hi Claus.

I don't think that we will use 8.x in the next few months (maybe 8.3 ?), and our 7.6 get-variable-"analysis"-viewhelper _looks_ like it is not causing any unwanted features. You do not need to worry about us here, we are good.  :-) 

Tobi

**Comment by NamelessCoder** [comment]
Cannot be solved by Flux - see https://github.com/FluidTYPO3/flux/issues/1671 for longer explanation.
