### ISSUE TITLE
Wrong PageId / Typoscript configuration on Root Level Pages

### ISSUE THREAD

**Issue by moger-xx** [FluidTYPO3/flux#1115]
TYPO3 6.2.18
Flux 7.2.3
Fluidpage 3.3.1
Fluidcontent 4.3.3

I have a multidomain tree with 4 root pids and 4 Provider Extensions - one for each sub-tree. I want to limit the available page templates and content elements in BE to their respective sub-tree.

I found out that this is possible -at least for page templates- by setting tx_myprovider.view.enable = 0 selectively for the other providers in each tree through typoscript like this:
```
# disable other page template providers
plugin.tx_firstprovider.view.enable = 0
plugin.tx_secondprovider.view.enable = 0
plugin.tx_thirdprovider.view.enable = 0
plugin.tx_fourthprovider.view.enable = 1
```

 It works so far - but only for subpages below root page level.

When I edit a root page (through the icon above in "page" view), the templates always show the ones from the provider extension, which is active on the root page with the lowest UID. I found out that this is due to a falsely determined currentPageId in 

`\FluidTYPO3\Flux\Configuration\BackendConfigurationManager::getPageIdFromRecordIdentifiedInEditUrlArgument`

Here is a stack trace.

... where 12364 is the uid of the root page I am editing
... and getCurrentPageId() returns 2

`#0 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Configuration/BackendConfigurationManager.php(77): TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getCurrentPageId() #1 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Configuration/BackendConfigurationManager.php(59): FluidTYPO3\Flux\Configuration\BackendConfigurationManager->getPrioritizedPageUids() #2 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php(46): FluidTYPO3\Flux\Configuration\BackendConfigurationManager->getCurrentPageId() #3 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php(112): TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getTypoScriptSetup() #4 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Service/FluxService.php(346): TYPO3\CMS\Extbase\Configuration\ConfigurationManager->getConfiguration('FullTypoScript') #5 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Service/FluxService.php(334): FluidTYPO3\Flux\Service\FluxService->getAllTypoScript() #6 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Provider/ProviderResolver.php(119): FluidTYPO3\Flux\Service\FluxService->getTypoScriptByPath('plugin.tx_flux....') #7 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Provider/ProviderResolver.php(141): FluidTYPO3\Flux\Provider\ProviderResolver->loadTypoScriptConfigurationProviderInstances() #8 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Provider/ProviderResolver.php(94): FluidTYPO3\Flux\Provider\ProviderResolver->getAllRegisteredProviderInstances() #9 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Provider/ProviderResolver.php(70): FluidTYPO3\Flux\Provider\ProviderResolver->resolveConfigurationProviders('pages', 'tx_fed_page_fle...', Array, NULL) #10 /var/www/web/htdocs/development/typo3conf/ext/flux/Classes/Service/FluxService.php(363): FluidTYPO3\Flux\Provider\ProviderResolver->resolvePrimaryConfigurationProvider('pages', 'tx_fed_page_fle...', Array, NULL) #11 /var/www/web/htdocs/development/typo3conf/ext/fluidpages/Classes/Service/ConfigurationService.php(106): FluidTYPO3\Flux\Service\FluxService->resolvePrimaryConfigurationProvider('pages', 'tx_fed_page_fle...', Array) #12 /var/www/web/htdocs/development/typo3conf/ext/fluidpages/Classes/Backend/BackendLayoutDataProvider.php(165): FluidTYPO3\Fluidpages\Service\ConfigurationService->resolvePageProvider(Array) #13 /var/www/web/htdocs/development/typo3conf/ext/fluidpages/Classes/Backend/BackendLayoutDataProvider.php(100): FluidTYPO3\Fluidpages\Backend\BackendLayoutDataProvider->getBackendLayoutConfiguration('12364') #14 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/View/BackendLayout/DataProviderCollection.php(81): FluidTYPO3\Fluidpages\Backend\BackendLayoutDataProvider->addBackendLayouts(Object(TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext), Object(TYPO3\CMS\Backend\View\BackendLayout\BackendLayoutCollection)) #15 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/View/BackendLayoutView.php(109): TYPO3\CMS\Backend\View\BackendLayout\DataProviderCollection->getBackendLayoutCollections(Object(TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext)) #16 [internal function]: TYPO3\CMS\Backend\View\BackendLayoutView->addBackendLayoutItems(Array, Object(TYPO3\CMS\Backend\Form\FormEngine)) #17 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/core/Classes/Utility/GeneralUtility.php(4309): call_user_func_array(Array, Array) #18 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(5200): TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction('TYPO3\\CMS\\Backe...', Array, Object(TYPO3\CMS\Backend\Form\FormEngine)) #19 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(1982): TYPO3\CMS\Backend\Form\FormEngine->procItems(Array, NULL, Array, 'pages', Array, 'backend_layout') #20 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(1910): TYPO3\CMS\Backend\Form\FormEngine->getSelectItems('pages', 'backend_layout', Array, Array) #21 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(1391): TYPO3\CMS\Backend\Form\FormEngine->getSingleField_typeSelect('pages', 'backend_layout', Array, Array) #22 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(1267): TYPO3\CMS\Backend\Form\FormEngine->getSingleField_SW('pages', 'backend_layout', Array, Array) #23 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(3961): TYPO3\CMS\Backend\Form\FormEngine->getSingleField('pages', 'backend_layout', Array, 'LLL:EXT:cms/loc...', 1, '', NULL) #24 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(1113): TYPO3\CMS\Backend\Form\FormEngine->loadPaletteElements('pages', Array, 'layout', '') #25 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Form/FormEngine.php(975): TYPO3\CMS\Backend\Form\FormEngine->getPaletteFields('pages', Array, 'layout', 'Seitenlayout') #26 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Controller/EditDocumentController.php(902): TYPO3\CMS\Backend\Form\FormEngine->getMainFields('pages', Array) #27 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/sysext/backend/Classes/Controller/EditDocumentController.php(698): TYPO3\CMS\Backend\Controller\EditDocumentController->makeEditForm() #28 /var/www/web/htdocs/development/typo3_src-6.2.18/typo3/alt_doc.php(40): TYPO3\CMS\Backend\Controller\EditDocumentController->main() #29 {main}`

**Comment by NamelessCoder** [comment]
Pretty sure this one is fixed in the `development` branch in a fix that adjusted the condition used by the method you mention, to return the page ID itself when editing pages (before, it would return the parent ID of the page, which in your case would be zero I assume, which then causes the first root TS template to be used).

I see that you are on TYPO3 6.2 so I have a few tips for how to proceed (since we no longer officially support this version):

* Start by forking Flux's repository, cloning your fork and checking out the `legacy` branch
* Locate commit(s) in `development` which change the backendconfigurationmanager and cherry-pick those that you need.
* If any conflicts arise, resolve them

At that point you should have it fixed on your own site and can commit your changes, push those to a new branch or "legacy" branch on your remote and then create a pull request for our legacy branch to merge from your branch.

The above method the only way to obtain a fix for this version of TYPO3 and Flux. We're happy to merge those pull requests but we don't create them ourselves due to TYPO3 6.2 no longer being supported by FluidTYPO3.
