### ISSUE TITLE
Typo3 7.6.5 - validation error with number-only in input field

### ISSUE THREAD

**Issue by thomasblass** [FluidTYPO3/flux#1116]
After updating to Typo3 7.6.5 i cannot enter a number in a flux:field.input . It is marked as invalid. If I enter a letter the error goes away. There was a change in the FormEngineValidation.js which seems realted to this issue

It seems to me the root-cause is a range-validation which is placed for each input field. 

flux/Classes/Form/Field/Input.php:103:

```
if ($minimum >= 0 || $maximum >= 0 && in_array('int', GeneralUtility::trimExplode(',', $validate))) {
```
should be
```
if (($minimum >= 0 || $maximum >= 0) && in_array('int', GeneralUtility::trimExplode(',', $validate))) {
```

**Comment by grimmcreative** [comment]
I can confirm this, same Problem.

**Comment by sascha-schieferdecker** [comment]
I can confirm this too, same here.

**Comment by thomasblass** [comment]
Dirty hack: 

Comment out the following:

File flux/Classes/Form/Field/Input.php:
/*
		if ($minimum >= 0 || $maximum >= 0 && in_array('int', GeneralUtility::trimExplode(',', $validate))) {
			$configuration['range'] = array(
				'lower' => $minimum,
				'upper' => $maximum,
			);
		}
		*/

**Comment by NamelessCoder** [comment]
Please try the `development` branch of Flux, this issue should be fixed with https://github.com/FluidTYPO3/flux/commit/706f35cb729ff4a01156c988a54726ad9b846705 :)
