### ISSUE TITLE
No pid for reference to content in preview

### ISSUE THREAD

**Issue by arsrobota** [FluidTYPO3/flux#1118]
Hi,
When I insert a reference to a content taken from another page, mouse-over tooltip doesn't return original pid of this content any more, it gives a message `Reference to content on page '' - click to jump to original` instead.
Daniel Goerz put me on flux way in [https://forge.typo3.org/issues/75544](https://forge.typo3.org/issues/75544)
![tooltip](https://cloud.githubusercontent.com/assets/12953474/14532555/b65b3842-0261-11e6-9b2e-5061f3d4cdfd.jpg)
Does anyone encounter the same trouble?
Cheers,
Alex

**Comment by arsrobota** [comment]
I found the solution: in flux/Classes/Backend/Preview.php (l.111), change
`$targetRecord = $this->getPageTitleAndPidFromContentUid(intval($row['records']));`
with
`$targetRecord = $this->getPageTitleAndPidFromContentUid(intval(substr($row['records'], 11)));`

**Comment by NamelessCoder** [comment]
Shortcut icon removed in https://github.com/FluidTYPO3/flux/commit/c51ca738a054d51f4b7fe75a38a39ee321f5d681
