### ISSUE TITLE
Add flux:field.group for page or content element selection

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1128]
Please add a `flux:field.group` element so that we can get proper page and content element selectors.

https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Group/Index.html

**Comment by NamelessCoder** [comment]
https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/Field/MultiRelation.php and https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/Field/File.php should allow you to get the results you need (although they're not named "group" in the API and are split into two with different arguments for each).

If I'm misunderstanding the request please elaborate and ask for the issue to be reopened ;)
