### ISSUE TITLE
Pasting an element w/ "gridelements" installed moves the original element to the new location

### ISSUE THREAD

**Issue by x3ro** [FluidTYPO3/flux#1129]
When Flux and [gridelements](https://typo3.org/extensions/repository/view/gridelements) are both installed, copying and then pasting an element will move the original element to the new location as well. This behavior appears to be caused by Flux' `ContentProvider`, more specifically by the [postProcessCommand method](https://github.com/FluidTYPO3/flux/blob/744e53c/Classes/Provider/ContentProvider.php#L125).

The `$command` parameter passed to the method is `copy`, both with and without `gridelements` installed. However, when using gridelements, the "callbackCommand" passed as `CB` in the query string does not exist, and thus the [`else` branch which moves the record](https://github.com/FluidTYPO3/flux/blob/744e53c/Classes/Provider/ContentProvider.php#L135) is executed. Here's a comparison between the requests when pasting w/ and w/o gridelements:

**Without gridelements:**
~~~
route=/record/commit
&token=0500c027bc9bfd71f90c0875a37c2cc935c3b634
&vC=9af99724f3
&prErr=1
&uPT=1
&CB[paste]=tt_content|28
&CB[pad]=normal&redirect=/typo3/index.php?M=web_layout
&moduleToken=[...]id=28
&CB[update][colPos]=0
&CB[update][sys_language_uid]=0
~~~

**With gridelements:**
~~~
ajaxID=/ajax/record/process
&ajaxToken=[...]
&cmd[tt_content][190][copy][action]=paste
&cmd[tt_content][190][copy][target]=-184
&cmd[tt_content][190][copy][update][colPos]=0
&cmd[tt_content][190][copy][update][tx_gridelements_container]=NaN
&cmd[tt_content][190][copy][update][tx_gridelements_columns]=false
&cmd[tt_content][190][copy][update][sys_language_uid]=0
~~~

To be honest, I have very little knowledge of what's going on there. To me, it looks like gridelements is simply using a different interface to the same functionality, and Flux' `postProcessCommand` is only considering the one that uses `CB`.

Is this something that should be fixed in Flux? Or is this a bug in gridelements? I'd build a PR for this, but I simply don't know what the best way of fixing this would be.

**Comment by x3ro** [comment]
Transcript from IRC by @NamelessCoder on 2016-05-11 starting at 20:55

> I'm not completely sure what's going on there, but there's obviously a big difference in the two calls. I would always assume that the one without gridelements (which should be the same as when not using Flux, btw) is the more correct one. The "worst" difference I see in the two calls is the reference to the target element.
> 
> the one where gridelements is installed seems to want to paste the element after another one. The one where gridelements is not installed wants to paste to a top position of a page column.
> 
> I know that gridelements replaces much of the page module including a lot of the JS that is used to operate it. If that switch to ajax calls when pasting is modified by gridelements, I would have to say a patch should be to make gridelements find the right relative UID for the paste action; if you are in fact pasting to a top column position, the call in gridelements is definitely wrong, since it would paste the element after element UID 184 (which means flux will copy parent and flux column name from that element)
> 
> what I can tell you is that TYPO3 will post using the "old" format (non-ajax) when using the paste icons in a page
> 
> I would check the following:
> 
> - if there are other places where this ajax post happens (list view?) then Flux needs to support that as well
> - if it is used in another way which might imply we *don't* want Flux providers to process that command, we may need to skip it if we detect that format being used.
> 
> the main issue being that because these are AJAX calls, and because Flux can modify records, the result in the UI may not be as expected (e.g. if you delete a flux container element and that gets posted as AJAX, then DOM gets changed - you may still see the old child elements that weren't removed from DOM even though they were recursively removed). If that's the case we want to skip running providers.
> 
> if it should be supported, the way and place to fix it would be in ContentService or FluxService if I recall. There are methods to resolve the command and originating record, those methods could possibly be changed to look in those other places first (logic: AJAX requests would have priority over normal ones)

**Comment by Bunnyfield** [comment]
Well - it seems there is a little misunderstanding about what "CB" stands for and how this is used. CB is short for ClipBoard and has nothing to do with a CallBack. And gridelements is doing it exactly as the core does it, since the "action" is the relevant part, determining that this is a copy AND "paste" action, in contrary to the default "copy" action that would just make a copy of a record without taking it from the clipboard.

Since the clipboard content is already defined when executing that action, there is no need to hand over the clipboard information via GET parameters, which is why the "action" part within the command is enough.

The if/else part in this case makes a wrong decision, since it just checks, if the command has been "copy" or "move" and if there has been no "paste" it makes a "move" anyway, even when the command has actually been "copy".
```
$pasteCommands = array('copy', 'move');
if (TRUE === in_array($command, $pasteCommands)) {
	$callback = $this->getCallbackCommand();
	if (TRUE === isset($callback['paste'])) {
		$pasteCommand = $callback['paste'];
		$parameters = explode('|', $pasteCommand);
		$this->contentService->pasteAfter($command, $row, $parameters, $reference);
	} else {
		$moveData = (array) $this->getMoveData();
		$this->contentService->moveRecord($row, $relativeTo, $moveData, $reference);
	}
}
```
should be changed to
```
$pasteCommands = array('copy', 'move');
if (TRUE === in_array($command, $pasteCommands)) {
	$callback = $this->getCallbackCommand();
	if (TRUE === isset($callback['paste'])) {
		$pasteCommand = $callback['paste'];
		$parameters = explode('|', $pasteCommand);
		$this->contentService->pasteAfter($command, $row, $parameters, $reference);
	} else if ($command === 'move') {
		$moveData = (array) $this->getMoveData();
		$this->contentService->moveRecord($row, $relativeTo, $moveData, $reference);
	}
}
```

**Comment by Bunnyfield** [comment]
BTW: Since CMS 7 there are two more parameters "pasteUpdate" and "pasteDatamap" that should be used with processCmdmap hooks - pasteUpdate is available for all three hooks, while pasteDatamap will only be there with the postProcess hook - should be useful for current changes in the copy/cut/paste/D&D behaviour of the core. IMHO this should make the CB parameters obsolete, even though the core might still use them in some places.

**Comment by neufeind** [comment]
This fix went through some testing at a customer. Their issues were resolved with that fix without any other obvious side-effects.

**Comment by NamelessCoder** [comment]
Thanks Jo for taking the time to investigate and explain it!
