### ISSUE TITLE
flux:form.sheet initially collapsed

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1130]
`<flux:form.sheet>` are initially collapsed in fluidcontent elements.
The first one should be visible initially.

Code to reproduce:

```
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
      xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
      xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers">

  <f:layout name="Content" />

  <f:section name="Configuration">
    <flux:form id="testsheet">
      <flux:form.sheet name="design" label="Design">
        <flux:field.input name="one" label="One"/>
      </flux:form.sheet>
      <flux:form.sheet name="other" label="Other">
        <flux:field.input name="two" label="Two"/>
      </flux:form.sheet>
    </flux:form>
  </f:section>

  <f:section name="Main">
  </f:section>
</html>
```

Screenshot:
![2016-04-28 fluidcontent flux sheet](https://cloud.githubusercontent.com/assets/59036/14882194/a2e7586e-0d37-11e6-9b67-699e2d2f63e0.png)

**Comment by NamelessCoder** [comment]
Hi Christian,

Do you know of a TCA setting that can define this? The issue is that the user session will store the active tab based on field name and restored with JS if I recall it correctly - so unless there is a TCA option to "show tab if no tab requested or requested tab does not exist" then I'm afraid we can't grant this wish.

If such a feature does not exist it could make sense to add it to TYPO3 itself, *then* we can easily allow setting it via Flux.

**Comment by cweiske** [comment]
Ok, I've debugged this a bit:

- The tabs are generated in `typo3/sysext/backend/Resources/Private/Templates/DocumentTemplate/Tabs.html`, which gets the `defaultTabIndex` set that is `1`.
- In my example, there are 3 tabs. The first tab does not have any content and is thus not rendered.
- This first tab has the title "Option(en)" (german), which leads to `tt_content.tx_flux_options`
- `tx_flux_options` is the default sheet added by `flux/Classes/Form.php` with the name `options`

What now?
- The quickfix is to give my first sheet the name `options`. Then it's open automatically with the current code.
- The real fix would be to remove the default sheet in flux when it's not used, and maybe re-key the array.

**Comment by cweiske** [comment]
You're already trying to remove empty sheets in `build()`, but the code does not work (anymore?).

**Comment by TheNaderio** [comment]
Is there still no way to realize that?

The workaround with naming the first sheet "options" ist still working but you cant rename the tab with locallang-settings.
