### ISSUE TITLE
Add "showIconTable" attribute for flux:field.select

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1134]
It would be nice to have a showIconTable attribute for the select view helper.

https://docs.typo3.org/typo3cms/TCAReference/stable/Reference/Columns/Select/#showicontable

**Comment by cdfre** [comment]
It's already been added in the development branch.

But i would like the addition of "selicon_cols":
https://docs.typo3.org/typo3cms/TCAReference/stable/Reference/Columns/Select/#selicon-cols

**Comment by cweiske** [comment]
Ah, the commit is https://github.com/FluidTYPO3/flux/commit/fd8a9e955234318a17d8bf0d65f6859b79db577e

**Comment by cdfre** [comment]
What about "selicon_cols"? Please don't close this issue so fast.

**Comment by cweiske** [comment]
Just open a new one, ok?
