### ISSUE TITLE
"requestUpdate" in latest development branch not working any more

### ISSUE THREAD

**Issue by cdfre** [FluidTYPO3/flux#1135]
I use the requestUpdate attribute for <flux:field.select> pretty often and it seems not to work any more in the development branch.

**Comment by NamelessCoder** [comment]
Seems to be one or more core bugs, see for example https://review.typo3.org/#/c/48417/. The JS that does validation and triggering is generally broken, but not under our control.

What is under our control is that the popup box that displays to request the update has no text - but we already have another issue for that.
