### ISSUE TITLE
[TYPO3 7.6.0] CE and form.object are not moved/deleted together

### ISSUE THREAD

**Issue by cgrossde** [FluidTYPO3/flux#1141]
[FLUX 7.3.0]
I have a content element with flexible amount of tabs. Each tab has a title and a checkbox to mark it hidden. I can add content elements to each tab. Everything works fine. But if I move "Tab 1" below "Tab 2" then the tabs move but the content stays in the same order which results in "Tab 2" being first but having the content of "Tab 1" and "Tab 1" being second but having the content auf "Tab 2" ... -.-

Here's my setup and also some images to clarify the issue:

    <f:section name="Configuration">
    	<flux:form id="contenttabs" label="{f:translate(key: 'contenttabs-fce-label')}"
    		description="{f:translate(key: 'contenttabs-fce-description')}" options="{ group:     'FCE' }">
    
    		<flux:form.section name="tab_container" label="{f:translate(key:     'contenttabs-container-label')}">
    			<flux:form.object name="tab_element" label="{f:translate(key:     'contenttabs-element-label')}">
    				<flux:field.input name="tab_title" label="{f:translate(key:     'contenttabs-tabs-title')}" />
    				<flux:field.checkbox name="tab_hide" label="{f:translate(key:     'contenttabs-tabs-hide')}" />
    			</flux:form.object>
    		</flux:form.section>
    
    		<flux:grid>
    			<f:for each="{tab_container}" as="tab" iteration="iteration">
    				<flux:grid.row>
    					<flux:grid.column name="contenttab{iteration.index}" label="Tab     {iteration.cycle}: {tab.tab_element.tab_title} {f:if(condition:     tab.tab_element.tab_hide, then:'[hidden]')}" />
    				</flux:grid.row>
    			</f:for>
    		</flux:grid>
    	</flux:form>
    </f:section>

**Before**
![before](https://cloud.githubusercontent.com/assets/2333584/15331092/ed05764c-1c5f-11e6-823d-a3ff32324085.png)

**Now i edit the FCE and move "Tab 1" below "Tab 2":**
![movetab1](https://cloud.githubusercontent.com/assets/2333584/15331166/48558af0-1c60-11e6-9d1a-b209612620f8.png)

**The result (content stays at same position, but titles changed):**
![after](https://cloud.githubusercontent.com/assets/2333584/15331278/d6535a6c-1c60-11e6-99cc-ee667d2c75e3.png)

**Comment by grimmcreative** [comment]
In 7.3 i can confirm
In FLUX 7.4 no more move possible.

**Comment by NamelessCoder** [comment]
To avoid this you have to name your content areas with a unique value that does not come from an iterator. Using the iterator this way your fields' names will change when you reorder the tabs.

Your section objects have a convenience property, `id`, which you can combine with a prefix and use as field name. That will keep your content area names when you reorder tabs.

Hope that helps!

**Comment by cgrossde** [comment]
Thanks you, that was the missing link :)
