### ISSUE TITLE
Required argument not working?

### ISSUE THREAD

**Issue by zelcode** [FluidTYPO3/flux#1143]
Hi,

this is code:

```html
<flux:form.sheet name="images">
    <flux:form.section name="images">
        <flux:form.object name="image">
            <flux:field.file name="file" required="1" minItems="1" maxItems="1" showThumbnails="1" allowed="jpg,jpeg,png" />
        </flux:form.object>
    </flux:form.section>
</flux:form.sheet>
```

Tried all combinations with arguments `required="1" minItems="1" maxItems="1"` but nothing.

Editor should not be able to save record with empty field of image name.

Regards.

**Comment by Dima776** [comment]
Have the same problem, minItems="1" maxItems="1" not working, please fix this issue!

**Comment by NamelessCoder** [comment]
See https://review.typo3.org/#/c/48417/
