### ISSUE TITLE
flux:field.inline.fal: Option "requestUpdate" not working?

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#1145]
Hey,

I want to show a specific field when an image gets uploaded or it exists in the FCE.

So I set `requestUpdate=1` on my `flux:field.inline.fal` element and `displayCond="FIELD:backgroundImage:REQ:true"` on my other field which should be displayed after uploading.

When I upload an image or choose one of the existing images then nothing happens. I have to save the FCE first and then the second field gets displayed. No popup pops up and ask me if I want to reload.

Is there any bug or do I miss something?

Thanks in advance!

Seems the same problem is in #1135 ?

**Comment by NamelessCoder** [comment]
Seems to be one or more core bugs, see for example https://review.typo3.org/#/c/48417/. The JS that does validation and triggering is generally broken, but not under our control.

What is under our control is that the popup box that displays to request the update has no text - but we already have another issue for that.
