### ISSUE TITLE
fluidcontent: pre define allowedContentTypes: several types do not work

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#1147]
Hi,

one type works:

 ```<flux:grid.column colPos="0" name="column0">
<flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
<flux:form.variable name="Fluidcontent" value="{allowedContentTypes: my_provider:TeaserBannerStart.html'}" />
</flux:grid.column> ```

but several do not work:
 ```<flux:grid.column colPos="0" name="column0">
<flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
<flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'my_provider:TeaserBannerStart.html','my_provider:TeaserBannerStart2.html'}" />
</flux:grid.column> ```

Also a combination of fluid styled content elements and fluidcontent elements do not work:

 ```
<flux:grid.column colPos="0" name="column0" variables="{allowedContentTypes: 'textmedia, table'}">
<flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
<flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'my_website:TeaserBannerStart.html'}" />
</flux:grid.column>
```

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin vom Donnerstag, 26. Mai 2016 bis und mit Freitag, 27. Mai 2016 wegen eines Feiertages nicht erreichbar, und gerne am Montag, 30. Mai wieder für Sie da.
 
Die Nachricht wird nicht weiter geleitet! In sehr dringenden Angelegenheiten bin ich auf dem Mobile zeitweise erreichbar. Falls nicht hinterlassen Sie bitte eine Nachricht, damit ich Sie zurückrufen kann. Vielen Dank!


Einen guten Tag wünscht

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by NamelessCoder** [comment]
You have a syntax error. Correct code:

```xml
'my_provider:TeaserBannerStart.html,my_provider:TeaserBannerStart2.html'
```

Note extra single quotes present in CSV list.
