### ISSUE TITLE
Why are the child elements (colPos 18181) hidden in record browser

### ISSUE THREAD

**Issue by fschaeffer** [FluidTYPO3/flux#1148]
I see that in RecordListGetTableHookSubscriber.php the child elements (typo 18181) are removed by purpose from the record browser but this leads to lot of inconsistencies for the editors.

E.g. I have an container content template which servers as an accordion container for content elements (colPos = 0). Then I create some content records in this accordion (all colPos 18181). If I now want to create a navigation on the page which allows the editor to select items from that page using the record browser the child content records are hidden and can't be selected at all.

Is it really necessary to hide them? Could we at least make this configurable?

**Comment by NamelessCoder** [comment]
See extension configuration for Flux, option `listNestedContent` toggles this (but read the description carefully before you toggle it on!)
