### ISSUE TITLE
Translations in Flux:Grids

### ISSUE THREAD

**Issue by haraldkrischner** [FluidTYPO3/flux#1151]
Hi, 
I have a grid content element with 3 flux columns. This element is available in all languages. Now I  translate the content elements and I get into 2 and a half problems:
1) Every element for every language is below each other so it look a little bit messy and confusing.
2) The element is in Frontend twice for the translations
3) (the half one) the backend page view with language columns doesn't look very handy.

Anyway, thanks for this nice tool!

Running Typo3 7.6.4, with master branches of flux, fluid & co.
![flux_err1](https://cloud.githubusercontent.com/assets/893237/15772553/0562fd8a-2972-11e6-9cae-43cc1624cf16.png)
![flux_err2](https://cloud.githubusercontent.com/assets/893237/15772706/fec3c8a0-2972-11e6-849f-0590f22b84e7.png)

**Comment by haraldkrischner** [comment]
I am sorry to bump this up again, but I have to move forward with this project and I do not have an idea yet, how to elegantly solve this grid element language problem. 
This looks to me like a not too uncommon set-up…

If there is no way to accomplish this I have to rethink that structure in favour of a more or less hideous solution.

**Comment by haraldkrischner** [comment]
I crawl forward slowly, but I must say localization handling does not seem to be production ready. The behaviour is erratic and the handling is painful. There is not very much documentation on this topic. 
It did help to set `mod.web_layout.allowInconsistentLanguageHandling = 1`, but duplicate output of an translated element (first time as translation, second time the element itself) could only be helped by disconnect the translation from the original field. 
Also changing a position of an element which is set for all languages inside the language view lead to a language change of that element, so it was hard to get an appropriate and consistent order throught all language versions.

Though I really really like Flux when only a single language is used.

**Comment by robsonrobi** [comment]
Is there any progress fixing the localization issues with flux ?

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin vom Freitag, 29. Juli 2016 bis und mit Dienstag, 16. August 2016 in den Ferien.
 
Die Nachricht wird nicht weiter geleitet! In dringenden Angelegenheiten wenden Sie sich bitte an Hugo Stalder, hugo.stalder@appline.ch. Vielen Dank!

Sonnige Grüsse

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.
