### ISSUE TITLE
Reason: File "browser.php" was not found (2)!

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#1153]
Hi there,

I just run into this issue after updating to:

- Flux version: 7.4
- TYPO3 version: 7.6.9

<flux:field.file name="file" label="File" /> is opening a popup with the "Page Not Found" Reason: File "browser.php" was not found (2)!

Any feedback is appreciated as always

**Comment by jmverges** [comment]
Gonna respond my self and close it, just for the record.
As I'm using nginx, .htaccess is not applied so no flux issue here. Sorry for the confusion.

**Comment by jmverges** [comment]
I'm gonna reopen this as I'm getting mad.

<flux:field.file /> is the one that open browser.php.

browser.php is not there since https://github.com/TYPO3/TYPO3.CMS/commit/f00efef1bd93181fe1c594bf169cd8ccb6eb7f63

when you use nginx, as Core doesn't provide a nginx rules you get a *not found file*

once you apply:

 ```
location ~* ^(?<bpath>.*/)(ajax|alt_clickmenu|alt_db_navframe|alt_doc|alt_file_navframe|browser|db_new|dummy|init|login_frameset|logout|mod|move_el|show_item|tce_db|tce_file|thumbs)\.php$ {
        include fastcgi_params;
        fastcgi_param   TYPO3_CONTEXT   Development;
        #fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-fpm-vagrant.socket;
        fastcgi_read_timeout 600;
        fastcgi_param SCRIPT_FILENAME $document_root${bpath}deprecated.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

```

or this:
`
rewrite ^(.*/)(ajax|alt_clickmenu|alt_db_navframe|alt_doc|alt_file_navframe|browser|db_new|dummy|init|login_frameset|logout|mod|move_el|show_item|tce_db|tce_file|thumbs)\.php$ $1deprecated.php$is_args$args last;

`

in nginx the browser.php window appears again.

However, once you select the file you want, a prompt is displayed saying:

https://typo3.slack.com/files/jmverges/F1FBH3NSC/pasted_image_at_2016_06_09_09_05_am.png

**Error - reference to main window is not set properly!**

where is the problem here? is the nginx snippet wrong? is the deprecated code wrong? I bet is the nginx, as I'm using flux:field.file with apache without problems.

Any thoughts and feedback is as welcomed as always.

Best,
Juan Manuel.

**Comment by cedricziel** [comment]
Can't view the screenshot since it's behind the great Slack'ian wall.

**Comment by jmverges** [comment]
@cedricziel is updated now, sorry for the wall!

**Comment by jmverges** [comment]
I can confirm the following: 
-Apache .htaccess is working and window.opener is not lost, so works properly. 
-Nginx conf I delivered is half working as the browser.php window is shown but window.opener is lost there.

**Comment by jmverges** [comment]
Follow up in here: https://forge.typo3.org/issues/76567 . Feel free to close this one at any time.

**Comment by NamelessCoder** [comment]
Closing this one - looks like we found a solution, see followups.
