### ISSUE TITLE
Nesting sections in container elements sections is not allowed (TYPO3 7.6.9)

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/flux#1154]
hello,
after we hit the update to TYPO3 7.6.9 the exception #1458745712 prevents using our content element in the backend. We're not sure if this is a bug or not so please look over our structure:

flux:form.sheet
--flux:form.section 1
----flux:form.object A
------flux:form.section 2
--------flux:form.object B

--------flux:form.object C

Should this be valid or not? Is there any other way to build this data structure? Thanks in advance.

**Comment by NamelessCoder** [comment]
See https://github.com/FluidTYPO3/flux/issues/1139 - unfortunately this is beyond our control.
