### ISSUE TITLE
Inputs in Nested Sections aren't Saved

### ISSUE THREAD

**Issue by VincentKoehler** [FluidTYPO3/flux#1155]
Hi,

I'm using the following setup:
Typo3 7.5.6
Fluid 7.6
Flux 7.4

I created a custom element with the following configuration:
`<flux:form.section name="categories">
				<flux:form.object name="category" label="Kategorie">
					<flux:field.input name="category-name" label="Name der Kategorie"/>
					<flux:form.section name="keywords">
						<flux:form.object name="keyword" label="Keyword">
							<flux:field.input name="keyword-entry" label="Suchbegriff"/>
						</flux:form.object>
					</flux:form.section>
				</flux:form.object>
			</flux:form.section>`

The problem:
Everything in the backend seems to work fine, I can create new categories and multiple keywords inside each category. Unfortunately when I press the save button, only the categories are saved, the keywords are kicked out.

Did I do something wrong or is this a bug? Thanks in advance!

**Comment by NamelessCoder** [comment]
Hi Vincent,

TYPO3 considers this structure invalid and using it on newer TYPO3 versions causes an Exception to be thrown. See https://github.com/FluidTYPO3/flux/issues/1139 and https://fluidtypo3.org/blog/news/bugs-core-or-flux.html
