### ISSUE TITLE
v:page.resources.fal not working in non-default languages

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#1156]
Hi i used the v:page.resources.fal to read the standard page property resource media field. Works fine in default language (in my case de), but not in a foreign language (in my case en):

```
<f:for each="{v:page.resources.fal(field: 'media', slide: '-1', limit: 1)}" as="image">
    <f:image src="{image.id}" alt="{image.alternative}" title="{image.title}" maxWidth="970" />
</f:for>
```

So i had to replace it by following TS, which works fine in all languages:

```
lib.image = IMAGE
lib.image {
    file {
        import.data = levelmedia:-1, slide
        treatIdAsReference = 1
        import.listNum = 0
    }
    maxW = 970
}
```

EXT:vhs 2.4.0
TYPO3 7.6.9

**Comment by NamelessCoder** [comment]
Duplicates https://github.com/FluidTYPO3/vhs/issues/996 (and is a VHS issue)
