### ISSUE TITLE
[BUG][TYPO3-7.6]Flux may forget the Fluid Content type

### ISSUE THREAD

**Issue by guelzow** [FluidTYPO3/flux#1161]
Hi everybody.

I'm not sure if this is the right place to report this.

**Description**
When editing an old flux element and then pressing the "save and create a new one", TYPO3 forgets the fluid content type.
This also happens when creating a new one, and creating two more elements via "save and create a new one".

**Typo3 version**
Typo3 7.6.9

**Extensions**
builder 1.1.1
vhs 2.4.0
fluidpages 3.6.0
fluidcontent 4.4.1
flux 7.4.0

**How to reproduce**
1. ) Setup a new typo3 7.6.
2. ) Install the extensions above.
3. ) Create a page.
4. ) Use Builder to kickstart a contentprovider.
5. ) Create a new template on the first page and activate the extension.
6. ) Create a new content element and save it.
7. ) Edit this element and then press "save and create a new one"

Flux then tells you:

> Warning
> Fluid Content type not selected - edit this element to fix this!

**What is happening inside the code**
`TYPO3\CMS\Backend\Form\FormDataProvider\DatabaseRowInitializeNew`
tries to initialize the new row we want to create with the data from
`GeneralUtility::_GP('defVals');`
The problem is, there there is nothing in there. The value will not be set, the `Fluid Content type` dropdown will not load correctly and the `error.html` template will be rendered.

Strangely, when your entrypoint is a new element (instead of editing an old one), this will only happen at the third new element.

**Our workaround so far:**
Nothing implemented yet.

Tobi

**Comment by NamelessCoder** [comment]
Solved, but technically belongs to fluidcontent so you'll find the commit there instead: https://github.com/FluidTYPO3/fluidcontent/commit/dfafa2703068f5f9f053e71f918f5badff1571d2

Thanks for reporting!

**Comment by guelzow** [comment]
Thanks for fixing   :-)
