### ISSUE TITLE
Collapse/Expand icon misplaced

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1169]
Hi,

as the title already says, the icon is misplaced and only visible on hover, which is not very userfriendly.

I did a small CSS hack to make the icon visible and better placed, but the best solution would be to generate Buttons in the button group like you see in gridelements.

here is my CSS-Hack:

.t3-page-ce .toggle-content {
    visibility: visible;
    position: absolute;
    top: 25px;
    left: 34px
}

**Comment by xf-** [comment]
Can you provide a preview/compare (Screenshot)?

**Comment by steffenk** [comment]
sure. This is without my hack:
![current](https://cloud.githubusercontent.com/assets/234874/19641638/d6325304-99e1-11e6-861d-47b031dd7dca.png)

it's only visible on hover.

This is my hack, always visible:
![bildschirmfoto 2016-10-24 um 12 00 00](https://cloud.githubusercontent.com/assets/234874/19641667/f70e5f50-99e1-11e6-983f-efcb6e9a62a3.png)

**Comment by NamelessCoder** [comment]
I'm afraid the conclusion to this one is that we won't fix this one - at least not before officially dropping 7.6 LTS support which would make it a moot point. You are however *very* welcome to prepare this little CSS fix as a PR for the `legacy` branch, but you may want to confirm that it doesn't mess with the (recently restyled) positioning of the icon on TYPO3v8+.
