### ISSUE TITLE
FlexForm Fields next to each other

### ISSUE THREAD

**Issue by MichiBeck** [FluidTYPO3/flux#1170]
Hello, I can´t find any documentation regarding this "feature" but is it possible to display FlexForm fields next to each other? Like this:

![flexforms](https://cloud.githubusercontent.com/assets/15154464/17662673/8efc52f4-62e7-11e6-8739-45cfe0166dab.jpg)

Please excuse me if this isn´t the right place to ask...

**Comment by NamelessCoder** [comment]
Palettes (such as that layout method is called in TYPO3) are currently not supported in FlexForms and therefore also not supported in Flux - but you're more than welcome to open a feature request in the official TYPO3 issue tracker: https://forge.typo3.org/projects/typo3cms-core/issues

**Comment by MichiBeck** [comment]
Someone did (but it´s not planned to change something yet...): 
https://forge.typo3.org/issues/75266
