### ISSUE TITLE
Images are deleted when publishing workspaces

### ISSUE THREAD

**Issue by dr2okevin** [FluidTYPO3/flux#1171]
I have the problem that Images get removed from the Server when i publish a new Content Element.
The error occurs under the following conditions
- The Element is made with flux
- It is new in the Workspace
- I select a file
Bevor publishing, all seems fine. After live Publish, the image file is deleted from the server, but still referenced in the Content Element.

The error occurs **not** when
- I don't user flux on that element
- I don't use workspaces
- I'm only editing the element

**Comment by CptCompiler** [comment]
Is there any solution for this bug yet?

**Comment by CptCompiler** [comment]
In typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php
is a function called "deleteRecord_flexFormCallBack" that traverses files of a flex form and deletes them if the field is a regular file field (and not a file_reference field).

In flux/Classes/Form/Field/File.php line 59 the internal_type is set to "file". If I change it to "file_reference" the file will not be deleted when the content element is published.

I don't really know what all that means but thats what I've found out. 
Perhaps @NamelessCoder could take a look at it ?!

**Comment by NamelessCoder** [comment]
@CptCompiler A patch to change `file` to `file_reference` looks appropriate. Standard file behavior is pretty much deprecated across the board.

**Comment by dr2okevin** [comment]
The Bug still exist in the current master (Commit 374c9ac). Tested with TYPO3 7.6.14
