### ISSUE TITLE
Drag&drop does not work on specific column/row combination

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/flux#1172]
When moving a content element with d&d into row2/column2 of a fluid-content grid the change does get persisted correctly. 

The current view is updated properly and the content element gets placed in row2/column2. No javascript error visible and also the AJAX request for the move operation shows no error.
But after a reload the content element is placed inside row3/column1.

The interesting fact ist, that all other areas (row3/column2; row2/column1;..) do work! Only this one area does not work. I suspect a edge-case error in the javascript but had not the time to look closer at this.

It is also not important from which area the element is moved into row2/column2 - the behaviour is always the same.

Versions:
flux: development
fluid-content: development
TYPO3: 7.6.10

Can anyone confirm this bug?

![screenshot 2016-08-18 10 24 30](https://cloud.githubusercontent.com/assets/1185872/17767914/3d04b6d8-6532-11e6-9e2b-75aba5c32d72.png)

**Comment by NamelessCoder** [comment]
Submitted as PR https://github.com/FluidTYPO3/flux/pull/1268
