### ISSUE TITLE
flux:field.custom does not work

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1173]
When i try to use the custom field, the argument for userFunc is not used at all, instead flux always renders the built-in dummy function .
hardcoded: 
$fieldConfiguration['userFunc'] = 'FluidTYPO3\Flux\UserFunction\HtmlOutput->renderField';

Please fix!

**Comment by NamelessCoder** [comment]
That function is the one responsible for rendering the closure that gets generated by the `flux:field.custom` ViewHelper. You cannot change this function in that ViewHelper, but in https://fluidtypo3.org/viewhelpers/flux/master/Field/UserFuncViewHelper.html you can!

**Comment by steffenk** [comment]
Hi,

i debugged it, but my user function was never called. This is how i used it:

<flux:field.custom name="icon" label="Icon" userFunc="EXT:basetheme/Classes/UserFunction/IconFontSelector.php:\\SKTYPO3\\Basetheme\\UserFunction\\IconFontSelector->renderField">
                        
                    </flux:field.custom>

Thi is the debug output of the closure:

// Rendering ViewHelper FluidTYPO3\Flux\ViewHelpers\Field\CustomViewHelper
$arguments17 = array();
$arguments17['name'] = 'icon';
$arguments17['label'] = 'Icon';
$arguments17['userFunc'] = 'EXT:basetheme/Classes/UserFunction/IconFontSelector.php:\\SKTYPO3\\Basetheme\\UserFunction\\IconFontSelector->renderField';
$arguments17['default'] = NULL;
$arguments17['required'] = false;
$arguments17['exclude'] = false;
$arguments17['transform'] = NULL;
$arguments17['enabled'] = true;
$arguments17['requestUpdate'] = false;
$arguments17['displayCond'] = NULL;
$arguments17['inherit'] = true;
$arguments17['inheritEmpty'] = true;
$arguments17['clear'] = false;
$arguments17['variables'] = array (
);
$arguments17['extensionName'] = NULL;
$arguments17['arguments'] = NULL;
$renderChildrenClosure18 = function() use ($renderingContext, $self) {
$currentVariableContainer = $renderingContext->getTemplateVariableContainer();
return '
                        
                    ';
};

UserFunction still gets untouched :(

**Comment by NamelessCoder** [comment]
Please note `flux:field.userFunc` is not the same as `flux:field.custom`!

**Comment by steffenk** [comment]
hm - now i'm confused :)
So flux:field.userFunc seems to do the job, so what is custom for as the userFunc inside is not respected? Does not make sense to me.

I now continue with userFunc, thx!

**Comment by NamelessCoder** [comment]
`flux:field.custom` lets you make a custom-HTML field inside the Fluid template (by generating a closure that renders the HTML later in the HtmlOutput user function of Flux). `flux:field.userFunc` lets you define a userFunc straight as TCA. Custom is a pre-configured implementation of userFunc in Flux.

**Comment by steffenk** [comment]
ok, thx!

btw - such additional sentence in the docs would make it more easy to understand :)
