### ISSUE TITLE
Class 'FluidTYPO3\Flux\Service\ContentService' not found in .../typo3conf/ext/flux/ext_tables.php on line 11

### ISSUE THREAD

**Issue by dev4q1** [FluidTYPO3/flux#1181]
Hi,

I just installed a clean typo3 instance and the flux extensions and get the following error when I check for broken extensions in the INSTALL TOOL:

`Class 'FluidTYPO3\Flux\Service\ContentService' not found in .../typo3conf/ext/flux/ext_tables.php on line 11`

My setup is the following:
- Apache
- MySQL
- Typo3 7.6.10 (Testing Application Context)

with the following extensions:
- bootstrap_grids
- fluidcontent
- flux
- gridelements
- realurl
- vhs

As it seems I can't use the Testing Application Context to separate my installatations since flux also uses the Testing Application Context which is really unfortunate.

Would it be possible to change this for the public version (https://typo3.org/extensions/repository/view/flux)?

Thanks!

**Comment by NamelessCoder** [comment]
Did you do `composer install`?

**Comment by dev4q1** [comment]
No, I downloaded it via terminal with wget.

**Comment by NamelessCoder** [comment]
In that case: do `composer install` and Bob's your uncle. The extensions no longer work without it!
