### ISSUE TITLE
How can I do it?

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/flux#1184]
This code does not work now.
```
<flux:form.sheet name="divsheet" label="Div sheet">
    <flux:form.section name="mrs" label="Mrs">
        <flux:form.object name="mr" label="Mr">
            <flux:field.input name="mrcss" label="Mr class"/>
            <flux:form.section name="mds" label="Mds">
                <flux:form.object name="md" label="Md">
                    <flux:form.container name="md-data" label="Md data">
                        <flux:field.text name="md-text" label="Md content"/>
                    </flux:form.container>
                    <flux:form.container name="md-option" label="Md options">
                        <flux:field.input name="md-width" label="Md(% oder px)"/>					
                    </flux:form.container>
                </flux:form.object>
            </flux:form.section>
        </flux:form.object>
    </flux:form.section>
</flux:form.sheet>
```
I get [error...](https://wiki.typo3.org/Exception/CMS/1458745712) / "Using nested FCEs (containers/grid) instead"
How can I do it now?
How to do it in a new way?
Has someone an example?

**Comment by NamelessCoder** [comment]
See https://github.com/FluidTYPO3/flux/issues/1154 and https://github.com/FluidTYPO3/flux/issues/1139. Long story short: this is no longer supported by TYPO3 itself and there is nothing we can do to get around that. We accept the decision of TYPO3 to declare this unsupported.

**Comment by typo3ua** [comment]
[As understand it?](https://wiki.typo3.org/Exception/CMS/1458745712)
They write ... "Using nested FCEs (containers/grid) instead"
I do not know How I do it?

**Comment by typo3ua** [comment]
How to do it without FLUX?
