### ISSUE TITLE
[BUG][TYPO3-7.6.11] Changing the order of content elements in a workspace also changes the order in LIVE workspace

### ISSUE THREAD

**Issue by robocopklaus** [FluidTYPO3/flux#1185]
## Actual Behavior

The order of content elements in a LIVE workspace changes if you change the order of content elements in a different workspace. This happens with default typo3 content elements in a default 4 column page layout without any dependencies on the flux extension. As soon as I deactivate the flux extension, everything works again as expected.
## Expected Behavior

The order of content elements in a LIVE workspace should not depend on changes in a different workspace.
## Extensions

workspaces, 7.6.0
flux, current development version (commit a477b8f)
## Steps to reproduce

1.) Setup a new typo3 7.6.11
2.) Install the extensions above
3.) Create a page (typo3 default 4 column layout)
4.) Create a new template on the first page with the following typoscript setup:

`page = PAGE`
`page.10 < styles.content.get`

5.) Add **Content Elements (fluid_styled_content)** as static extension to the template
6.) Create 3 **Header Only** content elements in the **normal column**
7.) Create a new workspace for the site and set your current admin user as an owner
8.) Reload the backend. The workspace is now available in the top menu.
9.) Switch to the newly created workspace
10.) Move the first header content element by dragging & dropping it between the second and third header
11.) Switch to the LIVE workspace (or load the LIVE frontend)
## Other information

OS: OS X
MAMP (4.0.5) Stack
PHP Version: 5.6.25
Apache: 2.2.31

**Comment by bauermar** [comment]
I've the same problem!

The following is fixing the problem in BE:

`FluidTYPO3\Flux\Service\RecordService`
```
     /**
     * @param string $table
     * @param array $record
     * @return boolean
     */
    public function update($table, array $record)
    {
        $connection = $this->getDatabaseConnection();
        if($GLOBALS['BE_USER']->workspace > 0 && intval($record['t3ver_wsid']) != $GLOBALS['BE_USER']->workspace) {
          return false;
        } else {
            return $connection->exec_UPDATEquery($table, "uid = '" . intval($record['uid']) . "'", $record);
        }
    }
```

Record Changes will not longer shown in Live-WS, but the problem is now the sorting of records in Workspace Preview View (Frontend) ... 

The sorting of records are in database wrong but in BE it is ok, is there any additional sorting function in preview page layout rendering?

**Comment by NamelessCoder** [comment]
Solved by recent patches to workspace compatibility.
