### ISSUE TITLE
Transform relation-field value is not working when nested in section/object

### ISSUE THREAD

**Issue by fkalka** [FluidTYPO3/flux#1191]
Hello,
the following Code does not work for me:

```
<flux:form.section name="beuserSection" label="Users">
  <flux:form.object name="beuserObject" label="User">
    <flux:field.relation name="beuser" label="User" table="be_users" transform="TYPO3\CMS\Extbase\Domain\Model\BackendUser" />
  </flux:form.object>
</flux:form.section>`
```

If i debug the Variable, it contains only the UID.

On the other hand
`<flux:field.relation name="beuser" label="User" table="be_users" transform="TYPO3\CMS\Extbase\Domain\Model\BackendUser" />`
without Section/Object works as expected, i get the actual Object when debugging the value.

Can anyone confirm this?

Flux: 7.4.0
VHS: 3.0.1
TYPO3: 7.6.10 and 7.6.11

**Comment by pixelplant** [comment]
I'm getting the same in TYPO3 7.6.15 with latest dev versions of VHS and Flux. Works great when defined outside  a section/object, while it only renders the uid for the relations stored inside a section/object.
