### ISSUE TITLE
FLUX: missing DBAL Doctrine in Typo3 8.3.1

### ISSUE THREAD

**Issue by kurtwithslc** [FluidTYPO3/flux#1193]
Testing fluidpages etc. in Typo3 8.3.1 results in error:
Argument 1 passed to TYPO3\CMS\Backend\View\PageLayoutView::getResult() must implement interface Doctrine\DBAL\Driver\Statement, boolean given, called in /html/typo3/typo3conf/ext/flux/Classes/View/PreviewView.php on line 525

**Comment by cedricziel** [comment]
What version of flux do you use?

**Comment by kurtwithslc** [comment]
Hi cedric,

7.4.0 / actual version downloaded from Github

Beste Grüsse
Kurt Knote

Mühlweg 39
D-92637 Weiden
kurt.knote@t-online.de

**Comment by kurtwithslc** [comment]
One bug seems to be in CORE -> Bug #78353
_PageLayoutView::makeQueryArray (inherited from AbstractDatabaseRecordList) creates invalid SQL_
Implementing the solution for this bug, Typo3 Backend gives no SQL-Bug Report anymore, but the exception report remains: Argument 1 passed to TYPO3\CMS\Backend\View\PageLayoutView::getResult() must implement interface Doctrine\DBAL\Driver\Statement, instance of mysqli_result given, called in /html/typo3/typo3conf/ext/flux/Classes/View/PreviewView.php

**Comment by kurtwithslc** [comment]
Problem solved with solution for CMS Bug #78096
