### ISSUE TITLE
flux:content.render creates not rendered output (Typo3 8.3.1)

### ISSUE THREAD

**Issue by kurtwithslc** [FluidTYPO3/flux#1199]
Rendering with <flux:content.render ... gives this result in FE:

&lt;div id="c28"&gt; &lt;div class="ce-textpic ce-center ce-above"v &lt;div class="ce-bodytext"&gt; &lt;h3 style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); margin-top: 20px; margin-bottom: 10px; font-size: 24px; "&gt;Dear reader,&lt;/h3&gt;

Adding f:format.raw  
&lt;f:format.raw>&lt;flux:content.render ... &lt;/f:format.raw> gives correct output:

Dear reader,
Thank you for your interest in the Fluid Powered TYPO3 project!

Flux 7.4.0, Typo3 8.3.1, fluid_styled_content 8.3.0

**Comment by NamelessCoder** [comment]
Fixed by setting `escapeOutput` behavior in this and other ViewHelpers.
