### ISSUE TITLE
Reference link defect?

### ISSUE THREAD

**Issue by nielsweb** [FluidTYPO3/flux#1200]
Hi Claus,

I noticed that the reference link in TYPO3 (7.6) backend with flux installed does not work. By clicking the link symbol, the entire backend opens in the right frame. I've found a ticket, but no solution to this issue: https://forge.typo3.org/issues/75544

My current workaround is to click on the content element icon, choose _info_ and edit the content element in pop up by clicking the title. Do you have a solution to fix this problem?

Thank you,
Niels

**Comment by NamelessCoder** [comment]
Hi Niels,

Looks like there's a bit of link generating we need to migrate. The solution is to copy the method used to build the link in the core's PageLayoutView class - if you're up to creating a pull request one that does this would be very welcome!

Cheers,
Claus

**Comment by NamelessCoder** [comment]
"Paste as reference" has been removed. There is an almost-as-easy-to-use procedure described on https://github.com/FluidTYPO3/flux/issues/1305#issuecomment-328512665.
