### ISSUE TITLE
flux:form.data returns empty array from parent pi_flexform

### ISSUE THREAD

**Issue by EdRoxter** [FluidTYPO3/flux#1216]
I have a template in which I'd like to set some things depending on a setting of its parent element, if applicable.

I want to try basically the same as @jenses in #801, but the returned array is always empty.

Snip:

    <flux:form.data table="tt_content" field="pi_flexform" uid="{data.tx_flux_parent}" as="mycontent">
      
      <f:debug>{mycontent}</f:debug>
    </flux:form.data>

Results: The line with Fluxparent shows the correct uid of the parent element. The line with `mycontent.settings.layout` is empty. The debug output shows `array (empty)`, so the field appears not to be parsed at all.

It definitely contains something - this is the raw content of the corresponding MySQL cell:

    <?xml version="1.0" encoding="utf-8" standalone="yes" ?>
    <T3FlexForms>
        <data>
            <sheet index="options">
                <language index="lDEF">
                    <field index="settings.layout">
                        <value index="vDEF">4</value>
                    </field>
                    <field index="settings.green">
                        <value index="vDEF"></value>
                    </field>
    [...]
                </language>
            </sheet>
        </data>
    </T3FlexForms>

Now what's really curious is the fact that _it works flawlessly_ when I try to select something from `content_settings` (for example `.settings.header.type`) instead of `pi_flexform`. But the entity I want to select is in `pi_flexform`, sadly.

This shouldn't actually make a difference, right? Could someone please look into this?

Edit & P.S.: Could it be something about the current element being a custom replacement for textmedia content type, and the parent element is fluidcontent_content?

**Comment by NamelessCoder** [comment]
Thanks for the detailed description @EdRoxter - we'll look into this. Re: your P.S, no, the type of current template should have no relevance whatsoever when you do as you do and specify the table, field and proper Flux parent ID. You should even be able to do this from a FLUIDTEMPLATE or EXT:news template.

Mentioning @mneuhaus here since I know he had a possibly related issue caused by this being in a multilanguage setup combined with the removal of nested language supports in FlexForms. Maybe that gives you a hint or something to try in case your setup is also a multilanguage setup...

**Comment by EdRoxter** [comment]
Thanks for the quick reply @NamelessCoder !

It is indeed a multilanguage setup, if that helps anything.

**Comment by NamelessCoder** [comment]
You could help us if you check out https://github.com/FluidTYPO3/flux/pull/1215 and let us know if that solves it then! :)

**Comment by EdRoxter** [comment]
Just checked it and it does fix it - thanks very much, looking forward to the next upstream release, and wish you a nice weekend! :)

**Comment by NamelessCoder** [comment]
Excellent news and thanks so much for confirming the PR so quickly! In it goes :)

**Comment by typo3ua** [comment]
**I use:**
TYPO3 8.7.10
FLUX 8.2.1
```
<flux:form.data table="tt_content" field="pi_flexform" uid="1" as="flexformData">
               {flexformData -> f:debug()}
</flux:form.data>
```
**I'm getting array (empty)**
