### ISSUE TITLE
Call to a member function resolveConfigurationProviders() on null

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/flux#1228]
After the recent update (dev-development) I get an error after pages are in the cache (works one time after clearing the cache):

Call to a member function resolveConfigurationProviders() on null 
Error thrown in file
/srv/www/client/typo3conf/ext/flux/Classes/ViewHelpers/Form/DataViewHelper.php in line 110.
82 FluidTYPO3\Flux\ViewHelpers\Form\DataViewHelper::renderStatic(array, Closure, TYPO3\CMS\Fluid\Core\Rendering\RenderingContext)
/srv/www/client/typo3temp/Cache/Code/fluid_template/MyTemplate_Content_partial_Content_SomeFluidContent_8966be7ef7ad090acc4055e607607feb886797eb.php: …

This line makes problems:

$providers = static::$configurationService->resolveConfigurationProviders($table, $field, $record);

Any hints on how to resolve this issue?
TYPO3 7.6, all flu* extensions updated;

**Comment by cedricziel** [comment]
Thank you for reporting. I found the issue and will prepare a fix ASAP.

**Comment by cedricziel** [comment]
@wazum I would like you to test whether the current development branch state fixes the issue. If not, feel free to re-open the case.

Thank you for bringing this to our attention! :)

**Comment by wazum** [comment]
Sorry, I don't know how to re-open this issue … too bad it still occurs … do you need a full stack trace (via pm)?

**Comment by cedricziel** [comment]
Nope, thank you. @NamelessCoder brought another issue to my attention.

**Comment by wazum** [comment]
Morning, any news on that? Which commit is not already affected from this bug, so I can go back for now? Tia

**Comment by cedricziel** [comment]
Moin,

I'm not entirely sure about that but you'd do me a favor if you tried.

Thx!

**Comment by wazum** [comment]
The bug occurs after removing typo3-cms-fluid-gap (after commit #965781feec0b943542dd6e11e2e29120f22a3311)

**Comment by cedricziel** [comment]
Do you run the most recent version of TYPO3 7.6?

**Comment by wazum** [comment]
7.6.14, all the Trait Classes from Fluid are there,
and all the flu* and vhs are updated as well (development)

Part of the stack trace
```Uncaught TYPO3 Exception
Call to a member function resolveConfigurationProviders() on null 

Error thrown in file
/var/www/clientxy/typo3conf/ext/flux/Classes/ViewHelpers/Form/DataViewHelper.php in line 110.

78 FluidTYPO3\Flux\ViewHelpers\Form\DataViewHelper::renderStatic(array, Closure, TYPO3\CMS\Fluid\Core\Rendering\RenderingContext)

/var/www/clientxy/typo3temp/Cache/Code/fluid_template/FluidcontentCore_CoreContent_layout_Default_2eb4ba015c4ce4d1166c5828861b64a898b46ada.php:
00070: };
00071: 
00072: $output0 .= FluidTYPO3\Flux\ViewHelpers\Form\DataViewHelper::renderStatic($arguments4, $renderChildrenClosure5, $renderingContext);
00073: 
00074: $output0 .= '

77 FluidCache_FluidcontentCore_CoreContent_layout_Default_2eb4ba015c4ce4d1166c5828861b64a898b46fda::render(TYPO3\CMS\Fluid\Core\Rendering\RenderingContext)

/var/www/clientxy/typo3_src/typo3/sysext/fluid/Classes/View/AbstractTemplateView.php:
00187:             }
00188:             $this->startRendering(self::RENDERING_LAYOUT, $parsedTemplate, $this->baseRenderingContext);
00189:             $output = $parsedLayout->render($this->baseRenderingContext);
00190:             $this->stopRendering();
00191:         } else {

76 TYPO3\CMS\Fluid\View\AbstractTemplateView::render()

/var/www/clientxy/typo3_src/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00310: 
00311:         if ($actionResult === null && $this->view instanceof ViewInterface) {
00312:             $this->response->appendContent($this->view->render());
00313:         } elseif (is_string($actionResult) && $actionResult !== '') {
00314:             $this->response->appendContent($actionResult);

75 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::callActionMethod()

/var/www/clientxy/typo3_src/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php:
00174:             $this->initializeView($this->view);
00175:         }
00176:         $this->callActionMethod();
00177:     }
00178: 

74 TYPO3\CMS\Extbase\Mvc\Controller\ActionController::processRequest(TYPO3\CMS\Extbase\Mvc\Web\Request, TYPO3\CMS\Extbase\Mvc\Web\Response)

/var/www/clientxy/typo3conf/ext/flux/Classes/Controller/AbstractFluxController.php:
00309:         $subRequest->setControllerActionName($this->provider->getControllerActionFromRecord($row));
00310:         try {
00311:             $potentialControllerInstance->processRequest($subRequest, $response);
00312:         } catch (StopActionException $error) {
00313:         }

73 FluidTYPO3\Flux\Controller\AbstractFluxController::callSubControllerAction("FluidTYPO3.FluidcontentCore", "FluidTYPO3\FluidcontentCore\Controller\CoreContentController", "text", "tx_fluidcontentcore_text")

/var/www/clientxy/typo3conf/ext/flux/Classes/Controller/AbstractFluxController.php:
00253:                     $controllerName
00254:                 );
00255:             return $this->callSubControllerAction(
00256:                 $extensionName,
00257:                 $foreignControllerClass,

72 FluidTYPO3\Flux\Controller\AbstractFluxController::performSubRendering("FluidTYPO3.FluidcontentCore", "CoreContent", "text", "tx_fluidcontentcore_text")

/var/www/clientxy/typo3conf/ext/flux/Classes/Controller/AbstractFluxController.php:
00218:         $actualActionName = null !== $requestActionName ? $requestActionName : $controllerActionName;
00219:         $controllerName = $this->request->getControllerName();
00220:         return $this->performSubRendering(
00221:             $controllerExtensionKey,
00222:             $controllerName,

71 FluidTYPO3\Flux\Controller\AbstractFluxController::renderAction()
```

**Comment by cedricziel** [comment]
@NamelessCoder I think it's happening when rendering FCC elements, could you chime in on the issue?

**Comment by cedricziel** [comment]
We're pretty confident this should fix your problem.

**Comment by wazum** [comment]
When the bug you introduced is fixed (no GeneralUtility and ObjectManager import) ;-) it works hooray! Thanks a lot!

**Comment by cedricziel** [comment]
Yeah, sorry about that. :-/

Have a nice day!

**Comment by wazum** [comment]
> On 5 Dec 2016, at 15:12, Cedric Ziel <notifications@github.com> wrote:
> 
> Yeah, sorry about that. :-/
> 

No problem, thanx for the fast support,
I'll talk to my bosses so they will spend some money to the project

**Comment by NamelessCoder** [comment]
@wazum please forward a big "thank you!" to your boss(es) for the kind donation. I'll put that to good use for a day of priority work before the expected release on December 15th/16th :)
