### ISSUE TITLE
Bug in function generateUniqueIntegerForFluxArea (Classes/Utility/MiscellaneousUtility.php)

### ISSUE THREAD

**Issue by rastocs2** [FluidTYPO3/flux#1233]
this calculation is really bad, because can return same value for different CE!
e.g.
fluxarea contains 6 columns with names "col1"..."col6"
put this fluxarea on same page twice (CE1: uid=10 and CE2:uid=11)
then calculated number in CE2 for "col1" will same like number in CE1 for "col2", etc...

need change it to something like this:
<pre>
	/**
	 * @param integer $contentElementUid
	 * @param string $areaName
	 * @return integer
	 */
	public static function generateUniqueIntegerForFluxArea($contentElementUid, $areaName) {
		$integers = array_map('ord', str_split($areaName));
		$string = (string)array_sum($integers);
		$string.= (string)(intval($contentElementUid));
		return 0 - (intval(substr($string,-11)) + self::UNIQUE_INTEGER_OVERHEAD);
	}
</pre>

**Comment by NamelessCoder** [comment]
Duplicates https://github.com/FluidTYPO3/flux/pull/1190 - @BenjaminBeck is kindly working on that one and we've agreed on a solution :)
