### ISSUE TITLE
flux:form:variable does not work correct

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1236]
I want to allow only 2 custom elements in a flux:grid.column:

<flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
 <flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'myext:Section.html','myext:Slide.html'}" />

with one Type in second line it works correct, but with these two i get the opposite: all other elements of myext except those 2.

**Comment by NamelessCoder** [comment]
You have a syntax error in the value of the `Fluidcontent` array:

```
'myext:Section.html','myext:Slide.html'
```

Must be:


```
'myext:Section.html,myext:Slide.html'
```

Since you must build a CSV value (or an array, but the CSV is a lot easier to manage).

**Comment by steffenk** [comment]
Thanks, sometimes it's hard to figure out the error while looking all the time to 2 lines of code ... :)
