### ISSUE TITLE
renderMode option deprecated

### ISSUE THREAD

**Issue by instruccionesaldorso** [FluidTYPO3/flux#1238]
TYPO3 7.x says: "renderMode" setting for select fields is deprecated.
Shouldn't be this removed as attribute from viewhelpers based on "select" type and "renderType" being supported?
For example here, "renderType" is not added:
https://fluidtypo3.org/viewhelpers/flux/master/Field/RelationViewHelper.html

**Comment by NamelessCoder** [comment]
Thanks for the heads-up :) code is now scheduled for removal - will close this issue to keep the tracker as clean as possible.
