### ISSUE TITLE
<flux:field.text name="tt_content.bodytext" /> does not work

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/flux#1250]
hi
typo3 7.6.14
latest TER Flux

``` <flux:field.text name="tt_content.bodytext" /> ```
does not work (save always in flexform)
```<flux:field.text name="tt_content.header" />```
works perfect!

**Comment by fkalka** [comment]
I can confirm this Bug (TYPO3: 7.6.11 / Flux: latest TER).
Although the Field tt_content.header is saved to the tt_content field, it is also present in the pi_flexform field.

**Comment by thopra** [comment]
I've tracked this issue down to this [condition](https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/AbstractProvider.php#L636) in \FluidTYPO3\Flux\Provider\AbstractProvider::preProcessRecord

    if (isset($row[$realKey])) {
        $row[$realKey] = $value['vDEF'];
    }

Since the incoming `$row` does not contain fields that are hidden in the current type, `tt_content.bodytext` (or any other field not present in the backend form) will not be overwritten.

The fix should be fairly simple by removing the condition at all. It shouldn't be necessary, because fields that are not present in the database will (afaik) just be ignored by the DataHandler. Haven't had the chance to extensively test it yet, though.

**Comment by NamelessCoder** [comment]
Thanks for investigating, @thopra - however, at the very least we should confirm that $realKey is a valid TCA column name before we go setting it into $row, or very bad things will happen ;)

**Comment by thopra** [comment]
I guess you're right.

for the record, I was able to solve my specific problem by XCLASSing fluidcontent's ContenProvider with the following, which works fine for me (TYPO3 7.6.15, Flux 7.4.0, Fluidcontent 4.4.1).


```

<?php 
namespace VENDOR\MyExtension\Xclass\Fluidcontent\Provider;
use TYPO3\CMS\Core\DataHandling\DataHandler;

/**
 * This xclass fixes a bug in flux where record columns could not be merged properly with the flexform values
 * @see https://github.com/FluidTYPO3/flux/issues/1250
 */
class ContentProvider extends \FluidTYPO3\Fluidcontent\Provider\ContentProvider {

    /**
     * Pre-process record data for the table that this ConfigurationProvider
     * is attached to.
     *
     * @param array $row The record by reference. Changing fields' values changes the record's values before display
     * @param integer $id The ID of the current record (which is sometimes now included in $row
     * @param DataHandler $reference A reference to the DataHandler object that is currently displaying the record
     * @return void
     */
    public function preProcessRecord(array &$row, $id, DataHandler $reference)
    {
        $fieldName = $this->getFieldName($row);
        $tableName = $this->getTableName($row);
        if (is_array($row[$fieldName]) && isset($row[$fieldName]['data']['options']['lDEF'])
            && is_array($row[$fieldName]['data']['options']['lDEF'])) {
            foreach ($row[$fieldName]['data']['options']['lDEF'] as $key => $value) {
                if (0 === strpos($key, $tableName)) {
                    $realKey = array_pop(explode('.', $key));
                    
                    // Fix #1250 BEGIN
                    if (isset($GLOBALS['TCA'][$tableName]) && isset($GLOBALS['TCA'][$tableName]['columns'][$realKey])) {
                        $row[$realKey] = $value['vDEF'];
                    }
                    // Fix #1250 END
                }
            }
        }
    }

}

```

However, please be aware that this solution does not take exclude fields into account. If the template author chooses to use a name matching an exclude field, a user without proper permissions will be able to see and edit that field in the flexform - but it will NOT be saved to the matching column.  You might also want to look into that, while you're at it (or at least mention that in the docs).

**Comment by glucka** [comment]
It works great! Thanks!!!! @NamelessCoder @thopra

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Vom 10. bis und mit 13. Sept. 2017 bin ich ausser Lande, und deshalb im Büro nicht erreichbar.
 
Die Nachrichten werden in dieser Zeit nicht gelesen! In dringenden Angelegenheiten bitte ich Sie, ein SMS zu schreiben oder eine Sprachnachricht zu hinterlassen. Vielen Dank!

Frohe Grüsse

Damian Parpan


ACHTUNG, NEUE ADRESSE SEIT DEM 6. SEPT. 2017:

Damian Parpan
appline
Obergrundstrasse 70
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch
