### ISSUE TITLE
Broken Flux by migration to TYPO3 7.6.14

### ISSUE THREAD

**Issue by snduesel** [FluidTYPO3/flux#1267]
Hi

i get an error by migration from 6.2 to 7.6.14
 
> Flux manifest file not found! I looked for /typo3conf/ext/my_extended_flux/flux.json - make sure the manifest exists. 
FluidTYPO3\Flux\Package\PackageNotFoundException thrown in file \typo3conf\ext\flux\Classes\FluxPackage.php in line 119.

Why is the file "flux.json" in my_extended_flux necessary?

**Comment by NamelessCoder** [comment]
Please include the versions of extensions you use - and confirm that the problem you report is not already solved, by using branch `dev-development` of Flux. NB: your extension MUST be installed but the flux.json manifest is NOT required (it is optional and allows a non-php method of declaring provider extensions' integrations).

**Comment by snduesel** [comment]
Hi @NamelessCoder 

the issue isn't solved.

i use the newest versions of the following extensions.

- flux-dev
- fluidcontent-dev
- my_extended_flux is a custom extension. Here i use the the flux api. I have only migrated the php registration from ext_tables.php to ext_localconf.php [3.1.4 Registration in PHP](https://fluidtypo3.org/documentation/templating-manual/templating/provider-extension/registration-in-php.html). The Extension still working in TYPO3 6.2.

**Comment by NamelessCoder** [comment]
What does your ext_localconf.php file contain?

**Comment by snduesel** [comment]
Only the registration in PHP

ext_localconf.php
```
<?php
if (!defined('TYPO3_MODE')) {
    die ('Access denied.');
}

//\FluidTYPO3\Flux\Core::registerProviderExtensionKey('anything', 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('anything', 'Content');
```
ext_tables.php
```
<?php
if (!defined('TYPO3_MODE')) {
    die ('Access denied.');
}
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript', 'anything');

// Speaker Plugin
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
		$_EXTKEY,
		'Speakers',
		'LLL:EXT:anything/Resources/Private/Language/locallang_db.xml:tx_anything_plugin.speakers'
);
```

**Comment by snduesel** [comment]
Issue is solved. I have delete the complete typo3temp/*. Now it's running...

**Comment by cedricziel** [comment]
Thx for the feedback!
