### ISSUE TITLE
[BUG][TYPO3-7.6] The property "options.Fluidcontent.sorting" on the subject was not accessible

### ISSUE THREAD

**Issue by stespot** [FluidTYPO3/flux#1281]
Hello FluidTYPO3 team, 

We tried installing the latest **Flux 8.0.0** on our TYPO3 7.6.15 websites, but it does give us the error `The property "options.Fluidcontent.sorting" on the subject was not accessible` when having more than one Fluidcontent element (using a provider extension, tried with a clean one from the Builder extension).

We found that inside the method **sortObjectsByProperty** in flux/Classes/Service/FluxService.php, line 147-148, changing `ObjectAccess::getProperty` to `ObjectAccess::getPropertyPath` fixes this.

I don't know if this is a correct fix or can cause problems (the old code used getPropertyPath) so I haven't made a Pull Request.

Also the _options.Fluidcontent.sorting_ path shall be changed to _options.sorting_? (Using the new flux viewhelper `<flux:form.option.sorting value="100" />` does generate the latter, but Fluidcontent still uses _options.Fluidcontent.sorting_ in fluidcontent/Classes/Service/ConfigurationService.php, line 303).

**Comment by TheNaderio** [comment]
I deleted all of my (21) FCE's in my extension and found out that you can have one FCE without problems. The second one throws the exception.

The changes by @stespot (thank you!) in `ObjectAccess::getProperty` can solve it for me too. The exception is gone and sorting works well.

**Comment by NamelessCoder** [comment]
@stespot getPropertyPath is the solution - feel free to prepare a pull request!

**Comment by stespot** [comment]
Thank you, I made a pull request, I hope it's ok. #1283

**Comment by NamelessCoder** [comment]
Merged
