### ISSUE TITLE
flux:form.container shows wrong element

### ISSUE THREAD

**Issue by seamofreality** [FluidTYPO3/flux#1291]
Flux version: 7.4.0
Typo3 version: 7.6.14

When I am trying to create a `flux:form.container` within my `flux:form` it doesn't show the defined fields as expected, but what I'd more likely expect from a `flux:form.section` and `flux:form.object` combination. To make sure it's not due to my field names or similiar things I tested it with the example provided by the fluidtypo3 ViewHelper reference. (See: https://fluidtypo3.org/viewhelpers/flux/master/Form/SectionViewHelper.html)

So this is my code:
```
<f:section name="Configuration">
    <flux:form id="subpage">
        <flux:form.container name="settings.name" label="Name">
            <flux:field.input name="firstname" label="First name"/>
            <flux:field.input name="lastname" label="Last name"/>
        </flux:form.container>
    </flux:form>
</f:section>
```

And this is what I get in the backend:
![flux_form_container_output](https://cloud.githubusercontent.com/assets/4711781/22012783/2367fa2e-dc96-11e6-9c32-d650d871f30e.png)

Is there something I might have overlooked?
I emptied every possible cache - I know of - several times.

**Comment by monosize** [comment]
I got this warning with flux 8.0 and TYPO3 7.6.15

```
PHP Warning: Invalid argument supplied for foreach() in /Volumes/Work/Websites/typo3_src-dev/typo3/sysext/backend/Classes/Form/Container/FlexFormElementContainer.php line 48 

TYPO3\CMS\Core\Error\Exception thrown in file
/Volumes/Work/Websites/typo3_src-dev/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 111.
```

**Comment by monosize** [comment]
duplicate issue #1201

**Comment by NamelessCoder** [comment]
Please continue in https://github.com/FluidTYPO3/flux/issues/1201 - for posterity, this is an issue in FormEngine, not Flux.
