### ISSUE TITLE
flux:field.input - lack of renderType property

### ISSUE THREAD

**Issue by vaxul** [FluidTYPO3/flux#1294]
Currently flux:field.input doesn't allow to set the renderType, for example for the more modern colorpicker.

Is this planned?

Best regards

**Comment by NamelessCoder** [comment]
It is possible I'm behind, but it used to be that this use case is solved by adding a normal input field (which has no renderType) and fitting it with a color picker wizard which has "hideParentField" set to true. I'll take the liberty of assuming this is still correct and close this issue.

Keep in mind always: Flux is merely an abstraction of TCA. If something isn't possible in TCA, it's not possible in Flux - and if it is possible, the structure must be created in the same way you'd create it in TCA (e.g. with a wizard field + hideParentField).
