### ISSUE TITLE
flux:content.render doesn't assign to variable defined in as-attribute

### ISSUE THREAD

**Issue by vaxul** [FluidTYPO3/flux#1298]
TYPO3 CMS 7.6.15
fluidtypo3/fluidcontent 4.4.1 
fluidtypo3/flux 7.4.0

<flux:content.render area="content" /> works correct, but I have to use <flux:content.render area="content" render="1" as="widgets" /> for wrapping each content element.

I'd like to get the nested content elements and a rendered items within an array.

Unfortunately the variable _widgets_ isn't created of filled. 

Here the reduced example content element with fluidcontent:
```html
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">

	<f:layout name="Default" />

	<f:section name="Configuration">
		<flux:form id="content.block">
			<flux:grid>
				<flux:grid.row>
					<flux:grid.column name="content">
						<flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
						<flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'Vendor.Project:Widget.html'}" />
					</flux:grid.column>
				</flux:grid.row>
			</flux:grid>
		</flux:form>
	</f:section>

	<f:section name="Preview"></f:section>

	<f:section name="Main">
		<f:comment><v:variable.set name="widgets" value="" /><!-- < it makes no different with or without --></f:comment>
		<flux:content.render area="content" render="1" as="widgets" />
		{_all -> f:debug()}
		<f:if condition="{widgets}">
			<f:for each="{widgets}" key="index" as="widget">
				<div class="widget-{index}">
					{widget -> f:format.raw()}
				</div>
			</f:for>
		</f:if>
	</f:section>
</div>
```

For comparsion a similar, but working example to read content elements from a page columns with VHS v:content.render within a page template.

```html
<v:variable.set name="teasers" value="" /><!-- < It seems the variable has to be defined before to get this work -->
<v:content.render column="0" limit="5" render="1" as="teasers" />
```

I debugged the code from flux:content.render till [this line](https://github.com/FluidTYPO3/flux/blob/development/Classes/ViewHelpers/Content/GetViewHelper.php#L172). Before this line the rendered content elements are correctly assigned to the variable _widgets_ within $templateVariableContainer, but gets remove with $templateVariableContainer->remove($as) afterwards in [this line](https://github.com/FluidTYPO3/flux/blob/development/Classes/ViewHelpers/Content/GetViewHelper.php#L173).

It looks like a bug for me, but I am not 100% sure. 

I'm hoping for a flux v7.4 fix, since v8 isn't compatible with the latest fluidcontent version.

Best regards

**Comment by NamelessCoder** [comment]
The variable is only available inside tag contents. The only exception to this rule when working with "as"-capable ViewHelpers, is `f:variable` (brand new, not released) and `v:variable.set`. The variable does not have to be defined beforehand.

**Comment by vaxul** [comment]
Ah, that is quite different than I expected.

```html
<flux:content.render area="content" render="1" as="widgets">
	{_all -> f:debug()}
</flux:content.render>
```

So _widgets_ is available within variables.

> The only exception to this rule when working with "as"-capable ViewHelpers, is f:variable (brand new, not released) and v:variable.set. 

This doesn't work as usual. I only get the whole rendered block. Whats wrong?
```html
<v:variable.set name="widgets" value="{flux:content.render(area: 'content', render: 1)}" />
OR
{flux:content.render(area: 'content', render: 1) -> v:variable.set(name: 'widgets')}
```

Either way big thanks for the quick response. Have nice weekend.!

**Comment by NamelessCoder** [comment]
`v:content.get` with `render="1"` is able to return individual, but rendered, content elements. If you need further access to the content record use `v:content.get` without rendering, loop the records, do what you must with their properties, then `v:content.render` with `contentUids` argument to render a single content element.

To output HTML stored in a variable you must use `{variable -> f:format.raw()}` to avoid escaping.
