### ISSUE TITLE
flux ContentTypes don't respect TypoScript view configuration

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/flux#1308]
I'd expect to be able to override the view settings in TS like this

    plugin.tx_myext {
        view {
            partialRootPaths {
                10 = EXT:myext/Resources/Private/Partials/
                20 = EXT:myotherext/Resources/Private/Partials/
            }
        }
    }

But it doesn't work and I think I found the bug:

* flux processes the "queued" content type registrations using a hook in `Bootstrap::runExtTablesPostProcessingHooks()`
* At that time `GLOBALS['TSFE']->id` is not set yet.
* That's the reason the TypoScript can not be loaded.
* The View objects are built and cached at that early stage so they are not influenced by any TypoScript settings.

Tested with: TYPO3 7.6.15 and flux 8.0.0

**Comment by smichaelsen** [comment]
Here's a workaround: https://gist.github.com/smichaelsen/bb042731c4bf7852e416f2cf823dd4fb
It forces reading the plugin view settings again from TypoScript in the ContentController.

**Comment by NamelessCoder** [comment]
Thanks for the info / workaround! I am on the lookout for a more reasonable place where 1) TS is available and 2) TCA is available but 3) any content types have not yet been analysed.

**Comment by NamelessCoder** [comment]
This should now be solved in Flux when it concerns 7.6 LTS - but TYPO3 master is affected by an issue with the priority of template paths.

**Comment by smichaelsen** [comment]
Confirmed. I was able to remove my workarounds after updating to 8.0.1. Thanks a bunch!
