### ISSUE TITLE
displayCond inside form.object

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/flux#1310]
Hello 

Is displayCond not supposed to work when used on fields inside a form.object or is this a bug I'm currently experiencing? For fields outside form.object it works just fine. I am using Flux 8.0.0 and fluidcontent 5.0.0 with TYPO3 7.6.15

Here's a simple test for a fluidcontent element:
**With a working displayCond**, while not using form.object
```	
<f:section name="Configuration">
	<flux:form id="swiperHeader" options="{group: 'FCE'}">
		<flux:form.section name="slides">
			<flux:field.select name="tester" items="a,b" default="a" requestUpdate="1"/>
			<flux:field.input name="tester2" displayCond="FIELD:tester:=:a" />
		</flux:form.section>
	</flux:form>
</f:section>
```

"tester2" gets displayed or hidden, according to the value of the select element.

**This here does not work and displayCond is ignored**. No field is displayed whatever value I have in the select:
```	
<f:section name="Configuration">
	<flux:form id="swiperHeader" options="{group: 'FCE'}">
		<flux:form.section name="slides">
			<flux:form.object name="slide">
				<flux:field.input name="title" required="1" />
				<flux:field.text name="description"/>
				<flux:field.select name="show" requestUpdate="1" required="1" items="images,video" />
				<flux:field.file name="image" required="1" displayCond="FIELD:show:=:images" maxItems="1" minItems="1"/>
				<flux:field.input name="video" displayCond="FIELD:show:=:video"  />
				<flux:field.input name="link" >
					<flux:wizard.link/>
				</flux:field.input>
			</flux:form.object>
		</flux:form.section>
	</flux:form>
</f:section>
```

I also tried with all possible values for the field name, meaning displayCond="FIELD:show:=:video" or displayCond="FIELD:slide.show:=:video" or displayCond="FIELD:slides.slide.show:=:video", and none of these values work.

If it's a limitation of the system then it would be a shame, as this would be a really neat feature. In my case I am trying to allow the customer to create multiple slides, and for a slide he can either specify a link to a video or an image, but I'd like him to be able to specify the type and show only the corresponding field, based on his selection.

Or am I wrong in assuming this is how we're supposed to add repeating records in flux? Is there another way to do what I'm trying?

Thank you

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin krankheitshalber abwesend, und nur bedingt einsatzfähig!
 
Die Nachricht wird nicht weiter geleitet! In dringenden Angelegenheiten erreichen Sie mich zeitweise auf dem Mobile. Vielen Dank!

Gesunde Grüsse

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by NamelessCoder** [comment]
According to TYPO3, this was solved approximately one month ago - so make sure you've got a recent enough TYPO3 version to include this fix (or wait a couple more days and jump onto TYPO3 8.6).

See also: https://forge.typo3.org/issues/75646

Bugs like these belong as TYPO3 core bugs since Flux isn't processing the displayCond. We only define it, just like you would have done in a standard FlexForm without Flux. The second part of the checklist on https://fluidtypo3.org/blog/news/bugs-core-or-flux.html should be helpful when determining where to report issues! :)

**Comment by pixelplant** [comment]
Hello

I am using the latest v7, the 7.6.15. displayCond works really well when not used inside a form.object but is completely ignored when inside form.object, that's why I thought it might be a flux bug in the generation of the configuration. I will wait for the 8.6 or 7.6 /7.7 update and will retest. If it still occurs then I'll file a TYPO3 bug report.

Thanks
