### ISSUE TITLE
Can't add other flux element inside flux-grid column (flux:grid.column)

### ISSUE THREAD

**Issue by szytek** [FluidTYPO3/flux#1312]
Adding the flux element with button [+Content] to the flux-grid column doesn't work properly. The new content element will be added, but "tx_flux_column" column is missing (is just empty ''), so the new element is only visible in the list module. It does work for any other standard Typo3 element. Workaround for flux-elements: creating flux element outside flux-grid column and per drag-and-drop move to wanted position ( after that "tx_flux_column" is correct ).

`

     <f:section name="Configuration">
		<flux:form id="grid-50-50" label="Grid 50-50" options="{group:'FCE'}">
			<flux:grid>
				<flux:grid.row>
					<flux:grid.column name="leftColumn" colPos="0" label="Left Column" />
					<flux:grid.column name="rightColumn" colPos="1" label="Right Column" />
				</flux:grid.row>
			</flux:grid>
        </flux:form>
    </f:section>`

Extensions
 	fluid 					7.6.0 
	fluidcontent 			5.0.0 
	fluidpages 				4.0.0 
	flux 					8.0.1 
	vhs 					4.0.0 
	Typo3 					7.6.15

![flux-grid-problem](https://cloud.githubusercontent.com/assets/8003729/22645725/bce93e9c-ec68-11e6-9705-9bf52d2b3935.PNG)

**Comment by NamelessCoder** [comment]
Fixed in fluidcontent:dev-development, will release soon.

**Comment by matthiasnitsch** [comment]
@NamelessCoder Can you name the commit where this is fixed?

**Comment by torvitas** [comment]
Just ran into the same problem. Could you please point me to the commit id?

**Comment by torvitas** [comment]
https://github.com/FluidTYPO3/fluidcontent/commit/a51e40bfd71b33a2ba1283a7aab44a9f1f5fd8f1 most probably its this one

**Comment by NamelessCoder** [comment]
https://github.com/FluidTYPO3/fluidcontent/commit/a51e40bfd71b33a2ba1283a7aab44a9f1f5fd8f1 is indeed the commit that added tx_flux_parent and tx_flux_column to the TCA. It seems that if your content type doesn't allow this field, it gets ignored when you attempt to save the record - and that behavior may be new in TYPO3 (I can see how it might be considered a bug that the fields still apply if they're not shown).

**Comment by wabajwa** [comment]
Hi, I have also the same issue, i have posted the details of it as open issue in Speciality 
[https://github.com/Ecodev/speciality/issues/58](url), I am using Flux 8.0.2, and when i try to create the contents in grid column, it shows the entry in log but after save and close, nothing shown up. 
Any help would be appreciated. Thanks in Advance

**Comment by grimmcreative** [comment]
Putting this line to ext_tables.php of your Provider Extension solved the Problem:

require_once(TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('flux', 'Configuration/TCA/Overrides/tt_content.php'));

but i dont think its the nice way to do it.
