### ISSUE TITLE
flux:field.file uploadFolder not working any more

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#1320]
Before flux 8, I used flux:field.file as follows:
<flux:field.file name="image" label="Image" allowed="png,jpg" minItems="0" maxItems="1" size="1" uploadFolder="uploads/media" showThumbnails="TRUE" />

As of flux 8.0.1 the uploadFolder arguments seems not used any more. In the <f:section name="Main"> {image} returns the path to the original image such as fileadmin/user_upload/file.jpg and not the path to the copy of the file in uploads/media/file.jpg any more. This is kind of OK for new installations but is a breaking change to all existing installations base on flux 7 or before as all images are then instantly lost after update of EXT:flux to 8.x. 
Furthermore the documentation is rather unclear about this. It just says for attribute uploadFolder: "Upload folder. DEPRECATED, will be moved to the File field ViewHelper". It does not clearly state that this is breaking change, which already happened.

TYPO3 7.6.15

**Comment by mkrappitz** [comment]
Found the cause of this error - EXT:flux/Classes/Form/Field/File.php line 61:
$configuration['internal_type'] = 'file_reference';
needs to be 
$configuration['internal_type'] = 'file';
for uploadFolder to work. 
This should not be of type file_reference hardcoded in there to be backwards compatible. At least let the user choose the type with an argument in the viewhelper.

**Comment by Eumolp** [comment]
I can confurm this fix solves the problem.

Q: is there a new way of using images in sections? If possible I'd like to use file_references instead of the upload folder?

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin für Kurzferien vom 3. bis und mit 6. Mai 2017 abwesend.
 
Die Nachrichten werden in dieser Zeit nicht gelesen! In dringenden Angelegenheiten erreichen Sie mich zeitweise auf dem Mobile, oder hinterlassen Sie eine Nachricht, damit ich Sie zurückrufen kann. Vielen Dank!

Sonnige Grüsse

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by Ben305** [comment]
Is there a fix scheduled? I would like to continue to use the uploads folder.
