### ISSUE TITLE
Requirement for templateNameAction() in ContentController

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#1322]
As of flux 8.0.1 for each content element I create now there is a requirement for a controller action in my ContentController named like the template file. The blog post about flux 8 says this:

"Two noteworthy changes should be mentioned here. First, the new Flux feature to allow a Fluid template file (containing a Flux form) to be registered directly for use as a new content type (with a custom CType value!). All this requires is:
- A call in your provider extension's ext_localconf.php file to FluidTYPO3\Flux\Core::registerTemplateAsContentType with just two arguments: your provider extension's Vendor.ExtensionName formatted key and either an absolute, relative or EXT:-prefixed path to your template.
- The presence of a ContentController in your provider extension (in the default location) which contains an action named according to your template file (e.g. if your template file name is MyTemplate.html then your controller must have a myTemplateAction method). "

But I did not use registerTemplateAsContentType() and do not need a custom CType for each of my fluid content elements. I still use the "classic" way in ext_tables.php such as \FluidTYPO3\Flux\Core::registerProviderExtensionKey('VENDOR.Providerextension', 'Content'); to register my provider extension having content elements. Anyway I now have to have not a controller action for each of my content elements. The blog post does not say that there is also a controller action requirement in this case. I belive this is an error or another undocumented breaking change.

TYPO3 7.6.15

**Comment by wazum** [comment]
I can't confirm that (same versions used).
It still works only with registerProviderExtensionKey without a ContentController class.
As soon as you have your own ContentController class you need the methods, that's right.

**Comment by mkrappitz** [comment]
So this actually is a (kind of breaking) change! Before with version 7, you could have a(n empty) ContentController and only needed to have action methods in there for those content elements, where you actually needed them. This at least needs to be documented. 
Anyway the behaviour before I think was making more sense. Now for example if you have e. g. 20 content elements with only 1 where you need to preprocess something with an action method in your ContentController, you would have to create another 19 empty methods to make this work.

**Comment by NamelessCoder** [comment]
Fixed in 8.0.2 which was released today.
