### ISSUE TITLE
Content Element icon missing

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#1323]
In current flux 8.0.1 and fluidcontent 5.0.0 content element icons show up in new content element wizard, but are invisible in the page and in the list module on the elements and broken in the content element edit form.

I did not set any special icon and expected just the standard black extbase icon to show up:
<flux:form id="someid" label="Some label" description="Some description" options="{group: 'FCE'}">
...
</flux:form>

Working in content element wizard:
![grafik](https://cloud.githubusercontent.com/assets/5528239/22834809/c6121cf4-efb6-11e6-9ba3-f0f82dd5cff2.png)
(taken from typo3conf/ext/fluidcontent/Resources/Public/Icons/Plugin.svg as i can see in the BE markup)

invisible on element in page module:
![grafik](https://cloud.githubusercontent.com/assets/5528239/22834838/dd7b752a-efb6-11e6-9b4b-f81abaeba6ee.png)

invisible on element in list module:
![grafik](https://cloud.githubusercontent.com/assets/5528239/22834854/e99b7882-efb6-11e6-8d63-eb444c5c5f73.png)

broken in content element edit form:
![grafik](https://cloud.githubusercontent.com/assets/5528239/22853307/67b53612-f053-11e6-9f4a-624f302ab635.png)

TYPO3 7.6.15

**Comment by NamelessCoder** [comment]
Solved in dev-development, will be released to TER shortly.

**Comment by mkrappitz** [comment]
With fluidcontent, only the icon in list module is fixed. All other of the above noted icon problems remain the same.
