### ISSUE TITLE
Flux 8.0.2 incompatible

### ISSUE THREAD

**Issue by wabajwa** [FluidTYPO3/flux#1336]
Core: Error handler (FE): PHP Warning: Declaration of FluidTYPO3\FluidcontentCore\Provider\CoreContentProvider::injectConfigurationService(FluidTYPO3\FluidcontentCore\Service\ConfigurationService $configurationService) should be compatible with FluidTYPO3\Flux\Provider\AbstractProvider::injectConfigurationService(FluidTYPO3\Flux\Service\FluxService $configurationService) in C:\xampp\---

I am getting this error, i have installed the specialty package, using php 7 also typo3 7.6.15 version, no issue where is the issue. I have tried the solution given in this link,

https://github.com/FluidTYPO3/flux/pull/1048/commits/729eb52bd78ac5f907c720dfe86765ca308a6bc4#diff-0f301c879bc342879d203a8707a9068bL141

But, after it, i don't get my front end but this error went off from backend log. 
Thanks

**Comment by NamelessCoder** [comment]
Please use `dev-development` of fluidcontent_core until further notice. You should also prepare for the inevitable deprecation of fluidcontent_core in favor of a standard integration with fluid_styled_content, possibly integrated in Flux itself. Which basically means you should avoid fluidcontent_core in new projects.

**Comment by wabajwa** [comment]
Thank you so much. It worked for me, now i am facing this issue, can you please help me in it. 

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1289386765: Could not analyse class: "FluidTYPO3\Flux\ViewHelpers\Widget\GridViewHelper" maybe not loaded or no autoloader? Class FluidTYPO3\Flux\ViewHelpers\Widget\GridViewHelper does not exist | TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException thrown in file C:\xampp\project\vendor\typo3\cms\typo3\sysext\extbase\Classes\Object\Container\ClassInfoFactory.php in line 37. Requested URL: http://localhost/typo3/index.php?M=web_layout&moduleToken=abe8a4d2449ec4d2163272bb821c19fe016fd20c&id=1`

Thanks

**Comment by NamelessCoder** [comment]
Remove all references to `<flux:widget.grid />` and take a quick read through https://fluidtypo3.org/blog/news/coming-changes-in-flux-72.html, section with header "Preview Widget replaced".

**Comment by cedricziel** [comment]
Seems to me that's more of an upgrade issue than the incompatibility that's the core of this issue.

Please feel free to open issues if you encounter new ones. :)
