### ISSUE TITLE
Document alternative to flux:widget.grid

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1339]
flux version 8.0.0 removed `<flux:widget.grid>` via #1269.

`Classes/ViewHelpers/GridViewHelper.php` [still says](https://fluidtypo3.org/viewhelpers/flux/master/GridViewHelper.html) that widget.grid should be used to render content element previews in the backend.

Please advice and document what should be used instead.

**Comment by TheNaderio** [comment]
Just remove <flux:widget.grid/> from your <preview>.

**Comment by NamelessCoder** [comment]
Good catch, @cweiske - I updated the phpdoc header for the VH to bring it up to date :)
