### ISSUE TITLE
v:page.info in the backend

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/flux#1344]
Is v:page.info not supposed to work in the backend?

So far if I call it in my "Preview" section I get an "Call to a member function getPage_noCheck() on null " error, and that's because the ViewHelper does this call in the renderStatic method:
```
$page = $GLOBALS['TSFE']->sys_page->getPage_noCheck($pageUid);
```
and of course $GLOBALS['TSFE'] only exists in the front.

It would be nice if we could retrieve page information in the backend too, as sometimes it's useful when selecting pages to show their details in the BE preview

**Comment by monosize** [comment]
@pixelplant see https://github.com/FluidTYPO3/vhs/issues/1250 and https://github.com/FluidTYPO3/vhs/pull/1251

**Comment by cedricziel** [comment]
To expand a little on the tickets Frank mentioned, we don't think it's a good idea to jump through the hoops and consider it a bad idea to access any other table than the one you're most probably rendering (tt_content), which is available already.

If you need it badly, consider building yourself a small utility viewhelper that uses `BackendUtility::getRecord` or the like.

`v:page.info` will begin to throw when used in the backend as soon as @bjo3rnf finishes the PR.
