### ISSUE TITLE
flux:field.select - default value didn't work in form.section

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/flux#1345]
I tried something like:
```
<flux:form.section name="testsection">
	<flux:form.object name="testobject">
		<flux:field.select name="testfield" default="second"
		 items="{
			1:{0:'First choice',1:'first'},
			2:{0:'Second choice',1:'second'},
			3:{0:'Third choice',1:'third'}
			}"
		/>
	</flux:form.object>
</flux:form.section>
```

When I use the `<flux:field.select />` as standalone field there is no problem with the predefined default value.
But when I use it like in the example here, it will everytime chose the first value.

I've tried different ways as workaround.
The only thing that works (but looks ugly) is to use `default="{0:'second'}"`.
This selects the default option but adds an unwanted option on the top Position:
![image](https://cloud.githubusercontent.com/assets/25088164/23381256/16bb1662-fd3e-11e6-9f2f-812466021216.png)

**Comment by NamelessCoder** [comment]
Please report this issue to the TYPO3 core bug tracker - https://forge.typo3.org/projects/typo3cms-core/issues. Flux does not render HTML of the components you use, we only create TCA. For a more in-depth explanation about how to distinguish Flux bugs from core bugs, see https://fluidtypo3.org/blog/news/bugs-core-or-flux.html.
