### ISSUE TITLE
Grid Preview shows duplicate entries

### ISSUE THREAD

**Issue by matthiasnitsch** [FluidTYPO3/flux#1353]
I file this under flux because I think the issue is a flux not fluidcontent probelm.

We have the strange behaviour that in an accordion element wie add maybe add two accordion panels, but in deh backend preview. Every panel gets rendered twice. Frontend looks normal.

My configuration for the element is like:

```
<f:section name="Configuration">
	<flux:form options="{group: 'Bootstrap'}" id="accordion">
		<flux:form.sheet name="panels">
			<flux:form.section name="panels">
				<flux:form.object name="panel">
					<flux:field.text name="title" rows="3" />
					<flux:field.checkbox name="active" />
					<flux:field.select name="class" items="default,primary,success,info,warning,danger" default="default"/>
				</flux:form.object>
			</flux:form.section>
		</flux:form.sheet>
		<flux:grid>
			<f:for each="{panels}" as="panel" iteration="iteration">
				<flux:grid.row name="row.{iteration.index}">
					<flux:form.content name="content.{iteration.index}" label="{f:if(condition: panel.panel.title, then: panel.panel.title, else: 'Content, panel {iteration.cycle}')}" />
				</flux:grid.row>
			</f:for>
		</flux:grid>
	</flux:form>
</f:section>
```
Flux, Fluidcontent are on latest versions, TYPO3 is on 7.6.

Any hint how this problem could be fixed would be nice.

**Comment by monosize** [comment]
you can't use `<flux:form.content>` inside a `<flux:grid>`use a `<flux:grid.column>`

more info here https://fluidtypo3.org/viewhelpers/flux/master/Form/ContentViewHelper.html

**Comment by NamelessCoder** [comment]
Fix suggested by @monosize will solve this issue.
