### ISSUE TITLE
Template could not be loaded

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/flux#1354]
Error: Template could not be loaded. I tried "/typo3conf/ext/some/Resources/Private/Templates/Content/Render.html", "/typo3conf/ext/some/Resources/Private/Templates/Content/render.html"

I try to understand whats happening here. As you can see it only tries to render the content element:

<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
     xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

    <f:layout name="Content" />
    <f:section name="Configuration">
	<flux:form id="capacity_download" label="Capacity Download" description="Select a PDF Document for the Capacity" options="{group: 'Boxes', icon: '{f:uri.resource(path: \'Icons/text_image.gif\', extensionName: \'some\')}'}">
	    <flux:form.sheet name="Download" label="File">
                <flux:field.file name="capacityfile" label="Capacity File" maxItems="1" allowed="pdf"/>
                <flux:field.input name="filelabel" label="File Label"/>
	    </flux:form.sheet>
	</flux:form>
    </f:section>

    <f:section name="Preview">
	<f:if condition="{filelabel}">
	    <f:then>
		<p class="pdf_capacity"><f:link.external uri="http://.../{capacityfile}" class="pdf_capacity">{filelabel} (PDF)</f:link.external></p>
	    </f:then>
	</f:if>
    </f:section>

    <f:section name="Main">
	<f:if condition="{filelabel}">
	    <f:then>
			<p class="pdf_capacity"><f:link.external uri="http://.../{capacityfile}" class="pdf_capacity" target="_blank">{filelabel} (PDF)</f:link.external></p>
	    </f:then>
	</f:if>
    </f:section>
</div>

It is old code I try to migrate so far. Using Flux 8.0.2

please see trace attached.
[render-exception.txt](https://github.com/FluidTYPO3/flux/files/811427/render-exception.txt)

I'm grateful for any hint.

**Comment by NamelessCoder** [comment]
Hi @webloft - I think we need a tiny bit more information:

* Which TYPO3 version are you using? LTS and 8.x branches differ a bit in template resolving so knowing which it is will help a lot. It *looks* like LTS from the exception trace but I'd better ask to make sure ;)
* What is the filename of your template?
* Is this a fluidcontent-registered template or are you converting it to the new CType feature in Flux?
* Does your content template have a controller class associated with it - and if so, does it also have an associated action method? Which class does it declare as parent class?
* Is the problem the same if you create a new element based on this template? (if your extension name changed at any point then DB needs to be updated)
* Are you overriding `templateRootPaths` of fluidcontent? (this is not expected)

With the above I should be able to reproduce the problem - and you might even find the cause for the problem in one or more of the items.

**Comment by webloft** [comment]
- TPYO3: 7.6.16 (isnt it LTS? - the one you get by get.typo3.org/current currently)
- Template: `typo3conf/ext/some/Resources/Private/Templates/Content/capacity_download.html`
- It was previoulsy registered by typoscript `plugin.tx_fed.fce` / I have changed to `registerProviderExtensionKey()` and set up the typoscript view paths.
- No controler. Just a simple fluidcontent element.
- Yes. I can select the element in content properties. 
- No

I forgot: I can select the element in the backend, but it shows no valid flexform - there is just a standard "the title" field or something.

**Comment by webloft** [comment]
Finally found the problem: the filename of the element doesn't start with uppercase letter. It is not directly flux related. Please raise an exception if fluidcontent found such a filename in Content.
