### ISSUE TITLE
flux:form, no label, no description and no own tab in the wizardTab (TYPO3 8.6.0)

### ISSUE THREAD

**Issue by rico3000** [FluidTYPO3/flux#1357]
I'm using a clean and new TYPO3 8.6.0 and flux:8.02 (and tested the current development branch) with the new registerTemplateAsContentType in my ext_localconf.php.

```php
\FluidTYPO3\Flux\Core::registerTemplateAsContentType(
 '…',
 \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('…', 'Resources/Private/Templates/Content/Twocols.html')
);
```

My Twocols.html starts the following way:

```html
<f:section name="Configuration">
 <flux:form id="twocols" label="Twocols" description="lorem ipsum" options="{group: 'own group '}">
```

With the option parameter nothing appears, if I remove the options parameter I see the default named new Tab: *Flux content* with one element: TYPO3 icon without name or description. I can choose it and everything works in the backend like wanted. 

I tried different things with *label="LLL:* and the option: *localLanguageFileRelativePath* but I didn't get any label or description output. 

Has anyone any advice? 

Update: I switched back to
```php
\FluidTYPO3\Flux\Core::registerProviderExtensionKey(
 '…',
 'Content'
);
```
and everything works.

**Comment by BenjaminBeck** [comment]
Hi @rico3000 
i had the same question with ``registerTemplateAsContentType`` but i figured out that you must follow these conventions:
``ext/{your_extension}/Resources/Private/Language/locallang.xlf`` ->
There you can make two entries:
```
<trans-unit id="flux.{fluxFormId}">
	<source>{your_name}</source>
</trans-unit>
<trans-unit id="flux.{fluxFormId}.description">
	<source>{your_description}</source>
</trans-unit>
```

**Comment by rico3000** [comment]
Thanks.
