### ISSUE TITLE
Unused method in \FluidTYPO3\Flux\Service\ContentService

### ISSUE THREAD

**Issue by monosize** [FluidTYPO3/flux#1360]
The method `\FluidTYPO3\Flux\Service\ContentService::pasteAfter`isn't used anymore.
we can remove it.

There are only calls in Tests
- `\FluidTYPO3\Flux\Tests\Unit\Service\ContentServiceTest::pasteAfterAsCopyRelativeToRecord`
- `\FluidTYPO3\Flux\Tests\Unit\Service\ContentServiceTest::pasteAfterAsReferenceRelativeToRecord`
- `\FluidTYPO3\Flux\Tests\Unit\Service\ContentServiceTest::pasteAfterAsMoveRelativeToRecord`
- `\FluidTYPO3\Flux\Tests\Unit\Service\ContentServiceTest::pasteAfterAsMoveIntoContentArea`

Can we also remove the tests methods? Or do we need a replacement for this?

**Comment by NamelessCoder** [comment]
Hi Frank - I actually had this one on my radar already, so thanks for confirming that the method is no longer being used! We can indeed remove this, and the test methods as well.

**Comment by NamelessCoder** [comment]
Method now removed.
