### ISSUE TITLE
flux:field.text - RTE becomes much too large

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/flux#1364]
Hi,

i'm using following fields:
```
<flux:form.sheet name="text">
   <flux:field.input name="settings.text.heading"/>
   <flux:field.input name="settings.text.subHeading"/>
   <flux:field.text name="settings.text.text" enableRichText="true"/>
</flux:form.sheet>
```
While I'm using the text-field inside a sheet the RTE becomes much longer then the browserheight.
the usage of "rows" is ignored (outside of sheets too) so i cannot control the size of the RTE.

Workaround:
After using browszoom function or changing the size of the browser the RTE size instantly shrinks to the normal value.

I'm using 
- TYPO3 7.6.16
- Flux 8.0.2 (stable release)

Supersized (after opening sheet):
![image](https://cloud.githubusercontent.com/assets/25088164/23582646/572abfaa-012f-11e7-85be-d2b8d94a5cc4.png)

Normalized (after zooming in and back out)
![image](https://cloud.githubusercontent.com/assets/25088164/23582652/6d7e7116-012f-11e7-91b7-ca774a7db9a5.png)

**Comment by NamelessCoder** [comment]
Hi @TheNaderio - please report this one on the TYPO3 core bug tracker, https://forge.typo3.org/projects/typo3cms-core/issues. Flux does not render the field, we only deliver metadata (TCA array) in exactly the same way it would be delivered for normal (non-Flux) FlexForm fields.
