### ISSUE TITLE
changing file order in flux:field.inline.fal 

### ISSUE THREAD

**Issue by rico3000** [FluidTYPO3/flux#1365]
I'm using flux 8.1 and TYPO3 8.6.0 with the following element

```html
<flux:field.inline.fal name="images" label="Slider" multiple="TRUE" maxItems="25" collapseAll="true" allowedExtensions="jpg,jpeg,png" />
```
Everything works in one language, but changing the element to "all-languages" / -1 I get the following error by saving: 

```php
Argument 3 passed to TYPO3\CMS\Core\DataHandling\Localization\DataMapProcessor::synchronizeFieldValues() must be of the type array, null given, called in /usr/share/php/typo3_src-8.6.0/typo3/sysext/core/Classes/DataHandling/Localization/DataMapProcessor.php on line 253 

TypeError thrown in file
/usr/share/php/typo3_src-8.6.0/typo3/sysext/core/Classes/DataHandling/Localization/DataMapProcessor.php in line 323.
```

**Comment by NamelessCoder** [comment]
Please report this issue to the TYPO3 core bug tracker - https://forge.typo3.org/projects/typo3cms-core/issues. Flux does not perform the operation you are having trouble with, we only create TCA to configure the behavior. Thus this would be a problem for any method of defining a FlexForm DS. For a more in-depth explanation about how to distinguish Flux bugs from core bugs, see https://fluidtypo3.org/blog/news/bugs-core-or-flux.html.
