### ISSUE TITLE
flux.field.select works only with limit of items

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1370]
Seems there is a parse problem with many items but correct syntax.

This select does work:

```
<flux:field.select name="columns" label="Column Arrangement"
                               items="{
0:{0:'[3/3/6 Responsive] S12 M3 L3/ S12 M3 L3 /S12 M6 L6', 1:'small-12 medium-3 large-3/small-12 medium-3 large-3/small-12 medium-6 large-6'},
1:{0:' - - [3/3/6] S3 M3 L3/ S3 M3 L3 /S6 M6 L6', 1:'small-3 medium-3 large-3/small-3 medium-3 large-3/small-6 medium-6 large-6'},
2:{0:'[3/4/5 Responsive] S12 M3 L3/ S12 M4 L4 /S12 M5 L5', 1:'small-12 medium-3 large-3/small-12 medium-4 large-4/small-12 medium-5 large-5'},
3:{0:' - - [3/4/5] S3 M3 L3/ S4 M4 L4 /S5 M5 L5', 1:'small-3 medium-3 large-3/small-4 medium-4 large-4/small-5 medium-5 large-5'},
4:{0:'[3/5/4 Responsive] S12 M3 L3 / S12 M5 L5 / S12 M4 L4', 1:'small-12 medium-3 large-3/small-12 medium-5 large-5/small-12 medium-4 large-4'},
5:{0:' - - [3/5/4] S3 M3 L3 / S5 M5 L5 / S4 M4 L4', 1:'small-3 medium-3 large-3/small-5 medium-5 large-5/small-4 medium-4 large-4'},
6:{0:'[3/6/3 Responsive] S12 M3 L3 / S12 M6 L6 / S12 M3 L3', 1:'small-12 medium-3 large-3/small-12 medium-6 large-6/small-12 medium-3 large-3'},
7:{0:' - - [3/6/3] S3 M3 L3 / S6 M6 L6 / S3 M3 L3', 1:'small-3 medium-3 large-3/small-6 medium-6 large-6/small-3 medium-3 large-3'},
8:{0:'[4/3/5 Responsive] S12 M4 L4 / S12 M3 L3 / S12 M5 L5', 1:'small-12 medium-4 large-4/small-12 medium-3 large-3/small-12 medium-5 large-5'},
9:{0:' - - [4/3/5] S4 M4 L4 / S3 M3 L3 / S5 M5 L5', 1:'small-4 medium-4 large-4/small-3 medium-3 large-3/small-5 medium-5 large-5'},
10:{0:'[4/4/4 Responsive] S12 M4 L4 / S12 M4 L4 / S12 M4 L4', 1:'small-12 medium-4 large-4/small-12 medium-4 large-4/small-12 medium-4 large-4'},
11:{0:' - - [4/4/4] S4 M4 L4 / S4 M4 L4 / S4 M4 L4', 1:'small-4 medium-4 large-4/small-4 medium-4 large-4/small-4 medium-4 large-4'},
12:{0:'[4/5/3 Responsive] S12 M4 L4 / S12 M5 L5 / S12 M3 L3', 1:'small-12 medium-4 large-4/small-12 medium-5 large-5/small-12 medium-3 large-3'},
13:{0:' - - [4/5/3] S4 M4 L4 / S5 M5 L5 / S3 M3 L3', 1:'small-4 medium-4 large-4/small-5 medium-5 large-5/small-3 medium-3 large-3'},
14:{0:'[5/3/4 Responsive] S12 M5 L5 / S12 M3 L3 / S12 M4 L4', 1:'small-12 medium-5 large-5/small-12 medium-3 large-3/small-12 medium-4 large-4'},
15:{0:' - - [5/3/4] S5 M5 L5 / S3 M3 L3 / S4 M4 L4', 1:'small-5 medium-5 large-5/small-3 medium-3 large-3/small-4 medium-4 large-4'},
16:{0:'[5/4/3 Responsive] S12 M5 L 5 / S12 M4 L4 / S12 M3 L3', 1:'small-12 medium-5 large-5/small-12 medium-4 large-4/small-12 medium-3 large-3'},
17:{0:'[5/4/3 Responsive] S12 M5 L 5 / S12 M4 L4 / S12 M3 L3', 1:'small-12 medium-5 large-5/small-12 medium-4 large-4/small-12 medium-3 large-3'},
18:{0:'[5/4/3 Responsive] S12 M5 L 5 / S12 M4 L4 / S12 M3 L3', 1:'small-12 medium-5 large-5/small-12 medium-4 large-4/small-12 medium-3 large-3'}
               }"
            />
```

if i add one item by duplicating last item, i get a parse error:

> Fluid parse error in template Default_action_Default_e337cb76ee381e67a3d0d0c31c05d0070962c854, line 141 at character 1. Error: Not all tags were closed! (error code 1238169398). Template source chunk: <flux:field.select name="columns" ...

TYPO3 v8.6.1, FLux v8.1.0

**Comment by NamelessCoder** [comment]
This is not something we can affect in Flux - if it can be solved, it has to be solved in Fluid, so it should be reported on https://github.com/TYPO3/Fluid/issues instead.

However, I strongly suggest you don't create such huge arrays in template source; each member has to be represented as a note and with this big an array that can be felt in parsing time. Putting such things in TS or PHP makes it much easier and cheaper to handle. Another aspect is that having a column arrangement suggests a rather big template overall (unless you separated it to partials in which case, disregard this) - and if that's true, you absolutely want to consider refactoring this in the first place.

Sorry to close like this but there's nothing we can do about this issue from this side except suggest the above workaround.

**Comment by steffenk** [comment]
I see. I was not sure where the the issue belongs to, but you're right, the error happens in fluid TemplateParser. I will create an issue in Fluid space.

I see your comments, but i do not think this is an huge array - select with 20 entries, 5 input fields, it's a "smaller" BE form. I simply converted existing form from flexform to flux form without any thoughts of refactor at first place. Motivated by your comment i tried to use a partial for the select only - seems to be ignored completely. Is it just me or is there any trap?

**Comment by jwittorf** [comment]
@steffenk could you please provide a link to the issue for Fluid? I just ran into the same problem, thanks in advance!

**Comment by Feanathiel** [comment]
We happened to run into the (seemingly) same issue today. We're running an old version, but I don't know if the issue still persists in a more recent version. In case you're running an old version and want to fix the issue, make sure that whatever is in an attribute isn't too long. So the `...` in `<flux:field.select items="{...}" />` can't exceed a specific amount of characters. I don't know at how many characters the issue triggers, but an easy fix is to move the data to the controller.

**Comment by NamelessCoder** [comment]
> can't exceed a specific amount of characters

This is actually a known issue in PHP itself and it is caused by a byte limit in the PCRE routines. Neither Flux nor Fluid can fix this problem - but thanks for mentioning the workaround here! It is the only way to work around the issue.

Locking issue since it's very old by now and there's no more info to add.

**Comment by danielDigitalArt** [comment]
> We happened to run into the (seemingly) same issue today. We're running an old version, but I don't know if the issue still persists in a more recent version. In case you're running an old version and want to fix the issue, make sure that whatever is in an attribute isn't too long. So the `...` in `<flux:field.select items="{...}" />` can't exceed a specific amount of characters. I don't know at how many characters the issue triggers, but an easy fix is to move the data to the controller.

Currently i also stumbled across this problem, but i could not figure out how to call a controller for getting the items here, could you be so kind a give some information here? I already searched a lot about requesting data from a controller but could not find anything about this. It also does not seem to be documented for the flux.field.select tag.

I also tried other things like increasing the max input_vars to 3000, aswell as increasing the memory Limit (512MB). What i can tell is that this problem occurs either because of there are about 20 Items in the List, or because of a character Limit of about 1600 which were reached with these 20 Items here, because of all thos "LLL" references for the labels.
