### ISSUE TITLE
Breaking changes in TYPO3v8.6+: the unique id of section / objects isn't stored anymore in the object field id

### ISSUE THREAD

**Issue by monosize** [FluidTYPO3/flux#1372]
since TYPO3v8.6+ the unique id of section / objects isn't stored anymore in the object field id.
The id is now the key of the object.

### Configuration 
```
	<flux:form.section name="panels">
		<flux:form.object name="panel">
			<flux:field.input name="title"/>
		</flux:form.object>
	</flux:form.section>
    
```

### T3FlexForms in TYPO3v7.6.x
```
<sheet index="panels">
	<language index="lDEF">
		<field index="panels">
			<el index="el">
				<section index="1">
					<itemType index="panel">
						<el>
							<field index="title">
								<value index="vDEF">Title 1</value>
							</field>
							<field index="id">
								<value index="vDEF">34acf04bea90d0fc2dfde288b3b4e71339834911</value>
							</field>
						</el>
					</itemType>
					<itemType index="_TOGGLE">0</itemType>
				</section>
				<section index="2">
					<itemType index="panel">
						<el>
							<field index="title">
								<value index="vDEF">Title 2</value>
							</field>
							<field index="id">
								<value index="vDEF">a117815b37be8710317927be95e371c7e883f849</value>
							</field>
						</el>
					</itemType>
					<itemType index="_TOGGLE">0</itemType>
				</section>
                                ...
			</el>
		</field>
	</language>
</sheet>
```

### T3FlexForms in TYPO3v8.6+
```
<sheet index="panels">
	<language index="lDEF">
		<field index="panels">
			<el index="el">
				<field index="58c6db34e8ade040735938">
					<value index="panel">
						<el>
							<field index="title">
								<value index="vDEF">Title 1</value>
							</field>
						</el>
					</value>
					<value index="_TOGGLE">0</value>
				</field>
				<field index="58c6db3a22360717735574">
					<value index="panel">
						<el>
							<field index="title">
								<value index="vDEF">Title 2</value>
							</field>
						</el>
					</value>
					<value index="_TOGGLE">0</value>
				</field>
                               ...
			</el>
		</field>
	</language>
</sheet>
```

### Get the unique Id
TYPO3v7.6.x
get the unique id of the object `{object.panel.id}`
```
<f:for each="{panels}" as="object">
    Unique ID: {object.panel.id}
</f:for>
```

TYPO3v8.6+
the unique id of the object is now the key of the object, which can be fetched during a for loop. `<f:for each="{panels}" as="object" key='id' >`
```
<f:for each="{panels}" as="object" key='id'>
    Unique ID: {id}
</f:for>
```

### Workaround to get unique ID with old and new T3FlexForms
Scenario: Updating from TYPO3 from 7.6.x to 8.6+
The stored T3FlexForm in pi_flexform has the old format.
This leads to a problem, If you create new data or edit data after the update. Then the T3FlexForm becomes the new format and is then incompatible.

```
<f:for each="{panels}" as="object" key='id'>
    Unique ID: {object.panel.id -> v:or(alternative:id)}
</f:for>
```

**Comment by hm-tim** [comment]
Coming back to this issue after some time. 
Your workaround helped for newer projects using TYPO3 v8.6+. However I do work on a project that is using TYPO3 7.6.23 and Flux 8.2.1 (which should work, as Flux 8.2.1 should be compatible with 
'typo3' => '7.6.13-8.7.99'
)
However with this combination you neither get the unique id as  {object.panel.id} nor the key of the object, there seems to be no way to distinguish the objects from one another.

**Comment by NamelessCoder** [comment]
Related issue: https://github.com/FluidTYPO3/flux/issues/1483 - I'm not sure how it is related, but I see two immediate possibilities. Either the object ID doesn't get set in the workspace version of the record due to this exact same problem. Or the object ID is not available at all after applying the workspace overlay. I would say the first is more likely.

Will close the other issue.

**Comment by cmichael-de** [comment]
The key isn't unique in my case - every label shows the same id in backend (TYPO3 8.7.22, Flux 9.1.0). 

```
<f:section name="Configuration">
        <flux:form id="accordion">
            <flux:form.option.group value="bootstrapelemente" />
            <flux:form.option.sorting value="2" ></flux:form.option.sorting>

            <flux:form.sheet name="panels" label="Pannels">
                <flux:form.section name="panels">
                    <flux:form.object name="panel" label="Pannel">
                        <flux:field.input name="title" label="Title" />
                        <flux:field.checkbox name="active" label="Active" />
                    </flux:form.object>
                </flux:form.section>
            </flux:form.sheet>

        <flux:grid>
            <f:for each="{panels}" as="panel" iteration="iteration" key='id'>
                <flux:grid.row>
                    <flux:grid.column colPos="1"   label="{id}" />
                </flux:grid.row>
            </f:for>
        </flux:grid>
        </flux:form>
    </f:section>
```

**Comment by NamelessCoder** [comment]
Replaced by either:

* Using `contentContainer="1"` on a `flux:form.object` and relying on automatic grid creation, or
* Using `flux:form.object.columnPosition` on a `flux:form.object` and manually defining a grid.
* Using `flux:form.object.columnPosition` on a `flux:form.object` without any grid and using the `.colPos` property while iterating the section objects.

Although the `flux:form.object.columnPosition` indicates the value will be used as `colPos` number, it is unique and can be used even without creating a grid (off-label use as "id" of a section object).¨

See https://github.com/FluidTYPO3/flux/commit/240cd68d7417cdd06ef7c91aeafa1ca70678ddb4

(requires Flux 9.4+)
