### ISSUE TITLE
[FEATURE] Rendering the configuration section should respect configuration

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/flux#1376]
When rendering the configuration (and preview?) section i think the template paths configuration of the provider extension should be used. 
In my usecase i want to use shared partials in the configuration section of fluid content elements registered as content type.

Using partials located in the default location works. But i can´t change the location or add a fallback path.

Before i try to implement this i would like to hear if there are objections?
@NamelessCoder ?

**Comment by NamelessCoder** [comment]
Please check https://github.com/FluidTYPO3/flux/pull/1371 before you spend time on it ;)

**Comment by NamelessCoder** [comment]
I'll close this one since it's been quite a while - if this is still a problem (on dev-development) ping me and I'll reopen the issue.
