### ISSUE TITLE
outlet does not work

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1379]
I tried the example from your blog:
https://gist.github.com/mneuhaus/9a8cff9f5b47ad8872eebae2808c54e7

Now if i submit the (empty|filled out) form, nothing happens: no validate, no message, no pipe action.

What i see is that my extension is used for controller action:

`?tx_myext_%5Baction%5D=outlet&tx_myext_%5Bcontroller%5D=Content`

But why is my extension postfixed with underscore?

I created a vanilla ContentController in my extension, but it's not called.

Did i missed anything?

**Comment by mneuhaus** [comment]
What version of Flux/Fluidcontent/TYPO3 are you running?

Could you try without the ContentController, that should not be needed for that functionality.

**Comment by steffenk** [comment]
I use latest versions (dev) of all. The own controller was only added because the above problem, so it makes no difference.

**Comment by xf-** [comment]
confirmed in v8
