### ISSUE TITLE
Severe Translation Error: Translating content elements that contain a FAL image does lead to incorrect sys_file_reference entries - FAL duplicates for original/root FCE

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/flux#1380]
We got a pretty severe problem with the latest FluidTypo3 extension family. We are using the latest master versions of vhs, fluidcontent, fluidpages and flux. They are running on TYPO3 7.6.16 LTS (composer mode) running on PHP 7.0.16. 

When translating via copy mode from the default language to another language everything gets copied correctly but the content elements that contain a FAL image do lack the image reference in the new language. 

After digging through the typo3 tables I found the reason for it. 
While copying a content element containing a FAL image from the default language to the foreign language another `sys_file_reference` entry gets created but for the wrong `foreign_uid` and `sys_language_uid`. 
The `foreign_uid` used is the `uid` from the original (root) content element of the default language. The `sys_language_uid` is set to 0. (default)

This has two impacts:

1. The image reference is missing for the copied content element
2. Even worse the original element has now two references in the `sys_file_reference` table which leads to errors while opening in the backend and frontend depending on how you output them. 

I'm not sure if this is a bug in fluidcontent or flux but it creates `sys_file_reference` duplicates when not stopping your editors to translate content containing FAL images.

-- Update --

We have tested a bit more and got to the conclusion that when translating existing pages and its content elements the above mentioned error occurs. 
But the error does not occur when creating new pages and content elements and translating them.

-- Update --

I can now describe the problem even further after testing out more usecases. I can confirm that there is definitely a problem with the latest master versions of flux right here. 

For the following page structure a translation of FCEs containing FAL images does **work**: 

Sorting 256: 

FCE with FAL image inside

Sorting 512: 

FCE with a container area like this:

```
      <flux:grid>
        <flux:grid.row>
          <flux:grid.column name="content">
            <flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
            <flux:form.variable name="Fluidcontent" value="{allowedContentTypes: '{settings.multiColElements}'}" />
          </flux:grid.column>
        </flux:grid.row>
      </flux:grid>
```

For the following page structure a translation of FCEs containing FAL images does **fail**:

Sorting 256:

FCE with a container area like this:

```
      <flux:grid>
        <flux:grid.row>
          <flux:grid.column name="content">
            <flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
            <flux:form.variable name="Fluidcontent" value="{allowedContentTypes: '{settings.multiColElements}'}" />
          </flux:grid.column>
        </flux:grid.row>
      </flux:grid>
```

Sorting 512:

FCE with FAL image inside

So in the end it is all about the sorting. If there is a container element at first that does not contain FCEs with FAL images, all the translations for FAL images that are sorted after the container element do fail. (and the original/root FAL image does get duplicates in `sys_file_reference` like mentioned in the description above) The funny things is if you put a FCE element containing a FAL image inside the first container element and translate the whole thing everything does work fine.

-- Update --

The first element that lets the translation of FCEs mit FAL images inside fail does not have to be a FCE with a grid area. Every FluidTYPO3 FCE triggers the bug as long as it does not contain a FAL image itself.

-- Update --

The problem is even there with the developement version of `flux`.
The whole things seems to be a similar bug like #1214

**Comment by jmverges** [comment]
Did you try: https://github.com/froemken/repair_translation ? Maybe this helps, I didn't try it by now but looks promising. If you try it, please give me feedback on this.

**Comment by mithri** [comment]
I can confirm the bug. Testest with flux dev branch and TYPO3 7.6.16.

The repair_translation didn`t help.

**Comment by mithri** [comment]
Using flux 7.4 and fluidcontent 4.4.1 does work with the FAL translations. But then the order of all translated elements is screwed up. So not usable right now.

How can we help? Would sponsoring help?

**Comment by DenisMir** [comment]
So I have found the error after hours of digging through the core. 

The error is in the `AbstractProvider` of Flux. 

The cache key generation for stored variables is definitely broken. 

```
    /**
     * @param array $row
     * @param string $variable
     * @return string
     */
    protected function getCacheKeyForStoredVariable(array $row, $variable)
    {
        $table = $this->getTableName($row);
        $field = $this->getFieldName($row);
        $contentType = $this->getContentObjectType();
        $uid = $row['uid'] ?? 0;
        return 'flux-storedvariable-' . $table . '-' . $field . '-' . $uid . '-' . $variable . '-' . $contentType;
    }
```
This method does result in the same cache key for completely different fluid content elements which leads to the above mentioned bug!
This does only happen during localization or copy processes since the `uid` of the given `row` is not already set since the row is not inserted at the event the cache key gets generated. In the end at this stage it is not possible to provide a useful cache key so the cache should be skipped. I will provider hour quick fix in a pull request.

**Comment by mithri** [comment]
Hi, i think this is not finally solved. We have a flux element with an inline.fal field. We created such an element in the second language and added an image. After saving, the image is gone, because the sys_file_reference is not fully updated. "uid_foreign" etc. is empty.

**Comment by NamelessCoder** [comment]
> After saving, the image is gone, because the sys_file_reference is not fully updated. "uid_foreign" etc. is empty.

This is a core issue, not a Flux issue. We cannot solve it from this side and it also appears using other FlexForm methods. To my knowledge: no, this is not solved in TYPO3.

**Comment by mithri** [comment]
Hi,

if i removed <flux:form.option name="static" value="1" /> it worked again. Maybe you can document this new option in detail sometime. Thanks!
