### ISSUE TITLE
#1237823695: Argument "icon" was not registered. 

### ISSUE THREAD

**Issue by wabajwa** [FluidTYPO3/flux#1384]
Hi,
After upgrading the TYPO3 from 6.3 to 7.6 and PHP 7.0, i am facing this issue, i searched on google but didn't find any thing helpful. On the front end, i am getting this view:
![image](https://cloud.githubusercontent.com/assets/24478656/24357069/b0dff450-12fc-11e7-86bc-e6cb67a94113.png)
and on the back-end, if i click on the page etc. i get the following display. 

`Uncaught TYPO3 Exception
#1237823695: Argument "icon" was not registered. (More information)

TYPO3\CMS\Fluid\Core\Parser\Exception thrown in file
/home/www/wwwdev/vendor/typo3/cms/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php in line 604`

Any help would be great. Thanks

**Comment by NamelessCoder** [comment]
You obviously upgraded not just TYPO3 but also Flux and possibly others - that matters a lot ;)

Now you have to migrate your templates. This may not be the only error you see, so see fluidtypo3.org for further information about breaking changes.

But, to solve that particular error, do not use `icon="..."` on `flux:form`. Instead, use either `<flux:form options="{icon: '...'}" />` or use `<flux:form.option name="icon" value="..." />` inside your `flux:form` tag.
