### ISSUE TITLE
Devlog: singleton BackendConfigurationManager needs a prototype

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1389]
The devlog is spammed with messages:

> The singleton "FluidTYPO3\Flux\Configuration\BackendConfigurationManager" needs a prototype in "injectQueryGenerator". This is often a bad code smell; often you rather want to inject a singleton.

Happens with flux 7.4.0

**Comment by NamelessCoder** [comment]
This error is from the parent class - which is in TYPO3 itself. See https://review.typo3.org/#/c/50033/ for a pending fix.
