### ISSUE TITLE
 [BUG][TYPO-8.7.0] page configuration content cannot be stored

### ISSUE THREAD

**Issue by ralfhueskes** [FluidTYPO3/flux#1393]
I use Typo3 LTS 8.7.0 with current stable flux. There are 2 page configuration specifications, which shown perfectly in the backend. If i try to change the value, nothing happen und the default is still activate.

This page configuration is within the flux:form
```
<flux:field.checkbox
                    name="flexSettings.positionbc"
                    label="Breadcrumb unter Stage anzeigen"
                    default="0"/>
<flux:field.select 
                     name="flexSettings.class"
                     items="{
                           0:{0:'Content Default',1:'content'},
                           1:{0:'Download (Liste)',1:'downloads_preview downloads'},
                           2:{0:'Download (Detail)',1:'downloads_detail downloads'}
                       }" />
```

**Comment by rico3000** [comment]
Maybe it's a core JavaScript-problem with all inputs (maybe especially with Chrome). 
A compromise solution: did you tried another browser? 

https://forge.typo3.org/issues/80632

**Comment by NamelessCoder** [comment]
Closing this under the assumption it is no longer an issue in the `dev-development` branch of Flux. If you're able to reproduce the problem with that branch installed please ping me!
