### ISSUE TITLE
No option to set renderType on flux:field.relation

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/flux#1396]
Now, I know that we should use "relation" instead of the "group" TCA type, but for the life of me I cannot recreate one of the old select boxes with this new configuration.

This is the old configuration:
```
<pageids>
	<TCEforms>
		<exclude>1</exclude>
	<label>LLL:EXT:crossggmap/locallang_tca.xml:crossggmap.pi_flexform.ggmap_pagedetuids</label>
		<config>
			<type>group</type>
			<internal_type>db</internal_type>
			<allowed>pages</allowed>
			<size>10</size>
			<maxitems>20</maxitems>
			<minitems>0</minitems>
			<show_thumbs>1</show_thumbs>
		</config>
	</TCEforms>
</pageids>
```

This used to generate a selectbox on the left side, with the pages I selected, and a small browse icon that opened a popup with the page tree that allowed me to add pages to the selectbox on the left.

But if I try to recreate it with relations:
```
<flux:field.relation table="pages" size="10" name="ggmap_pagedetuids" minItems="0" maxItems="10" multiple="true"/>
```
The code will generate 2 select boxes, the one on the left holds my selection (good), and the one on the right holds ALL the pages from the site (not good), but how can I replace this second select with the popup I had before which displayed the nice page tree?

Thank you

**Comment by NamelessCoder** [comment]
`flux:field.multiRelation` or `flux:field.tree` can be used here. That being said, `flux:field.relation` generates a `select` type but lacks the `renderType` argument which would allow you to control this and make it a `selectSingle` (then combine it with a browse or list wizard).

Will keep this open as a feature request but you can probably solve your issue using the above.

**Comment by pixelplant** [comment]
Just for the record, this is what I'm trying to achieve (that we used in a previous version of TYPO3). So it's a simple select that shows the page that you have chosen so far, and once you click on the folder you can browse the entire page tree and add additional pages to this list.
![old_selector](https://cloud.githubusercontent.com/assets/492082/25384128/65157fac-29bf-11e7-98c4-521aad3278a3.png)

Adding a tree element generates a tree of the page with checkboxes, which is not that bad at first sight, so for the selection part it is just great. Check your pages, save and you're good to go. But once you go back to the element to see the pages you selected (and add new ones or uncheck old ones) you see the entire page tree, and when you have 600+ pages it's quite a nightmare to handle. Another downside is that you cannot specify an order to your selection, so there's no way to tell it take this page first, this other one second, etc.
![tree_version](https://cloud.githubusercontent.com/assets/492082/25384184/ab148f84-29bf-11e7-82ef-9682f451d8d9.png)

The current version we use made with field.relation is not user friendly, as it shows ALL the pages in a list on the right side. Yet again, going through a list of 600+pages, not nice.
![current_version](https://cloud.githubusercontent.com/assets/492082/25384113/59a39b5e-29bf-11e7-8c2d-7361187edcf7.png)

Multirelation seems to be the best approach so far, since it has the autocomplete box and it also shows the path to the page and once you add your elements they are displayed in a simple list that you can order, but we would have loved the old approach better, as you don't always remember the exact name of the page, so you prefer to look it up in a page tree component and then add it to the list.
![multi_version](https://cloud.githubusercontent.com/assets/492082/25384305/1b2c676a-29c0-11e7-82c3-01e9a45dcdde.png)

Anyway, if the first approach is not possible we'll just go with multirelation, as it is the closest one to what we want.

Thank you once again for your help

P.S: There's no **renderMode** argument defined for flux:field.relation. It is present in the [documentation ](https://fluidtypo3.org/viewhelpers/flux/master/Field/RelationViewHelper.html) but try using it in a template and you will get an "argument not defined" error.

**Comment by NamelessCoder** [comment]
`renderType` is now available on every multi-value field type since moving it to AbstractMultiValueFormField. Hopefully that lets you set the desired display also for the type of field you wanted to use to begin with and now have to change to a different one.

Indeed, `renderMode` is long gone by now and `renderType` lets you do what it did, and more :)

**Comment by rungissan** [comment]
Typo3 v10 , fluidtypo3/flux 9.4.2  
Undeclared arguments passed to ViewHelper FluidTYPO3\Flux\ViewHelpers\Field\RelationViewHelper: renderType. ???
Relation extends AbstractRelationFormField
AbstractRelationFormField extends AbstractMultiValueFormField

**Comment by hellfish303** [comment]
Typo3 v10 , fluidtypo3/flux 9.4.2:
<flux:field.relation table="myTable maxItems="999" size="10" name="myName" label="myLabel" config="{renderType:'selectMultipleSideBySide'}">
works like a charm :)
