### ISSUE TITLE
[BUG][TYPO3-8.7.0] ContentService.php / Translation of nested Elements

### ISSUE THREAD

**Issue by pmuelhaupt** [FluidTYPO3/flux#1397]
(Maybe this is a dublicate of #1151, but I'm not really sure)

Versions:
TYPO3: 8.7.0, 8.7.1 (also happened on 7.6)
Flux: 8.1.0 (development)

Reproduce:
1. Insert a Flux-Element with a grid (uid = 1)
2. Translate the element to another language (uid = 2)
3. Insert a content element into the grid
4. Translate the content element (via 'edit' and pick 'english [new]' in the dropdown)

Result:
the newly created element shows up in the flux-element in the source-language, not the translated flux-element. (tx_flux_parent is '1', rather than '2')

This is what I got so far:

/Classes/Service/ContentService.php:260
`&& $oldRecord['pid'] === $row['pid']`
at least in TYPO3 >= 8.7.0 $oldRecord['pid'] is a string, while $row['pid'] is an integer, therefore the condition is never true

/Classes/Service/ContentService.php:267
```
$translatedParents = (array) $this->workspacesAwareRecordService->get(
                    'tt_content',
                    'uid,sys_language_uid',
                    '1=1 ' . BackendUtility::deleteClause('tt_content')
                );
```
returns _all_ content-element that are not hidden and deleted. So when trying to fetch the uid a few lines later (273), you end up with the uid of the very first element that has the target language.
A few commits back, the WHERE-clause included `t3_origuid = "' . $oldRecord['tx_flux_parent'] . '` (I cant find the exact commit, where the clause is changed)

After I changed the condition and altered the WHERE-clause, the correct values are stored in $overrideValues. Sadly, these values don't get written into the DB, but this is where I have to give up.

I'm not sure what the implications of these changes would be, so I thought I'll just report this and let you guys decide, whether it's an actual bug or this would break other stuff.

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.

You will however need to upgrade TYPO3 to at least 8.7 to enjoy the benefits of Flux 9.0.
