### ISSUE TITLE
flux:field.file not working in latest v8

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/flux#1398]
Hello

I have a simple flux:field.file field which worked great in the latest TYPO3 v7 version.
Once I switched to v8 it no longer works. I am using the latest version of flux too.

This is the configuration of the field:
```
<flux:field.file name="image" maxItems="1" minItems="0" label="Image"/>
```

The field is displayed properly in the backend, but once I click on the "browse" folder icon, instead of displaying the list of files, the popup gives me this error:
**Uncaught TYPO3 Exception:** $className must be a non empty string

'The specified element browser "' . $className . '" does not implement the required ElementBrowserInterface', called in _typo3/sysext/recordlist/Classes/Controller/ElementBrowserController.php_

![screen](https://cloud.githubusercontent.com/assets/492082/25220374/d6f689c0-25b1-11e7-8b34-99b78d04c5f6.png)

**Comment by pixelplant** [comment]
Ok, so I got it working. I needed to specify **useFalRelation="1"** otherwise the popup looks for file_reference instead of file as it's elementbrowser. This worked before with the same code, so it might be a bug.

So, this code shows the file selection popup:
```
<flux:field.file name="mobileImage" useFalRelation="1" showThumbnails="1" maxItems="1" minItems="0" label="Image"/>
```

This one does not:
```
<flux:field.file name="mobileImage"  showThumbnails="1" maxItems="1" minItems="0" label="Image"/>
```

In Form/Field/File.php by default the internal_type is set as 'file_reference', and there's no $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ElementBrowsers']['file_reference'] configuration in T3 v8.7.1 (or at least not on my machine) and this is what generates the error in the popup.
Setting it as FAL switches the internal_type to 'db', which does have a definition setup.

**Comment by mkrappitz** [comment]
Can confirm. Thanks for fix. One more breaking change, not mentioned anywhere.

**Comment by fnagel** [comment]
Bug confirmed for TYPO3 8.7.2 and flux 8.2.1 used with fluidcontent 5.2.0.

**Comment by Ben305** [comment]
Somewaht related to #1320

**Comment by NamelessCoder** [comment]
I hope you'll forgive me for not remembering the exact reason why this one was changed - but I've now at least added a VH argument that will let you override this as you see fit. See linked commit. With apologies for the breaking change.

**Comment by develth** [comment]
I still got this error in the current versions.
Solution from @dacostafilipe in #1375 fixed it.
