### ISSUE TITLE
flux:form group option not translated in v8

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/flux#1399]
Hello

I've got this basic configuration in one of my fluidcontent elements:
```
<flux:form id="carouselElement" options="{group: '{f:translate(key: \'flux.element.needsContainer\')}'}">
```
This fetches my translation, but instead of displaying it as a text, it displays it as a formatted id (spaces replaced with underscore, parantheses removed, etc)
_flux.element.needsContainer_ is translated as "**(Container elements)**" in my locallang file.
In the backend wizard though, instead of seeing the text "(Container elements)" in the content tab, I see "group_Container_elements" which I assume is the id of this new tab. How do I get it to keep its id but display the actual translation in the tab?

![groups](https://cloud.githubusercontent.com/assets/492082/25220889/83c00e28-25b3-11e7-9814-412799c3d6e9.jpg)

Thank you

**Comment by NamelessCoder** [comment]
Fixed in fluidcontent in https://github.com/FluidTYPO3/fluidcontent/commit/7050c137ef00c803813f304e6fa7665c0ea9cc09, not released to TER yet but you can use `dev-development` of fluidcontent if you need the fix badly.
