### ISSUE TITLE
form.section objects generate an error on the first save in v8

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/flux#1400]
I am using flux:form.section with form.object inside it in a lot of my fluidcontent elements. In TYPO3 v8.7.0, when I save the object for the first time I always get this error: 	
1: Attempt to insert record on page '[root-level]' (0) where this table, tt_content, is not allowed

Let's take this configuration for example:
```
<f:section name="Configuration">
	<flux:form id="infos" options="{group: 'Components'}">
		<flux:form.section name="blocks" label="Information blocks">
			<flux:form.object name="block" label="Information block">
				<flux:field.select name="icon" required="1" items="hospital,personel,bed,graph,steto,heart,calculator" label="Icon"/>
				<flux:field.input name="title" required="1" label="Title" />
				<flux:field.input name="subtitle" required="1" label="Subtitle" />
			</flux:form.object>
		</flux:form.section>
	</flux:form>
</f:section>
```
This configuration allows me to create a series of "Information blocks", like in this screenshot

![blocks](https://cloud.githubusercontent.com/assets/492082/25223155/df156046-25ba-11e7-93d0-233f486d0a6c.jpg)

Once I save this element for the 1st time, I get the following error: 	
**1: Attempt to insert record on page '[root-level]' (0) where this table, tt_content, is not allowed**
As you can see, since I created 3 block objects, I get 3 error messages.
![errors](https://cloud.githubusercontent.com/assets/492082/25223239/234e52a4-25bb-11e7-8653-d9fcacd197c6.jpg)

Now, once I save the element, I can recreate the "information blocks" and save them and everything works fine. It's just during the first save, once the element is created ,that I get this error, for any fluidcontent element that contains a form.section area.

Thank you

**Comment by ervaude** [comment]
Hi, this was already identified as a TYPO3 core regression. It could be helpful if you provide additional information to the TYPO3 bug tracker so that this makes it into one of the next bugfix releases: https://forge.typo3.org/issues/80825

**Comment by NamelessCoder** [comment]
Thanks @pixelplant for reporting - and @ervaude for the link to the core issue. Please continue the discussion there.

**Comment by grimmcreative** [comment]
Ah good to know its already placed here. Searching for solution since hours :D
