### ISSUE TITLE
[BUG?][TYPO3-7.6.18] recursive correction of "sorting" field by  hook for "copy" results in corruption of sorting fields on multiple records

### ISSUE THREAD

**Issue by sypets** [FluidTYPO3/flux#1407]
Hello,
a severe problem occured where multiple tt_content records (couple of 1000) had the sorting field (automatically) changed. tstamp was not set and sys_log / sys_history records not created. This occurs when a tt_content text+image is inserted as shortcut (using the functionality from gridelements: "Insert as reference"). Multiple content elements that have nothing to do with this operation will be manipulated. The "sorting" value will be set to their t3_origuid counterparts. 

**Info**

TYPO3 version 7.6.18
compatibility6 installed
flux version 8.2.1
gridelements version 7.1.0

**Reproduce / Analysis**

tracked this down to an insert operation in the history:
_Record 'Reference' (tt_content:223581) was inserted on page 'xyz' (5278) (msg#1.1.10)_

record 223581 is of type shortcut. References a text / image content element with one image.

**Debug**

When the problem occurs, the recursive function **copySortingValueOfChildrenFromOriginalsToCopies** will set the "sorting" field to "sorting" value of its  t3_origuid counterpart. 

This apparently occurs because copySortingValueOfChild... was called with an array containg 0 as 'uid'.

This happens because $reference->copyMappingArray['tt_content'][$id] in processCmdmap_postProcess is empty. In fact $reference->copyMappingArray is empty (possibly due to the insert as reference?)

**Is this really a bug in flux or a result of a bug somewhere else**

- I am not sure, but I think especially the recursive function should make extra sure, that the input values are ok. 

The question is, should DataHandler->copyMappingArray[$table][$uid] always be set? If this should be the case, the bug must be tracked further to the original problem. For now however, an extra check in flux might be not such a bad idea. 

**Possible Fix** 

-  quit the copySortingValueOfChildrenFromOriginalsToCopies function immediately if !$parentRecord['uid'] (and use sys_log to log an error)
- processCmdmap_postProcess should check $reference->copyMappingArray['tt_content'][$id]

**Question**

Does the original problem in the core still exist for fixing the sort order?

Quote: _"We now check if we're doing a copy command once again. Due to internals of TYPO3, child records of the parent being moved (if child records exist) have now gotten their sorting values reset. The only way currently to patch this is a semi-expensive recursive operation to copy the sorting value from the original record to the copy (and to the placeholder and versioned records if those exist). This is less than ideal but the alternative is consistently wrong (read: sql insertion order based, to end user same as random) sorting of *all* child records after a copy operation - so we compromise."_

**Comment by sypets** [comment]
Since TYPO3 support has been dropped (https://github.com/FluidTYPO3/flux/pull/1378), this request no longer is relevant and should probably be closed.

**Comment by enilee** [comment]
Hello,

i have the same Problem in 
TYPO3-Version	8.7.24
PHP-Version	7.1.26
Datenbank (Default)	MySQL 5.5.5
flux	8.2.1

This occurs when a tt_content is inserted as shortcut (using the functionality "Insert as reference"). Multiple content elements that have nothing to do with this operation will be manipulated on each pages.

How i can fix this?

Best regards

**Comment by NamelessCoder** [comment]
@enilee This issue is almost two years old and your particular problem does not appear to be caused by Flux (which does not touch the references field of the shortcut type). You can perhaps find more information with the following search in the TYPO3 core bug tracker:

https://forge.typo3.org/projects/typo3cms-core/search?all_words=1&attachments=0&commit=Submit&issues=1&options=0&page=1&q=tt_content+sorting&scope=&titles_only=&utf8=%E2%9C%93

And I would recommend upgrading your Flux version to the new 9.1 version since 8.2.x is getting old. 9.1 is compatible with TYPO3 8.7.

Locking the issue.
