### ISSUE TITLE
[BUG?][TYPO3-8.7] Custom Provider overrides default FlexForm from Plugin

### ISSUE THREAD

**Issue by fkalka** [FluidTYPO3/flux#1409]
Hi there,
i am using a Custom Provider to extend the FlexForms of 3rd-party plugins like news based on this: [newsflux](https://github.com/NamelessCoder/newsflux)

In TYPO3 7 it worked like a charm, the FlexForm of news was extended with an additional tab.
In TYPO3 8 it just overrides the FlexForm of news and only the FluxForm as defined in the overridden template is shown.

When i enable the following Provider, **all** list-Type content elements have no longer their FlexForm:

```
class TestProvider extends Provider  implements ProviderInterface {
    protected $tableName = 'tt_content';
    protected $fieldName = 'pi_flexform';
    protected $contentObjectType = 'list';
    protected $listType = 'news_pi1';
    protected $extensionKey = 'GeorgRinger.News';
}
```

If i remove the $contentObjectType variable, it only breaks news but no other extensions.

As mentioned, in TYPO3 7 everything works as expected. I've read in the blog article about Flux 8, that the Providers had some API changes, but i was not able to find out, if the behaviour i described is part of the API changes...

Am i doing something wrong?

TYPO3: 8.7.0
Flux: 8.2.1

**Comment by NamelessCoder** [comment]
@fkalka I took the liberty of letting this commit close the issue - but please do give your Provider class a try on `dev-development` of Flux to confirm that the DS appends/overrides rather than replaces the entire DS. The patch doesn't cause any problems with vanilla Flux but I'm not completely sure it works with your precise setup.

Please comment here if there is any trouble ;)

**Comment by fkalka** [comment]
I am getting an error:

Argument 1 passed to FluidTYPO3\Flux\View\PreviewView::getPreviewOptions() must be an instance of FluidTYPO3\Flux\Form, boolean given, called in /.../typo3_cms/typo3conf/ext/flux/Classes/View/PreviewView.php on line 164

20 FluidTYPO3\Flux\View\PreviewView::getPreviewOptions(boolean) -> line 164
19 FluidTYPO3\Flux\View\PreviewView::getPreview(GeorgRinger\News\Provider\TestProvider, array) -> line 804
18 FluidTYPO3\Flux\Provider\AbstractProvider::getPreview(array) -> line 89
17 FluidTYPO3\Flux\Backend\Preview::renderPreview("<strong><a href="/typo3/index.php?route=%2Frecord%…tt_content-9" title="Edit">News</a></strong><br />", "<a name="c9"></a>", array, boolean) -> line 70
16 FluidTYPO3\Flux\Backend\Preview::preProcess(TYPO3\CMS\Backend\View\PageLayoutView, boolean, "<strong><a href="/typo3/index.php?route=%2Frecord%…tt_content-9" title="Edit">News</a></strong><br />", "<a name="c9"></a>", array) -> line 1732
15 TYPO3\CMS\Backend\View\PageLayoutView::tt_content_drawItem(array) -> line 645
...

I added the "Preview" section in List.html Template from news to be sure it is not related to that.
I am not sure if this is related to my setup or flux, i will set up a fresh installation and test it again tomorrow.

**Comment by fkalka** [comment]
Ok the problem was something else. Everything is working great, thanks for the fix!

**Comment by fkalka** [comment]
Because i am not able to use the dev-branch atm, i created a patch that allows me to use custom Providers on pi_flexform with the current repo version of FluidTYPO3
[DynamicFlexForm.txt](https://github.com/FluidTYPO3/flux/files/1141995/DynamicFlexForm.txt)

Maybe it is useful for someone...

**Comment by NamelessCoder** [comment]
In case you like to apply your diffs manually:

```diff
--- Original
+++ New
@@ -24,6 +24,11 @@
 {
 
     /**
+     * @var boolean
+     */
+    protected static $recursed = false;
+    
+    /**
      * @var ObjectManagerInterface
      */
     protected $objectManager;
@@ -88,6 +93,9 @@
      */
     public function getDataStructureIdentifierPreProcess(array $tca, $tableName, $fieldName, array $record)
     {
+        if (static::$recursed) {
+            return [];
+        }
         // Select a limited set of the $record being passed. When the $record is a new record, it will have
         // no UID but will contain a list of default values, in which case we extract a smaller list of
         // values based on the "useColumnsForDefaultValues" TCA control (we mimic the amount of data that
@@ -113,12 +121,22 @@
         if (count($providers) === 0) {
             return [];
         }
-        return [
+        $fft = GeneralUtility::makeInstance(ObjectManager::class)->get(\TYPO3\CMS\Core\Configuration\FlexForm\FlexFormTools::class);
+        static::$recursed = true;
+        $identifier = [
             'type' => 'flux',
             'tableName' => $tableName,
             'fieldName' => $fieldName,
-            'record' => $limitedRecordData
+            'record' => $limitedRecordData,
+            'originalIdentifier' => $fft->getDataStructureIdentifier(
+                [ 'config' => $GLOBALS['TCA'][$tableName]['columns'][$fieldName]['config']],
+                $tableName,
+                $fieldName,
+                $record
+            )
         ];
+        static::$recursed = false;
+        return $identifier;
     }
 
     /**
@@ -151,7 +169,10 @@
             $record = $this->recordService->getSingle($identifier['tableName'], '*', $record['uid']);
         }
         $fieldName = $identifier['fieldName'];
-        $dataStructArray = [];
+        
+        $fft = GeneralUtility::makeInstance(ObjectManager::class)->get(\TYPO3\CMS\Core\Configuration\FlexForm\FlexFormTools::class);
+        $dataStructArray = $fft->parseDataStructureByIdentifier($identifier['originalIdentifier']);
+        
         $providers = $this->configurationService->resolveConfigurationProviders($identifier['tableName'], $fieldName, $record);
         if (count($providers) === 0) {
             // No Providers detected - we will cache this response
```

Thanks @fkalka for extracting that patch!
