### ISSUE TITLE
Grids in Workspaces are not working as expected.

### ISSUE THREAD

**Issue by turko** [FluidTYPO3/flux#1411]
1. Create a new content in Workspace that use a dynamic grid.
2. Add a few columns or areas
3. Save and close
4. Edit it again and add a new area.
5. Save and close
6. Try to add content to the new area

This is due to the method: AreaListItemsProcessor -> getContentAreasDefinedInContentElement which do not use the workspace overlay. 
Adding a:
```
        \TYPO3\CMS\Backend\Utility\BackendUtility::workspaceOL('tt_content', $record);
```
after line 92 fix this issue.

This is valid for Typo3 7.6 and Flux 7.4.0 but it should be also working on Typo3 8.x and Flux 8.x

**Comment by NamelessCoder** [comment]
Thanks for the suggested fix @turko - this place was indeed forgotten while revamping the workspaces support during the winter!

If you're up for it you are more than welcome to prepare a pull request ;)
