### ISSUE TITLE
flux:field.tree - Elemenents with sub elements not selected

### ISSUE THREAD

**Issue by Lumrenion** [FluidTYPO3/flux#1414]
In this example, I assume that the table is 'pages'.
When I select a page that has sub pages, it first gets selected in the tree. After saving it is set in the database correctly. 
When the form gets loaded again, the input field is missing the previously selected pages that has sub pages. So the node is not selected and when saving again it is missing in the database if it was not manually selected again.

I checked the default 'categories' field when editing a page - this one works as expected. This leads me to the conclusion that it is a bug in flux.

My Versions:
TYPO3: 8.7.1
PHP: 7.1
Flux: 8.2.1
fluidpages (this is where the form gets rendered): dev-development

**Comment by NamelessCoder** [comment]
Please re-check that you're filling all required properties to operate a tree component, then if that's all in order, report this issue to the TYPO3 core bug tracker - https://forge.typo3.org/projects/typo3cms-core/issues. Flux does not render HTML of the components you use, nor do we handle saving of the selected values - we only create TCA. For a more in-depth explanation about how to distinguish Flux bugs from core bugs, see https://fluidtypo3.org/blog/news/bugs-core-or-flux.html.

Note that field types work differently depending on *where* you use them, so you can't compare the standard categories field unless your case matches this 100% including using the component outside, not inside, a flexform.
