### ISSUE TITLE
[BUG][TYPO3-8.7.1] Moving a record to another page causes error in SQL statement

### ISSUE THREAD

**Issue by sypets** [FluidTYPO3/flux#1416]
**System environment**

- TYPO3 8.7.1
- flux version : 8.2.1 (current version)
- versions and workspaces extensions not installed

I used a fresh TYPO3 8.2.1 installation with introduction package to reproduce this to ensure a clean environment without sideeffects from other extensions.

**Results**
The following steps results in this error message:

```
Oops, an error occurred!
An exception occurred while executing 'SELECT `t3ver_move_id` FROM `tt_content` WHERE (15) AND ((`tt_content`.`deleted` = 0) AND (`tt_content`.`hidden` = 0) AND (`tt_content`.`starttime` <= 1495543860) AND ((`tt_content`.`endtime` = 0) OR (`tt_content`.`endtime` > 1495543860))) GROUP BY ` AND t3ver_state = 3 AND deleted = 0 AND uid = 15`'
: Unknown column ' AND t3ver_state = 3 AND deleted = 0 AND uid = 15' in 'group statement'
```

**Steps to reproduce**

You can reproduce this with minimal TYPO3 system without having created any flux containers.

The steps to reproduce are the same as in this issue: https://github.com/FluidTYPO3/flux/issues/1415

1. Select a record from a page (e.g. pid=35) and cut it to clipboard.
2. Select a different page (e.g. pid=2), in list mode choose "paste in clipboard content"

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/c07dffec7386b0e8197acb1317bc035256995837
