### ISSUE TITLE
Richtext processing is using old methods which leads to problems

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1421]
I encounter these problems when editing existing text having multiple paragraphs. On each save, there were new empty paragraphs after saving.
After some study i found the reason in flux. If using the setting `enableRichtext="true"`, it is internally translated to
`defaultExtras = richtext:rte_transform[flag=rte_enabled|mode=ts_css]`

The correct way would be not to use defaultExtras anymore, but directly `enableRichtext="true"`

After changing this in flux/Classes/Form/Field/Text.php, the problem disappeared.

Would you like me to send a pull request?

**Comment by cedrictempestini** [comment]
Same problem :/

**Comment by kersten** [comment]
@steffenk  thanks for the debug. I have this problem too.

**Comment by kraftb** [comment]
I also fixed this issue. I also added a TypoScript configuration option which allows to set the RTE configuration being used (minimal, default, full)

**Comment by NamelessCoder** [comment]
Closed via https://github.com/FluidTYPO3/flux/pull/1438
