### ISSUE TITLE
Incorrect rendering of anchor links (symbol "c" is missing)

### ISSUE THREAD

**Issue by gvv1401** [FluidTYPO3/flux#1424]
I have 2 nested FCE elements (FCE_Table.html and FCE_Td.html).
FCE_Td has RTE field:
<flux:field.text name="cell-text" enableRichText="1" rows="4" default="" label="Cell content"/>
When I inserted anchor link into this field I got wrong result on FE: http://domain.de/?id=3#119 instead of http://domain.de/?id=3#c119
Symbol "c" missing!
When FCE_Td is not nested into FCE_Table - anchor link is correct.

I think next line of FCE_Table has a problem: <flux:content.render area="tbody" />

TYPO3: v.7.6.19
Flux: v.8.2.1

**Sources of FCE files**
====================================
FCE_Table.html:
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	 xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	 xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	 xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

	<f:layout name="Content" />
	
	<f:section name="Configuration">
		
		<flux:form id="t3ua_table" options="{group: 'Tabellen', icon: '{f:uri.resource(path: \'Icons/ContentElements/table.png\', extensionName: \'t3_sitepackage\')}'}">
		
			<flux:form.sheet name="thsheet" label="Header of table">
                <flux:form.section name="ths" label="Cells (TH)">
					<flux:field.checkbox name="double-width" label="Add .tDoubleWith to first column" default="0" />
                    <flux:form.object name="th" label="Cell (TH)">
                        <flux:field.text name="cell-text" enableRichText="0" rows="4" default="" label="Cell content"/>
                        <flux:field.custom name="cell-option"><h3>Cell options</h3></flux:field.custom>    
                        <f:comment><flux:field.input name="cell-width" label="Spalten-Breite (% oder px)" size="6"/></f:comment>
                        <flux:field.input name="cell-colspan" size="10" default="0" label="Colspan value"/>
                        <flux:field.input name="cell-rowspan" size="10" default="0" label="Rowspan value"/>
                    </flux:form.object>
                </flux:form.section>
			</flux:form.sheet>
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column name="tbody" colPos="18182" label="{f:if(condition: '{0: \'{table.tag}\'} == {0: \'table\'}', then: 'tbody', else: '{table.tag}') -> f:format.case(mode: 'upper')}" style="width: 100%; border: 1px solid #000; margin: 10px 0;"/>
                </flux:grid.row>
            </flux:grid>

		</flux:form>
				
	</f:section>

	<f:section name="Preview">
		<table border="1" style="width:100%;">
            <tbody>
				<tr>
					<f:for each="{ths}" as="cell" iteration="cellIteration">				
						<td style="padding:2px!important;"{f:if(condition: '{cell.th.cell-rowspan}', then: ' rowspan="{cell.th.cell-rowspan}"')}{f:if(condition: '{cell.th.cell-colspan}', then: ' colspan="{cell.th.cell-colspan}"')} class="{cssClass}">
                            {cell.th.cell-text}
						</td>
					</f:for>
				</tr>
			</tbody>
		</table>
    </f:section>

	<f:section name="Main">
		<v:variable.set name="cellTag" value="th" />
		<v:variable.set name="containerClasses" value="bTableWrap mScroll" />
		<v:variable.set name="tableClasses" value="bTable mTableType_1 mSingleColOnMob" />
		<v:variable.set name="tableStyles" value="" />
		<f:if condition="{v:content.info(field: 'layout')} == 102">
			<v:variable.set name="containerClasses" value="bTableWrap mScroll" />
			<v:variable.set name="tableClasses" value="bTable mTableType_1" />
			<v:variable.set name="tableStyles" value="style='min-width: 500px;'" />
		</f:if>
		<f:if condition="{v:content.info(field: 'layout')} == 103">
			<v:variable.set name="cellTag" value="td" />
			<v:variable.set name="containerClasses" value="bTableWrap" />
			<v:variable.set name="tableClasses" value="bTable mTableType_2 responsive" />
		</f:if>
		<f:if condition="{v:content.info(field: 'layout')} == 104">
			<v:variable.set name="containerClasses" value="bTableWrap" />
			<v:variable.set name="tableClasses" value="bTable mTableType_3 responsive" />
		</f:if>
        <div class="{containerClasses}">
            <table class="{tableClasses}" {tableStyles}>
				<v:tag name="{f:if(condition: '{ths}', then: 'tr', else: 'none')}">
					<f:for each="{ths}" as="cell" iteration="cellIteration">
						<f:if condition="{cellIteration.cycle} == 1">
						<f:then>
							<{cellTag}{f:if(condition: '{cell.th.cell-rowspan}', then: ' rowspan="{cell.th.cell-rowspan}"')}{f:if(condition: '{cell.th.cell-colspan}', then: ' colspan="{cell.th.cell-colspan}"')}{f:if(condition: '{double-width} == 1', then:' class="tDoubleWith"', else:"")}>
								{cell.th.cell-text}
							</{cellTag}>
						</f:then>
						<f:else>
							<{cellTag}{f:if(condition: '{cell.th.cell-rowspan}', then: ' rowspan="{cell.th.cell-rowspan}"')}{f:if(condition: '{cell.th.cell-colspan}', then: ' colspan="{cell.th.cell-colspan}"')}>
								{cell.th.cell-text}
							</{cellTag}>
						</f:else>
						</f:if>
					</f:for>
				</v:tag>
                <v:tag name="{f:if(condition: '{tbody}', then: 'tbody', else: 'none')}">
                    <flux:content.render area="tbody" />
                </v:tag>
            </table>
        </div>
	</f:section>
	
</div>

FCE_Td.html
=============================
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	 xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	 xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	 xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

	<f:layout name="Content" />
	
	<f:section name="Configuration">
		
		<flux:form id="t3ua_td" options="{group: 'Tabellen', icon: '{f:uri.resource(path: \'Icons/ContentElements/table.png\', extensionName: \'t3_sitepackage\')}'}">
			<flux:form.sheet name="tdsheet" label="Row cells">
                <flux:form.section name="tds" label="Cells (TD)">
					<flux:field.checkbox name="double-width" label="Add .tDoubleWith to first column" default="0" />
                    <flux:form.object name="td" label="Cell (TD)">
                        <flux:field.custom name="cell-data"><h3>Cell data</h3></flux:field.custom>
                        <flux:field.text name="cell-text" enableRichText="1" rows="4" default="" label="Cell content"/>
                        <flux:field.custom name="cell-option"><h3>Cell options</h3></flux:field.custom>    
                        <f:comment><flux:field.input name="cell-width" label="Spalten-Breite (% oder px)" size="6"/></f:comment>
                        <flux:field.input name="cell-colspan" size="10" default="0" label="Colspan value"/>
                        <flux:field.input name="cell-rowspan" size="10" default="0" label="Rowspan value"/>
                        <flux:field.custom name="cell-images"><h3>Image</h3></flux:field.custom>
                        <flux:field.file name="image" label="Select image" showThumbnails="1" allowed="jpg,jpeg,png,gif"/>
                    </flux:form.object>
                </flux:form.section>
			</flux:form.sheet>
		</flux:form>
				
	</f:section>

	<f:section name="Preview">
		<table border="1" style="width:100%;">
            <tbody>
				<tr>
					<f:for each="{tds}" as="cell" iteration="cellIteration">
						<td style="padding:2px!important;"{f:if(condition: '{cell.td.cell-rowspan}', then: ' rowspan="{cell.td.cell-rowspan}"')}{f:if(condition: '{cell.td.cell-colspan}', then: ' colspan="{cell.td.cell-colspan}"')}>
                            <f:if condition="{cell.td.image}">
                                <f:then>
                                    {f:image(src: '{cell.td.image}', alt: '{cell.td.cell-text}', width: '60c')}
                                </f:then>
                                <f:else>
                                    {cell.td.cell-text -> f:format.raw()}
                                </f:else>
                            </f:if>
						</td>
					</f:for>
				</tr>
			</tbody>
		</table>
	</f:section>

	<f:section name="Main">
	
        <v:tag name="{f:if(condition: '{tds}', then: 'tr', else: 'none')}">
            <f:for each="{tds}" as="cell" iteration="cellIteration">
                {v:variable.get(name: 'elementData.ths.{cellIteration.index}.th.cell-text') -> flux:form.data(table: 'tt_content', field: 'pi_flexform', record: '{pageElement}', as: 'elementData') -> f:if(condition: '{pageElement.uid} == {v:content.info(field: \'tx_flux_parent\')}') -> f:for(each: '{v:content.get(column: \'0\', render: \'0\', pageUid: \'uid\')}', as: 'pageElement') -> v:variable.set(name: 'data')}
				
				<f:if condition="{cellIteration.cycle} == 1">
				<f:then>
					<f:if condition="{double-width} == 1">
						<v:variable.set name="doubleWidth" value="tDoubleWith" />
					</f:if>
				</f:then>
				<f:else>
					<v:variable.set name="doubleWidth" value="" />
				</f:else>
				</f:if>				

                <f:if condition="{v:content.info(contentUid: '{v:content.info(field: \'tx_flux_parent\')}', field: 'layout')} == 102">
                    <td{f:if(condition: '{data}', then: ' data-th="{data}"')}{f:if(condition: '{cell.td.cell-rowspan}', then: ' rowspan="{cell.td.cell-rowspan}"')}{f:if(condition: '{cell.td.cell-colspan}', then: ' colspan="{cell.td.cell-colspan}"')} class="{doubleWidth}">
                        <f:if condition="{cell.td.image}">
                            <f:then>
                                <div class="bGImg">
                                    <figure>
                                        <div data-image="{f:uri.image(src: '{cell.td.image}')}" data-gallery-id="id_{v:content.info(field: 'uid')}" class="jsShowGModal jsFirstImage">
                                            <img src="{f:uri.image(src: '{cell.td.image}')}" alt="">
                                        </div>
                                        <figcaption>
                                            <span data-image="{f:uri.image(src: '{cell.td.image}')}" data-gallery-id="id_{v:content.info(field: 'uid')}" class="eGImg_ico jsShowGModal jsFirstImage"></span>
                                            <span data-gallery-id="id_{v:content.info(field: 'uid')}" title="{cell.td.cell-text -> f:format.raw()} ©" class="jsGModalText">{cell.td.cell-text -> f:format.raw()}</span>
                                        </figcaption>
                                    </figure>
                                </div>
                            </f:then>
                            <f:else>
								{cell.td.cell-text -> f:format.html()}
							</f:else>
                        </f:if>
                    </td>				
                </f:if>
                <f:if condition="{v:content.info(contentUid: '{v:content.info(field: \'tx_flux_parent\')}', field: 'layout')} == 103">
                    <td{f:if(condition: '{cell.td.cell-rowspan}', then: ' rowspan="{cell.td.cell-rowspan}"')}{f:if(condition: '{cell.td.cell-colspan}', then: ' colspan="{cell.td.cell-colspan}"')} class="{doubleWidth}">
						{cell.td.cell-text -> f:format.html()}
                    </td>				
                </f:if>
                <f:if condition="{v:content.info(contentUid: '{v:content.info(field: \'tx_flux_parent\')}', field: 'layout')} == 104">
                    <td{f:if(condition: '{cell.td.cell-rowspan}', then: ' rowspan="{cell.td.cell-rowspan}"')}{f:if(condition: '{cell.td.cell-colspan}', then: ' colspan="{cell.td.cell-colspan}"')} class="{doubleWidth}">
						{cell.td.cell-text -> f:format.html()}
                    </td>				
                </f:if>
				
            </f:for>
        </v:tag>
	</f:section>
	
</div>

Regards, Vadym.

**Comment by NamelessCoder** [comment]
No longer an issue in `dev-development`, will be fixed with release 9.0. Please note that the anchors are not added by Flux itself so the exact anchor value may depend on the "content rendering extension" (fluid styled content, css styled content, or custom content rendering ext) you currently use.
