### ISSUE TITLE
Dropzone containers do not respect BE-User allowed_languages

### ISSUE THREAD

**Issue by pkracht** [FluidTYPO3/flux#1429]
- TYPO3 8.7.2 LTS
- Flux: Fluid FlexForms	flux	8.2.1 (stable)

In original \TYPO3\CMS\Backend\View\PageLayoutView there is a check before inserting the `<div class="t3-page-ce-dropzone-available t3js-page-ce-dropzone-available"></div>` using checkLanguageAccess() like:

```
                if ($this->getBackendUser()->checkLanguageAccess($lP)) {
                    $content[$columnId] .= '
                    <div class="t3-page-ce t3js-page-ce" data-page="' . (int)$id . '" id="' . StringUtility::getUniqueId() . '">
                        <div class="t3js-page-new-ce t3-page-ce-wrapper-new-ce" id="colpos-' . $columnId . '-' . 'page-' . $id . '-' . StringUtility::getUniqueId() . '">'
                            . $link
                            . '</div>
                        <div class="t3-page-ce-dropzone-available t3js-page-ce-dropzone-available"></div>
                    </div>
                    ';
                }

```

In class \FluidTYPO3\Flux\View\PreviewView the templates array always contains the dropzone-div. This allows BE users (limited to just some languages) to drag'n'drop ce elements in languages view from their own language column into default! It is possible to drag elements in default language into flux elements, too. The second case is not saved by TYPO3, the first case is.

**Comment by NamelessCoder** [comment]
Solved in Flux 9.x - won't be solved in Flux 8.2.x since this branch is no longer maintained. You should be able to use Flux 9.x on TYPO3 8.7 so hopefully you've been able to upgrade since creating this issue :)
