### ISSUE TITLE
Make it possible to align flexform fields in a line (like a palette

### ISSUE THREAD

**Issue by kaystrobach** [FluidTYPO3/flux#143]
![2013-05-06_11-07-22](https://f.cloud.github.com/assets/1185776/465309/e0ef0e32-b62c-11e2-826f-8c0a731d1b29.png)

On Top you see, how it is, below you see, how i would like to have it :D

Thanks

Sources:
http://lists.typo3.org/pipermail/typo3-german/2010-February/065592.html

**Comment by opi99** [comment]
Adding as reference https://forge.typo3.org/issues/75266
