### ISSUE TITLE
[FEATURE] Configurable cropVariants in FAL image elements ("Image manipulation" feature)

### ISSUE THREAD

**Issue by geldmacher** [FluidTYPO3/flux#1433]
It would be really nice, if the crop, focus and cover area feature could be configurable for FAL elements. See: https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/ImageManipulation.html

Are you planing anything or is this already possible?

**Comment by NamelessCoder** [comment]
There is no Flux API for this new TCA option so it's not currently possible, and there are no currently active plans to add it. I don't object to it though, so if you can confirm that this component also works in a flexform context you are more than welcome to create a pull request to add the VH and Form components needed to create this new type of pseudo-field.

**Comment by geldmacher** [comment]
Ok, thanks. I will have a look at it ... I hope there is some free time for it in the near future. =D

**Comment by steffenk** [comment]
I use the crop config in PageTS, and this works also in flux fal fields.

**Comment by raWINce** [comment]
This is the way I do it right now. I hope this helps someone. (*This of course only works if you do **not** use [fluidcontent](https://github.com/FluidTYPO3/fluidcontent)*)

**TCA/Overides/tt_content.php:**
```php
$GLOBALS['TCA']['tt_content']['types']['flux_slider']['showitem'] .= ',--div--;Image,assets,';

$GLOBALS['TCA']['tt_content']['types']['flux_slider']['columnsOverrides']['assets']['config'] = [
    'minitems' => 1,
    'maxitems' => 5,
];

$GLOBALS['TCA']['tt_content']['types']['flux_slideritem']['columnsOverrides']['assets']['config']['overrideChildTca']['columns']['crop']['config'] = [
    'cropVariants' => [
        'default' => [
            'disabled' => true,
        ],
        'mobile' => [
            ...
        ],
        ...
        ],
    ],
];
```

**Comment by GuidoJansen** [comment]
@raWINce This doesn't work with me. Can you show me the `<flux:field>` configuration and the `<flux:form>` configuration on your example?

**Comment by chriskrj** [comment]
@raWINce i have the same problem like @GuidoJansen i can see all my settings in the configuration Tool but in my own Content-Element this doesn't work. Why do you you one time flux_slider and one time flux_slideritem?

Would be nice if you could show us your <flux:form>

**Comment by raWINce** [comment]
I updated my original answer. Hope it helps

**Comment by GuidoJansen** [comment]
@raWINce Thanks for sharing. I will take a look into it.
