### ISSUE TITLE
tx_flux_column empty when content elements added into flux grid column 

### ISSUE THREAD

**Issue by typecat** [FluidTYPO3/flux#1439]
TYPO3 8.7.3
flux 8.2.1
fluidcontent: 5.2.0

How to recreate:
- Create a conten element with flux:grid.column (e.g. 2 column container).
- Click on "+ Conten" button inside the grid column and add a content element (doesn't matter if fluidcontent element like text or custom flux content element)
- Save & close  and the nested content element is not displayed in the grid column

Cause:
tx_flux_column is empty, but actually should contain the name of the grid column

This happens only if content elements are created inside the grid column. If content elements are dragged into the grid column, the tx_flux_column is set properly.

Related Issues:
https://github.com/FluidTYPO3/flux/issues/1330
https://github.com/FluidTYPO3/flux/issues/1312

In TYPO3 7.6.x it was possible to fix this bug by putting the following line to ext_tables.php of the provider extension:
require_once(TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('flux', 'Configuration/TCA/Overrides/tt_content.php'));

Unfortunately this doesn't work in TYPO3 8.7.x anymore.

**Comment by pixelbrackets** [comment]
Same here, any thoughts about this @NamelessCoder ?

**Comment by typecat** [comment]
Found the reason: I was using
`<flux:grid.column name="1" label="middle column"/>`
Apparently a number isn't a valid column name anymore. Using
`<flux:grid.column name="column.1" label="middle column"/>`
solves the problem shorthand and #1440 is also no problem anymore. But it would be nice to know why it became that way. I tried debugging but got lost at some point. Imho it sould be at least noted in the view helper's documentation.

**Comment by marcodefelice** [comment]
Hi these solution not solve the problem. example

<flux:form.sheet name="name" label="Stile visore">
                <flux:grid>
                    <flux:grid.row>
                        <flux:grid.column name="namecomp" label="Label" />
                    </flux:grid.row>
                </flux:grid>
            </flux:form.sheet>
        </flux:form>

but with the name, into the BE not show an elements

**Comment by marcodefelice** [comment]
I've solved now the problem by including a tt_content.php into ext_table.php, and modify tt_content.php adding the following code ( old code ) ( at line 14 )

$GLOBALS['TCA']['tt_content']['types']['fluidcontent_content']['showitem'] = '
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:general,
            --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.general;general,
            --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.header;header,
            --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance, layout;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:layout_formlabel,
            --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.appearanceLinks;appearanceLinks,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language, --palette--;;language,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access,
            --palette--;;hidden,
            --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.access;access,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:categories,
            --div--;LLL:EXT:lang/Resources/Private/Language/locallang_tca.xlf:sys_category.tabs.category, categories,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:notes, rowDescription,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:extended,
            --div--;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tabs.relation, tx_flux_parent, tx_flux_column
        ';

**Comment by typecat** [comment]
I'm aware of this solution and tried this before (see issue description, the flux/Configuration/TCA/Overrides/tt_content.php containts pretty much the same). Unfortunately this doesn't work for TYPO3 v8 and higher, because the ext_tables.php file is deprecated since TYPO3 7.3 (see https://wiki.typo3.org/TYPO3.CMS/Releases/7.3/Deprecation#Deprecation:_.2365344_-_typo3conf.2FextTables.php_deprecated).
I haven't tested my workaround for sheets yet. But maybe someone from the flux team can give a solution?

**Comment by NamelessCoder** [comment]
> because the ext_tables.php file is deprecated since TYPO3 7.3

This is not the same file. `typo3conf/extTables.php` is deprecated - `typo3conf/ext/foobar/ext_tables.php` is not.

**Comment by typecat** [comment]
@NamelessCoder My bad. Anyway the solution using the TCA entries does not work in TYPO3 8.7. But since we've got your attention, maybe you can explain why  `<flux:grid.column name="1" label="middle column"/>` doesn't work anymore and how to use the grid structures properly now? All I can say that we had no trouble before flux 8.0.

**Comment by NamelessCoder** [comment]
It's likely TYPO3 and Flux confuses the column name with a `colPos` value. The treatment of nested content is triggered by differences in the column identifier. This is also the reason why there is both a `colPos` and `name` argument on `flux:grid.column` - one should use strings, the other integers.

Use it the same as before except try to avoid any possibility of TYPO3 or Flux confusing your column identifier with a `colPos` value.

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.
