### ISSUE TITLE
Default language locallang file

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/flux#1444]
Isn't better file `locallang_db.xlf` instead of `locallang.xlf`?

**Comment by NamelessCoder** [comment]
Extbase/Fluid's default is locallang.xlf and Flux is tightly integrated with those - this is why we use that filename as the default. Same as if you had used `f:translate` in a BE Fluid template ;)

**Comment by ogrosko** [comment]
What about to configure this path eg. in plugin `extConf` ?
