### ISSUE TITLE
TYPO3 8.7.4 + Flux destroys FCE-Elements while editing/saving

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1448]
I'm running TYPO3 8.7.4 with Flux 8.2.1, fluidpages  4.1.0 and fluidcontent 5.2.0.

The primary language is working fine. Trying to localize to a second language showed a very strange behaviour. After translation of FCE Content-Elements the localised element looks fine at first. But after editing the localized element and saving it, it renders useless as some information for flux/fluidcontent seems to miss afterwards.

It then shows this warning after saving the localized element:
> **Warning**
> Fluid Content type not selected - edit this element to fix this!

----------------
**Primary Language CE**
![](https://image.prntscr.com/image/lcz5fRGcSL6P-eGIYIJCMA.png)

----------------
**After Localisation and Saving the localized CE**
(sometimes 2-times saving is needed, even works without changing anything)
![](https://image.prntscr.com/image/4EneJ6GhS_GiKoNbngaQiw.png)

**Comment by typoworx-de** [comment]
I tried to figure out what happens and compared the tt_content records of the primary language record and the localized damaged record.

Despite of the obviously different field/values these are different or empty:
- Field: tx_fed_fcefile, Primary Language: "fluidtemplates:Dividers.htm", Secondary Language:  ""
- Field: tx_flux_children, Primary Language: "0", Secondary Language: NULL

The Field "pi_flexform" looks fine (same content).

**Comment by typoworx-de** [comment]
I tried to manually set the field tx_fed_fcefile with the value of the primary-language record. Afterwards the error was gone!

Localisation seems to ignore this field.

**Comment by typoworx-de** [comment]
Seems to be related to this Ticket #1161. Already checked if I can use the solution from there. But EXT:fluidcontent/Configuration/TCA/Overrides/tt_content.php already looks like the solution mentioned there.

**Comment by NamelessCoder** [comment]
Did you test this on `dev-development` of Flux (and Fluidcontent)? Pretty sure this isn't a problem on those versions so it would be great if you can confirm that.

**Comment by dacostafilipe** [comment]
I have the same problem after moving from `master`to `development`.

Typo3 **8.7.8**
Flux  **dev-development (5a21462)**
fluidcontent **dev-development (aae5fa6)**
vhs **dev-development (404d860)**

**Comment by xf-** [comment]
@dacostafilipe  and @typoworx-de  i had an issue with duplicate content and a controller until i removed fluidcontent in favor of flux with native CType.

**Comment by dacostafilipe** [comment]
@xf- We would have to rewrite a lot of CE's, but getting rid of fluidcontent was on our radar anyway. Could you point me to same guide/code example on how you implemented it? Thx

**Comment by xf-** [comment]
Only thing i had todo is converting the DB - instead of fluidcontent you need the extension name lowercase (i think together) and _id (or template name lowercase - always the same in my case).
Easiest way is to remove fluidcontent on a test instance, update flux and go into an existing record and select the new CType. Take a look at the DB before and after.
Afterwards i created a few query's to set the CType based on filename.

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.
