### ISSUE TITLE
Asset loading

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1449]
Hi,

on fresh TYPO3 8.7.4, flux with development branch, i got several exceptions because resources where not found (In BE rendering Flux elements).

After debugging i found this to be the correct way to include them, you see i the patch.
I didn't checked it with fluid_content, but i'm happy to use flux as standalone.
If you want i can create a pull request.

Patch:
   ```
$pageRenderer->addCssFile(
-                $doc->backPath . GeneralUtility::getFileAbsFileName('EXT:flux/Resources/Public/css/grid.css')
+                'EXT:flux/Resources/Public/css/grid.css'
             );

protected function attachAssets()
     {
-        $GLOBALS['TBE_STYLES']['stylesheet'] = GeneralUtility::getFileAbsFileName('EXT:flux/Resources/Public/css/icon.css');
+        $GLOBALS['TBE_STYLES']['stylesheet'] = 'EXT:flux/Resources/Public/css/icon.css';
     }

```

**Comment by steffenk** [comment]
Pull request: #[1450](https://github.com/FluidTYPO3/flux/pull/1450)

**Comment by NamelessCoder** [comment]
Pull request merged, closing.
