### ISSUE TITLE
Support .svg and .jpg icons

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1455]
The "Icon name by convention" feature only supports .png and .gif icons, but not .svg and .jpg: https://github.com/FluidTYPO3/flux/pull/687

.svg scales properly (even the flux fallback icon is svg!) and .jpg is useful if you use small screenshots of elements

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Vom 31.8 bis und mit 1.9.2017 nehme ich an einer Konferenz teil (frontend conference https://www.frontendconf.ch), und bin deshalb im Büro nicht erreichbar.
 
Die Nachrichten werden in dieser Zeit nur sporadisch gelesen! In dringenden Angelegenheiten erreichen Sie mich zeitweise auf dem Mobile. Ansonsten bitte ich Sie eine Sprachnachricht zu hinterlassen, damit ich Sie zurückrufen kann. Vielen Dank!

Sonnige Grüsse

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by cweiske** [comment]
I just see that .svg is supported now.
