### ISSUE TITLE
v:page.languageMenu raises error!

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1458]
Error & How to reproduce:

I'm using this Fluid-Code:
>             <v:page.languageMenu
>                 as="languageNavigation"
>                 linkCurrent="0"
>                 hideNotTranslated="0"
>             >

As you can see there is no attribute "languages". But on my System (tested on PHP 7.0 and 7.1 running on Linux, Apache2, PHP-FPM) this code raises a serious problem in these ViewHelper Codelines:

File: vhs/Classes/ViewHelpers/Page/LanguageMenuViewHelper.php

>         $limitLanguages = static::arrayFromArrayOrTraversableOrCSVStatic($this->arguments['languages'] ?? []);
>         if (empty($limitLanguages)) {
>             $where = 'uid IN (' . implode(',', $limitLanguages) . ')';
>         } else {
>             $where = '1=1';
>         }

empty always returns TRUE even if $limitLanguages is an empty array! This will raise an SQL-Error afterwards.

Resolve:
I was able to fix this using count() instead of empty() .

**Comment by cedricziel** [comment]
Please re-open the ticket on the vhs issue tracker.
