### ISSUE TITLE
Content rendered twice

### ISSUE THREAD

**Issue by benfansc** [FluidTYPO3/flux#1460]
Hi,

I do not really know where to put this (in vhs, flux, fluidcontent...) ?
Since the installation of vhs 4.3.0, each nested content of all the FCE using <flux:content.render..., is rendered twice in the frontend: once on the right place an a second time right before the FCE.
For example the content of the columns of a two columns FCE is rendered once before the FCE and one in the column.
vhs is not used in this FCE.
The problem dissapears with downgrading to vhs 4.2.0 and reappears with vhs 4.3.0.

I have Typo3 8.7.6 / fluidcontent 5.2.0 / fluidpages 4.1.0 / flux 8.2.1 / vhs 4.3.0

Here is the one of the FCE:
	<f:section name="Configuration">
		<flux:form id="panel">
			
			<flux:form.option name="group" value="Fluid elements"/>
		</flux:form>
		<flux:grid>
			<flux:grid.row>
				<flux:grid.column name="panelContenu" label="LLL:flux.panel.contenu" />
			</flux:grid.row>
		</flux:grid>
	</f:section>

	<f:section name="Main">
		<flux:content.render area="panelContenu" />
	</f:section>

Thanks.

**Comment by NamelessCoder** [comment]
This is a bug in VHS 4.3.0. It's solved in VHS dev-development but not yet in any TER release. See https://github.com/FluidTYPO3/vhs/pull/1362
