### ISSUE TITLE
Multi-Language setup using 'hideNonTranslated' causing SQL-Errors

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1461]
I'm getting some strange results trying to use multi-language mode on TYPO3 v.8 using 'strict' mode combined with 'hideNonTranslated'.

```
config {
    sys_language_mode = strict
    sys_language_overlay = hideNonTranslated

    language = en
    sys_language_uid = 0
    locale_all = en_GB.UTF-8

    htmlTag_langKey = en
    htmlTag_setParams = lang="en" dir="ltr"

    linkVars := addToList(L)
}
```
In Frontend this is resulting in this exception:

> caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
>    ERROR => **'Unknown column 'hideNonTranslated'** in 'where clause'' (52 chars)
>    lastBuiltQuery => 'SELECT uid FROM tt_content WHERE colPos = '1' AND pid = 1 AND (`tt_content`.
>       `deleted` = 0) AND (`tt_content`.`t3ver_state` <= 0) AND (`tt_content`.`hidd
>       en` = 0) AND (`tt_content`.`starttime` <= 1505122140) AND ((`tt_content`.`en
>       dtime` = 0) OR (`tt_content`.`endtime` > 1505122140)) AND (((`tt_content`.`f
>       e_group` = '') OR (`tt_content`.`fe_group` IS NULL) OR (`tt_content`.`fe_gro
>       up` = '0') OR (FIND_IN_SET('0', `tt_content`.`fe_group`)) OR (FIND_IN_SET('-
>       1', `tt_content`.`fe_group`)))) AND (**sys_language_uid IN (-1, 0, hideNonTran
>       slated)**) ORDER BY sorting ASC' (561 chars)

hideNonTranslated should never be used inside MySQL Query!

**Comment by typoworx-de** [comment]
May be it is related to VHS and this ticket...
https://github.com/FluidTYPO3/vhs/issues/1327

**Comment by cedricziel** [comment]
Care to prepare a pull request?

**Comment by NamelessCoder** [comment]
Being taken care of in https://github.com/FluidTYPO3/vhs/pull/1366 but I still need some confirmations - feel free to test and add review!
