### ISSUE TITLE
<flux:content.render> doesn't find new elements in workspace when using preview link.

### ISSUE THREAD

**Issue by cushingw** [FluidTYPO3/flux#1462]
I came across this while fixing up our content element problems found in FluidTYPO3/fluidcontent#399. We've got a fluid content element that renders tabs using <flux:content.render>. We've found that workspace preview links show the correct content for elements that have been updated in the workspace. However, elements that are new in the workspace don't show up at all.

This is remarkably similar to the issue we opened for <v:content.render> in FluidTYPO3/vhs#1297. I've found that the solution documented there seems to work here as well. Removing the call to versioningPlaceholderClause() in GetViewHelper.php seems to fix the problem.

```diff
diff --git a/flux/Classes/ViewHelpers/Content/GetViewHelper.php b/flux/Classes/ViewHelpers/Content/GetViewHelper.php
index ad14441..da209cf 100644
--- a/flux/Classes/ViewHelpers/Content/GetViewHelper.php
+++ b/flux/Classes/ViewHelpers/Content/GetViewHelper.php
@@ -159,12 +159,11 @@ class GetViewHelper extends AbstractViewHelper implements CompilableInterface
         // Depending on the TYPO3 setting config.sys_language_overlay, the $record could be either one of the
         // localized version or default version.
         $conditions = sprintf(
-            "(tx_flux_parent = '%s' AND tx_flux_column = '%s' AND pid = %d AND colPos = 18181) %s %s",
+            "(tx_flux_parent = '%s' AND tx_flux_column = '%s' AND pid = %d AND colPos = 18181) %s",
             $id,
             $area,
             $record['pid'],
-            $contentObjectRenderer->enableFields('tt_content'),
-            BackendUtility::versioningPlaceholderClause('tt_content')
+            $contentObjectRenderer->enableFields('tt_content')
         );
         $rows = static::$recordService->get('tt_content', '*', $conditions, '', $order, $offset . ',' . $limit);
 

```

**Comment by cushingw** [comment]
OK, I spoke somewhat too quickly. Removing the call to versioningPlaceholderClause() did cause the workspace preview link to show new elements, but it also resulted in elements that had been moved in the workspace showing up in both their old and new locations. So, clearly it's needed to handling moves.

**Comment by NamelessCoder** [comment]
@cushingw I plan to give the Flux content ViewHelpers the same treatment as the VHS ViewHelpers, which means that nearly all of these conditions will be removed (leaving only the parent, column and colPos conditions). You are welcome to give that a try but it's likely to happen over the weekend anyway ;)

**Comment by NamelessCoder** [comment]
Flux content ViewHelpers now use `TSFE->getRecords()` which should do all the overlaying and previewing you expect when using the "preview" links from workspaces (and in general when previewing FE as a logged-in BE user).
