### ISSUE TITLE
field:none

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/flux#1466]
When I use field `<flux:field.none name="identifier" label="Identifier" default="some default value"/>`. Field is not stored in flexform. Why it's bug or feature?
I need readonly input for `flux:form` or `flux:form.section` how to achieve this?

flux: v8.2.1
t3: 8.7.7

**Comment by NamelessCoder** [comment]
The `None` field type actually does mean that the field does not support a value at all, it only supports having a default value that can then be read in, for example, displayConds. It isn't very useful to be honest, but it's possible in TCA so it's possible in Flux.

If you want a hidden HTML field you'll need the Custom field type and create the HTML yourself.

**Comment by NamelessCoder** [comment]
Closing, assuming answer takes care of the question.
