### ISSUE TITLE
#641 continued - fluidtemplate with gridelement move and copy colPos -1 problem

### ISSUE THREAD

**Issue by TrueType** [FluidTYPO3/flux#1467]
we spend quite some time today trying to understand/get around this problem. #641 
see below with [move]=PID for empty gridelement and [move]=UID_of_relative_before_contentelement * -1

sry to open this up again, but we see no help but patching this line here - removing it:
```
            } elseif (0 > (integer) $relativeTo) {
....
//                $row['colPos'] = $relativeToRecord['colPos'];
```

/typo3/index.php?ajaxID=/ajax/record/process&ajaxToken=195db39819bb5ed7a3e54e66868a46290c9eab3b&cmd[tt_content][413][move]=74&data[tt_content][413][colPos]=-1&data[tt_content][413][tx_gridelements_container]=400&data[tt_content][413][tx_gridelements_columns]=101&data[tt_content][413][sys_language_uid]=0

/typo3/index.php?ajaxID=/ajax/record/process&ajaxToken=195db39819bb5ed7a3e54e66868a46290c9eab3b&cmd[tt_content][413][move]=-412&data[tt_content][413][colPos]=-1&data[tt_content][413][tx_gridelements_container]=400&data[tt_content][413][tx_gridelements_columns]=101&data[tt_content][413][sys_language_uid]=0

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Vom 9. bis und mit 14. Okt. 2017 bin ich ferienhalber ausser Lande, und deshalb im Büro nicht erreichbar.
 
Die Nachrichten werden in dieser Zeit nicht gelesen! In dringenden Angelegenheiten bitte ich Sie, ein SMS zu schreiben oder eine Sprachnachricht zu hinterlassen. Vielen Dank!

Frohe Grüsse

Damian Parpan


ACHTUNG, NEUE ADRESSE SEIT DEM 6. SEPT. 2017:

Damian Parpan
appline
Obergrundstrasse 70
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by jazzica** [comment]
Vielen Dank für Ihre Anfrage. Ich bin vom 07.10.17 bis einschl. 22.10.17 nicht zu erreichen.

Mit freundlichen Grüßen
Jessica Schlierenkamp

**Comment by NamelessCoder** [comment]
Very likely fixed by https://github.com/FluidTYPO3/flux/commit/720ced39c2c5a40266113b1e85ba1160ee851176 so taking the liberty of closing. Patch prevents passing negative colPos values and having them considered as relative to record UIDs - and should avoid the issue described in your report.
