### ISSUE TITLE
allowedContentTypes fluidcontent_content fails in TYPO3 8 flux 8.2.1

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#1470]
TYPO3 8.7.8
flux 8.2.1
fluidcontent 5.2.0
fluidpages 4.1.0

When predefining a fluidcontent ce in fluidpages, this doesn't work any longer:
in V 7 it worked.

The result is:
No fluidcontent ces are predefined.
```
<flux:grid>
	<flux:grid.row>
					<flux:grid.column colPos="10" name="main">
<flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
<flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'MyVendor.MyExt:ExampleOne.html,MyVendor.MyExt:ExampleTwo.html'}" />
	</flux:grid.column>
				</flux:grid.row>
			</flux:grid>
```

**Comment by blueamerican** [comment]
i had the wrong syntax.
right is:
<flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'my_ext:ExampleOne.html,my_ext:ExampleTwo.html'}" />

**Comment by MartinH0** [comment]
For me this is not working anymore, no matter what I do.

TYPO3 9.5.9
Flux 9.2.0
Fluidpages 5.0.0
VHS 5.2.0

This is my Folder structure
```
myext
  Ressource
    Private
      Template
        Content
          Copyright.html (id="copyright")
```

my Code:
```
<flux:grid.column colPos="30" colspan="8" rowspan="2" name="oben-links" label="Links groß">
  <flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
  <flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'myext:Copyright.html'}"/>
</flux:grid.column>
```
![image](https://user-images.githubusercontent.com/17692860/64862823-c0edd900-d633-11e9-9bab-e67fd61a5182.png)


If I remove:

```
  <flux:form.variable name="allowedContentTypes" value="fluidcontent_content" />
  <flux:form.variable name="Fluidcontent" value="{allowedContentTypes: 'myext:Copyright.html'}"/>
```

Everything will be fine and ALL FCE are getting shown

**Comment by X-Tender** [comment]
I use the CType of my CEs to set the allowedContetTypes, not via the ext:CE.html syntax, that didn't work for me either.
