### ISSUE TITLE
flux.form or flux.grid is not rendered in FE

### ISSUE THREAD

**Issue by anglee72** [FluidTYPO3/flux#1471]
Since fluidcontent is obsolete I don't use it anymore and have now following issue:
Content elements with flux.form or flux.grid are not rendered in Frontend anymore.

ERROR: Content Element with uid "108" and type "flux_apartment" has no rendering definition!

Seems to be the same or a similar issue [#1442]( https://github.com/FluidTYPO3/flux/issues/1442), but unfortunately I still do not know exactly how to solve the problem.
Is this a bug that will be solved in a later flux version? 
Or can someone clearly explain, what I have to do, to solve the issue? The very first solution from @pegle [#1442]( https://github.com/FluidTYPO3/flux/issues/1442) crashes the BE ... 

I'm using:
typo3 8.7.8
fluidpages 4.1.0
flux 8.2.1
vhs 4.3.2
fluid_styled_content 8.7.8

Sorry, I'm kind of a «simple typo3 user» and not a developer. 
Thanks for some support!

**Comment by jmverges** [comment]
Hi @anglee72,

are you using a database for a project that was working with fluidcontent? If so, you may need to update manually with sql your tt_content table.

**Comment by xf-** [comment]
Like @jmverges wrote. Maybe you need to update the record in Database OR go into backend and set the content element. We use now the native CType column (CType is Selectbox with Text, Form, Media ...). If you still have an issue, please comment again.
