### ISSUE TITLE
ContentTypeBuilder class, method "addPageTsConfig" bug

### ISSUE THREAD

**Issue by zoranilic** [FluidTYPO3/flux#1472]
Arround line 255 in "ExtensionManagementUtility::addPageTSConfig" there is a "sprintf" function.

`mod.wizards.newContentElement.wizardItems.%s.show := addToList(%s)`

This part gets the wrong value for the first "%s". That's actually last but one parameter for "sprintf".
Instead of "$group" it should be sanitized string. Check the screenshot:

![sanitize-string](https://user-images.githubusercontent.com/7780949/32143068-1c3ecab8-bca4-11e7-9070-3ab893e563ef.png)

**Comment by NamelessCoder** [comment]
Looks correct! @zoranilic would you like to prepare a patch for that one?
