### ISSUE TITLE
Can't see Flux Fields in Custom Content Elements as non-admin

### ISSUE THREAD

**Issue by moger-xx** [FluidTYPO3/flux#1477]
Flux: dev-development (cd43208c73eeb633ecb783040fa4f44ad322eb5a), also tested with the one from today.
TYPO3: 8.7.8

I've created some Content Templates with Flux. Everything works as expected: The Elements appear in the new content element wizard under "FCE" and show up as ctypes in the access rights configuration. Also I see the flux fields under "plugin options" - but only as admin.

As a non-admin user I cannot see the flux fields despite having permission for all possible tables, ctypes and enablefields.  

Flux form definition example:
```php    <f:section name="Configuration">
        <flux:form id="herocustom" label="Hero Unit - Freitext" options="{group: 'FCE'}">
            <flux:field.text name="text" label="Text" />
            <flux:field.input name="link" label="Button Linkziel (URL oder interne ID)">
                <flux:wizard.link />
            </flux:field.input>
            <flux:field.input name="linkText" label="Buttontext" />
        </flux:form>
    </f:section>
```

ext_localconf of provider ext:
```php 
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Constructiva.Yesican', 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Constructiva.Yesican', 'Content');
```
It makes no difference whether the flux fields are marked as `exclude="true"` or not.

**Comment by wazum** [comment]
Until this is resolved (through custom allow/exclude section in backend user configuration, as it has been provided by fluidcontent extension) you have to explicitly set ` exclude="false" ` for all your flux:field` elements. E.g.: 
``` <flux:field.text exclude="false" name="teaser" label="LLL:EXT:xxx" rows="5" cols="30" enableRichText="1" />
```

**Comment by NamelessCoder** [comment]
Already done a little while ago :) https://github.com/FluidTYPO3/flux/commit/25e7e7bf9d066cbe91d35a8a8bc48b4dd7aed55d

**Comment by jsegars** [comment]
I think the problem is actually in AbstractFieldViewHelper.  It flipped the default value of the view helper argument.

At least in my quick testing, the VH is always doing the setting so the default value for the property in AbstractFormField doesn't get used.

**Comment by NamelessCoder** [comment]
Of course! We have two places where defaults are applied and not all those defaults are constants.

I've pushed https://github.com/FluidTYPO3/flux/commit/afb5b3013a74299109ca1a30c6c0b1bc65a7bdc3 to also change the default in the VH API. Thanks for pointing it out!

**Comment by jsegars** [comment]
Perfect. Thanks for the quick fix!

**Comment by NamelessCoder** [comment]
You're very welcome. 9.0.1 will be made tomorrow I think - already, two rather serious fixes have been made (this one and a prevention of fatal errors when deleting records from tables other than tt_content).
