### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by Lagerregal** [FluidTYPO3/flux#1486]
I've tried to run Flux with PHP 7.2.0 but the following error occurred:

`Fatal error: Cannot use FluidTYPO3\Flux\Form\Container\Object as Object because 'Object' is a special class name in typo3conf/ext/flux/Classes/Form/AbstractFormComponent.php on line 15`

**Comment by NamelessCoder** [comment]
Applied via https://github.com/FluidTYPO3/flux/commit/46f20a9fc0a86fb1a0d55aad06421ba1bdfc81ef
