### ISSUE TITLE
Not working in PHP 7.2

### ISSUE THREAD

**Issue by lisandi** [FluidTYPO3/flux#1497]
We changed and updated but in PHP 7.2 flux gives an error
PHP Fatal error:  Cannot use FluidTYPO3\\Flux\\Form\\Container\\Object as Object because 'Object' is a special class name in .... typo3conf/ext/flux/Classes/Form/AbstractFormComponent.php on line 15

**Comment by NamelessCoder** [comment]
This should already be fixed in `dev-development` - which in general should be PHP 7.2 safe (but does not use any 7.2-specific features). Would you mind re-checking on that branch?

**Comment by xf-** [comment]
I had no problem with PHP7.2 on dev-development

**Comment by lisandi** [comment]
Wir sind auf die vorherige Version zurueck da die letzte schlichtweg nicht
lief


With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

 *ANDI BECKER*

CEO/General Manager LisAndi Co., Ltd.

*about.me/andibecker
<http://about.me/andibecker>--------------------------------------------------*
*LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk/Facetime/eMail:  andi@lisandi.com

--------------------------------------------------

**Comment by xf-** [comment]
Still works without a problem and also no error on any log about Flux on the production server
