### ISSUE TITLE
Drag and Drop inside a col is broken

### ISSUE THREAD

**Issue by golserma** [FluidTYPO3/flux#1500]
Hi I try to drag a fluid content element in to a two col grid. And it will not work :( Any ideas why?

Drag and drop from inside the col element seems to work.

[Example Video](https://drive.google.com/file/d/1Wg10LhbrBLCHeditfRAXnQ6-fk7C0xlF/view)

Typo 7.6.23
Flux: 8.2.1

**Comment by bauermar** [comment]
I've the same problem, the solution could be that the height of draging container will be set as placeholder on old position. Then it should work better, only a idea...

**Comment by xf-** [comment]
Not an issue in Flux dev-development (8.7+)

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.
