### ISSUE TITLE
Drag & drop to first position inside a grid.column does not work

### ISSUE THREAD

**Issue by mclewing** [FluidTYPO3/flux#1502]
When dragging any content element to the first position of a grid column it loses the relation to the parent element. Database rows "tx_flux_parent" and "tx_flux_column" are both set to "". This only occurs when trying to drop an element to the first position.

**Comment by xf-** [comment]
confirmed - wrong column

**Comment by wazum** [comment]
see #1534 for a working pull request to fix this

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.
