### ISSUE TITLE
[BUG] Flux Grid into preview workspace doesn't work correctly

### ISSUE THREAD

**Issue by marcodefelice** [FluidTYPO3/flux#1505]
Hi, I think to have discovered a issue into a Flux grid component. When I created a new page into a workspace, if I want to see the preview page with workspace link generated the grid component doesn't render a content associated.

I identify the bug into ../typo3conf/ext/flux/Classes/ViewHelpers/Content**/GetViewHelper.php** file at 177 row.

I removed these function and it worked fine 
"BackendUtility::versioningPlaceholderClause('tt_content')"

**Comment by NamelessCoder** [comment]
Please make sure you use the `development` branch here from GitHub - it has several fixes for exactly this problem and should work correctly.

**Comment by marcodefelice** [comment]
Yes sure, but I've not find any TASK or BUGFIX for these issue.
Can I push these fix into branch development ?

**Comment by NamelessCoder** [comment]
Here is the current development branch source of the file in question:

https://github.com/FluidTYPO3/flux/blob/development/Classes/ViewHelpers/Content/GetViewHelper.php

And here's that same file on master branch (current TER release): 

https://github.com/FluidTYPO3/flux/blob/master/Classes/ViewHelpers/Content/GetViewHelper.php

Neither of those have that function call in line 177. The one from the latest TER release has it in line 167 - but it's still there and would cause the same problem. So even if these line numbers indicate to me that you're currently not using the most recent TER release, even upgrading that would not solve this problem.

So please make sure that you test this with the `development` branch. It does not contain this function call, I've double-checked. You won't need to push any fixes - you will just need to fork the clone the Flux repository from GitHub, by default you will then be on the `development` branch.

**Comment by marcodefelice** [comment]
ok thanks a lot ! now I'll check the branch and the file
thank you soo much
