### ISSUE TITLE
[BUG] flux not parse a javascript code into template

### ISSUE THREAD

**Issue by marcodefelice** [FluidTYPO3/flux#1506]
Hi, if I've a HTML and a JavaScript code into a flux template, flux not parse a JavaScript
for example

```
<f:main>
<h1>Title</h1>
<p> sub title </p>
</p>
<script>
... same script here
</script>
</f:main>
```

**fluid print:**

Title
sub title
<script>
... same script here
</script>

**Comment by NamelessCoder** [comment]
This almost certainly is not related to Flux - if anything, it's a question for Fluid, but the ViewHelper you used there (`f:main`) does not exist in Fluid. Most likely you have another ViewHelper around that template code and this ViewHelper escapes your HTML but allows headers and paragraphs (`f:format.html` would do this with the right configuration).

In any case, you'll have to take this question to the TYPO3 support channels and include the actual template code that causes the problem. There's nothing we can do to help you from here, sorry.
