### ISSUE TITLE
Use Flux instead of fluidcontent: Label for newContentElement wizard missing

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#1507]
When i use flux for my CEs, instead of fluidcontent

`\FluidTYPO3\Flux\Core::registerProviderExtensionKey('my_provider', 'Page');`

and create as usaal a content element with the code:

`<flux:form options="{group: 'Flexible Content Elemente'}" id="containerFormOverlay">`

i do not get the label "Flexible Content Elemente" in the newContentElement wizard.
The label is missing.

What can i do?
![unbenannt-3](https://user-images.githubusercontent.com/5647051/35350937-b8486240-013f-11e8-9024-38f2c31e21dc.jpg)

**Comment by TheNaderio** [comment]
Maybe try this:
```
<flux:form id="containerFormOverlay">
    <flux:form.option name="group" value="Flexible Content Elemente"/>
```
This works fine for me.

**Comment by blueamerican** [comment]
thank you.

A problem was the string itself.

This works now:
 <flux:form.option.group value="Flexible-Inhalts-Elemente" />

**Comment by dahaupt** [comment]
@blueamerican I think this is a serious issue. It looks like something with the parsing of the group name is not working correctly. I will look into this if I find time in the next days.

**Comment by tpinne** [comment]
This is still an issue with `^9.2`

`<flux:form.option.group value="mein Menü" />` converts to ` ` (empty string)
`<flux:form.option.group value="mein Menue" />` converts to ` ` (empty string)
`<flux:form.option.group value="mein-Menü" />` converts to `mein-Men`
`<flux:form.option.group value="mein-Menue" />` converts to `mein-Menue`
