### ISSUE TITLE
flux.field.inline.fal - images could not be rendered in preview section

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/flux#1508]
Fal-images are not visible in the Preview Section.
In the Frontend there is a filled array when I do `<f:debug>{v:content.resources.fal(field: 'images')}</f:debug>` - but in Backend the same array is empty.
when debugging {images} directly it says `3` (the number of images)

The rendering in the Frontend works without problems.

Here's the Code:
```
<f:section name="Configuration">
        <flux:form id="mainslider" label="" description="">
            <flux:form.option name="group" value="FCE"/>
            <flux:form.option name="Fluidcontent" value="{sorting: 1}"/>
            <flux:form.option name="icon" value="EXT:naderioprovider/Resources/Public/Icons/Content/Example.svg"/>

            <flux:field.input name="headline" />
            <flux:field.inline.fal name="images" minItems="2" maxItems="5"/>
        </flux:form>
    </f:section>

    <f:section name="Preview">
        
        <p>Slider-Element{f:if(condition: headline, then:': {headline}')}</p>
        
        <f:for each="{v:content.resources.fal(field: 'images')}" as="image" iteration="iterator">
            <f:image treatIdAsReference="1" src="{image.id}" title="{image.title}" alt="{image.alternative}" class="img-responsive"/>
        </f:for>
        
    </f:section>
``` 

Any ideas for that?

Thank you :)

**Comment by Chris-dev** [comment]
For me it works when I add `uid: '{record.uid}')` to the tag for the backend preview section:

`v:content.resources.fal(field: 'images', uid: '{record.uid}')`

**Comment by TheNaderio** [comment]
Bull's-eye! Added it and the pictures were displayed immediately!
Thank you very much @Chris-dev 

Here's the working code:
```
<f:for each="{v:content.resources.fal(field: 'images', uid: '{record.uid}')}" as="image" iteration="iterator">
    <f:image treatIdAsReference="1" src="{image.id}" title="{image.title}" alt="{image.alternative}" class="img-responsive"/>
</f:for>
```

**Comment by beam2web** [comment]
Since over two years its the only way to do this like in your code:
https://forge.typo3.org/issues/71239

Example:
http://p.cweiske.de/246

**Comment by NamelessCoder** [comment]
Closing this issue - if you want images to be rendered in the Preview section you must manually create the preview, and for example use the suggestion from @Chris-dev above, to load the FAL records and use either the path from the objects it returns, or pass them to `f:image`.

There is no magic preview generation for Flux and it will not copy preview methods from, for example, the `Textmedia` content type. In Flux, all previews are manually created.

**Comment by neufeind** [comment]
Would be nice to maybe mention that in the docs or so.
https://viewhelpers.fluidtypo3.org/fluidtypo3/flux/8.0.2/Field/Inline/Fal.html
