### ISSUE TITLE
Broken workflow if you are using translation

### ISSUE THREAD

**Issue by golserma** [FluidTYPO3/flux#1509]
If you add new content to the original language and the new content to the translated pages the parent child link gets lost and you can not drag the content to the parent to fix this.

Video: https://drive.google.com/file/d/1HYwfzpUWputRQpd6HugRiMfDcax1899v/view?usp=drivesdk
typo3 7.6.23
flux 8.2.1
fluid 7.6.23

**Comment by golserma** [comment]
@TheNaderio I was following your tutorial on youtube maybe you have a solution for this issue?

**Comment by dahaupt** [comment]
@golserma I've watched your video and I experienced similar behavior in the past. I always did some workarounds to achieve my results. 

A temporary workaround for you could be to select the column manually in the settings of your text element. But this has to get fixed seriously soon as it's really annoying and customers won't understand that behavior.

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.
