### ISSUE TITLE
object's unique id is only set on first CE save

### ISSUE THREAD

**Issue by hm-tim** [FluidTYPO3/flux#1511]
The unique id thats assigned to section > object elements is only created/saved on the elements first creation. If you later edit that element and add new objects into the section, they do not get the id-attribute.

Simple Fluid Template for testing:

```
{namespace flux=FluidTYPO3\Flux\ViewHelpers}
<f:layout name="Content" />

<f:section name="Configuration">
	<flux:form id="sectionobjects" label="SectionObject-Test" description="Test Case for Section Object Ids">
		<flux:form.sheet name="panels">
			<flux:form.section name="section">
				<flux:form.object name="panel">
					<flux:field.input name="title" label="Panel-Title"/>
				</flux:form.object>
			</flux:form.section>
		</flux:form.sheet>
	</flux:form>
</f:section>

<f:section name="Preview">
	<f:debug>{section}</f:debug>
</f:section>

<f:section name="Main">
</f:section>
```

Creating a new element adding an object and saving shows an id in the debug output:
![image](https://user-images.githubusercontent.com/8760110/35681616-345a3f2e-075e-11e8-9ab0-23260816b037.png)

Editing that element, adding another object and saving shows the following output:
![image](https://user-images.githubusercontent.com/8760110/35681660-66717c34-075e-11e8-8e34-06270925102d.png)

TYPO3 8.7.9
flux - 8.2.1 (development)

**Comment by monosize** [comment]
take a look at #1372

**Comment by hm-tim** [comment]
Thank you. The solution given in that issue helps fixing the problem in my use-case.  But I still don't think this is intended behaviour. Creating the id-attributes only on newly created elements and omitting them on edits looks like an oversight.

**Comment by NamelessCoder** [comment]
Duplicates https://github.com/FluidTYPO3/flux/issues/1372 - please follow the status there.
