### ISSUE TITLE
No internal_type "folder" available?

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#1512]
I need a flux field for selecting a folder inside the user_upload folder.
It works with the normal flexform configuration:
```
<config>
  <type>group</type>
  <internal_type>folder</internal_type>
  <minitems>1</minitems>
  <maxitems>1</maxitems>
  <size>1</size>
</config>
```

but can I achive this same thing with a flux field without creating a custom one?
And if yes how would I do this? 

Thanks in advance!

**Comment by NamelessCoder** [comment]
Hi @MarvinRudolph,

You almost surely figured out a way to implement it, but for posterity:

`flux:field.file` can accept an `internalType="folder"` - whether or not that is actually supported, may depend on the version of TYPO3. You *should* be able to configure the basics like `maxItems` (note capital `i` in Flux name!) but it may not support every option you need.

See https://github.com/FluidTYPO3/flux/blob/development/Classes/ViewHelpers/Field/FileViewHelper.php#L28 for which attributes you can use.
