### ISSUE TITLE
Passing Arguments in flux:content.render

### ISSUE THREAD

**Issue by beam2web** [FluidTYPO3/flux#1517]
I use fluidcontent elements and want to nesting them. Is it possible to hand over arguments to the child fluidcontent elements? I might consider some conditions in child how to render the structure or check, which is the parent for different outputs.

I need a way like that:
`<flux:content.render area="myArea" arguments="{_all} /> or <flux:content.render area="myArea" arguments="{variable: value}" />`

**Comment by NamelessCoder** [comment]
Each content element you render has its own context in terms of variables. Normally you are not allowed to transfer variables between these contexts but there is one way of doing it - the load register, which can contain "global" variables that are always there in nested renderings. However, the ViewHelpers you use for that, are in VHS: https://fluidtypo3.org/viewhelpers/vhs/master/Variable/Register/GetViewHelper.html

The situation is the same regardless how you render the content elements; TS, VHS and Flux all have the same constraints - the register is the only universal method. And it can also be used from TS to apply things like wrapping.

**Comment by beam2web** [comment]
Thanks for the tip. It helped me find a solution because the register was not helpful in my case.
```

<f:comment>Code for the child to check parent</f:comment>
{v:content.info(field:"tx_flux_parent")->v:variable.set(name: "parentId")}

<f:if condition="{parentId}">
    {v:content.info(contentUid: parentId, field: "tx_fed_fcefile")->v:variable.set(name: "parentFCE")}
    
    <f:if condition="{parentFCE} == 'extensionname:parentElement.html'">
        Make special things in the child template
    </f:if>
</f:if>
```
