### ISSUE TITLE
[question] TYPO3 9.x compatibility?

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/flux#1527]
Will there be full compatibility to 9.x?
I can't find any information about it anywhere :)

**Comment by NamelessCoder** [comment]
I can promise you there will be v9 compatibility. There basically already is, with some exceptions judging from recently opened issues. What I can't promise you is *when* that might happen. You'll have to take things as they come and if the need is great enough, give the `dev-development` branch a try and report what you find if you find any problems - or better still, try to solve them and make a pull request ;)

_Patience, young Skywalker!_ 🐢
