### ISSUE TITLE
Own Image Dimensions for flux:form.option.icon

### ISSUE THREAD

**Issue by beam2web** [FluidTYPO3/flux#1528]
Is it possible to add width and height for the preview image in the backend to overwrite the "normal output" for:
https://github.com/FluidTYPO3/flux/blob/master/Classes/ViewHelpers/Form/Option/IconViewHelper.php

The most own created content elements are not good describable with an 32px SVG icon. I would like integrate preview images for the editor.

Best Regards

**Comment by NamelessCoder** [comment]
I'm afraid that's not possible to do out of the box. TYPO3 itself does support overrides you might be able to use for this, but I doubt you would be able to completely implement such a change (for example, content type icons appear in a `<select>`, in list views, in the new content wizard, and are often also rendered by third party extensions). Flux just passes a reference to an icon file in any arbitrary resolution, TYPO3 then scales that to fit the various places the icon must be used.

It's not really the domain of Flux or other FluidTYPO3 extensions, though. This icon size consistency is being enforced by TYPO3 - the best option you have to describe a content element is to use the `label` and `description` it supports (where `description` can contain much more text).

**Comment by beam2web** [comment]
To remove the width and height i use now:
`{icon -> v:format.pregReplace(pattern: '/(width|height)="\d*"/', replacement: '') -> f:format.raw()}`

instead of

`{icon -> f:format.raw()}`

**Comment by cedricziel** [comment]
:scream:
