### ISSUE TITLE
#1407 wow

### ISSUE THREAD

**Issue by jsdmind** [FluidTYPO3/flux#1529]
Wow. This feature - #1407 - today turned my project into a fruit cake right after going public. Funny thing, the fix didn't make it into composer on both the flux or core way. Please close.

**Comment by NamelessCoder** [comment]
I'm afraid I don't really understand what you're trying to say? #1407 is already closed - and as far as I am aware, the original issue still exists in TYPO3 on all branches. Solving it is *VERY* far from easy, several attempts have been made already.

So I'm not sure what you would like us to do with this issue? Pretty sure you didn't open this issue just to tell us to close it again, but it kind of reads that way ;)

**Comment by NamelessCoder** [comment]
Closed due to lack of response. I highly recommend upgrading to Flux 9.0 when this gets released (run the migration script in EM after you do). That release will fix the parent/child relationship issues that have been popping up and which #1407 was addressing.
