### ISSUE TITLE
Support TYPO3 8 language synchronization feature (allowLanguageSynchronization)?

### ISSUE THREAD

**Issue by spackmat** [FluidTYPO3/flux#1531]
Hi,

I would love to use the new language synchronization feature on flux fields to replace the old translation setting in flux [wich was removed in TYPO3 7.7](https://fluidtypo3.org/blog/news/flux-option-translation-and-typo3-76-lts.html). There are always content fields like images, which don't need to be translated (and now must filled in the translation), but the text beneath it does.

What is the state of this? Are there plans to support this? Is it already supported and I didn't see it? Am I misinterpreting [the allowLanguageSynchronization setting](https://docs.typo3.org/typo3cms/TCAReference/8-dev/ColumnsConfig/Type/Flex.html#behaviour)?

Greets,
spackmat

**Comment by NamelessCoder** [comment]
I'm afraid we can't fulfil requests to handle translation *inside* flexforms - but you can set the TCA setting `behavior` in your TCA (by overriding it in the `tt_content` TCA for `pi_flexform`, or by setting it for whichever field you're using Flux with).
