### ISSUE TITLE
flux:field.text + RTE = no custom classes

### ISSUE THREAD

**Issue by Geddo** [FluidTYPO3/flux#1541]
TYPO3 8.7.11 + current Flux master:
When creating an RTE Text field like this, the RTE comes up, but my custom css-styles is missing (e.g, button-styles etc.):
`<flux:field.text name="links" label="links" enableRichText="true"></flux:field.text>`
Any chance to get it back working?

**Comment by Geddo** [comment]
Just updated to the dev-branch, now I'm getting no output - seems like my provider extension doesnt work anymore. Do you have an overview what changed, or an example where I can orientate at?

**Comment by NamelessCoder** [comment]
Check the log, there could be some errors - also, check if the same happens if you create a new content element of your type.

**Comment by Geddo** [comment]
Just found out that "richtextConfiguration" is now an option - a "minimal" configuration works, maybe that the way to inject my custom css. Too bad that flux doesnt take my custom yaml file set via typoscript (which works in all other RTEs).

**Comment by breakone** [comment]
@Geddo How have you set your yaml-file? For me it works, when I override the default Preset with:
`$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'fileadmin/.../Default.yaml';`

and also use the default Present in Page TS config
`RTE.default.preset = default`

**Comment by Geddo** [comment]
thanks for the hint. I rearranged the content for that site so I didnt try it but I will in the future :)
