### ISSUE TITLE
flux:form.container example does not work as expected

### ISSUE THREAD

**Issue by ghost** [FluidTYPO3/flux#1543]
Hello,

When I try to implement an flux:form.container the way it is described in the example
```
<flux:form.container name="settings.container.name" label="Name">                        
<flux:field.input name="firstname" label="First name"/>                                    
</flux:form.container>
```

It creates an section with the Label name, below an button with an arrow and the (german) Label Alle umschalte.
Below that an Button with an plus sign and no label. Clicking on the plus sign does not result in the firstanem field beeing added. [Image](http://abload.de/image.php?img=flux-containersdsa4.jpg)

Once I wrap the flux:file.input in an flux:form.object tag the container behaves like an flux:form.section.

I'd expect to get an Section with an input field with the label "First name" and the arrow "Alle umschalten" button, when i use the flux:form.container element.

Typo3 8.7.10
Flux 8.2.1
VHS 4.4.0

**Comment by NamelessCoder** [comment]
Closing as "can't solve" - TYPO3 is undergoing a longer process of cleaning up and restricting what is actually possible to do inside a FlexForm, and the "container-without-section-object" one is among those removed. You can still put section objects inside containers but object-less fields (previously resulting in a plain array) are no longer possible.
