### ISSUE TITLE
[BUG ?][TYPO3-7.6] flux:field.select renderType option causes a PHP Warning

### ISSUE THREAD

**Issue by mcmietz** [FluidTYPO3/flux#1550]
Hello, 

I use the flux:field.select in my Content Element Configuration. For the items argument an array with the select option values and title is set. 
```
<flux:field.select name="name"
                           multiple="true"
                           minItems="0"
                           maxItems="1000"
                           items="{value1: 'title1', value2: 'title2'}"
                           renderType="selectCheckBox"
                           size="6"/>
```
If I use the renderType "selectCheckBox", then I get a TYPO3 Exteption in the backend.

`#1: PHP Warning: array_flip() expects parameter 1 to be array, null given in /typo3/typo3_src-7.6.23/typo3/sysext/backend/Classes/Form/Element/SelectCheckBoxElement.php line 46`

The line 46
```
// Get values in an array (and make unique, which is fine because there can be no duplicates anyway):
$itemArray = array_flip($parameterArray['itemFormElValue']); 
```
in the render function causes the error. But it seems to be, that the function is called twice. By first call the $parameterArray['itemFormElValue'] is filled with my values, but at second time the array is empty. 

If I change the renderType Option to "selectMultipleSideBySide" than I see a side by side window with my values.

Extension | Version
-- | --
flux | 7.4.0
TYPO3 | 7.6.23

**Comment by NamelessCoder** [comment]
Sorry to say this, but we can't help you with this one. The problem happens in a TYPO3 core class.

If this still happens please create a bug report on https://forge.typo3.org/projects/typo3cms-core.
