### ISSUE TITLE
Template order is not reversed

### ISSUE THREAD

**Issue by billdagou** [FluidTYPO3/flux#1555]
When I use
```
plugin.tx_template {
    view {
        layoutRootPaths.0= EXT:template/Resources/Private/Layouts/
        templateRootPaths.0= EXT:template/Resources/Private/Templates/
        templateRootPaths.99= EXT:new_template/Resources/Private/Templates/
        partialRootPaths.0= EXT:template/Resources/Private/Partials/
    }
}
```
for my template extension, the ```templateRootPaths.99``` doen't work at all.

After some debug, I think the reason is in ```\FluidTYPO3\Flux\View\TemplatePaths::resolveTemplateFileForControllerAndActionAndFormat()``` in ```flux```. The ```$this->getTemplateRootPaths()``` should be iterated in opposite order.

My quick fix is as below.

```
public function resolveTemplateFileForControllerAndActionAndFormat($controller, $action, $format = self::DEFAULT_FORMAT) {
    $action = ucfirst($action);
    $templateRootPaths = $this->getTemplateRootPaths();
    while (null !== ($templateRootPath = array_pop($templateRootPaths))) {
        $candidate = $templateRootPath . $controller . '/' . $action . '.' . $format;
        $candidate = $this->ensureAbsolutePath($candidate);
        if (true === file_exists($candidate)) {
            return $candidate;                     
        }
    }
    return null;
}
```

**Comment by HenningCash** [comment]
Which version of flux and TYPO3 are you using?  
This might be related to #1371 and https://forge.typo3.org/issues/81340

I just had the same issue. If you are using the latest TYPO3 8.7 (> 8.7.2) and the `development` branch of flux everything should work fine.

**Comment by billdagou** [comment]
I'm using TYPO3 v8.7.15 and Flux v8.2.1 from TER.

Yes, I think it will be an easy fix in the future version :)

**Comment by NamelessCoder** [comment]
This is already fixed in development, which delegates resolving of template files to the now Fluid native resolving class.
