### ISSUE TITLE
Check for unnecessary calls

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/flux#1556]
Please check for unnecessary calls which slow down the rendering.

For example we have profiled a litte project and found out that `Flux\Helper\ContentTypeBuilder->registerContentType()` is called 585 times directly by 
`Flux\Backend\TableConfigurationPostProcessor->spoolQueuedContentTypeRegistrations()` (which is called 39 times).

The corresponding line is:
`$contentTypeBuilder->registerContentType($controllerExtensionName, $contentType, $provider, $pluginName);`

Stack:
```
#1 Flux\Helper\ContentTypeBuilder->registerContentType() x585
#2 Flux\Backend\TableConfigurationPostProcessor->spoolQueuedContentTypeRegistrations() x39
#3 Flux\Backend\TableConfigurationPostProcessor->processData() x39
#4 call_user_func_array() x39
```

That calls include 50% of total render time.

**Comment by NamelessCoder** [comment]
Calls reduced with https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. The solved problem was that inclusion got called for every TS template inclusion. The solution targets the special content rendering templates to load TS at exactly the right time and only once.
