### ISSUE TITLE
CKeditor keeps adding empty paragraphs in FlexForms

### ISSUE THREAD

**Issue by adick** [FluidTYPO3/flux#1557]
When using a text field with RTE enabled, (``<flux:field.text name="text" label="Text" required="true" enableRichText="1" />``), the editor keeps adding empty paragraphs after saving. 

Basically this isn't a flux problem directly, but as described here, the fix is easy: https://forge.typo3.org/issues/80778

To implement this in flux, ``enableRichtext`` needs to be set to 1 in the ``buildConfiguration`` method in ``flux/Classes/Form/Field/Text.php``

 ````
if(true === $this->getEnableRichText()) {
	$configuration['enableRichtext'] = 1;
}

$renderType = $this->getRenderType();
````

flux 8.2.1
typo3 8.7

**Comment by NamelessCoder** [comment]
Hi @adick - this bug is solved in `dev-development` and will be part of the 9.0 release that's coming soon.
