### ISSUE TITLE
Error when getting application context

### ISSUE THREAD

**Issue by kraftb** [FluidTYPO3/flux#1561]
With 9.2 the application context is retrieved in a different way. I have created a patch which fixes this issue for 9.2 and will submit it via a pull request.

**Comment by kraftb** [comment]
The patch does not tackle the proplem of inter-version compatibility. By applying this patch the code will only work in 9.2. I guess the solution will be to create an if-condition accessing the TYPO3 version number and eventually putting the "getContext" lines in a wrapper method.

**Comment by NamelessCoder** [comment]
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0.
