### ISSUE TITLE
[FEATURE] Allow nested or parallel folder for ProviderExtension Content/Page

### ISSUE THREAD

**Issue by iamandrewluca** [FluidTYPO3/flux#1569]
As a developer would be great to group somehow `Content` and `Page` Templates.  
As I know there is `flux:form.option.group` for `Content`, that will group them into `sheets` in backend, don't know if this exists for `Page`

It seems to be 2 ways for grouping Templates

<details>
<summary>Parallel folders</summary>
<br/>

Add `AnotherContentController` that extends `FluidTYPO3\Flux\Controller\ContentController`
```bash
Controllers/
    PageController.php
    ContentController.php
    AnotherContentController.php # new controller
```

Creat new folder for `AnotherContent` templates
```bash
Templates/
    Page/
        PageTemplate.html
        ...
    Content/
        SomeContentTemplate.html
        ...
    AnotherContent/ # new folder for templates
        AnotherContentTemplate.html
        ...
```

Register controller in `ext_localconf.php`, but we must distinguish somehow from `Page` and `Content`  
```php
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.ExtensionKey', 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.ExtensionKey', 'Content');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.ExtensionKey', 'AnotherContent');
```

see: https://github.com/FluidTYPO3/fluidcontent/issues/323#issuecomment-400616741
</details>

<details>
<summary>Nested folders suggested by @NamelessCoder</summary>
<br />

Having `ContentController` that extends `FluidTYPO3\Flux\Controller\ContentController`  
Add `AnotherContentController` that extends `ContentController`
```bash
Controllers/
    PageController.php
    ContentController.php # extends FluidTYPO3\Flux\Controller\ContentController
    AnotherContentController.php # extends above ContentController
```

Creat new folder for `AnotherContent` templates
```bash
Templates/
    Page/
        SomePageTemplate.html
        ...
        AnotherPage/ # same will go for pages if we have extended controllers
            AnotherPageTemplate.html
            ...
    Content/
        SomeContentTemplate.html
        ...
        AnotherContent/ # new folder for templates inside Content
            AnotherContentTemplate.html
            ...
```

Register controller in `ext_localconf.php`, but we must distinguish somehow from `Page` and `Content` and detect if controller is nested
```php
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.ExtensionKey', 'Page');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.ExtensionKey', 'Content');
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.ExtensionKey', 'AnotherContent');
```

see: https://github.com/FluidTYPO3/fluidcontent/issues/323#issuecomment-400688491
</details>

**Comment by NamelessCoder** [comment]
Achieved for content templates in the form of sub-folders (option 2 above) through https://github.com/FluidTYPO3/flux/commit/9d31f938e4403bdea040d7eafd45f465a02d82d7 but with a single limitation imposed by TYPO3 - custom controller actions will not work with templates placed in sub-folders.

**Comment by NamelessCoder** [comment]
Achieved for page templates in same way as described above, with same limitation, through https://github.com/FluidTYPO3/flux/commit/0483090ce312e43c136de8f92543882383e2d97d.
