### ISSUE TITLE
flux:field.multiRelation does not display element-chooser

### ISSUE THREAD

**Issue by neufeind** [FluidTYPO3/flux#1570]
When using flux:field.multiRelation the list of selected elements is not displayed anymore and there is no link to open a browser for selecting new elements.
This is due to commit 0bd5466f85b0ad9962803a396d7a9ac624c65cc4 which switched from an unset renderType to renderType=selectSingle.

Workaround: Reverting the above mentioned commit or in Classes/Form/Field/MultiRelation.php adding a line:
unset($configuration['renderType']);

**Comment by neufeind** [comment]
I haven't yet figured out what renderType-default it seems to be using internally:
https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Group.html#
Since having an unset renderType seems to be deprecated I wonder what we need to set it to. Or is that just for "select" and not for field-type "group"?

**Comment by NamelessCoder** [comment]
Solved by nulling `renderType` on the component, which then causes it to be skipped when the TCEforms array is built.
