### ISSUE TITLE
Creating page translations fails

### ISSUE THREAD

**Issue by luzat** [FluidTYPO3/flux#1571]
When trying to create a translation of a page, TYPO3 8.7 with the 9.0.0 release throws this exception:

    Argument 1 passed to TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::eq() must be of the type string, null given, called in /var/www/html/web/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php on line 342 
    TypeError thrown in file /var/www/html/vendor/typo3/cms/typo3/sysext/core/Classes/Database/Query/Expression/ExpressionBuilder.php in line 108.

`$languageField` is not set correctly because `pages` uses overlays. I am not sure what the handler does exactly, but it probably could just skip pages and possibly should check for `languageField` being set? I patched (5caba0343650a095ad10d763abbfd234d4863d13)  `cascadeCommandToChildRecords` to return early for `pages` which at least fixes that case for me.

**Comment by luzat** [comment]
Related: When deleting a translation of the page, the following exception is thrown:

    An exception occurred while executing 'SELECT `uid`, `pid` FROM `pages_language_overlay` WHERE (`colPos` IN (8040, 8000)) AND (`sys_language_uid` = 1) ORDER BY `sorting` DESC': Unknown column 'colPos' in 'where clause' 

This happens because

    FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber::getParentAndRecordsNestedInGrid("pages_language_overlay", 80, "uid, pid")

is called. I do now skip `pages_language_overlay` and `pages` in `cascadeCommandToChildRecords` to avoid both problems (but not sure if this is correct).

**Comment by NamelessCoder** [comment]
Thanks for the input @luzat. It looks like I forgot to add a check in the first-level loop here:

https://github.com/FluidTYPO3/flux/blob/development/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php#L118

```php
if ($table !== 'tt_content') {
    continue;
}
```

In theory, any table could use a grid and have nested records - but we need to remedy it for now by restricting to `tt_content`. In the future a solution is needed which knows when to include `colPos` and how to work around not having it available but there are currently zero implementations not based on `tt_content`.

A pull request would be appreciated! ;)
