### ISSUE TITLE
[BUG] Flux could not extract a Flux definition

### ISSUE THREAD

**Issue by grimmcreative** [FluidTYPO3/flux#1572]
Tried to Update to FLUX 9.
After Update Fluidpages and Flux to latest TER Version Errors comes like:

```
Oops, an error occurred!
Flux could not extract a Flux definition from "*/Resources/Private/Templates/Content/Accordion.html". Check that the file exists and contains the necessary flux:form in the configured section "Configuration"
```

But file exist and there is a necessary flux:form in the configured section Configuration.

**Comment by NamelessCoder** [comment]
Hi @grimmcreative - did you check the EM upgrade script? It will attempt to detect any templates that need to be migrated.

For the record, the `colPos` argument is now required on `flux:grid.column` where before it was optional. That could be why the template can't be parsed - and it's the only thing you need to change in templates to be compatible.

**Comment by grimmcreative** [comment]
Hi Claus, yes i checked it but as i see i understood it a bit wrong :)
Now i changed all colPos Numbers because i always started from 100 "haha"
After that i changed all of them in Database too.

Now it seems that everything is working nice and more then that, it feels now blazing fast Backend and Frontend is much much much faster now - WOW. Good Job! I like it a lot.

**Comment by NamelessCoder** [comment]
Great when the solutions are easy :) and you made my day for noticing the performance improvements that I didn't mention a word about in change logs etc. - sooo much better without those overrides! ^^
