### ISSUE TITLE
Warning about too great colPos values

### ISSUE THREAD

**Issue by NamelessCoder** [FluidTYPO3/flux#1573]
Building from https://github.com/FluidTYPO3/flux/issues/1572 it would be nice to throw a warning or even an error if a developer chooses a colPos value that is greater-than-or-equal-to the MULTIPLIER constant's value.

Such configurations currently fail silently and may put elements under the wrong parent.

**Comment by albirs** [comment]
I don't know if this is part of this: 
I have a page layout with colPos 0,1,2 but in the backend it always shows in area 1 and 2 [ invalid value ("1") ] or [ invalid value ("2") ] on "Column" dropdown on the Content element. 
Only in area with colPos="0" Main its correct.
`
<f:layout name="Page" />

<f:section name="Configuration">
<flux:form id="homepage">
</flux:form>
<flux:grid>
<flux:grid.row>
<flux:grid.column colPos="1" name="Slider" label="Slider" />
</flux:grid.row>
<flux:grid.row>
<flux:grid.column colPos="0" name="Main" label="Main" />
</flux:grid.row>
<flux:grid.row>
<flux:grid.column colPos="2" name="Banner" label="Banner" />
</flux:grid.row>
</flux:grid>
</f:section>
`
Updated on latest version (from 10 July) on Typo3 8.7.16

**Comment by NamelessCoder** [comment]
@albirs I'm not sure it's related - here is what should be expected when you edit a content element and try to use the `colPos` selector box:

* If the element is already within a Flux parent, you will see those areas grouped together in an `<optgroup>` and should be able to move an element from one column to another by changing this. You will also see the page-level columns so you can move an element out of a parent element.
* If the element is not within a Flux parent, you only see the page level columns.

I assume that what you have there is a Page template? In that case, the columns you defined there should show up as page content columns, if:

* You selected the special `backend_layout` - I forgot to note in release notes that it's different now and must be changed!
* You select the proper page template under the "Page Layout" tab.

Hope this helps. It may be that you just need to change the `backend_layout` on the root page.

**Comment by albirs** [comment]
Thanke @NamelessCoder ! its exact how you described. This is the page layout on the Homepage where i need more columns colPos to render and it is select the "Page Layout" tab:
Page Layout - this page  -> "Homepage"
Page Layout - subpages -> "Standard"

but still is showing the [ invalid value ("2") ]  ... or [ invalid value ("1") ]  ... the good thing is that at any rate in the Frontend works normal... 
there is only a "weird feeling" about this "invalid value..." (future updates and so on...)

**Comment by NamelessCoder** [comment]
This really sounds like perhaps you need to select the `backend_layout` (note that this is in Appearance, not in Page Layout). Hope you find it. You might face "no access" problems otherwise...

**Comment by albirs** [comment]
Ok after some tests i think that's a problem in pages that are set as "Use as Root Page". I'm using this page as my first page and "Homepage" too. If i make a copy of this page as first page in the page tree under the root page, its working.

so not working is this:
Root Page --> as Homepage 
..........| .......... Page Layout - this page -> "Homepage", Page Layout - subpages -> "Standard"
..........|
..........| --.--> first Subpage

working:
Root Page 
..........|
..........| -- --> Homepage
..........| ........... Page Layout - this page -> "Homepage", Page Layout - subpages -> "Standard"
..........|
..........| --.--> first Subpage

**Comment by NamelessCoder** [comment]
Closing as "won't fix" regarding the original issue description. Column position values above 99 are technically allowed, but only in page templates, and the `flux:grid.column` ViewHelper cannot determine if the template in which it is used, is a page template. ViewHelper's documentation states the expected value range and this has to suffice.

The other issues described are not related to incorrect colPos values.

Issue with "use as root page" may be possible to solve with "siteRootInheritance" setting, see https://github.com/FluidTYPO3/flux/search?q=siteRootInheritance&unscoped_q=siteRootInheritance.

Another possible cause may be inability to resolve TypoScript for additional root level pages, which is explained on https://github.com/FluidTYPO3/flux/issues/1671.

Closing the issue.
