### ISSUE TITLE
Copying page loses child records in "flux:grid.column"

### ISSUE THREAD

**Issue by fiedomedia** [FluidTYPO3/flux#1580]
I use a content template for building grids with custom columns:
```
<flux:grid>
    <flux:grid.row>
        <flux:grid.column name="column1" label="{settings.width.col1}/12 Columns" colPos="10">
        </flux:grid.column>
    </flux:grid.row>
</flux:grid>
```

Now when a page in the pageTree is copied and pasted, all content elements are present, except for child records within flux:grid.column of my grids.
Can anybody confirm this?

I used the latest dev-development version of flux.

**Comment by NamelessCoder** [comment]
@fiedomedia Can you inspect the database directly after copying your values? I'd like to know if:

1. The child records get copied but get the wrong `colPos` or `pid` values (colPos is supposed to be `($parentUid * 100) + $colPosYouDefined`).
2. Something else unexpected happened to the copied child records - e.g. they got deleted or pid was set to a negative value.
3. The child records don't get copied at all.

This would help me track down what's going wrong. I think we may be looking at the first thing (copied, but wrong pid somehow).

It would also help to know if you are pasting 1) after another page, 2) into another page, 3) to somewhere outside the normal site root.

**Comment by fiedomedia** [comment]
Hi @NamelessCoder

Indeed, the records are in the database, but with pid=0 and colPos=10.
The grid element has id=42, so the colPos of children should be 4210.
deleted=0 looks good.
sorting=16 looks bad, original has 512 and 768.

I've tested pasting after page, pasting into page, pasting into another root page, always the same results.

**Comment by NamelessCoder** [comment]
Thanks @fiedomedia - if you decide to debug further, I think the problem might be that the method which post-processes the copy operation (post-database-operation) in DataHandlerSubscriber somehow resolves the wrong value for pid and new parent UID, which then causes the calculated colPos to be `0 + $localColPos` and of course `pid = 0`. If you don't get a "failed to insert record on pid = 0" flash message after copying that would help support the suspicion that it happens in that particular method.

**Comment by NamelessCoder** [comment]
Fixed, I hope, by https://github.com/FluidTYPO3/flux/commit/2169525b40044f4f41106975db2358c300c22780 - if you are on the development branch I would appreciate if you could pull and confirm it also solves your use case ;)

**Comment by fiedomedia** [comment]
Hi @NamelessCoder, great job, my use case is solved.

**Comment by mithri** [comment]
The patch doesn`t work for us. Neither when copying pages or copying/moving container elements with translated child elements. The nested translated elements have the wrong pid.

**Comment by NamelessCoder** [comment]
@mithri can you open a new issue please and describe your specific case - is this children-of-children or direct children? How do you paste them - top of column, after other element, into other language? Is the page column you copy from/to in free or connected mode?

This seems to be working for most users so I suspect there is something special or just infrequently used configuration in your use case. More info will help :)
