### ISSUE TITLE
No input fields in backend for flux content element

### ISSUE THREAD

**Issue by ubrt** [FluidTYPO3/flux#1584]
Hello,

I'm currently building my first provider extension for flux and I'm stuck while creating my first content element. It is recognized and loaded so I can choose it in the new content element wizard but all the configuration fields are missing, it's just empty. I also tried the [content element example](https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/content-element.html) from the documentation with the same result.

![image](https://user-images.githubusercontent.com/12350410/42748914-1dd8d886-88e2-11e8-829c-f9785c6707c3.png)

Typo3 Version is 8.7.17
Relevant Extensions: 
- flux: 9.0.0
- fluidpages: 4.2.0
- fluid: 8.7.17
- fluid_styled_content: 8.7.17
- vhs: 5.01

This is my, currently simplified, configuration:
  ```xml
<f:section name="Configuration">
        <flux:form.option.group value="boostrap" />
        <flux:form id="alert" options="{group: 'bootstrap'}">
            <flux:field.input name="header" />
        </flux:form>
    </f:section>
```
Layouts/Content.html
```xml
<f:layout name="Content" />
<f:render section="Main" />
```

ext_Tables

```php
call_user_func(
    function() use($_EXTKEY)
    {

        \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile('fluxtemplate', 'Configuration/TypoScript', 'Flux Templating');

        \FluidTYPO3\Flux\Core::registerProviderExtensionKey($_EXTKEY, 'Content');
        \FluidTYPO3\Flux\Core::registerProviderExtensionKey($_EXTKEY, 'Page');
    }
);
```
setup.txt
```ts
plugin.fluxtemplate.view {
    templateRootPaths.0 = {$plugin.tx_fluxtemplate.view.templateRootPaths.0}
    partialRootPaths.0 = {$plugin.tx_fluxtemplate.view.partialRootPaths.0}
    layoutRootPaths.0 = {$plugin.tx_fluxtemplate.view.layoutRootPaths.0}
}
```
In the page template I've loaded fluid_styled_content and the definition from my provider extension. Is there anything I'm currently missing? Has anybody a hint? Thanks in advance!

**Comment by NamelessCoder** [comment]
Your setup looks correct with one minor detail that's not correct: you have a `flux:form.option` node outside of the `flux:form` - it needs to go inside that node.

That should however not affect the TCA loading in this way. I would expect to see the default TCA chunk you see in the `Configuration/TCA/Overrides/tt_content.php` file - maybe you can figure out if something is modifying that TCA?

**Comment by ubrt** [comment]
@NamelessCoder 

Thanks for pointing that out. It was working the way it was but this is indeed not very semantic. But neverless as you expectet this does not influence the TCA Output. 

Maybe I messed something up before, I'll give a blank typo3 installation a try. Is there any example provider extension with content elements (compatible with 8.7.17) for reference? I initially tried to use the FluidTYPO3 Development Support Builder but it's not compatible with 8.7... so I've build my extension from scratch with the feeling that I overlooked something. 

Thank you again for your help!

**Comment by NamelessCoder** [comment]
[test-provider-extension.zip](https://github.com/FluidTYPO3/flux/files/2197422/test-provider-extension.zip)

You can study this one for reference (rename or symlink so extension folder is named `testing`). It's kind of a sandbox extension so not everything is working - for example, don't use the section-objects-as-grid template.

**Comment by ubrt** [comment]
@NamelessCoder 

Okay, that was helpful. The only difference was that in the sandbox extension the provider registration is called from ext_localconf.php and not ext_tables.php 

If I refer to the [documentation](https://fluidtypo3.org/documentation/templating-manual/templating/provider-extension/registration-in-php.html) both should be working up from Typo 6.3?

> On TYPO3 6.2 and above, you only need to add this in ext_localconf.php or ext_tables.php - which one you choose doesn't matter, but for consistency we recommend always using ext_localconf.php.

I think registering the provider in ext_tables might be to early and the TCA gets overwritten in the process?

But finally, it's working :+1:  Thanks a lot for the great work.
