### ISSUE TITLE
Cant delete pages in Typo3 when Flux is activated

### ISSUE THREAD

**Issue by M4rt1n17** [FluidTYPO3/flux#1587]
My Setup:
Typo3 v8.7.17

builder v1.2.0
fluidcontent v5.2.0
fluidpages v4.2.0
flux v9.0.0
vhs v5.0.1

When I try to delete a Page I get this error:

> **Oops, an error occurred!**
> Argument 1 passed to TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::eq() must be of the type string, null given, called in /var/www/vhosts/flux.#######.de/httpdocs/typo3/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php on line 342

After deactivating Flux (and everything that depends on, I can delete every Page I want to

**Comment by dahaupt** [comment]
This is already fixed by d5d53e46a983f3e0b46fdbbdf0e05b1578bb53db and I think we will get a minor release (9.0.1) in the next days after some more bug fixes will get merged.

**Comment by chriskrj** [comment]
Right now i would go into the Database and delete the Page right there.

**Comment by M4rt1n17** [comment]
Thanks to @dahaupt did not know it will also fix my issue.

@chriskrj no I dont like deleting things in the DB, I just updated my /flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php manually so I'm on 9.0.0 but this file is already the new one.
