### ISSUE TITLE
Flux 9.0(.1) breaks tt_content colPos dropdown options

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/flux#1593]
**General information:** 
* TYPO3 8.7.17
* Flux 9.0.1

If I take a completely(!) new TYPO3, create a backend layout there and use it, the following selection appears in the tt_content.colPos dropdown:

![image](https://user-images.githubusercontent.com/25088164/43258666-d5fb95ae-90d3-11e8-8e6c-d07cd85f2741.png)
yes, the typo is intended ;)

When I now install `Flux 9.0.1`, the content of this drop-down changes to the default TYPO3 colPos options - when I add content over the list module. In this case I don't have a chance to add content into my col10:

![image](https://user-images.githubusercontent.com/25088164/43258848-8b186bba-90d4-11e8-8573-7ed24e51d869.png)

-----

When I add any content over the page module directly with the button of the column(in this case it's `colPos 10`):
![image](https://user-images.githubusercontent.com/25088164/43258908-c952e5e0-90d4-11e8-9b30-163c10d624f5.png) 
then, the colPos Dropdown shows `[ INVALID VALUE ("10") ]`.
![image](https://user-images.githubusercontent.com/25088164/43258937-e6121c5a-90d4-11e8-899e-23c7f0d6ecad.png)

This is the only way to insert content correctly. It doesn't look good, but it works :)

-----

Editing the Element, again shows the invalid value message:
![image](https://user-images.githubusercontent.com/25088164/43259056-49e57b64-90d5-11e8-9706-23fa23b8ff9c.png)
![image](https://user-images.githubusercontent.com/25088164/43259066-4f5d849c-90d5-11e8-8079-e219d602c327.png)

-----

Everything worked correctly with Flux 8.2.1.

**Comment by yesjoar** [comment]
Same problem here.
- Fresh TYPO3 8.7.17
- Flux 9.0.1

Added a backend layout with Column. (colPos=10)
When adding some content I'll got the same Invalid Value error.

**Comment by Geddo** [comment]
Same here

**Comment by netthinks** [comment]
same problem here, worked before in 8.x

**Comment by almfisch** [comment]
I made 'initializeDataProviderCollection' in 'BackendLayoutView.php' inactive, now it works:

https://github.com/FluidTYPO3/flux/blob/development/Classes/Integration/Overrides/BackendLayoutView.php

/*
    protected function initializeDataProviderCollection()
    {
        // This is an override designed to perform no operations except create a valid data provider collection instance
        $this->setDataProviderCollection(GeneralUtility::makeInstance(DataProviderCollection::class));
    }
    */

**Comment by srdosramos** [comment]
This solved the issue

**Comment by NamelessCoder** [comment]
Appears to be solved in `dev-development` - if you experience otherwise, ping me to reopen the issue.

**Comment by leslawp** [comment]
I still have this problem when I have different layout for subpages (with less number of columns). Seems that this is do to precedence of SubPageProvider over PageProvider, I fixed it by just lowering priority of SubPageProvider (\FluidTYPO3\Fluidpages\Provider\SubPageProvider) from 50 to 40. And comment for this class says "This Provider has a slightly lower priority than the main PageProvider". So what you think about this @NamelessCoder?
I'm not sure if just adding this:
```
  /**
   * @var integer
   */
  protected $priority = 40;
```
to class body is proper solution...

**Comment by leslawp** [comment]
Actually as you can see it was rather problem of Fluidpages.

**Comment by can0199** [comment]
I upgraded a System, now I had the same Problem in FE/BE also is functional except the option colPos in content elements, i have the same  issue as @TheNaderio  described it. I also tried the solution from @almfisch but this does not worked for me also switching to the dev branch does not correct the issue.

I dont have the fluidpage extension installed

Im using Typo3 9 v.9.5.14 with flux in version 9.3.2, has some any ideas to correct the issue ?

**Comment by cweiske** [comment]
(This issue is the same as #1762 and has been fixed with commit 6f6a64e89623dde2e3080e4e28ac28333e479e0b, released in 9.4.0)
