### ISSUE TITLE
Fluid parse error in template; Error: Required argument "colPos" was not supplied.

### ISSUE THREAD

**Issue by Geddo** [FluidTYPO3/flux#1594]
Just updated from flux 8.2 to 9. This is how one of my fluxies look like:

```
<f:section name="Configuration"> 
    <flux:form id="grid3col" options="{group: 'Grids'}"> 
        <flux:grid>  
            <flux:grid.row>
                <flux:grid.column name="leftCol" colspan="4"></flux:grid.column>
                <flux:grid.column name="middleCol" colspan="4"></flux:grid.column> 
                <flux:grid.column name="rightCol" colspan="4"></flux:grid.column>  
            </flux:grid.row>  
        </flux:grid>  
    </flux:form> 
</f:section>
```

How should I change this, I mean what value should I set as colPos?
As my Backend totaly crashed I cannot to anything there. I'm on composer here, is there anything I can do? Thanks for any hint

**Comment by grimmcreative** [comment]
`flux:grid.column` need a `colpos` value now from 0 to 99.

**Comment by Geddo** [comment]
Ok, but which colPos should I take? No matter what I choose, my quadrillion-Grids in the backend show 
> INVALID VALUE ("flux_fluxgrid2col")

Feels bad man. Is there any chance to get my grids working again without to change every content-element?

**Comment by Geddo** [comment]
After the EM upgrade-script didnt work for me I inspected the database and this how it looks:
Setup of my fluxie:
```
<f:section name="Configuration">
        <flux:form id="grid3col" options="{group: 'Grids'}">
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column name="leftCol" colspan="4" colPos="0"></flux:grid.column>
                    <flux:grid.column name="middleCol" colspan="4" colPos="1"></flux:grid.column>
                    <flux:grid.column name="rightCol" colspan="4" colPos="2"></flux:grid.column>
                </flux:grid.row>
            </flux:grid>
        </flux:form>
    </f:section>
```

The Ctype of the grid went from "flux_fluxgrid3col" to "templateflux_fluxgrid3col" (my flux provider ext is called "template_flux" so this should be easy to fix through an mysql update. 
BUT all the CEs withing the grids changed from colPos "18181" to "277800", "277801" or "277802"  - where the last digit is the ColPos-ID from my template, right?

Well I guess I can also fix that via an mysqlquery. Will try and post again

**Comment by NamelessCoder** [comment]
New colPos values are `$parentUid * 100 + $localColPos` - the EM upgrade script adjusts those, if your templates are in order before you run it (otherwise, we can't tell which colPos value to use.

SQL is exactly how you should fix the CType migration.

**Comment by Geddo** [comment]
Sheeet
```

// Renaming the CTYPE
UPDATE tt_content SET CType='templateflux_fluxgrid1col' WHERE CType='flux_fluxgrid1col';
UPDATE tt_content SET CType='templateflux_fluxgrid2col' WHERE CType='flux_fluxgrid2col';
UPDATE tt_content SET CType='templateflux_fluxgrid3col' WHERE CType='flux_fluxgrid3col';


// Generating the right ColPos based on the ColPos-Template Settings
// Affects all nontranslated CEs
UPDATE tt_content SET colPos=(tx_flux_parent * 100) WHERE tx_flux_column='content' AND l18n_parent=0;
UPDATE tt_content SET colPos=(tx_flux_parent * 100) WHERE tx_flux_column='middleCol' AND l18n_parent=0;
UPDATE tt_content SET colPos=(tx_flux_parent * 100 + 1) WHERE tx_flux_column='leftCol' AND l18n_parent=0;
UPDATE tt_content SET colPos=(tx_flux_parent * 100 + 2) WHERE tx_flux_column='rightCol' AND l18n_parent=0;

// Affects all translated CEs with
UPDATE tt_content t2, (SELECT tx_flux_parent, uid FROM tt_content) t1 SET t2.colPos = (t1.tx_flux_parent * 100) WHERE t1.uid = t2.l18n_parent AND t2.l18n_parent<>0 AND t2.tx_flux_column='content';
UPDATE tt_content t2, (SELECT tx_flux_parent, uid FROM tt_content) t1 SET t2.colPos = (t1.tx_flux_parent * 100) WHERE t1.uid = t2.l18n_parent AND t2.l18n_parent<>0 AND t2.tx_flux_column='middleCol';
UPDATE tt_content t2, (SELECT tx_flux_parent, uid FROM tt_content) t1 SET t2.colPos = (t1.tx_flux_parent * 100 +1) WHERE t1.uid = t2.l18n_parent AND t2.l18n_parent<>0 AND t2.tx_flux_column='leftCol';
UPDATE tt_content t2, (SELECT tx_flux_parent, uid FROM tt_content) t1 SET t2.colPos = (t1.tx_flux_parent * 100 +2) WHERE t1.uid = t2.l18n_parent AND t2.l18n_parent<>0 AND t2.tx_flux_column='rightCol';
```

**Comment by NamelessCoder** [comment]
Nice way to handle it, those SQL queries. As mentioned, the last two groups of queries can be performed with the EM update script for Flux (it does the same queries but resolves the values from your templates so you don't have to hardcode them). The only catch is that the templates must be adapted first to include the `colPos`. But you can run the EM script as many times as you need to ;)

**Comment by Geddo** [comment]
In some curious way it didnt work for me - there where some warnings about colpos > 99 (which is true at some point) and after the script was done, only two records where updated. Anyway it works with the custom querys so I guess this issue can be closed
