### ISSUE TITLE
Documentation up-to-date?

### ISSUE THREAD

**Issue by nostartbutrings** [FluidTYPO3/flux#1596]
Hi,
can anybody confirm that the documentation on FluidTYPO3 website is up-to-date? Are there any UP_TO_DATE samples out there, that work with TYPO3 v8 and development-branch of FluidTYPO3 extensions definitely?

Best regards!

**Comment by samowitsch** [comment]
IMHO the website in detail is not up-to-date and reflects not the current state. Rare infos are spread over different issues in different repositories of FluidTYPO3 and from there are links to hints on Stackoverflow. Something is obsolete there, something maybe abandoned on the other hand, CType migration with SQL Script on Stackoverflow and so on...
I like the idea behind FluidTYPO3 very much but this is very annoying!
Currently i am also in a migration trial and error situation :confused:

**Comment by TheNaderio** [comment]
Take a look at [https://viewhelpers.fluidtypo3.org/fluidtypo3/](https://viewhelpers.fluidtypo3.org/fluidtypo3/ )

**Comment by samowitsch** [comment]
@TheNaderio thx for the link. This one i doesn't know. But nowhere are tipps to migrate to current ext:flux with removal of obsolete ext:fluidcontent. A update of https://fluidtypo3.org/documentation/templating-manual/appendix/migration.html would be fine with an additional page "To Flux 9.0" or something like that.
