### ISSUE TITLE
Using field in flux page configuration throws exception in TYPO3 core

### ISSUE THREAD

**Issue by nostartbutrings** [FluidTYPO3/flux#1597]
Hi,
if I use e.g `<flux:field.input ...` in a page template, it throws an exception while trying to edit page properties in backend. TYPO3 v 8.7.17, flux 9.0.1 and corresponding fluidpages, vhs (master and development branch). 
This page template configuration 
```
<f:section name="Configuration">
    <flux:form id="startPage">
        <flux:field.input name="settings.helloWorld" required="true" label="asdadsad" />
    </flux:form>
    <flux:grid>
        <flux:grid.row>
            <flux:grid.column colPos="0" colspan="4" name="headerimg" />
        </flux:grid.row>
        <flux:grid.row>
            <flux:grid.column colPos="1" colspan="3" name="welcome" />
            <flux:grid.column colPos="2" name="right" />
        </flux:grid.row>
    </flux:grid>
</f:section>
```
throws an exception #1440676540 in `typo3\sysext\core\Classes\Configuration\FlexForm\FlexFormTools.php` line 726.
Commenting this peace of code in FlexFormTools.php let me edit the page successfully, but uncommenting again + clearing cache in install tool reactivates the error.

Any ideas?
Best regards, Alex

**Comment by nostartbutrings** [comment]
The problem ist the 'Sheet compacting' (basic.compact) option in extension manager.
Since I work on a new site I thought I can set this option but if set `FluidTYPO3\Flux\Provider\AbstractProvider -> postProcessDataStructure` returns a bad datastruct array that causes the TYPO core exception. This is because the `$newDataStructure = $form->build()` provides a datastruct that does not lead to a valid datastruct after recusive replacing.

**Comment by NamelessCoder** [comment]
Thanks for the followup, @nostartbutrings - the sheet compacting feature will be removed since TYPO3 now does something similar when a TCEforms container has a single sheet. It is unlikely it will become compatible with the Flux-based compacting again.
