### ISSUE TITLE
Return type in BackendLayoutView is wrong

### ISSUE THREAD

**Issue by georgringer** [FluidTYPO3/flux#1598]
If you are using IRRE for tt_content elements, there is an exception because of wrong return type in https://github.com/FluidTYPO3/flux/blob/development/Classes/Integration/Overrides/BackendLayoutView.php#L126

`protected function loadRecordFromTable(string $table, int $uid): array`

this can be also null because with IRRE; the record is not yet persisted and therefore doesn't have any uid => nothing found

**Comment by burgdigital-np** [comment]
Could you please give an example of where you have " IRRE for tt_content elements"?
I have an related error, but am sure I dident change the core settings for the BackendView
