### ISSUE TITLE
record variable not available in backend when using sections

### ISSUE THREAD

**Issue by codingnik** [FluidTYPO3/flux#1601]
After upgrading to vhs 5.0.1 and flux 9.0.1 {record} isn't available in a backend section anymore. Using record directly in the preview section works. In frontend everything is okay.

Sample code follows:

	<f:section name="Configuration">
		<flux:form id="sample" options="{group: 'fce'}">
	
			<flux:field.inline.fal name="settings.image" multiple="false" maxItems="1" />
	
		</flux:form>
	</f:section>
	
	<f:section name="Preview">
	
		<f:comment>record is available here</f:comment>
		<f:debug>{record}</f:debug>
		
		<f:render section="BackendImage" arguments="{settings: settings}"></f:render>
		
	</f:section>
	
	<f:section name="BackendImage">
	
		<f:comment>record is not available here. At least not in flux 9.0.1</f:comment>
		<f:debug>{record}</f:debug>
	
	</f:section>
	
	
	<f:section name="Main">
	
		<f:comment>record is available in frontend</f:comment>
		<f:debug>{record}</f:debug>
	
	</f:section>

My current workaround is setting record explicitly when rendering the section:

	<f:render section="BackendImage" arguments="{settings: settings, record: record}"></f:render>

**Comment by NamelessCoder** [comment]
`<f:render section="BackendImage" arguments="{settings: settings}"></f:render>` is where the problem happens. You intentionally did not transfer the `{record}` variable so it is null in the section. This is not different in earlier Flux versions - there was never a custom VariableProvider implementation that automatically transferred such variables - so at some point you must have changed something that for example turned `{_all}` into `{settings: settings}` in the Preview section.

PS: `{settings}` is automatically transferred so you never have to add that to arguments **unless** you want to overwrite settings specifically with a different value. You never need to transfer `{settings: settings}`.

**Comment by codingnik** [comment]
I will check that. Thank you for the info concerning the settings.
