### ISSUE TITLE
flux:grid.column after colPos migration not showing multi language children

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#1603]
After updating from EXT:flux 8.latest to EXT:flux 9.latest on TYPO3 8.latest and adding colPos attributes to flux:grid.column viewhelper and migrating the children via e.g. 
UPDATE `tt_content` SET colPos = CONCAT(tx_flux_parent, "1") WHERE tx_flux_column = "content.left"; 
the elements and all of its children render fine in frontend in all languages and also in the page module in the CMS backend in the default language everything is shown correctly, but not in a non-default language. In the non default language the children of a flux:grid.column container are not shown. See for example:

![grafik](https://user-images.githubusercontent.com/5528239/43885841-50fff646-9bba-11e8-8b77-ab940bee6f2f.png)

The language connection between the children is correct as well if you look at the list module:

![grafik](https://user-images.githubusercontent.com/5528239/43887053-ef852f2c-9bbd-11e8-8efb-8788c6b7c9c1.png)

Also in the frontend everything is rendering fine:
DE: https://www.aemka.de/dienstleistungen/design.html
EN: https://www.aemka.de/en/services/design.html

latest version are meant as of today.

**Comment by mkrappitz** [comment]
> This doesn't look right.

So, it should be like the following?
UPDATE tt_content SET colPos = CONCAT((tx_flux_parent * 100), "1") WHERE tx_flux_column = "content.left";

> I suggest using the EM upgrade script to do the migration of related records.

Which EM upgrade script? There is none available in the EM:

![grafik](https://user-images.githubusercontent.com/5528239/43897622-efa65958-9bdc-11e8-8c04-01b9c1b4af63.png)

**Comment by NamelessCoder** [comment]
The EM upgrade script is shown if you have the legacy fields in the database schema. If you do not have those in the schema then the SQL queries would fail.

https://github.com/FluidTYPO3/flux/blob/development/class.ext_update.php#L27

Maybe that gives you the hint you need?

**Comment by NamelessCoder** [comment]
`CONCAT((tx_flux_parent * 100), "1")` I'm no SQL genius but wouldn't that result in a colPos value of `123001` instead of the desired `12301`?

**Comment by mkrappitz** [comment]
ok, now I got the update script working! 

And the correct SQL would be:
UPDATE tt_content SET colPos = ((tx_flux_parent * 100) + 1) WHERE tx_flux_column = "content.left";

Thanks for clarifying!
