### ISSUE TITLE
flux:field.text name="tt_content.bodytext" does not work again

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/flux#1604]
just like #1250 
with latest flux

**Comment by advOpk** [comment]
Flux version 9.x breaks tt_content.* named form fields to be saved in database.  

Previously in 8.x \FluidTYPO3\Flux\Backend\TceMain::processCmdmap_preProcess executed executeConfigurationProviderMethod('preProcessCommand').

Now \FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber::processDatamap_preProcessFieldArray is dealing only with colPos typo3 issues [[BUGFIX] Add workaround for forge Issue 85013](https://github.com/FluidTYPO3/flux/commit/ec0cf25f6f4e9de07d8a309e2d5471afe2e70224#diff-93ddaa2e34830c84cb681ad5c240d4b1)

**Comment by glucka** [comment]
Solved by #1636
