### ISSUE TITLE
Exception while open any CE in any container

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/flux#1607]
This happens with latest version (9.0.1 or master)

If i click on edit of any CE inside a container (mask, gridelements, etc) i get this exception:
Return value of FluidTYPO3\Flux\Integration\Overrides\BackendLayoutView::loadRecordFromTable() must be of the type array, null returned

This is a blocker!

It works correct in v8.2.1

**Comment by steffenk** [comment]
while investigating i found the reason

// colPos
$parentRecordUid = -1
...
if ($parentRecordUid) {
               $parentRecord = $this->loadRecordFromTable('tt_content', $parentRecordUid);
...
Sure that this has no result 😉 
this happens inside function addColPosListLayoutItems
seems to be easy one:
if ($parentRecordUid > 0) { ...

**Comment by vruescas** [comment]
Hi, 

Same issue with v9.1.0, still this problem in the extension? Somebody knows if this will be fixed in the next versions?

Return value of FluidTYPO3\Flux\Integration\Overrides\BackendLayoutView::loadRecordFromTable() must be of the type array, null returned.

Thanks.

**Comment by nidema** [comment]
Hi,

Did you set the colPos attribute on the <flux:grid.column/> ?
It's required since version 9 because the parent/children relation completely changed.

**Comment by arnekolja** [comment]
Any news on this? I just found this problem, too.

* colPos is set for flux:grid.column.
* Migration from flux+fluidcontent to flux only is done, including data like upgrading the colPos column.

**Comment by arnekolja** [comment]
Ah, sorry, didn't check master. Seems like it has been fixed by pulling #1633.

**Comment by NamelessCoder** [comment]
Fixed but not closed (the new "dictated but not read") with https://github.com/FluidTYPO3/flux/pull/1633.
