### ISSUE TITLE
[resolved] Dont see configuration section in backend (9.0.x)

### ISSUE THREAD

**Issue by Gitsko** [FluidTYPO3/flux#1610]
Hi,

i install a new TYPO3 9.3 with flux (dev-branch), fluidpages and so on. 

I can see my new content elements, but wenn i choose this, i see only the TYPE Name and no configuration area.

I added for a test also this example https://gist.github.com/mneuhaus/9a8cff9f5b47ad8872eebae2808c54e7 but the same problem. 

Can anybody help ?

**Comment by Gitsko** [comment]
Add this line in ext_tables.php solve the Problem:
`require_once(TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('flux', 'Configuration/TCA/Overrides/tt_content.php'));`

**Comment by NamelessCoder** [comment]
Most likely cause: not having either `css_styled_content` or `fluid_styled_content` installed and/or not having the static TS template from whichever of those is installed, loaded in the root TS template of your site. Or somehow having TCA setup which removes or resets the `types` array of the `tt_content` table - both of which would fit with @Gitsko's problem description.

If you have a custom solution for content rendering which replaces `css_styled_content` or `fluid_styled_content` then you need to be aware of the special `contentRenderingTemplates` setting and how to register the TS of your alternative content rendering extension as a "content rendering template". You can search the web for `contentRenderingTemplates` in conjunction with TYPO3 for more information - but this is far outside the context of Flux and I cannot offer additional support for this ;)

Hopefully this helps. Will close the issue.
