### ISSUE TITLE
f:if condition inside flux:form doesn't update properly

### ISSUE THREAD

**Issue by X-Tender** [FluidTYPO3/flux#1611]
Following example form:
```
<flux:form id="standard">
	<flux:field.checkbox name="trigger" requestUpdate="1" />
	<f:if condition="{trigger}">
		<f:then>
			<flux:field.input name="settings.helloWorld" required="true" />
		</f:then>
		<f:else>
			<flux:field.input name="settings.helloWorld2"  />
			<flux:field.input name="settings.helloWorld3"  />
		</f:else>
	</f:if>
</flux:form>
```

Start:
`trigger`not checked -> 2 inputs visible
-> `trigger`gets checked -> page reloads -> 2 inputs visible
-> `trigger`gets unchecked -> page reloads -> 1 inputs visible
-> Save pressed -> 2 inputs visible

Looks like the update is a step behind.

flux: 9.0.1

**Comment by manikandankasi** [comment]
I want to make an image responsive of a column to open another column like a column just with image and if i click or hover it should open the next column and if anyone have ideas.please let me know
