### ISSUE TITLE
The copy/paste for flux content element, assigns a wrong value to the column colPos

### ISSUE THREAD

**Issue by gianstraf** [FluidTYPO3/flux#1615]
**Environment**

TYPO3: 8.7.9-8.7.17
flux: 8.2.1
PHP: 7.0.27

**The problem**

When I copy  one (or more) content element, with a simple configuration (see after), and then I paste the CE in another page with "Paste in clipboard content" header button, the new content element copied assumes the column _colPos_ equals to destination pid.

This is the button, that causes the problem:

![paste-button](https://user-images.githubusercontent.com/16322192/45543225-56357200-b814-11e8-92ef-3b6a774d466c.png)

**Flux CE source code**
```
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
    xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
    xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
    xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers">
<f:layout name="Content" />

<f:section name="Configuration">
  <flux:form id="grid1col" options="{group: 'Layout Elements'}">
  <flux:field.input name="title" label="Grid block title"/>
  <flux:grid>
    <flux:grid.row>
      <flux:grid.column style="width: 100%" name="col1" label="Column 1" />
    </flux:grid.row>
  </flux:grid>
  </flux:form>
</f:section>

<f:section name="Main">
<div class="grid1col container-fluid px-4 px-md-5">
  <div class="row">
    <div class="col">
      <h2 class="mb-3">{title}</h2>
      <flux:content.render area="col1" />
    </div>
  </div>
</div>
</f:section>

<f:section name="Preview">
{title}
  <flux:grid />
</f:section>

</div>
```

With debugging, I see that the problem could be localized in class FluidTYPO3\Flux\Service\ContentService, method _moveRecord_, around rows 196-201:

```
           } elseif (0 <= (integer) $relativeTo) {
                // moving to first position in colPos, means that $relativeTo is the target colPos. PID is already set!
                $row['tx_flux_parent'] = null;
                $row['tx_flux_column'] = null;
                $row['colPos'] = $relativeTo;
            } else {
```

Thank you,
Gianluca

**Comment by NamelessCoder** [comment]
Please update to Flux 9.0 which fixes this problem. There will be no further releases in the 8.2 branch.
