### ISSUE TITLE
BACKEND: The content elements that have children (containers) can not be closed/opened.

### ISSUE THREAD

**Issue by alexbirke** [FluidTYPO3/flux#1616]
TYPO3: 8.7.19
flux: 9.0.1
PHP: 7.0.30-0+deb9u1

### **The problem**

**Backend:** The content elements that have children (containers) can not be closed/opened.

### **The patch**

**IMHO:** the reason is contained in the **file flux/Classes/Integration/HookSubscribers/ContentIcon.php**, in line 108:
```php
if ($cachedIconIdentifier !== null) {
```
Too strict verification prevents proper operation.

In my project, I replaced '**!==**' at '**!=**' and now it works correctly.

Please fix this bug in the next release of Flux.

Thank you.

**Comment by NamelessCoder** [comment]
The `null` explicit check is intentional and avoids attempts to regenerate icons if an empty entry was cached (meaning there is no resolved icon). So I suspect there is another cause to this, as removing that check would only cause needless executions of sometimes expensive code.

**Comment by alexbirke** [comment]
I admit my patch is not the best, but I think for workaround it's Ok.

I hope some day ~~you'll join us~~  :wink: you'll fix it in the right way.

**Comment by rangerluke** [comment]
The get-method of the CacheManager returns false and not null if there is no cache entry. This core method was changed in the 8er version. So i changed line 108 in the class ContentIcon to 
` if ($cachedIconIdentifier !== false && $cachedIconIdentifier !== null) {`
than its working for me and the collapse button is only shown für grids.
