### ISSUE TITLE
Backend: label of flux:grid.column not shown in translation

### ISSUE THREAD

**Issue by fiedomedia** [FluidTYPO3/flux#1620]
My setup:
TYPO3: 8.7.19
flux: dev-development
fluidpages: 4.2.0

I have a default language (EN) and a translation (de_DE). Now I've created a simple flux content element example with one column:
```html
<f:section name="Configuration">
    <flux:form id="container">
        <flux:grid>
            <flux:grid.row>
                <flux:grid.column colPos="0" name="column" label="Container-Content">
                </flux:grid.column>
            </flux:grid.row>
        </flux:grid>
    </flux:form>
</f:section>
```
**Problem:** in connected mode the label is missing in the german column, instead the colPos for the child records is shown.
![label_connected_mode](https://user-images.githubusercontent.com/2965516/46002441-581df180-c0ae-11e8-9508-62162ff09386.PNG)
(translated child record has uid 201870)

As you can see in the following screenshot, the label of the column "Container-Content" is shown in both languages, if the translation mode of the current page is "free mode". In this case the content elements are not translated to german but copied.
![label_free_mode](https://user-images.githubusercontent.com/2965516/46002433-53593d80-c0ae-11e8-951e-3eeba2c9cebc.PNG)

BUT: my page template also has a label "Content", which is shown in every situation.
`<flux:grid.column colPos="0" name="Main" label="Content">`

**Comment by MediKathi** [comment]
I didn't tested multiple languages so far, but label="LLL:EXT:yourExt/Resources/Private/Language/locallang.xlf:flux.TwoColumns.columns.Col1" works for me.

Does Flux (9.1.0) not Check the locallang any more? Or is there a other key needed?

**Comment by fiedomedia** [comment]
I had also tested it with my locallang.xlf file, but the result was the same in connected mode.
It only shows the label in the default language.

**Comment by MediKathi** [comment]
While Migration work I found following for the Preview Section

{f:translate(key: 'flux.TwoColumns')} shows nothing, but {f:translate(key: 'LLL:EXT:myExt/Resources/Private/Language/locallang.xlf:flux.TwoColumns')} works so I tested: {f:translate(key: 'flux.TwoColumns', extensionName: 'myExt')} wich also works.

maybe you can use label="{f:translate(key: 'someKey', extensionName: 'yourExt')}"

**Comment by almfisch** [comment]
Any news here? I have the problem with translations and Column-Labels. I don't use translations for the labels, only label="Col 1". In the translated version the label is a number, e.g. '80123'.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/5fde1b6d2cd448e6ad64c7a3f70a7de4ad79190f
