### ISSUE TITLE
TYPO3 9.5 #1294585866 InvalidArgumentException

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/flux#1631]
TYPO3 9.5
Fluidpages: 4.3.0
Flux: 9.1.0

We just updated a working TYPO3 8.7.17 to the current TYPO3 9.5 and received this error:

<img width="1162" alt="screen shot 2018-10-09 at 13 46 09" src="https://user-images.githubusercontent.com/3603346/46667452-fee3b100-cbc9-11e8-8026-c151df6aeff8.png">

Fluidcontent is not installed. All caches have been cleared. Autoload has been refreshed.

**Comment by NamelessCoder** [comment]
It looks like perhaps one or more of your configuration files, ext_localconf.php files or cached configuration has not been cleared. Note that sometimes after such an upgrade you have to use the install tool / Maintenance module to clear caches and update DB before the "clear cache" buttons in the BE will actually work.

**Comment by NamelessCoder** [comment]
Hint: the class definitely no longer exists and is not normally referred to from anywhere except Flux's ext_localconf.php, you can confirm it isn't mentioned there. The new class name that is expected instead is `\FluidTYPO3\Flux\Integration\HookSubscribers\TableConfigurationPostProcessor`.

**Comment by MrMooky** [comment]
Thanks for the hint. :)
