### ISSUE TITLE
Copy & Paste child elements

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/flux#1632]
Hi, we have problems with moving translated child within flux grid columns. They are not moved or copied when nested. I`ve made a screenshot to show the problem.  Only the first child elements gets moved when moving a container element. 

The copies of all the elements are created, but not with the right colpos. After copying/moving the container elements to another page and then moving the single elements around, they appear in the right position. So this is only the matter when copying/moving to another page or copy a whole page.

I hope the image explans it. If someone needs sponsoring for this to fix, please ask.

Thanks! 
Tobias

![screen](https://user-images.githubusercontent.com/5941531/46738841-77687180-cc9f-11e8-99f1-88cf37ea42fd.png)

**Comment by tobiasgraeber** [comment]
Hi @NamelessCoder,

first of all, thanks for your great work. As @mithri already points out above, we have the same problem.
We try to copy a page (containing multiple nested elements) in full as usual, but after copy, looking on the page elements, only those elements copied correctly which have a nesting of max 2 elements (so 1 container and 1 child element). If there are elements, with more childs, say 1 container, 1 child inside that container and another one inside the child - these (last childs) won´t get copied (seems like the same as in the screenshot above).

Info:
We noticed, that you could work around the issue, if you copy the elements one-by-one or even all at once (wrapping all of them into one temporary content element/container), if you dont copy the page itself but copy the single element (containing multiple nested elements) "by hand/manually" from one page to another.

So it seems there is a general problem in copying nested elements by using the "page copy" feature.

Could you maybe investigate into that / give this topic a higher priority?
We are currently facing the challenge to copy one page (as template) for up to 20-30 other pages, and doing this "by hand" would be an enormous higher effort (and also would take much much more time and is much more error-prone.

Wourd really really appreciate to hear from you (and anyone else) regarding this topic!
Thank you very much in advance!

**Comment by NamelessCoder** [comment]
Hey @tobiasgraeber,

> Could you please investigate into this topic / give this topic a higher priority?

I'm afraid I don't currently have the time to invest - changing the priority wouldn't help with that. Meanwhile you can help identify the more exact cause or line of code that for whatever reason stops or fails to continue recursion.

You may end up finding that it requires a specific composition of records to trigger it.

I would also look for differences in the instance of DataHandler and its properties, as it is received by Flux's hooks in the case that works and the other that doesn't.

Lastly, if you are under pressure and must have a solution quickly, it may be possible if you register a second DataHandler hook listener like the one Flux has, which executes the recursive child record copy only in this specific case where Flux fails to do it.

See also / focus around https://github.com/FluidTYPO3/flux/blob/development/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php#L269

**Comment by robsonrobi** [comment]
And progress here? Localization is so important. Flux is great but only for single language pages. I will try to implement a post cleanup for locslization...😞

**Comment by glucka** [comment]
This is one of the reason of this bug:
https://github.com/FluidTYPO3/flux/blob/f1c2765d9a84f9e924c6b367d140061cd6c032d9/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php#L130
isset($dataHandler->cmdmap[$table][$uidInDefaultLanguage]['move']) is always false with copy operation
I keep researching...
