### ISSUE TITLE
Copying pages with grids fails; copying only content works

### ISSUE THREAD

**Issue by codingnik** [FluidTYPO3/flux#1640]
I am experiencing a similiar problem as stated in https://github.com/FluidTYPO3/flux/issues/1589. 

The error "The record tt_content:1957 was designated as Flux parent ..." appears when copying a complete page with quite some elements. The bug doesn't appear when I copy only the content elements from that page. In order to copy them all at once, I wrapped the content elements in an element using a flux:grid.column.

flux: 9.1.0
fluidpages: 4.3.0
TYPO3: 8.7.19

**Comment by codingnik** [comment]
After quite some research I will close this ticket as it is not directly a bug in flux.

Copying of complete pages was impossible due to some content elements having an improper sorting value. This led to child elements being copied before their parents resulting in the known error message.

Still I have no idea why sorting was messed up but after correcting those values copying was fine.

**Comment by fnagel** [comment]
Might be related to one of those core issue: 

https://forge.typo3.org/issues/59901
https://forge.typo3.org/issues/82032
