### ISSUE TITLE
enableMultiSelectFilterTextfield

### ISSUE THREAD

**Issue by magedeveloper** [FluidTYPO3/flux#1641]
I am having a relation field for multiselect that needs the search field above, but i haven't found a solution for this.
Since TCA has slightly changed in TYPO3 9 LTS, the suggest wizard has changed to `enableMultiSelectFilterTextfield=>true`

`                    
<flux:field.relation 	condition="ORDER BY title"
                                            maxItems="5"
                                            minItems="0"
                                            size="5"
                                            multiple="false"
                                            table="tx_dataviewer_domain_model_record"
                                            name="area"
                                            label="Webseitenbereich">
</flux:field.relation>
`
Can someone give advice or is it currently not possible?

**Comment by X-Tender** [comment]
Oh I just stumbled upon this issue too. :/
