### ISSUE TITLE
[BUG ?][Typo3-9.5.1] Flux Group not working properly

### ISSUE THREAD

**Issue by christianjung87** [FluidTYPO3/flux#1644]
Hi,
I have a quite fresh installation of Typo3 9.5.1 with Flux 9.1.0.

I want all of my FCEs to rest in a individual groups. So a rather simple FCE looks like this:

```
<div xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers" xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers">

    <f:layout name="Content/Clean" />

    <f:section name="Configuration">
        <flux:form id="image">
            <flux:form.option.group value="system" />
            <flux:form.option.icon value="/typo3conf/ext/provider/Resources/Public/Icons/Content/Image.svg" />
        </flux:form>
    </f:section>

    <f:section name="Preview">
        <strong>Image-Service</strong>
    </f:section>

    <f:section name="Main">
        // TEMPLATE
    </f:section>
</div>
```

It works totally fine for the new "Create new content element"-Popup as you can see here:

![image](https://user-images.githubusercontent.com/16928867/47779955-ab611080-dcfa-11e8-9778-fff98ccb141a.png)

But inside the FCE-Mask the Icon is broken and it seems that the FCE is not assigned to the group (both of my individual groups are not showing up)

![image](https://user-images.githubusercontent.com/16928867/47780055-e400ea00-dcfa-11e8-9654-4c0d39997aa7.png)

The only addition I made is hiding standard fluid_style_conten-CEs via PAGETS.

**Comment by NamelessCoder** [comment]
Hi @christianjung87,

I tried every method I know but as far as I can determine, we will not be able to represent the group name in the dropdown list of the `CType` field. In the core API Flux uses there is simply no way to insert the special pseudo-option which would render the group name.

By the way the reason you see the content types in the `Forms` group is that this group is the last group (after you've disabled other types with pageTSconfig) and Flux's content types are appended to the end of the list, which then causes them to appear grouped in the last group inserted in this field.

It *might* be possible for you to manually fix this, but will be a custom solution that only applies to your specific elements. You would need to add `Configuration/TCA/Overrides/tt_content.php` to your extension and within this file, manipulate `$GLOBALS['TCA']['tt_content']['columns']['CType']['config']['items']` - if you dump this array you should see some options which have a label of `--div--` and the group name as option value. If you iterate the array and as soon as you detect one of your own content types, add a corresponding `--div--` entry at the right place in the array (you'd need to count entries, split the items array in two, and recreate the items array using the two split parts with the special `--div--` option inbetween).
