### ISSUE TITLE
Example website

### ISSUE THREAD

**Issue by golserma** [FluidTYPO3/flux#1651]
Is there an example project using flux and fluid?
I find it hard to find an up to date code example.

Bonus I could look at the changes and see what is necessary for upgrades.

**Comment by ZweisteinT** [comment]
Hi,
I learnt These days from his tutorials: https://www.youtube.com/user/NaderiosTNT/videos

But its german! But i think you yould still watch and repeat his steps.

**Comment by chriskrj** [comment]
There is a pretty good example provider ext. with Bootstrap for TYPO3 8.7 
https://github.com/benjaminkott/bootstrap_package
Maybe check this project.  Could be useful for u.

**Comment by NamelessCoder** [comment]
@chriskrj That one I'm afraid has nothing to do with Flux. It's an example implementation of templating based entirely on TypoScript - which is exactly what Flux aims to avoid.

The tutorial from @thenaderio above is quite good, but I would recommend using Composer to install the project. That way you don't have to mess around with finding the right versions to download and can instead run a couple of commands to get a working site.

**Comment by kimchristiansen** [comment]
You could take a look at https://github.com/bootstraptheme-for-typo3/fluidbootstraptheme
Don't know how well the repository is maintained.

**Comment by NamelessCoder** [comment]
The `fluidbootstraptheme` looks like it isn't really maintained anymore, but the templates within still gives a good impression about how to use Flux. For migration info you can look at https://github.com/FluidTYPO3/flux/issues/1542 - and of course use the provided extension update script (which is relevant if you come from Flux versions prior to 9.0). One thing to note about `fluidbootstraptheme` is that the contents of `ext_tables.php` should actually be placed in `ext_localconf.php`.

The next version of Flux will also provide you with two additional ways of declaring content types:

* Record based, in which you create "content type" records in the root page level (pid=0)
* Drop-in, in which you place templates in a designated design directory (which gets bootstrapped with an example template)

Operating the basics does not require detailed knowledge of TYPO3, but creating form fields requires at least a superficial knowledge of TCA. The field ViewHelpers provided by Flux all generate TCA but have a slightly different API - you can find documentation on each ViewHelper on https://viewhelpers.fluidtypo3.org/fluidtypo3/flux/.

Closing the issue.
