### ISSUE TITLE
Copying page w/ record with uid smaller than parent fails

### ISSUE THREAD

**Issue by andreaswolf** [FluidTYPO3/flux#1670]
## The problem

Imagine the following situation:

* a page with a Flux container with uid X
* a content element with uid Y in the container (colPos = X * 100)
* Y < X (i.e. the content was created before the container and later moved inside)

Copying that page will fail with a message "The record tt_content:X was designated as a Flux parent for tt_content:NEW… during a copy operation, but the designated parent record does not appear to have been copied. It is possible this is caused by a third-party hook subscriber somehow setting invalid values in DB."

## Analysis

This happens due to the nature of the copy process:

* copying a page in TYPO3 triggers DataHandler with a corresponding cmdmap (command map) that contains a copy operation for this one page
* this cmdmap triggers a call to `DataHandler::copyPages()`
  * this copies the page, and then triggers a copy operation for each record on the page, ordered by uid (`DataHandler::copyRecord()`)
  * each of these copy operations creates its own child instance of DataHandler, with a corresponding datamap
    * after each of these copy operations, Flux' hook implementation `DataHandlerSubscriber::processDatamap_afterDatabaseOperations()` is invoked and tries to remap the `colPos` value to the new parent
    * this fails because the record with uid Y will be copied after the record with X, but the hook looks for Y's copy directly after X was copied

## Solution(s)

One viable solution IMO is to keep a stack of all these "failed" records, and remap them after each operation.

Another would be to do all these remappings only when the cmdmap is finished. For that, the mentioned hook implementation should only record the "records to be remapped" and another hook (to be determined, probably in `DataHandler::process_cmdmap()`) would do the actual mapping then.

**Comment by NamelessCoder** [comment]
@andreaswolf can you give this one a second test while you have https://github.com/FluidTYPO3/flux/pull/1663 applied? Unfortunately I have not had time to test it myself but if you can add a 3rd positive vote I don't have any objections to merging that PR.

**Comment by andreaswolf** [comment]
I just tested our exact failure case and it works perfectly with #1663 applied. I did not do a code review etc., however.

**Comment by NamelessCoder** [comment]
Thank you Andreas! I'll take care of the code review and CGL adjustments before merging.

**Comment by NamelessCoder** [comment]
#1663 is merged
