### ISSUE TITLE
New "Allow translating child content with localize button" features breaks localization in TYPO3 v8

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/flux#1675]
I've just tested the latest `development` branch (3509426ab3351afcc3a7f38cad487c8bfbacb7f9) and noticed a fatal error due to the usage of `TYPO3\CMS\Core\Http\JsonResponse` which is not available in TYPO3 8.7. Another issue is the new method decleration, which will throw a PHP warning:

`#1476107295: PHP Warning: Declaration of FluidTYPO3\Flux\Integration\Overrides\LocalizationController::getRecordLocalizeSummary(Psr\Http\Message\ServerRequestInterface $request): Psr\Http\Message\ResponseInterface should be compatible with TYPO3\CMS\Backend\Controller\Page\LocalizationController::getRecordLocalizeSummary(Psr\Http\Message\ServerRequestInterface $request, Psr\Http\Message\ResponseInterface $response) in .../typo3conf/ext/flux/Classes/Integration/Overrides/LocalizationController.php line 0
`

This issue has been introduced with this commit: ae671cc805f16bf43b90edd72cf367c875aef067

**Comment by fnagel** [comment]
Not a real fix but a condition to not use the override in TYPO3 8.7: https://github.com/fnagel/flux/commit/1a1960cb745387c6e5919d465938ca4505a779bf

**Comment by NamelessCoder** [comment]
Thanks for pointing to this one @fnagel - I fixed it by a version check in the override of the localization controller. Today I went through 4+ hours of attempting to make this particular feature work on 8.7 and so far I've had to give up. It really does look like this translation process can't be supported on 8.7 - if you have any ideas whatsoever don't hesitate.

**Comment by fnagel** [comment]
@NamelessCoder Thanks for the fix! 

Oh boy, that sounds pretty frustrating. 

Not sure how I could help here but IMO localization is a mess in TYPO3 8.x anyway, so perhaps it's OK to just support 9.x. I had editors asking why there is no button but they have learned to deal with it. It's not perfect but at least I did not have more complains about that missing button.

**Comment by NamelessCoder** [comment]
Exact same Q came across my desk today, hence the hunting session. I did find an override: move the element out of the container, button appears, translate, move parent back into container and translation will follow. In my case this was even further hindered by not allowing the child content type in the page content column so it couldn't be moved outside - so our nasty workaround is to move the container to another column, move the child out, translate, move back in and move the parent back.

It's not exactly pretty but it does work. I'm left with having to give the recommendation to upgrade TYPO3 to 9.5 LTS as soon as that's possible. The good news is that both Flux and VHS no longer require the v8 compatibility extension!
