### ISSUE TITLE
fields in table "tt_content" have not been saved correctly

### ISSUE THREAD

**Issue by tsurfer84** [FluidTYPO3/flux#1676]
Hi,

I have a 2-col grid-element:

        <flux:grid>
            <flux:grid.row>
                <flux:grid.column name="left" colPos="11" label="links" />
                <flux:grid.column name="right" colPos="12" label="rechts" />
            </flux:grid.row>
        </flux:grid>        

in that page layout:

            <flux:grid.row>
                <flux:grid.column colPos="0" name="Content" label="Flux-Inhalte"/>
            </flux:grid.row>

When I add some additional content element inside the 2col-grid (e.g. a simple text) und save, I get the following red error:

"1: These fields of record 1310 in table "tt_content" have not been saved correctly: colPos! The values might have changed due to type casting of the database."

None of the added content elements appears in the 2-col gridelement.
In the typo3 list view, I see each content element is saved in col 32767, no matter if I originally tried to add it in the left or the right col of the gridelement.

Can one help?

**Comment by glucka** [comment]
See here the right syntax for the page layout:
https://github.com/FluidTYPO3/test_provider_extension/blob/master/Resources/Private/Partials/TwoColumnGrid.html

**Comment by tsurfer84** [comment]
That did not solve the problem, because the error occurs as I mentioned in the backend, right after saving some content inside die grid. My Code for frontend looks like:

<f:section name="Main">
<flux:content.render area="left" />
<flux:content.render area="right" />
</f:section>

The mentioned error even occurs with the test provider extension.

**Comment by NamelessCoder** [comment]
> 32767

Hmm. This looks suspicious. Might your DB schema for `tt_content.colPos` have redeclared the field as no longer a `BIGINT` by a third party extension?

**Comment by NamelessCoder** [comment]
Do you for example have `gridelements` installed and does it load *after* Flux?

https://github.com/TYPO3-extensions/gridelements/blob/master/ext_tables.sql#L43

**Comment by tsurfer84** [comment]
Match! Gridelements is the problem, in my case version 8.3. with Typo3 8.7.

After deinstalling it and altering the DB, flux works as it should.

ALTER TABLE tt_content CHANGE layout `layout` INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE colPos `colPos` BIGINT DEFAULT 0 NOT NULL 

Static templates load in sequence: first gridelements, then own provider extension.

But how can I solve the problem with gridelements in generall? Or it impossible to use both flux and gridelements?

**Comment by NamelessCoder** [comment]
> Static templates load in sequence: first gridelements, then own provider extension.

Template loading order doesn't matter. Extension loading order does. Only `depends` and `suggests` set at extension level can affect that order.

> But how can I solve the problem with gridelements in general?

Workaround: make your provider ext depend on both Flux and Gridelements, then copy `ext_tables.sql` from Flux to your own extension. This will give your extension the final word about data type of that column.

If you ask me, `smallint` is very aggressive but that's another discussion for another time.

> Or is it impossible to use both flux and gridelements?

I honestly wouldn't recommend mixing the two, mainly because of the core logic overrides Gridelements contains. If you're looking for the least invasive solution that's Flux. But it doesn't come with the same UX - Flux prioritises developer-level integration.

**Comment by NamelessCoder** [comment]
Closing the issue - except for the extension loading order and encouraging Gridelements to not redeclare the column type for `colPos` to smallint, we cannot solve this issue from our side.

**Comment by christophlehmann** [comment]
https://github.com/TYPO3-extensions/gridelements/pull/42
