### ISSUE TITLE
Clean flexform with cleanFlexFormXML not working

### ISSUE THREAD

**Issue by almfisch** [FluidTYPO3/flux#1679]
Hi,

I tried to make a task-script for cleaning flexform fields in tt_content. In the development phase fields are often deleted or renamed, so I thought a task would be good.

A test with something like this is not working:

`$flexFormTools = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Configuration\FlexForm\FlexFormTools::class);
$flexFormTools->cleanFlexFormXML('tt_content', 'pi_flexform', array(123));`

The error is:
TCA misconfiguration in table "tt_content" field "pi_flexform" config section: ds_pointerField "list_type" points to a field name that does not exist.

Thank you for any hints to make the task working
Andi

**Comment by NamelessCoder** [comment]
Hi @almfisch,

Flux does not use `ds_pointerField`. Are you certain this is a Flux-related issue?

**Comment by NamelessCoder** [comment]
Closing issue due to lack of response. See also https://github.com/FluidTYPO3/flux/issues/1666 which explains the prerequisites of cleaning (most importantly, you must specify the full record of TYPO3 will not trigger Flux to read a dynanic data structure).
