### ISSUE TITLE
sys_file_reference - pid wrong when CE is moved

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/flux#1680]
Hi,

the sys_file_reference entry isn`t updated when a flux content element with a fal field is copied/moved to another page. Not a problem as long as the original page is not deleted. If deleted the sys_file_reference is deleted, too, and the flux CE is not working anymore.

flux: 9.1.0, TYPO3 v8

I hope this helps.

Thanks.
Tobias

**Comment by NamelessCoder** [comment]
Hi @mithri,

Please report this to forge.typo3.org - if this is a problem in Flux it is also a problem in any other FlexForm context, meaning it is a core issue we cannot solve in Flux. I'm not completely sure but I seem to recall seeing a couple of TYPO3 patches this year about correct handling of references contained within FlexForm structures. Perhaps the issue no longer exists in more recent versions of TYPO3?
