### ISSUE TITLE
Copy pages with grid fails (children missing in copied page)

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/flux#1682]
I'm having issues when copying pages in TYPO3 8.7.24 with latest development branch of EXT:flux (3509426ab3351afcc3a7f38cad487c8bfbacb7f9 - after using my fix in #1675). I've tested this in a custom installation and a fresh introduction package instance. Error does not appear when using latest stable (9.1.0).

## How to reproduce

Here's what I do:

* Create a new page
* Add a grid (see template below)
* Add content within the grid element
* Copy that page
* Grid content is missing and error message is shown

## Screenshots
![1](https://user-images.githubusercontent.com/116824/54697815-87c62780-4b2e-11e9-9db9-4cb10a7e6e59.PNG)
![2](https://user-images.githubusercontent.com/116824/54697813-872d9100-4b2e-11e9-8b48-6cb1e6f42325.PNG)
![3](https://user-images.githubusercontent.com/116824/54697814-872d9100-4b2e-11e9-8792-bc1b21cba527.PNG)

## Error messages

Error message: 
``
2: SQL error: 'Unknown column 'colPos' in 'field list''
``

![error](https://user-images.githubusercontent.com/116824/54697857-9ad8f780-4b2e-11e9-8292-350069052595.PNG)

## Template (simplified)

	<f:section name="Configuration">
		<v:variable.set name="columnItems" value="{
			null: 'Default (equal width)',
			'12': 'Full width',
			'10': '5/6 width',
			'9': '3/4 width',
			'8': '2/3 width',
			'6': '1/2 width',
			'4': '1/3 width',
			'3': '1/4 width',
			'2': '1/6 width'
		}" />

		<flux:form id="row" label="Grid Row" description="Add content in columns.">
			<flux:form.option.group value="common" />
			<flux:form.option.icon>EXT:project/Resources/Public/Icons/grid.svg</flux:form.option.icon>

			<flux:form.section name="columns">
				<flux:form.object name="column" label="Column">
					<flux:field.select label="Large devices" name="class-large" items="{columnItems}" />
					<flux:field.select label="Medium devices" name="class-medium" items="{columnItems}" />
					<flux:field.select label="Small devices" name="class" items="{columnItems}" />
					<flux:field.checkbox name="center" label="Center column" />
				</flux:form.object>
			</flux:form.section>
			<flux:grid>
				<flux:grid.row>
					<v:condition.type.isArray value="{columns}">
						<f:for each="{columns}" as="sectionObject" iteration="iteration">
							<flux:grid.column name="column{iteration.cycle}" colPos="{iteration.cycle}" label="auto" />
						</f:for>
					</v:condition.type.isArray>
				</flux:grid.row>
			</flux:grid>
		</flux:form>
	</f:section>

Anybody having the same issue?

**Comment by NamelessCoder** [comment]
Claus from the rear line with the 10-minute fix-and-push :) thanks again @fnagel!

**Comment by NamelessCoder** [comment]
@fnagel do you experience any other major or semi-major issues? I'm asking because I think this could be a good time to make a new release, but I don't want to do that if you've experienced other things like the above which are definite show-stoppers...

**Comment by fnagel** [comment]
@NamelessCoder No, we (medium size project with lots of Flux grids and four languages) did not experience any other issues using this branch (just a fix for that localization controller issue in 8.7): https://github.com/fnagel/flux/commits/fix-allow-translating-child-content-with-localize-button-for-typo3-87 

I will now test your latest commits. As always, thanks a lot for the quick help!

**Comment by fnagel** [comment]
@NamelessCoder Latest commits (90774c92df697b00a8f773e057020c3942f9c1df and 1d4642384f3cda38f4a5e1ae5ab55dd4cabec073) work as expected in TYPO3 8.7.24

**Comment by fnagel** [comment]
@NamelessCoder We did notice another issue with copying localized grids. I will create a ticket soon.

**Comment by fnagel** [comment]
@NamelessCoder See here for remaining copy bug: #1683
