### ISSUE TITLE
Values did'n update properly inside flux form aka. requestUpdate issues

### ISSUE THREAD

**Issue by X-Tender** [FluidTYPO3/flux#1685]
I broke down the Issue to the minimum and that's how it looks like:
```html
<flux:field.input name="one" label="One" />
<flux:field.none name="two" label="Two" default="{one}" />
```
1. I insert "Hello" into "One"
2. Save
3. One = "Hello", Two = ""
4. I insert "World" into "One"
5. Save
6. One = "World", Two = "Hello"
??

That's also the problem with `requestUpdate`.
When I have a `select` and would like to display the selected value in a `field.none` it always shows the previous value:

**Comment by NamelessCoder** [comment]
I'm unable to confirm this problem. On my TYPO3 9.5 LTS test system:

```xml
<flux:field.input name="newfield1" />
<flux:field.none name="parentvalue" default="{newfield1}" />
```

Lets me enter a value in "newfield1" and immediately after saved, this new value is shown in "parentvalue".

Do you have the `static` option for the Flux form set to `true`? That will cause the DS array to be cached - and the `default` is part of that array.

**Comment by X-Tender** [comment]
No I didn't set the static value. Just copy pasted your example and had the same issue :/
I use v 9.1.0 flux + 9.5.4 typo3

**Comment by NamelessCoder** [comment]
By `static` I mean `<flux:form.option name="static" value="1" />` or `<flux:form ... options="{static: 1}">` - this is the flag that makes the DS statically cached. If you're using that you have to disable this feature for that particular form (because it's no longer static when you use dynamic values in the DS).

**Comment by X-Tender** [comment]
Yes I know this option :) And we didn't use it.
I tried it now with ` <flux:form.option name="static" value="0" />`but same problem.

**Comment by NamelessCoder** [comment]
Excellent (good option to know btw). Is anything else happening when you save the record - do you for example see (related or unrelated) errors as FlashMessages, see form validation issues, etc?

And does this *only* happen if you use requestUpdate (because I didn't use that in my tests).

**Comment by X-Tender** [comment]
I've created now a complete new CE with just this test fields:
```html
<div
	xmlns="http://www.w3.org/1999/xhtml"
	lang="en"
	xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
>
	<f:layout name="Content" />

	<f:section name="Configuration">
		<flux:form id="test" label="Test">
			<flux:field.input name="newfield1" />
			<flux:field.none name="parentvalue" default="{newfield1}" />
		</flux:form>
	</f:section>

	<f:section name="Preview"> </f:section>

	<f:section name="Main"> </f:section>
</div>
```

1. I've added it to my Backend page.
2. Entered "Hello"
3. Saved 
4. `parentvalue` input contains "Hello"
5. Entered "World"
6. Saved
7. `parentvalue` input stoll contains "Hello"
8. Entered "Lorem"
9. Saved
10. `parentvalue` input contains "World"

**Comment by NamelessCoder** [comment]
I'm still not able to reproduce this - can you please try with Flux 9.2?

**Comment by X-Tender** [comment]
Great, now it works as expected. Thanks.
