### ISSUE TITLE
Flux Update 9.1 to 9.2 Content Element has no rendering definition

### ISSUE THREAD

**Issue by andigo-west** [FluidTYPO3/flux#1689]
Hi,

i just updated Flux from 9.1 to 9.2. Now all custom elements i made with Flux show an error "ERROR: Content Element ... has no rendering definition!". Any hints how i can solve that Problem?

TYPO3 is up to date and i cleared all caches.

**Comment by grimmcreative** [comment]
Delete typo3temp folder.

**Comment by andigo-west** [comment]
Tried to delete the typo3temp folder already. Still no success

**Comment by andigo-west** [comment]
Found the problem. My filesnames were "1_example.html" and the new Flux Version does not like the underscore. I removed the underscore and changed the CType of the elements via MySQL, now everything works fine again

**Comment by NamelessCoder** [comment]
Thanks for the update @andigo-west - filenames should indeed be `UpperCamelCase` (and should not start with numbers btw). Hopefully this helps someone else who comes here searching for a similar issue.
