### ISSUE TITLE
Empty grid element causes PHP warning

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/flux#1693]
When saving an empty (= no columns added) grid element following warning will show up in page module: 

``
#1476107295: PHP Warning: array_push() expects at least 2 parameters, 1 given in /var/www/project/typo3conf/ext/flux/Classes/Integration/PreviewView.php line 320
``

![grafik](https://user-images.githubusercontent.com/116824/56364363-a3385700-61ee-11e9-9498-8af530c7365b.png)

Using TYPO3 8.7.24 with EXT:flux 9.2.0
Grid configuration similar to the one posted here: https://github.com/FluidTYPO3/flux/issues/1683

**Comment by fnagel** [comment]
@NamelessCoder Thanks for the fix. I've just tested this and it seems I'm now running into a follow-up issue: 

```
Uncaught TYPO3 Exception
An exception occurred while executing 'SELECT * FROM `tt_content` WHERE (`tt_content`.`pid` = 749) AND (`colPos` IN (0)) AND (`sys_language_uid` IN (0, -1) AND colPos IN () ) AND ((`tt_content`.`deleted` = 0) AND ((`tt_content`.`t3ver_wsid` = 0) OR (`tt_content`.`t3ver_state` <= 0))) ORDER BY `sorting` ASC LIMIT 100': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) AND ((`tt_content`.`deleted` = 0) AND ((`tt_content`.`t3ver_wsid` = 0) OR (`' at line 1

Doctrine\DBAL\Exception\SyntaxErrorException thrown in file
/var/www/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 90.
```

Seems the issue is the empty `colPos IN ()`.

**Comment by NamelessCoder** [comment]
Hey Felix - do you have a stack trace or just the first one or two items in the stack?

**Comment by NamelessCoder** [comment]
The only place I could find in Flux that does an `in()` query with Doctrine, is in \FluidTYPO3\Flux\Integration\HookSubscribers\DataHandlerSubscriber::getParentAndRecordsNestedInGrid which does have a guard for empty child colPos values... could this be caused by RECORDS() on ContentObjectRenderer?

**Comment by NamelessCoder** [comment]
Found it - `\FluidTYPO3\Flux\Integration\Overrides\PageLayoutView::getContentRecordsPerColumn`.

**Comment by fnagel** [comment]
Hey Claus, sure, here you go: https://pastebin.com/rKvytqUA

**Comment by NamelessCoder** [comment]
Perfect, thanks! Fix coming in a few seconds.

**Comment by fnagel** [comment]
Almost there :-D

Seems the `$columns` array is not empty: 

![grafik](https://user-images.githubusercontent.com/116824/57076505-2034f780-6cea-11e9-8b9f-e806fb471a80.png)

**Comment by NamelessCoder** [comment]
Curse the unsanitised input from legacy core classes... would you mind checking if adding:

```
$columns = array_filter($columns, 'is_numeric');
```

above the "empty" check solves the problem? I'm hoping this removes the empty string but won't nuke a value of `'0'`.

**Comment by fnagel** [comment]
Yes, that seems to work. No more exception but a TYPO3 alert message: 

![grafik](https://user-images.githubusercontent.com/116824/57081713-9b4fdb00-6cf5-11e9-87b7-b0a62e8724af.png)

> I'm hoping this removes the empty string but won't nuke a value of '0'.

Adding a hard coded `$columns = [0 => '0'];` before all checks won't be removed 👍

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/90cf60d526adb164841029767766af11f5a78c08
