### ISSUE TITLE
clear-Attribute/"clear value" checkbox with no effect

### ISSUE THREAD

**Issue by spackmat** [FluidTYPO3/flux#1696]
Hello,

I observed that the "clear value" checkbox enabled by the "clear" attribute of an input field has no effect in all my installations. So checking it for any field in a page configuration and saving that page changes nothing, the previous value of that field is still there and no inheritance happens. Additionally deleting the field's value before saving deletes its value, but still doesn't lead to any inheritance. A simplified example of my page template configuration setting looks like this:

    <f:section name="Configuration">
        <flux:form id="standard">
            <flux:field.input
                name="settings.aSimpleInput"
                default=""
                clear="true"
            />
            <flux:field.text
                name="settings.aTextField"
                enableRichText="true"
                rows="2"
                clear="true"
            />
        </flux:form>
    </f:section>

I would expect, that checking the "clear value" checkbox deletes the value in whole from the stored XML, so that the value of the parent page's subpages-setting gets inherited. And I am pretty sure that this worked before, when I implemented the page in TYPO3 7 LTS two years ago.

My current environment:
TYPO3 8.7.24
fluidpages 5.0.0
flux 9.2.0
vhs 5.2.0

Am I misunderstanding something?

**Comment by spackmat** [comment]
I talked to an editor about that and indeed did this work before and was used widely in several projecs, I implemented before and now stopped working with current versions mentioned above.

**Comment by NamelessCoder** [comment]
The field-clear functionality is now re-implemented in a TYPO3v10+ compatible way. The next release of Flux will restore it for all supported versions of TYPO3.
