### ISSUE TITLE
flux.form sections aren't inherited to child pages in page properties

### ISSUE THREAD

**Issue by X-Tender** [FluidTYPO3/flux#1703]
I have the following flux form in my page properties:
```html
<flux:form.section name="adformPixel" label="Adform-Pixel" >
	<flux:form.object name="pageLoad" label="Pageload-Pixel">
		<flux:field.input name="pm" label="Tracking-ID" required="1" />
		<flux:field.input name="pagename" label="Page name" required="1" />
	</flux:form.object>
</flux:form.section>
```
When I set the Data for the child pages `tx_fed_page_flexform_sub` the data is not available in the child pages. When I set teh data for the current page, it is available.
When I use a flux.input the data is inherited for the childs. So basicly the inheritance work, but not for sections.

**Comment by X-Tender** [comment]
Meanwhile I discoverd that sections didn't get inherited AFAIK Don't know if bug or feature.

**Comment by NamelessCoder** [comment]
@X-Tender have you tried this with `dev-development` of Flux? There should be no difference in terms of inheritance between normal fields and section objects...

**Comment by NamelessCoder** [comment]
Two things:

* It was alaways the case that the `inherit` attribute of `flux:form.sction` was `false` (no inheritance by default).
* Even so, enabling inheritance for a section caused potentially strange behaviors (merged inherited sections) - this issue is now solved in `dev-development`.

**Comment by stex2** [comment]
This change causes the following error in the backend when i try to open the page settings of any page in the backend:

![image](https://github.com/FluidTYPO3/flux/assets/3473044/a86d6289-7b56-4ad6-9680-260731e4a8bf)

I could fix it in my case by adding " ?? []" in PageProvider.php:302 and PageProvider.php:309, but im not much into this topic and don't know if this is sufficient for all cases.

**Comment by NamelessCoder** [comment]
@stex2 I guess that makes sense in case there are zero inherited values. I pushed a patch that should take care of it - and you were right about null coalescing ;)
