### ISSUE TITLE
[BUG][TYPO3-9.5.7]Deleted tt_content records are referenced on copy to other page

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#1704]
Hello,
We came across an error while copying content to another page:
![image](https://user-images.githubusercontent.com/9860558/59584933-97c6b680-90df-11e9-9a97-3ec2b0ef9131.png)
After a short investigation, we came to the fact that the original content and copy have a different uid than those from the message. Going further, it turned out that uid from the message are deleted=1 and are the master content for copied content. We came to the conclusion that Flux wrongly (or rightly?) does not ignore the deleted content. We decided that this line is a good starting point for this error:
https://github.com/FluidTYPO3/flux/blob/5380e40d07165a46e4da7c3d0a41d8b2eb00abfd/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php#L353

Effect: 
The content is copied correctly but an error appears which stops the page refresh procedure. This is confusing for the editor. After deleting permamently the records with flag "deleted = 1" the copying process takes place without any problem.

We are using:
Typo3: 9.5.7
Flux: 9.2.0 stable
VHS: 5.2.0

If we can still help somehow, let me know.

**Comment by hieslc** [comment]
Exactly the same problem here.

**Comment by glucka** [comment]
Thanks for the contributing. Im going to check this next week.

**Comment by nitori** [comment]
Is here potentially a regression? I'm getting exactly this error with the same steps above on TYPO3 10.4.13 with Flux 9.4.2

It seems to have been reverted in 77d66df04cec886f8d7292069e176846f8f7d486 due to issue https://github.com/FluidTYPO3/flux/issues/1745
