### ISSUE TITLE
Bug path image copy paste content

### ISSUE THREAD

**Issue by filoucrackeur** [FluidTYPO3/flux#1707]
TYPO3 9.5.8 
FLUX 9.2.0

When i copy and paste a content with images path become absolute 

![image](https://user-images.githubusercontent.com/2182548/61039900-ea8a4a00-a3cf-11e9-86c2-5053d87f9be0.png)

![image](https://user-images.githubusercontent.com/2182548/61040010-1a395200-a3d0-11e9-8a68-bab28d02e77c.png)

**Comment by NamelessCoder** [comment]
Hi @filoucrackeur,

This has to be a behavior in TYPO3 itself - Flux doesn't re-write the relations you selected, with the single exception of rewriting colPos and pid for child records when parent is moved/copied. 

You may want to report this to forge.typo3.org...

**Comment by NamelessCoder** [comment]
Closing the issue with reference to TYPO3 core. Sorry @filoucrackeur but this is outside our control!
