### ISSUE TITLE
Content element language is always resets to default after copy or move operation

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/flux#1710]
If language is set to "all"

**Comment by akiessling** [comment]
That might be a core bug: https://forge.typo3.org/issues/83533

**Comment by NamelessCoder** [comment]
Is indeed a core issue - and unfortunately still exists in TYPO3 10.2. Will close this issue (but if you find it via search, check the status of the bug in TYPO3 but following the link provided by @akiessling).
