### ISSUE TITLE
Suggestion of fludicontent_core in composer.json

### ISSUE THREAD

**Issue by Shupal** [FluidTYPO3/flux#1713]
Hi there,

first thanks for all the work on flux. Its amazing!

is there any reason to keep fluidcontent_core ext as suggestion on composer install?

`    "suggest": {
....
        "fluidtypo3/fluidcontent_core": "Gives the ability to render core content elements with pure fluid."
    },`

fluidcontent_core is still public but displaced from fluid_style_content as core ext.
fluidcontent is deprecated and archived. 

At the ext_emconf.php file there are no suggestions at all. 

So either remove the suggest part on both files or make it equal. 
Or did i miss something?

I can push a PR as well.

**Comment by markus-mueller-ka** [comment]
Vielen Dank für Ihre Nachricht. 

ich bin bis einschließlich 13. September 2019 nicht im Büro erreichbar und kann Ihre Mail nicht lesen. Ihre Mail wird nicht weitergeleitet.

In dringenden Fällen wenden Sie sich bitte an einen meiner Kollegen oder Kolleginnen oder an unsere zentrale E-Mail-Adresse support@mueller-new-media.de.

Mit freundlichen Grüßen

Markus Müller

**Comment by NamelessCoder** [comment]
Fixed by 9e6692f695d4b6433f9f3a5c26e755d76b9ddf4e
