### ISSUE TITLE
Can't create own FCE

### ISSUE THREAD

**Issue by Pekkonen** [FluidTYPO3/flux#1714]
Hi guys!
I have a problem with FLUID and can't create own FCE.
It's TYPO3 9.5.8 project but upgraded from 6.x
1. I have installed:
fluid    9.5.8
fluid_styled_content    9.5.8
flux    9.2.0
and my main ext with all templates and etc, named "Mysite"
2. I register directory for FCE in "Mysite/etc_localconf.php" as
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Myvendor.Mysite', 'Content');
3. I put simple FCE file to "Mysite/Resources/Private/Templates/Content/Test.html" with content:
```
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
      xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
      xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
      xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">
`<f:layout name="Content"/>    `
<f:section name="Configuration">
    <flux:form id="test" label="test_label" description="test_description">
        <flux:field.input name="headline" />
        <flux:field.text name="teasertext" rows="5" cols="30" required="TRUE" />
`      `
    </flux:form>
</f:section>
<f:section name="Preview">
    <table width="100%">
        <tr>
        <td width="50%">
            {headline}
            </td>
            <td width="50%">
                <f:format.crop maxCharacters="50">{teasertext}</f:format.crop>
`               `
            </td>
        </tr>
    </table>
</f:section>
<f:section name="Main">
    <div class="quickstart-teaser">
        <article>
        <h1>{headline}</h1>
`      `
        <div class="text-wrapper">
            <f:format.nl2br>{teasertext}</f:format.nl2br>
`           `
        </div>
        </article>
    </div>
</f:section>
</div>
```
4. Now I can select this Fluid content element in BE. After filled header and teaser and save it I see correct element in BE list, but see an error in FE and can't fix it!
5. FE error is:
(1/2) #1278450972 TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException
Class Myvendor\Mysite\Controller\ContentController does not exist. Reflection failed.
I don't have any classes in this extension and as I know it's no need for FCE. In other project with clean TYPO3 9 it's works like a charm...

**Comment by TimoWinkler** [comment]
I don't remember the exact reason why, but flux is looking for said ContentController in your Extension. You can create an empty controller like the one referenced by this [issue](https://github.com/FluidTYPO3/fluidtypo3org/issues/37) of fluidtypo3org
In this Issue are all files and modifications you might need in order to set up your provider extension

**Comment by Pekkonen** [comment]
I checked your solution, but unfortunately this don't work for me.
1. I already tried create this controllers before (but only ContentController) - with no success too.
2. In other site I see how FCE work without ContentController and PageController 
I'm a little bit confused of this...

**Comment by TimoWinkler** [comment]
Did your Error Message change after adding the suggested Controller?
If the message does not change maybe it is not loaded yet in the autoloader.
You could try clearing autoloading cache in the backend module or with composer if you are using a composer install.

**Comment by Pekkonen** [comment]
Hi Timi!
First, thanks for your help!
I see strange behavior of this...
Once I see correct FE page but with yellow error about problem with definition content element.
After I reloaded my extension (uninstall/install it in BE), I see again initial error:

> (1/2) #1278450972 TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException
> Class Myvendor\Mysite\Controller\ContentController does not exist. Reflection failed.
And this error still exist without changes
Also I tried clear "Flush TYPO3 and PHP Cache" in InstallTool - no result.
I created new page with new instance of this FCE - no result.
Now I always see an error about ContentController does not exist.
I don't understand logic of this behavior.
I clear cache in BE as usual too.
BTW - I don't using composer
Could you explain this "You could try clearing autoloading cache in the backend module", what kind of cache do you mean, maybe it will be a solution for me?..

**Comment by TimoWinkler** [comment]
There is a new button in the backend module Maintenance: "Rebuild PHP Autoload Information" that is responsible for Loading Classes in PHP in non composer installation.

**Comment by Pekkonen** [comment]
Thank you. Found this button, but after clean nothing changes... "ContentController does not exist."
And main problem is in I don't understand how I can debug of this problem. Where exactly is the problem.

**Comment by TimoWinkler** [comment]
The last thing I can suggest is checking your namespaces in your ContentController and directory names leading to it.
Maybe the [flux documentation](https://fluidtypo3.org/documentation/templating-manual/advanced-provider-extensions/custom-flux-controllers/creating-flux-controllers.html) for creating provider extensions can help you as well

**Comment by Pekkonen** [comment]
> The last thing I can suggest is checking your namespaces in your ContentController and directory names leading to it.
Bingo!
Thanks Timo!!
I again checked names and found an error!
Reason was in Capital letter - my extension named e.g. "my_extension"
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Myvendor.Myextension', 'Content');
instead of correct
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Myvendor.MyExtension', 'Content');
Myextension -> MyExtension -stupid error...
BTW - controllers is not need for own FCE!
