### ISSUE TITLE
flux:field.inline.fal: You must either specify a string src or a File object

### ISSUE THREAD

**Issue by Geddo** [FluidTYPO3/flux#1722]
This is my flux setup:

    <flux:form id="xxx">
    	<flux:form.option.group value="FlexibleContentElements" />
        ...
            <flux:field.inline.fal name="file" minItems="1" maxItems="1" />

And this is my preview:

    <f:section name="Preview">
            ...
           <f:if condition="{file}">
               {v:content.resources.fal(field: 'file') -> v:variable.set(name: 'test')}
               <f:debug>{test}</f:debug>
               <f:image treatIdAsReference="1" src="{file.id}" crop="{file.crop}" title="{file.title}" alt="{file.alternative}" class="img-round" maxWidth="100" maxHeight="100"/>
            </f:if>
        </f:section>

When I open a page which includes the flux-object in the backend I receive this error:
**You must either specify a string src or a File object**

So the debug results in NULL. Funny, this setup worked some time ago but with an composer update it broke :-(
I also tried the sample code from the docs from flux:field.inline.fal - same result. What I'm missing?

**Comment by MartinH0** [comment]
Had the same issue.
For me it appeared when I wanted to place a .svg image (vector image) in it.

**Comment by Geddo** [comment]
also have the issue with jpgs. sadly I also cannot see the images in the FE. Sad

**Comment by Geddo** [comment]
Solution https://github.com/FluidTYPO3/vhs/issues/1500#issuecomment-411299484
