### ISSUE TITLE
Child element lost when moving container to new page in workspace

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1723]
When moving a container element in a workspace to a new page, child elements get lost.

flux 9.2.0, TYPO3 9.5.9.

# Steps to reproduce

1. Switch to live workspace
1. Create a two pages
1. On the first page, create a container element and a child element in this container
1. Switch to some editor workspace
1. Cut container element on first page
1. Paste container element on second page
1. The child element is gone

Reason for this: In database, the container element gets a "MovePointer" and a "MovePlaceholder" record that stores the moved state in the workspace.
The child record directly gets its `pid` value changed directly without a MovePointer, presumably by `DataHandlerSubscriber::recursivelyMoveChildRecords()`.

Discarding the workspace changes does not restore the previous state; the child element stays lost.

----

I do not really know how to solve this problem.
Maybe `DataHandlerSubscriber::recursivelyMoveChildRecords()` should use TYPO3's own `DataHandler` to move the child records, which would automatically take care of [creating the MovePointer records](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Workspaces/Index.html#scenario-move-record-to-different-page).

**Comment by NamelessCoder** [comment]
> `DataHandlerSubscriber::recursivelyMoveChildRecords()`

This might be the solution, but only if it also allows us to override fields like `colPos` in the process.

**Comment by NamelessCoder** [comment]
Don't spend any effort on this - I have a fix locally that should work.
