### ISSUE TITLE
Partials in Configuration section of Flux-Elements

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#1725]
Hello there,

if I want to have a Partial in teh configuration section of a Flux-Element like `<f:render section="Form" optional="true" partial="MyPartial" optional="true" arguments="{_all}" />` erverthing works fine. But if I add an second PartialPath via TypoScript, the Partial from the second path will not load.
This Setup worked with Fluidcontent in the past.

Current CMS Data:
Typo3: 9.5.10
Flux: 9.2.0
Fluidpages: 5.0.0 

The same behavior also occurs with Fluidpages.

**Comment by NamelessCoder** [comment]
See https://github.com/FluidTYPO3/flux/issues/1671 and https://github.com/FluidTYPO3/flux/issues/1485. This is highly unlikely to be solved and cannot be solved in Flux - would have to be solved in TYPO3 core. Sorry, but we just don't have any reasonable way to make this work.
