### ISSUE TITLE
Flux field relation 

### ISSUE THREAD

**Issue by Brezelfelder** [FluidTYPO3/flux#1730]
He Flux Team,

it looks like there is a bug in the element "Relation".
In the Doku: https://fluidtypo3.org/viewhelpers/flux/master/Field/RelationViewHelper.html there is a Argument called "renderMode" - 
If you use this argument you get an error. The argument does not seem to be part of the "realtion" anymore.

An alternative could be the arguments itemListStyle and selectedListStyle - here, however, are missing information on the possible strings.

thanks for your support, 
Ralf

**Comment by Brezelfelder** [comment]
Is it fixed ?

**Comment by glucka** [comment]
@Brezelfelder see comment message "The "config" array then supports every TCA option"

**Comment by Brezelfelder** [comment]
Sorry, Thanks a lot ! @NamelessCoder @glucka
