### ISSUE TITLE
[FEATURE] Prevent an element from becoming it's own parent element.

### ISSUE THREAD

**Issue by guelzow** [FluidTYPO3/flux#1731]
"As an editor who has to handle a lot of nested elements I don't want the back end page gone, when I accidentally assign an element as it's own parent."

Acceptance criteria
- Prevent an element from becoming it's own parent (directly, or with some levels of nesting in between)

or
- Prevent the endless rendering loop

Tobi

**Comment by NamelessCoder** [comment]
Hi @guelzow,

Can you describe the actions a BE editor has to take in order to trigger this problem?

**Comment by guelzow** [comment]
Hi Claus.

You can cut/paste an element into itself.
When building many "nesting pyramides" there is a chance that this can happen.

Tobi

**Comment by guelzow** [comment]
Hi Claus.

Thanks for fixing. That is what I call fast.
😄

Tobi
