### ISSUE TITLE
New Plug and Play features throws error

### ISSUE THREAD

**Issue by MartinH0** [FluidTYPO3/flux#1733]
I'm using:
TYPO3 v10.2.2
PHP v7.4.1

I used Flux at a 2 month old development version and everything was working fine.
Now I updated to the new version (e386431a4109c22b64b0f94fe50b3c64c7e9cce2) and as soon as I updated to this version it still works, but. I did not change any settings but ran the "Analyze Database Structure" function and updated the things (just flux related things, 4 things if I remember right.)

As soon as I now call the frontend I get this at the very top of every page:

`Please select a page template in page properties.`

But the site looks good, beside this error. No broken things or anything else, and a page template was selected and has been seleted since ever.

I'm using the page-template from "bootstrap_package" btw. Hope this helps to identify the bug.

Also strange:
I did deactivate (befor rendering the page/calling the frontend) in the settings the "plug and play template thing" but the template directory structure (called "design") was still created in the public root directory.. I dont like that. I deactivate it for not creating that folder and for not using that feature as I dont need it.

I reverted back to the version befor, this one is working fine. I think it is (c19b676ed9cb07a5eedefc2e28a2483ef5e7e7aa)
[flux-development.zip](https://github.com/FluidTYPO3/flux/files/4007769/flux-development.zip)

**Comment by NamelessCoder** [comment]
Do you still have Fluidpages installed?

Does the `design` folder appear again after disabling the setting and deleting the folder?

**Comment by NamelessCoder** [comment]
The `Please select a page template` warning should be possible to remove by adding TS:

`page.5 >`

anywhere in your TS template.

**Comment by NamelessCoder** [comment]
See tip above for removing the message "Please select a page template in page properties" message; for reasons of compatibility the `design` folder will be created automatically, but you can delete it again after disabling the "Plug and play templates" feature. The folder will be created by Flux in any request, including the view where you deactivate the setting - so the only way to truly avoid it being created is when deploying a site where the setting is disabled right from the start.
