### ISSUE TITLE
File field and FAL fields don't work in TYPO3 10.2.2 and Flux 9.2

### ISSUE THREAD

**Issue by geronimoooo** [FluidTYPO3/flux#1734]
I was trying to get a new page up and running on TYPO3 10.2.2 and flux 9.2.0.
I need content elements with images, so I first tried to port some content elements using <flux:field.file> Field, which is deprecated [[1]](https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Group.html#internal-type)[[2]](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Deprecation-86406-TCATypeGroupInternal_typeFileAndFile_reference.html):

> TCA internal_type of field "image.imageLarge" in table tt_content must be set to "db" or "folder".

After that, I tried to use FAL fields for images but unfortunately, the TCA configuration seems to be wrong and the "select" button of the FAL field opens a database record browser, not a file browser. After digging in the TCA and comparing the Flux TCA to the TCA generated by \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getFileFieldTCAConfig, I came up to a hotfix that seems to work for the moment:

Everything is in flux/Classes/Form/Field/Inline/Fal.php:

Replace Line 171 - 181 with the following:
```
        $configuration['overrideChildTca'] = [  
            'columns' => [  
                'uid_local' => $configuration['foreign_selector_fieldTcaOverride']  
            ],  
            'types' => $configuration['foreign_types']  
        ];  
        if (!empty($this->cropVariants)) {  
            $configuration['overrideChildTca']['columns']['crop'] = [  
                'config' => [  
                    'cropVariants' => $this->cropVariants  
                ]  
            ];  
        }  
```
[Downloads Fal.php with hotfix included](https://github.com/FluidTYPO3/flux/files/4032785/Fal.php.zip)

After that, the FAL field is working again, BUT it's not possible to use names containing a dot, for examle "image.large" as fieldname won't work, "imageLarge" will work.

That's why I suggest to remove the <flux:field.file> fieldtype as it is deprecated and to update the TCA structure of the <flux:field.inline.fal> fieldtype. Also, as FAL fields can't be nested inside sections, there is currently no way convenient way to create elements like sliders, team-listings and so on.

<img width="636" alt="Bildschirmfoto 2020-01-07 um 22 44 46" src="https://user-images.githubusercontent.com/7362999/71935828-b8e81500-319f-11ea-90ac-8920745da2c7.png">

Thank you flux team for all your effort - I love to use flux and hope to see the FAL field working again in future versions :-)

**Comment by cweiske** [comment]
Related: #1803
