### ISSUE TITLE
flux 9.3.0 installation error

### ISSUE THREAD

**Issue by infabo** [FluidTYPO3/flux#1735]
`composer create-project typo3/cms-base-distribution my-new-project ^9.5`

`cd my-new-project`

`ddev config`

setup wizard of TYPO3 to finish first installation.

`ddev composer req fluidtypo3/flux`

`ddev exec vendor/bin/typo3 extension:install flux`

produces following error:

`Uncaught TYPO3 Exception The "/var/www/html/public/design/Templates/Content/" directory does not exist.
thrown in file /var/www/html/vendor/symfony/finder/Finder.php
in line 602
`

**Comment by infabo** [comment]
![image](https://user-images.githubusercontent.com/3999104/73561626-991fd600-4459-11ea-9c68-ad985b017867.png)

**Comment by infabo** [comment]
`$ ddev exec vendor/bin/typo3cms cache:flush

                                                                                  
  [ Helhum\Typo3Console\Core\Booting\StepFailedException ]                        
  The "/var/www/html/public/design/Templates/Content/" directory does not exist.  
                                                                                  

Caused by:
                                                                                  
  [ Symfony\Component\Finder\Exception\DirectoryNotFoundException ]               
  The "/var/www/html/public/design/Templates/Content/" directory does not exist.  
                                                                                  

cache:flush [--files-only]

Failed to execute command vendor/bin/typo3cms cache:flush: exit status 1`

**Comment by infabo** [comment]
` mkdir -p public/design/Templates/Content/` to get around.

Now there is no mention in README, that you HAVE TO setup a site-configuration. If you do not - the content element wizard is broken and just keeps spinning.

![image](https://user-images.githubusercontent.com/3999104/73561881-2f53fc00-445a-11ea-808f-455dbaa884a3.png)

**Comment by infabo** [comment]
Once you have setup a site confguration you can go further.

But where is the sample flux CE?

![image](https://user-images.githubusercontent.com/3999104/73561959-5d394080-445a-11ea-99d5-983a9058b3d6.png)

**Comment by infabo** [comment]
And even stranger: why are there any page layouts available?

![image](https://user-images.githubusercontent.com/3999104/73562001-780bb500-445a-11ea-8981-4a53d8c09110.png)

**Comment by infabo** [comment]
![image](https://user-images.githubusercontent.com/3999104/73562194-e8b2d180-445a-11ea-81a8-4849185170cf.png)

But design folder still not initialized.

**Comment by infabo** [comment]
```
$ ddev exec vendor/bin/typo3 extension:install flux

                                                                                                       
 [OK] Activated extension flux successfully.      ```

**Comment by infabo** [comment]
Give up for now. As I try to set it up for about an hour now. It is not plug&play and not up and running within minutes.

**Comment by NamelessCoder** [comment]
Sorry about the failures - looks like I should have run One More Test (TM) from a completely blank state after adding the last feature. Should be fixed now in `dev-development` and I'll follow up with a bug fix release tomorrow (change log generator is limited to one release per day).

**Comment by TrueType** [comment]
yeah, got right into it. fixed with dev-development.

**Comment by NamelessCoder** [comment]
9.3.1 is now released, containing the fixes for issues reported here!

**Comment by infabo** [comment]
I am too dumb for using ext:flux. Still no page layouts available in backend - but on the filesystem there is one. I don't get it. And no dataproviders in site configuration as well empty.
