### ISSUE TITLE
flux 9.3.0 flux:form.option.icon value is ignored

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/flux#1738]
I see in backend always the the default /typo3conf/ext/flux/Resources/Public/Icons/Plugin.png

**Comment by NamelessCoder** [comment]
@glucka Couple of questions:

* What is the value you enter in the `icon`setting?
* Where is the template file located (extension, drop-in, record-based, other?)

If you use a custom icon then the `icon` option value should be an `EXT:...` formatted path - for templates that exist within an extension I'd recommend using the automatic lookup: if the template file is named `MyContent.html` then the icon Flux will look for, should be placed in `$yourExtensionFolder . '/Resources/Public/Icons/Content/MyContent.svg` (also supported are `png` and `gif` file types but of course `svg` looks best).

**Comment by glucka** [comment]
I use
`<flux:form.option.icon value="EXT:theme/Resources/Public/Icons/Content/Default.svg"/>`
Intresting because it works with 9.5.12 an flux 9.1

**Comment by NamelessCoder** [comment]
That should definitely work - that's the format I tested a few hours ago. I tested with a template file located in an extension and a drop-in template file, both are working for me (new content wizard and page view in backend). I'm in the process of tagging 9.3.2 which fixes an issue with some types of Flux form ViewHelpers, perhaps that will fix the issue...

**Comment by NamelessCoder** [comment]
Release is done, please test this again ;)

**Comment by glucka** [comment]
Definitely work again! ;) Thx!

**Comment by NamelessCoder** [comment]
Great, seems this was becasue `renderStatic` was not called on `OptionViewHelper` because of the `callRenderMethod` problem I fixed in https://github.com/FluidTYPO3/flux/commit/70642e3f5ec4ddd10756ddd3ccaaa3e55e23d46e. Thanks for testing so quickly!

**Comment by VivekNitsan** [comment]
`<flux:form.option.icon value="EXT:pg_bea_theme/Resources/Public/Icons/Example.svg"`  used this in my custom extension but not working in typo3 v11 is there any solution

**Comment by boettner-it** [comment]
Yes, you will have to use the Icon API:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Icon/Index.html

And then the key you registered your icon with. Like in the first code block in the docs
`<flux:form.option.icon value="mysvgicon"`
