### ISSUE TITLE
 Could not ultimately dispatch the request after 101 iterations

### ISSUE THREAD

**Issue by typo3rel** [FluidTYPO3/flux#1741]
Hi,
i installed flux 9.3, 9.3.1 and 9.3.2 on Typo3 9.5.13 with composer and i got:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1217839467: Could not ultimately dispatch the request after 101 iterations. Most probably, a @TYPO3\CMS\Extbase\Annotation\IgnoreValidation annotation is missing on re-displaying a form with validation errors. | TYPO3\CMS\Extbase\Mvc\Exception\InfiniteLoopException thrown in file ***public/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php in line 69.`

flux 9.2 is ok

thx

**Comment by NamelessCoder** [comment]
Hi @typo3rel,

I'm not sure this is related to Flux, it sounds like an error from the Extbase controller dispatcher trying to call a (custom?) controller action that isn't correctly annotated. The controller that ships with Flux should be correctly annotated in all actions that are called by the framework.

Can you see from the stack trace which controller class is causing this problem?

**Comment by typo3rel** [comment]
Hi,
thanks for your quick reply. Its a relatively fresh intallation without an provider extension. 

composer:
```        "config": {
                "platform": {
                        "php": "7.2"
                }
        },
        "require": {
                "helhum/typo3-console": "^5",
                "typo3/minimal": "^9.5",
                "typo3/cms-about": "^9.5",
                "typo3/cms-adminpanel": "^9.5",
                "typo3/cms-belog": "^9.5",
                "typo3/cms-beuser": "^9.5",
                "typo3/cms-felogin": "^9.5",
                "typo3/cms-fluid-styled-content": "^9.5",
                "typo3/cms-form": "^9.5",
                "typo3/cms-impexp": "^9.5",
                "typo3/cms-info": "^9.5",
                "typo3/cms-redirects": "^9.5",
                "typo3/cms-reports": "^9.5",
                "typo3/cms-rte-ckeditor": "^9.5",
                "typo3/cms-setup": "^9.5",
                "typo3/cms-seo": "^9.5",
                "typo3/cms-sys-note": "^9.5",
                "typo3/cms-t3editor": "^9.5",
                "typo3/cms-tstemplate": "^9.5",
                "typo3/cms-viewpage": "^9.5",
                "georgringer/news": "^7",
                "fluidtypo3/vhs": "^6",
                "svewap/ws-scss": "^1.1",
                "friendsoftypo3/tt-address": "^5.0"
        },
        "scripts":{
                "typo3-cms-scripts": [
                        "typo3cms install:fixfolderstructure",
                        "typo3cms install:generatepackagestates",
                        "typo3cms database:updateschema"
                ],
                "post-autoload-dump": [
                        "@typo3-cms-scripts"
                ]
        }
```

if i add flux 9.3+ i get this error

`Stack trace:\n#0 /var/www/test/public/typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php(92): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#1 /var/www/test/public/typo3/sysext/extbase/Classes/Core/Bootstrap.php(172): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#2 /var/www/test/public/typo3/sysext/extbase/Classes/Core/Bootstrap.php(159): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#3 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#4 /var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(5983): call_user_func_array(Array, Array)\n#5 /var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(41): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#6 /var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(816): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#7 /var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(732): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#8 /var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(678): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array, '5')\n#9 /var/www/test/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(246): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#10 /var/www/test/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(268): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageContent(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController))\n#11 /var/www/test/public/typo3/sysext/frontend/Classes/Http/RequestHandler.php(168): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageContentWithHeader(Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController), NULL)\n#12 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/OutputCompression.php(46): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#13 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Frontend\\Http\\RequestHandler))\n#14 /var/www/test/public/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelDataPersister.php(44): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#15 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelDataPersister->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#16 /var/www/test/public/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelRenderer.php(46): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#17 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelRenderer->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#18 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/ContentLengthResponseHeader.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#20 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php(65): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#21 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#22 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/PrepareTypoScriptFrontendRendering.php(118): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#23 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#24 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/PageArgumentValidator.php(99): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#25 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#26 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/MaintenanceMode.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#27 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#28 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/PageResolver.php(170): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#29 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#30 /var/www/test/public/typo3/sysext/redirects/Classes/Http/Middleware/RedirectHandler.php(70): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#31 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Redirects\\Http\\Middleware\\RedirectHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#32 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/StaticRouteResolver.php(66): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#33 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#34 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/SiteBaseRedirectResolver.php(86): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#35 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#36 /var/www/test/public/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelInitiator.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#37 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelInitiator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#38 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/SiteResolver.php(68): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#39 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#40 /var/www/test/public/typo3/sysext/adminpanel/Classes/Middleware/SqlLogging.php(49): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#41 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\SqlLogging->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#42 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/BackendUserAuthenticator.php(95): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#43 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#44 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/FrontendUserAuthenticator.php(79): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#45 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#46 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/TypoScriptFrontendInitialization.php(90): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#47 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#48 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/EidHandler.php(50): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#49 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#50 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/PreprocessRequestHook.php(57): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#51 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PreprocessRequestHook->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#52 /var/www/test/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#53 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#54 /var/www/test/public/typo3/sysext/frontend/Classes/Middleware/TimeTrackerInitialization.php(49): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#55 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#56 /var/www/test/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#57 /var/www/test/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#58 /var/www/test/public/typo3/sysext/frontend/Classes/Http/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#59 /var/www/test/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\\CMS\\Frontend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#60 /var/www/test/public/index.php(24): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#61 /var/www/test/public/index.php(25): {closure}()\n#62 {main}"}`

thank you

**Comment by NamelessCoder** [comment]
Can you dump the arguments array in: `/var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(41)`?

**Comment by NamelessCoder** [comment]
I'm not completely sure about this, but adding `page.5 >` to your root TS template might get rid of the problem.

**Comment by typo3rel** [comment]
`page.5 >` this solves the problem

**Comment by NamelessCoder** [comment]
Thanks for the feedback and report @typo3rel. I'll consider a way to make this part of the integration work smoother, seems that about 50/50 of users don't use fluid page templating and have no use for this part of the integration - making it less "invasive" would help that half without hurting the other.

**Comment by typo3rel** [comment]
> Can you dump the arguments array in: `/var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(41)`?

`$tempContent = $this->cObj->callUserFunction($conf['userFunc'], $conf, '');
        var_dump($conf['userFunc']);`
this one?
```
string(37) "TYPO3\CMS\Extbase\Core\Bootstrap->run"
string(37) "TYPO3\CMS\Extbase\Core\Bootstrap->run"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
```

**Comment by NamelessCoder** [comment]
In this case the `$conf` variable would probably contain a hint that Flux's PageController was to blame, which in turn points toward the automatic TS that gets included with index `.5` which seems to be the core of the problem. That would be one of the first two items in that list.

**Comment by typo3rel** [comment]
> > Can you dump the arguments array in: `/var/www/test/public/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(41)`?
> 
> `$tempContent = $this->cObj->callUserFunction($conf['userFunc'], $conf, ''); var_dump($conf['userFunc']);`
> this one?
> 
> ```
> string(37) "TYPO3\CMS\Extbase\Core\Bootstrap->run"
> string(37) "TYPO3\CMS\Extbase\Core\Bootstrap->run"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> string(62) "TYPO3\CMS\Frontend\DataProcessing\MenuProcessor->getDataAsJson"
> ```
this was made with page.5 >
and this without
```
array(4) { ["userFunc"]=> string(37) "TYPO3\CMS\Extbase\Core\Bootstrap->run" ["extensionName"]=> string(4) "Flux" ["vendorName"]=> string(10) "FluidTYPO3" ["pluginName"]=> string(4) "Page" } 
```
and then the error occurs

Thank you very much

**Comment by NamelessCoder** [comment]
That completely explains the problem - thanks for confirming!
