### ISSUE TITLE
Exception when editing FCEs if there is anything listed in [flux_content_types] Selected Items 

### ISSUE THREAD

**Issue by vistainteractive** [FluidTYPO3/flux#1744]
When Available content types (empty selection means allow-all)[flux_content_types] Selected Items in Site Configuration contains any values, then editing a flux content element crashes with the error:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Invalid argument supplied for foreach() in ....typo3conf/ext/flux/Classes/Integration/FormEngine/ProviderProcessor.php line 36

Leaving [flux_content_types] Selected Items blank enables editing of the content element as normal. 

TYPO3 9.5.14
Flux 9.3.2

**Comment by NamelessCoder** [comment]
If `$result['processedTca']['columns']['CType']['config']['items']` is not an array this probably points to another issue. Is the `CType` field disabled in your content type, or is access somehow prevented through user permissions, or are you running the site with a custom "content rendering" extension as replacement for `fluid_styled_content`? Just asking so I can attempt to replicate this locally and/or give solution suggestions ;)

**Comment by vistainteractive** [comment]
The site is using fluid_styled_content. It was happening on an admin user login so there were no user permission restrictions and the CType field is not disabled. 

Extensions used:
cal
ke_search
news
powermail
and our own custom extension using Flux to implement the UIKIT css framework.

**Comment by NamelessCoder** [comment]
Unfortuantely I'm still unable to reproduce this. Can you provide more information, e.g. what is the actual value of `$result['processedTca']['columns']['CType']['config']['items']` if it is not an array?

**Comment by NamelessCoder** [comment]
Solved by guard clauses; the data type of the Site configuration field is not consistent on all TYPO3 versions so additional checks were required.
