### ISSUE TITLE
Using f:translate in the Configuration section

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#1746]
Hello,

the usage of `{f:translate(key: 'myKey', extensionName: 'MyExt')}` causes:
```
Return value of TYPO3\CMS\Extbase\Utility\LocalizationUtility::getLanguageService() must be an instance of TYPO3\CMS\Core\Localization\LanguageService, null returned
```
The ´{f:translate}´ viewhelper is used in labels and select field options

Is there something to keep in mind while migrating from Flux 9.2.0 to 9.3.2?

Typo3 10.3.0
Flux 9.3.2

**Comment by NamelessCoder** [comment]
You should not use `f:translate` in the configuration section - instead, use `LLL:EXT...` references which are fully supported by TYPO3 for field labels, select option values and so on.

**Comment by nirmalyamondal** [comment]
Changing here works for me typo3\sysext\extbase\Classes\Utility\LocalizationUtility.php
/**
     * @return \TYPO3\CMS\Core\Localization\LanguageService
     */
    protected static function getLanguageService(): LanguageService
    {
        //return $GLOBALS['LANG'];
        //return ‪$GLOBALS['LANG'] ?: ‪LanguageService::create('default');
        return LanguageService::create('default');
    }
}`
