### ISSUE TITLE
Wrong sys_language_uid with flux:field.inline.fal

### ISSUE THREAD

**Issue by Tomowok** [FluidTYPO3/flux#1749]
Hello,

In a other language than the default (sys_language_uid = 1), when i add a new relation to a file (i'm not in translation mode, i use custom values) :
	- In a flux content with flux:field.inline.fal : the sys_file_reference record is created with the sys_language_uid = 0
	- In page properties, ressources tab : the sys_file_reference record is created with the sys_language_uid = 1

If an editor doesn't have right for the default language, he can't see the content. The following message is shown :

Sorry, you didn't have proper permissions to perform this change.
ERROR: Language was not allowed.

Can you reproduce this issue or maybe i missed something...

- TYPO3 v9.5.14
- Flux v9.3.2

**Comment by Tomowok** [comment]
Any news about this issue ?
Same thing with TYPO3 9.5.19 & Flux 9.4.0

In addition, if i add the relation to a file directly with my user (no right for the default language), the sys_file_reference record is created with the sys_language_uid = -1

**Comment by NamelessCoder** [comment]
@Tomowok This sounds like a problem that is outside of Flux's control. Flux only creates the data structure array that TYPO3 uses to display the editing form and process relations - and this data structure does not contain any settings to enforce a specific language. Normally the language would be determined by TYPO3 based on the record that contains the IRRE FAL field - if this does not work within FlexForms like it does with root-level TCA fields then I have to assume this is a bug in TYPO3.

I suggest reporting this on https://forge.typo3.org (and maybe search through the bug-tracker issues to check if it is a known problem, there may be a workaround).
