### ISSUE TITLE
Flux 9.3.2 Wrong Partials are used

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#1750]
Hello,

in the new Version of Flux (9.3.2) is it no possible to add partial paths.

even a direct override in the `protected function initializeView(ViewInterface $view)` method of the `AbstractFluxController` has no effect on the rendering (this worked in flux 9.2.0).

The TypoScript is loaded and all of the path are visible in the TypoScript Object Browser.
This includes the view part of my Template Povider extension and the view part of tx_flux.
The tx_flux typoscript object is also feeded by my ext_localconf.php (with `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptSetup`) with the same partail paths as my provider extension.

Is there an other method of telling flux wich partail parts it should use?

Update:

code from AbstractFluxController->initializeView
```
        $renderingContext->setTemplatePaths(
            $this->objectManager->get(TemplatePaths::class, $extensionKey)
        );
```

I checked the result of `$this->objectManager->get(TemplatePaths::class, $extensionKey)`. The partial Paths are wrong, not in the corrent order.

What I need to archiv:

setup.typoscript
```
plugin.tx_myext {
	view {
		templateRootPaths.0 = {$plugin.tx_myext .view.templateRootPaths.0}
		partialRootPaths { 
					0 = EXT:mylib/Resources/Private/Partials/
					1 = {$plugin.tx_myext.view.partialRootPaths.0}
		}
		layoutRootPaths.0 = {$plugin.tx_myext.view.layoutRootPaths.0}
	}
}
```

not matter what I do I was not able to overwrite the partialRootPaths.0, even if I code the paths direclty into AbstractFluxController->initializeView (the var_dump) shows the corrent order but the renderresult not.

The only thing that works is:
Rename the partial folder of `myext` to something like `Partials2` then adjust the Paths in the TS-Config and the result is as it has to be.
The `TypoScript Object Browser` shows now 2 entries, but a vardump of $this->objectManager->get(TemplatePaths::class, $extensionKey) returns 3 entrie.
The Fist postition is the Partialpath I can't overwrite, the second from `mylib` and the third from `myext`

For some reason it is not possible to overwrite the default partial path of an extension.

**Comment by NamelessCoder** [comment]
Flux, like any other TYPO3 extension using Extbase's ConfigurationManager, is affected by limitations of the ConfigurationManager when reading TypoScript. See https://github.com/FluidTYPO3/flux/issues/1671 for a more detailed explanation.

**Comment by Cyasi** [comment]
@MediKathi hey ex-colleague and greetings from austria!
Do you have a solution? Having the exact same issue here.

**Comment by MediKathi** [comment]
@Cyasi The only working workaround I found so far is:
Renameing the `Partial` folder so something like `PartialExtension` and use this path of this Folder as PartialPath for the Extension.

It seams that is currently not possible to change the Base PartialPath of an extension, it will always use EXT:myext/Resources/Private/Partials/ as path 0
There is no way to use EXT:mylib/Resources/Private/Partials/ as path 0

I was not able to overwrite the path 0, all atemps to do so in TypoScript and PHP failed. I don't know if this is a bug or a feature of Typo3

In short:
Use the default PartialPath for the Libary EXT:mylib/Resources/Private/Partials/ 
For the Extension which uses the Libary change its Partial Folder to something else then Partials for example `ExtPartials`

The config for the extension should be something like:

```
plugin.tx_myext {
	view {
		templateRootPaths.0 = {$plugin.tx_myext .view.templateRootPaths.0}
		partialRootPaths { 
					0 = EXT:mylib/Resources/Private/Partials/
					1 = EXT:myext/Resources/Private/ExtPartials/
		}
		layoutRootPaths.0 = {$plugin.tx_myext.view.layoutRootPaths.0}
	}
}
```

The Extension will still serach in EXT:myext/Resources/Private/Partials/ but the folder does not exist and it will continue in ExtPartials

**Comment by Cyasi** [comment]
ok thank you, this is exactly what i did already. I hoped you would have found a more elegant solution, because this is more a temporal solution.
Hope this will be fixed in the core.

**Comment by NamelessCoder** [comment]
Closing issue - for more information about how Flux expects template files to be located, see https://github.com/FluidTYPO3/flux/issues/1485#issuecomment-1305660431
