### ISSUE TITLE
SysFolders in the first level are not accessible -> Tried resolving a template file...

### ISSUE THREAD

**Issue by eckonator** [FluidTYPO3/flux#1753]
TYPO3 9.5.14
PHP 7.2
Flux 9.3.2
Fluidpages 5.0.0

SysFolders in the first level (on the same level as root pages with globe icon) are not accessible via web module. An error is displayed that no template is found:

 `TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException`

`Tried resolving a template file for controller action "Page->default" in format ".html", but none of the paths contained the expected template file (). The following paths were checked: /var/www/birco/public_html/typo3conf/ext/fluidpages/Resources/Private/Templates/`

SyFolders on second level working fine...

I think it results from the fact that there is no TypoScript Root Tempalte above this point. In this case a fallback should be implemented.

![bug](https://user-images.githubusercontent.com/13748683/76407494-b6ff2580-638b-11ea-86a8-0c27b7afd671.png)

**Comment by NamelessCoder** [comment]
I'm not able to reproduce this issue, but it looks like you are using Fluidpages. I suggest that you migrate to Flux 9.3+ (and uninstall Fluidpages) - Flux provides a default template file for the Page controller.

**Comment by NamelessCoder** [comment]
Unable to reproduce on any currently supported TYPO3 version with Fluidpages not installed. Please uninstall Fluidpages to solve this problem. Upcoming 9.4 of Flux will display this as a FlashMessage warning instead of allowing the exception to be thrown.

**Comment by NamelessCoder** [comment]
The linked patch should make migration after uninstalling Fluidpages a lot easier.
