### ISSUE TITLE
Issue with adding content in columns, depends on colPos

### ISSUE THREAD

**Issue by buepro** [FluidTYPO3/flux#1755]
# Environment
- TYPO3 9.5.9
- flux 9.3.2
- bootstrap_package 11.0.2
- gridelements 9.5.0

# Bug description

It was found that the new content element wizard doesn't load fully when the `colPos`-values are 101 and 102 in a two columns grid. When the values are 1 and 2 it works fine. 

## Template working fine:
```
<f:section name="Configuration">
    <flux:form id="testColumns" label="Test columns" />
    <flux:grid>
        <flux:grid.row>
            <flux:grid.column name="column1" colPos="1" label="Column 1" />
            <flux:grid.column name="column2" colPos="2" label="Column 2" />
        </flux:grid.row>
    </flux:grid>
</f:section>
```

## Template having problems:
```
<f:section name="Configuration">
    <flux:form id="testColumns" label="Test columns" />
    <flux:grid>
        <flux:grid.row>
            <flux:grid.column name="column1" colPos="101" label="Column 1" />
            <flux:grid.column name="column2" colPos="102" label="Column 2" />
        </flux:grid.row>
    </flux:grid>
</f:section>
```

**Comment by NamelessCoder** [comment]
Values of colPos must be between 0 and 99; higher or lower values cause failures in calculating the parent UID.

**Comment by buepro** [comment]
Thank you very much Claus! Greetings, Roman
