### ISSUE TITLE
tt_content colPos dropdown options

### ISSUE THREAD

**Issue by buepro** [FluidTYPO3/flux#1756]
This might be related to issue #1593

## Environment
- TYPO3 9.5.9
- bootstrap_package 11.1
- gridelements 9.5.0
- Flux 9.3.2

## Error description
Without flux beeing installed `colPos` with value 10 is shown correctly:

![no_flux-colPos](https://user-images.githubusercontent.com/37214997/77044950-9e60c200-69c0-11ea-9e16-203a2ceed35c.jpg)

After installing flux it looks as following:

![flux-colPos](https://user-images.githubusercontent.com/37214997/77045316-39f23280-69c1-11ea-8dc1-34b69b57b6bc.jpg)

**Comment by buepro** [comment]
It looks like something goes wrong with resolving the page provider. Actually in my setup just content element templates are used (page templates are not registered in `ext_localconf.php`). As well the flux configurations `autoload` and `plugAndPlay` are disabled and the static template isn't included.

When adding `false &&` to the first condition as showed below the colPos-list is correct.

`Classes/Integration/Overrides/BackendLayoutView.php`

```
public function getSelectedBackendLayout($pageId)
    {
        if (false && $this->addingItemsForContent) {
            $pageRecord = $this->loadRecordFromTable('pages', (int)$pageId);
            if (!$pageRecord) {
                return null;
            }
            $pageLevelProvider = $this->resolvePrimaryProviderForRecord('pages', $pageRecord);
            if ($pageLevelProvider instanceof GridProviderInterface) {
                return $pageLevelProvider->getGrid($pageRecord)->buildExtendedBackendLayoutArray(0);
            }
        }
        // Delegate resolving of backend layout structure to the Provider, which will return a Grid, which can create
        // a full backend layout data array.
        if ($this->provider instanceof GridProviderInterface) {
            return $this->provider->getGrid($this->record)->buildExtendedBackendLayoutArray(
                $this->resolveParentRecordUid($this->record)
            );
        }
        return parent::getSelectedBackendLayout($pageId);
    }
```

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/6f6a64e89623dde2e3080e4e28ac28333e479e0b
