### ISSUE TITLE
Unconsistent content element order

### ISSUE THREAD

**Issue by buepro** [FluidTYPO3/flux#1759]
## Enironment
- TYPO3: 9.5
- flux: 9.3.2

## Description
On two different Servers with the same TYPO3 and flux version the order from the flux content elements various:

**Server 1:**

![FluxIssue-ncew1](https://user-images.githubusercontent.com/37214997/78023799-9822fc00-7357-11ea-9b36-f2072fb6f3da.jpg)

**Server 2:**

![FluxIssue-ncew2](https://user-images.githubusercontent.com/37214997/78023807-9ce7b000-7357-11ea-81c0-c10d890344e0.jpg)

## Improvement
This could be fixed by adding a sorting in the method `registerProviderExtensionKey` from `\FluidTYPO3\Flux\Core` as following:

Current:
```
$contentTypeManager = GeneralUtility::makeInstance(ContentTypeManager::class);
$finder = Finder::create()->in($templateRootPath)->name('*.html');
foreach ($finder->files() as $file) {
```

With sorting:
```
$contentTypeManager = GeneralUtility::makeInstance(ContentTypeManager::class);
$finder = Finder::create()->in($templateRootPath)->name('*.html')->sortByName();
foreach ($finder->files() as $file) {
```

**Comment by NamelessCoder** [comment]
Implementing sorting here would be fine - would you like to prepare a pull request? :)
