### ISSUE TITLE
Flux 9.3.2 "automatic mode" completly blocks and destroys backend access with Exception!

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1760]
The "default mode" using /design activated by default completly destroys and locks up TYPO3 Backend. I don't think it's a  good idea to do this! This mode automatically tries to setup/create some files and folders at root level - which can be annyoing and junk up document-root.

I'm trying to migrate site-package extension providing some FCEs. This behaviour is really annoying as I don't even can access Install-Tool nor Extension-Manager at all every time getting this:

```
(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Content->tStandard" in format ".html", but none of the paths contained the expected template file (.../public/design/Templates/Content/t/Standard.html). The following paths were checked: .../public/typo3conf/ext/flux/Resources/Private/Templates/,.../public/design/Templates/
```
I also don't understand why there is '/t/' in the path at all. Things like this completly locking up backend should never ever happen or be activated by default!

**Comment by NamelessCoder** [comment]
@typoworx-de Sorry for the inconvenience - can you provide the full stack trace which causes this error?

Re: access to install tool you should be able to access it by calling it directly instead of attempting to access it through the backend. This should work regardless of which extension might throw an error that breaks the backend.

**Comment by typoworx-de** [comment]
I actually manually disabled plugAndPlay-Mode in the LocalConfiguration.php. I don't think this mode should be enabled by default, as it's junking up document-root with "design" folder structure which may not be wanted/needed. I think this feature can be nice - but should be optionally made available (plugAndPlay to "false" instead of "true").

**Comment by NamelessCoder** [comment]
Feature disabled by default. Template resolving problem covered in https://github.com/FluidTYPO3/flux/issues/1757.
