### ISSUE TITLE
columns from PageTS BackendLayout are not populated

### ISSUE THREAD

**Issue by jonaseberle** [FluidTYPO3/flux#1762]
In TYPO3 9.5.15 with `fluidtypo3/flux` dev-development, 9.2.0 and 9.3.2 the default columns are not added from PageTS `mod.web_layout.BackendLayouts`.

![image](https://user-images.githubusercontent.com/1678001/79484649-472c2c80-8014-11ea-80e9-bc68ba890386.png)

The columns shown are the default ones from `EXT:frontend`. 

`flux` overrides the default `itemProcFunc` in `EXT:flux/Configuration/TCA/Overrides/tt_content.php`:

    $GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFunc'] =
      \FluidTYPO3\Flux\Integration\Overrides\BackendLayoutView::class . '->colPosListItemProcFunc';

In there it calls `\TYPO3\CMS\Backend\View\BackendLayoutView::colPosListItemProcFunc` but that returns an empty array in that context.

Deactivating `flux` shows the column names (and the default `colPosListItemProcFunc` works as expected).

NB:
I registered flux for "Content" only 

    \FluidTYPO3\Flux\Core::registerProviderExtensionKey('Vendor.MyExt', 'Content');

**Comment by michael-binder** [comment]
I think this is related to #1756 and #1593 

I have the same behavior in my project and I also use PageTS BackendLayouts.

Here is a blog post that also describes a similar problem (only in german) https://blog.t3bootstrap.de/2019/12/spalten-auswahl-im-element-wird-nicht-korrekt-befuellt/

My first workaround that works is a combination of the solutions described in the other tickets. But I don't know if there are any side effects

Changes are all in "Classes/Integration/Overrides/BackendLayoutView.php"
Insert `parent::initializeDataProviderCollection();`: 
```
protected function initializeDataProviderCollection()
{
  // This is an override designed to perform no operations except create a valid data provider collection instance
  $this->setDataProviderCollection(GeneralUtility::makeInstance(DataProviderCollection::class));

  parent::initializeDataProviderCollection();
}
```

Add `false && `  to the first condition
```
public function getSelectedBackendLayout($pageId)
    {
        if (false && $this->addingItemsForContent) {
            $pageRecord = $this->loadRecordFromTable('pages', (int)$pageId);
            if (!$pageRecord) {
                return null;
            }
            $pageLevelProvider = $this->resolvePrimaryProviderForRecord('pages', $pageRecord);
            if ($pageLevelProvider instanceof GridProviderInterface) {
                return $pageLevelProvider->getGrid($pageRecord)->buildExtendedBackendLayoutArray(0);
            }
        }
        // Delegate resolving of backend layout structure to the Provider, which will return a Grid, which can create
        // a full backend layout data array.
        if ($this->provider instanceof GridProviderInterface) {
            return $this->provider->getGrid($this->record)->buildExtendedBackendLayoutArray(
                $this->resolveParentRecordUid($this->record)
            );
        }
        return parent::getSelectedBackendLayout($pageId);
    }
```

**Comment by michael-binder** [comment]
Thanks for the fast fix, but this does not work. I've tested it with a new installed TYPO3 v8 and v9 with the Introduction Package. The PageTS BackendLayouts are not loaded. 

And i've figured out, that the return in this early step breaks my Flux Content-Elements. I still don't know if I have an an exotic setup or if I miss I miss some configuration for Flux? Here is my patch which works for me:
```
--- Classes/Integration/Overrides/BackendLayoutView.php	(revision ba879b29fd3ab6c03d462536c635ffd3f3c1f922)
+++ Classes/Integration/Overrides/BackendLayoutView.php	(date 1587992401054)
@@ -42,6 +42,8 @@

     protected function initializeDataProviderCollection()
     {
+        parent::initializeDataProviderCollection();
+
         // This is an override designed to perform no operations except create a valid data provider collection instance
         $this->setDataProviderCollection(GeneralUtility::makeInstance(DataProviderCollection::class));
     }
@@ -63,6 +65,21 @@

     public function getSelectedBackendLayout($pageId)
     {
+        $identifier = $this->getSelectedCombinedIdentifier($pageId);
+
+        // Delegate resolving of backend layout structure to the Provider, which will return a Grid, which can create
+        // a full backend layout data array.
+        if ($this->provider instanceof GridProviderInterface) {
+            return $this->provider->getGrid($this->record)->buildExtendedBackendLayoutArray(
+                $this->resolveParentRecordUid($this->record)
+            );
+        }
+
+        // Early return parent method's output if selected identifier is not from Flux
+        if (substr($identifier, 0, 6) !== 'flux__') {
+            return parent::getSelectedBackendLayout($pageId);
+        }
+
         if ($this->addingItemsForContent) {
             $pageRecord = $this->loadRecordFromTable('pages', (int)$pageId);
             if (!$pageRecord) {
@@ -73,13 +90,7 @@
                 return $pageLevelProvider->getGrid($pageRecord)->buildExtendedBackendLayoutArray(0);
             }
         }
-        // Delegate resolving of backend layout structure to the Provider, which will return a Grid, which can create
-        // a full backend layout data array.
-        if ($this->provider instanceof GridProviderInterface) {
-            return $this->provider->getGrid($this->record)->buildExtendedBackendLayoutArray(
-                $this->resolveParentRecordUid($this->record)
-            );
-        }
+
         return parent::getSelectedBackendLayout($pageId);
     }
```

**Comment by jonaseberle** [comment]
@NamelessCoder I get out-of-memory in page module with current dev-development in TYPO3 9.5.15.
@michael-binder your patch fixes it for me, too.
