### ISSUE TITLE
Not TYPO3 v10 compatible

### ISSUE THREAD

**Issue by MartinH0** [FluidTYPO3/flux#1763]
First I used this setup:

TYPO3 v10.3.0
Flux v9.2.0

Now I use:

TYPO3 v10.3.0
Flux v9.3.2

I choosed Flux 9.2 because its the latest and only that worked for me on TYPO3 10.2.1.

But now on TYPO3 v10.3.0 I do encounter erros, so I can not edit any pages anymore. I honestly dont like that plug & play design feature as it breaked my whole installation.

Anyway, may this trace will help you to fix that bug so I may can test it.

### TRACES (caution, two Traces!)

**TYPO3 v10.3.0 & Flux 9.2.0**:
![TYPO3 Site edit Bug 1](https://user-images.githubusercontent.com/17692860/79491326-94150080-801e-11ea-887d-53d33259d99e.PNG)
![TYPO3 Site edit Bug 2](https://user-images.githubusercontent.com/17692860/79491331-96775a80-801e-11ea-8102-12e908eb9deb.png)

**TYPO3 v10.3.0 & Flux 9.3.2**:
![TYPO3 Site edit Bug 1 9 3 2](https://user-images.githubusercontent.com/17692860/79492342-24077a00-8020-11ea-882b-7e5daab8aaeb.PNG)
![TYPO3 Site edit Bug 2 9 3 2](https://user-images.githubusercontent.com/17692860/79492343-2538a700-8020-11ea-9b97-a90eb27f8e17.png)

In fact I can not edit any pages anymore.

**Comment by bnf** [comment]
Sorry, saw this only after discussing this one in slack: the development branch already has a workaround for that in place:
https://github.com/FluidTYPO3/flux/blob/f83a100561eea5f8d058e83d69e7a06888158ad4/Classes/Integration/PreviewView.php#L380

So I think this issue could be closed. You check checkout the flux development branch to verify it is working for now.

**Comment by MartinH0** [comment]
But its still not letting me edit anything.
![TYPO3 Flux Error Edit Page](https://user-images.githubusercontent.com/17692860/79495608-23bdad80-8025-11ea-9a11-d77dec0fb7e7.PNG)

**Comment by MartinH0** [comment]
@NamelessCoder is there a chance to get some feedback if this issue is related to Flux or if I have to search elsewhere for the root of the problem?

Thanks in advance!

**Comment by boris85** [comment]
@MartinH0 isn't this the same one as this #1748?

**Comment by MartinH0** [comment]
Yes I think its related to the same issue.

**Comment by MartinH0** [comment]
Now updated to TYPO3 LTS 10.4.0 and this issue is still here.

**Comment by ghwaldo** [comment]
Did some one find workaraounds ?
Does anybody know when there will be compatibility with TYPO3 10.4.x ?

And does the builder work on TYPO3 10.4.x ? Any experienses ?

**Comment by MartinH0** [comment]
@NamelessCoder just wanted to thank you and tell that this fix worked for me, I now can see all the content elements.
Maybe a release with this fix including would be good to provide this to all of the people which want to get this update from TER?
