### ISSUE TITLE
Lost relation when exporting db

### ISSUE THREAD

**Issue by buepro** [FluidTYPO3/flux#1766]
# Environment
- TYPO3 9.5.15
- Flux 9.3.2

# Error description

Related issues: #903

When creating the db-data for a distribution images used in flux elements are not exported. The flux element has the following configuration: [Template](https://github.com/buepro/typo3-flux_elements/blob/1.0.2/Resources/Private/Templates/Content/Card.html), [image sheet](https://github.com/buepro/typo3-flux_elements/blob/1.0.2/Resources/Private/Partials/Content/Card/Configuration/Sheets/Image.html), [image](https://github.com/buepro/typo3-flux_elements/blob/1.0.2/Resources/Private/Partials/Field/InlineImage.html).

The preview from the tree to be exported reflects the loss from the relation to the image:

![fluxcard](https://user-images.githubusercontent.com/37214997/80070890-05cfdb80-8544-11ea-9f23-183959807d96.jpg)

For a gridelements element it looks as following:

![gridelementscard](https://user-images.githubusercontent.com/37214997/80070990-2d26a880-8544-11ea-9eb8-b478a4829ac7.jpg)

# Findings
It looks like the impexp-plugin can't detect the relation to the image due to missing configuration in 
`$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds']`. When adding the following configuration the impexp plugin detects the relation:

`$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds']['*,fluxelements_card'] = 'FILE:EXT:flux_elements/Configuration/FlexForms/Card.xml';`

# Corrections
- Could the flexform be configured in a separate file or are there any compatibility issues or drawbacks with it?
- Could the entries to `$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds']` be generated by flux?

**Comment by NamelessCoder** [comment]
> Could the flexform be configured in a separate file or are there any compatibility issues or drawbacks with it?

Only that it wouldn't be dynamic and isn't defined in the template which uses it. Should work the same in all other ways.

> Could the entries to $GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds'] be generated by flux?

Yes, but only safely so, in cases where the `static` option for the Flux form is set to true - if the DS isn't static it is implied dynamic and couldn't be generated universally for all instances of the CType.

However, if `impexp` doesn't detect the references that might indicate another problem - there is an API for resolving the DS which should trigger Flux if used, but if `impexp` doesn't use this API and only looks for the `ds` TCA option that would explain the problem. If this is the case it would be a core bug.

**Comment by buepro** [comment]
Thank you very much for the answer. Since the form has some dynamic elements the `ststic` option can't be used. It looks like the [external (in a separate file)](https://github.com/buepro/typo3-flux_elements/blob/master/Configuration/FlexForms/Card.xml) and the [local configuration](https://github.com/buepro/typo3-flux_elements/blob/master/Resources/Private/Templates/Content/Card.html) are merged. This works for the given use case.

**Comment by NamelessCoder** [comment]
This issue should be fixed now, since re-introducing the "TCEforms" wrapper element in the resolved DS. Nearly all places in TYPO3 did correctly support a DS without this wrapper (in fact, it is removed by the FormEngine...) but some places - like impexp or the suggest wizard receiver - were not capable of handling a DS without it.
