### ISSUE TITLE
10.4 and typo3_console

### ISSUE THREAD

**Issue by infabo** [FluidTYPO3/flux#1770]
Triggering a "cache:flush" via typo3_console results in the following error:

```
$ ddev exec vendor/bin/typo3cms cache:flush

                                                                                                                                                                       
  [ Helhum\Typo3Console\Core\Booting\StepFailedException ]                                                                                                             
  Warning: array_search() expects parameter 2 to be array, null given in /var/www/html/private/typo3conf/ext/flux/Classes/Integration/ContentTypeBuilder.php line 300  
                                                                                                                                                                       

Caused by:
                                                                                                                                                                       
  [ TYPO3\CMS\Core\Error\Exception ]                                                                                                                                   
  Warning: array_search() expects parameter 2 to be array, null given in /var/www/html/private/typo3conf/ext/flux/Classes/Integration/ContentTypeBuilder.php line 300  
                                                                                                                                                                       

cache:flush [--files-only]

Failed to run typo3cms cache:flush: exit status 1 
```

Same for "ddev exec vendor/bin/typo3cms extension:setupactive"

branch: development 0c8a21a27e38e1fab680a8f913208c1eb0f5c4e5

**Comment by Geddo** [comment]
Have the same problem, but only when my custom flux-template provider installed. without it no problem :-(

**Comment by NamelessCoder** [comment]
Appears to be caused by TCA of tt_content not being loaded, which might be caused by the way this particular CLI action works and/or the loading order imposed by the action. I can suppress that warning but then can't guarantee that TCA (which gets cached) would contain the necessary items, but I guess it's better to have to flush the system caches after calling this action, than to see a PHP warning when calling it.

**Comment by Geddo** [comment]
@NamelessCoder yes, seems like the TCA is not loaded at that point. if you use \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadBaseTca(); in your ContentTypeBuilder.php  before calling the TCA on line 300 it works also for the typo3console. Strange.

**Comment by NamelessCoder** [comment]
I haven't been able to reproduce this problem (TYPO3 9.5 + TYPO3 Console ^5) but even so, it isn't much of a problem to lift the same solution the core uses in `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPlugin` which is the method that gets called at the bottom of the call stack when registering plugins, as is done in the ContentTypeBuilder. So I assume it is safe to ignore missing TCA as opposed to attempting to initialize it manually.

I'm sure you will let me know if that isn't the case on your systems ;) if/when you do, please include the TYPO3 and Console versions you're using!

**Comment by infabo** [comment]
TYPO3 10.4.x / typo3_console 6.x

**Comment by NamelessCoder** [comment]
@infabo Does this mean that the patch I made doesn't solve the issue?

**Comment by infabo** [comment]
I did not test the patch yet. Just wanted to note, the reported problem was in TYPO3 10.4 with typo3_console 6.x. Can't speak about v9 as I did not test it in v9.
