### ISSUE TITLE
 contentContainer in Section Object removes ability to configure Grid

### ISSUE THREAD

**Issue by HomelessRaccoon** [FluidTYPO3/flux#1771]
When using the contentContainer feature on section objects the automatically created grid overwrites the manually created grid, so it's not possible to set variables or specific grid layouts (as far as I know). I would like to be able to set the allowedContentTypes, so it would be useful to have the option of enabling the "create colPos for each object"-Feature of contentContainer, without enabling the automatic grid creation. 

using flux 9.2.0

**Comment by NamelessCoder** [comment]
Added in linked commit, but you will need to upgrade to the Flux 9.4 branch when it is released.
