### ISSUE TITLE
[DOC] how to migrate flux:field.inline.fal to flux:field

### ISSUE THREAD

**Issue by infabo** [FluidTYPO3/flux#1773]
Would be nice to know, since all flux:field.* viewhelpers are deprecated and are removed in v10.

So for example, how to migrate flux:field.inline.fal to flux:field?

**Comment by buepro** [comment]
May be [this example](https://github.com/buepro/typo3-flux_elements/blob/1.0.2/Resources/Private/Partials/Field/InlineImage.html) helps...

**Comment by infabo** [comment]
I see. Thanks @buepro for the reference. Looks like a damn hard job for anybody migrating from <10 to 10.x then. And already hard for anybody using it right now already. TCA in fluid arrays. yeah...

**Comment by NamelessCoder** [comment]
That is indeed a nasty amount of array syntax. In the core there's a function that assists with creating IRRE configurations for FAL references, perhaps this can be wrapped in a ViewHelper which can generate this huge array for you with just the field name / file type permissions as input.

**Comment by codeKerl** [comment]
Ok. Thanks for your hint. @buepro 
Is there any website or other reference to look up the structure of these config array's
For example, where can I put my cropVariants?
