### ISSUE TITLE
flux:field.inline.fal broken

### ISSUE THREAD

**Issue by infabo** [FluidTYPO3/flux#1774]
```html
<html lang="en" data-namespace-typo3-fluid="true"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="https://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
      xmlns:flux="https://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
      xmlns:v="https://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">

<f:layout name="Content/Default"/>

<f:section name="Configuration">
  <flux:form id="quote" label="Zitat" description="Dieses Inhaltselement erstellt ein Zitat-Inhaltselement auf der Website.">
    <flux:form.option.icon>EXT:site_package/Resources/Public/Icons/element-content-default.svg</flux:form.option.icon>
    <flux:field.inline.fal name="settings.image" required="1" maxItems="1" minItems="1"/>
  </flux:form>
</f:section>

<f:section name="Main">
</f:section>

</html>
```

results in:

![image](https://user-images.githubusercontent.com/3999104/80478308-a3187e80-894d-11ea-81d4-193ae04b05b1.png)

and the wizard is a record-wizard instead of a file wizard:

![image](https://user-images.githubusercontent.com/3999104/80478360-b3305e00-894d-11ea-9162-1a5072490e7f.png)

branch: 0c8a21a27e38e1fab680a8f913208c1eb0f5c4e5

**Comment by GD-HS** [comment]
Can confirm this for a fresh TYPO3 ~10.4 installation with Flux 9.3.2 and dev-master (same installation works with TYPO3 ^9).
But someone should also mention that Flux has not been released for TYPO3 ~10.4 yet. (Packagist says ^10, but TER 10.2.99)

**Comment by faschinr92** [comment]
Have same problem, it saves the files with false id and because of that it looks like nothing would be saved. NEWxxxxxx instead of the sys_file_reference.uid.

TYPO3~9.5.4 and Flux 9.3.2

**Comment by fgerards** [comment]
Same problem here: TYPO3 10.4.2 & Flux Develop-Branch
