### ISSUE TITLE
latest changes introduce memory limit crash in page module

### ISSUE THREAD

**Issue by TrueType** [FluidTYPO3/flux#1776]
I was working with version development-dev 0c8a21a as I ran into a memory size error in the page module of the backend. I can create a content element, which uses flux.grid.row, but I cannot close the element - open the page in columns mode. It then crashes with the said memory error. Going back to version 34fd49920f3efd6cdd14e5edc7d9f1ec0905a06b does not show the problem.

**Comment by NamelessCoder** [comment]
Are you on TYPO3 10.3 or 10.4 - or earlier?

**Comment by TrueType** [comment]
Sry. I forgot. I have v9.5.15

**Comment by Flimmerkiste** [comment]
Ran into the same issue today when using the latest `development` version (Because before that I ran into  #1763 ;-) ). Reverting to the commit mentioned by @TrueType fixed it for me as well. I'm on TYPO3 10.4.1

**Comment by NamelessCoder** [comment]
I'm not able to reproduce this problem - and I can't identify any commit inbetween the two commits mentioned by @TrueType which would increase memory consumption by any noticable amount, or would cause issues with infinite recursion. I'll need a bit more info.

* Does it happen on all pages, even freshly created blank pages? _If it doesn't happen on freshly created pages, please provide the steps I need to perform to trigger the issue starting with a blank page_.
* Does the error happen only when there is nested content, or does it happen with any content type that allows nested content?
* Are you in workspaces?

It might also help if one or both of you are able to attach an example Flux content template. I've tested with "Column Splitter" from https://github.com/FluidTYPO3/test_provider_extension and it doesn't appear to have any issues.

**Comment by NamelessCoder** [comment]
Only thing I could find that's possibly related is the commit linked to above this comment. Please check if that solves the issue on your end.

**Comment by TrueType** [comment]
I will try to help you here. It is nothing with workspace.

**Comment by TrueType** [comment]
`<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	 xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	 xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	 xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">
	<f:layout name="Content"/>
	<f:section name="Configuration">
		{v:variable.typoscript(path: 'plugin.tx_fluidcontentbootstrap.settings') -> v:variable.set(name: 'settings')}
		{f:if(condition: settings.gridColumns, then: settings.gridColumns, else: 12) -> v:variable.set(name:'countOfGridColumns')}
		<flux:form id="row" options="{useTypoScript: 0, group: 'mygroupxx'}">
			<flux:form.section name="columns">
				<flux:form.object name="column">
					<flux:field.select
                            name="class"
                            items="{f:render(section: 'Value', arguments: {iteration: iteration})-> v:iterator.loop(count: countOfGridColumns, iteration: 'iteration', minimum: 1)}"
                            label="Columns: numberOfColumns"
                    />
					<flux:field.input name="additionalClass"/>
				</flux:form.object>
			</flux:form.section>
			<flux:grid>
				<flux:grid.row>
					<v:condition.type.isArray value="{columns}">
						<f:for each="{columns}" as="sectionObject" iteration="iteration">
							<v:variable.set name="width" value="{sectionObject.column.class -> v:format.substring(start: 6)}"/>
							<v:variable.set name="percent" value="{width  -> v:math.division(b: countOfGridColumns) -> v:math.product(b: 100) -> v:math.round(decimals: 2)}"/>
							<flux:grid.column colPos="{iteration.index}" style="width: {percent}%; min-width: 600px !important;" name="column{iteration.cycle}" label="{percent}%"/>
						</f:for>
					</v:condition.type.isArray>
				</flux:grid.row>
			</flux:grid>
		</flux:form>
	</f:section>
	<f:section name="Main">
		<div class="container">
			<div class="row">
				<f:for each="{columns}" as="sectionObject" iteration="iteration">
					<div class="{sectionObject.column.class} {sectionObject.column.additionalClass} {f:if(then: 'well', else: '', condition: '{sectionObject.column.addWell}')}">
						<flux:content.render area="column{iteration.cycle}"/>
					</div>
				</f:for>
			</div>
		</div>
	</f:section>
	<f:section name="Preview">
		<flux:grid/>
	</f:section>
	<f:section name="Value">small-{iteration.cycle} columns {f:if(condition: iteration.isLast, else: ',')}</f:section>
</div>
`

**Comment by TrueType** [comment]
ah well... you did a commit. Will check that out. But later.

**Comment by Flimmerkiste** [comment]
> Only thing I could find that's possibly related is the commit linked to above this comment. Please check if that solves the issue on your end.

Hey @NamelessCoder, sorry for the late reply. The commit you mentioned fixes the issue for me \o/
