### ISSUE TITLE
TCEFORM.tt_content.CType.keepItems Problem

### ISSUE THREAD

**Issue by Geddo** [FluidTYPO3/flux#1777]
I have this in my tsconfig:
```
[request.getQueryParams()['colPos'] == 0]
TCEFORM.tt_content.CType.keepItems = textpic,textmedia
[global]
```
works as expected until I try to add a Grid: Instead of adding the Grid it gives me only textpic, textmedia as an option:
![image](https://user-images.githubusercontent.com/11272741/80588835-5dc18300-8a19-11ea-95f8-dfaa3b22898e.png)

**Comment by NamelessCoder** [comment]
Can this be fixed by adding `TCEFORM.tt_content.CType.keepItems = *` in global scope, before this colPos-specific instruction?

**Comment by Geddo** [comment]
TCEFORM.tt_content.CType.keepItems = * doesnt work. It seems to hide all CEs

**Comment by Geddo** [comment]
OMG, I'm so sorry ('0' insteat of 0)
```
[request.getQueryParams()['colPos'] == '0']
    TCEFORM.tt_content.CType.keepItems = textpic,textmedia
[global]
```
