### ISSUE TITLE
How to get rid of the /design folder

### ISSUE THREAD

**Issue by Geddo** [FluidTYPO3/flux#1778]
What I already tried:
- I disabled "Plug-and-play templates" from the extension settings
- flux ts in my own template-extension with overriden pathes
- page.5 <.
- all above + deleting the folder

but everytime I do an composer update, cache:flush or page reload the folder comes back like it's from a stephen king movie 😂

**Comment by NamelessCoder** [comment]
That does indeed sound like a bug - I'll check!

![download](https://user-images.githubusercontent.com/2228052/80591857-afb8d780-8a1e-11ea-9c41-1eb0e77ba185.gif)

**Comment by NamelessCoder** [comment]
Unable to reproduce - folder only appears to be created if the plug and play templates setting is actually enabled...
