### ISSUE TITLE
TYPO3 v9 + flux 9.3.2 without fluidpages leads to missing flux grid in backend?

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1779]
I'm actually trying to get work flux 9.3.2 without fluidpages for a TYPO3 migration previously using older flux + fluidcontent + fluidpages. The good news... I think I've actually got it mostly working. Frontend seems to work well more or less.

But backend pages doesn't work at all. I can open page in backend and it displays some content-elements, but it always seems to use some kind of fallback / default TYPO3 core grid and competly ignores the flux:grid defined in my templates.

I actually noticed that fluidpages should not be required anymore as flux 9.3.2 has already ported fluidpages in flux with some fallback-switches if fluidpages is already installed natively. But actually I don't want that mess anymore and really would love to only have flux as single requirement for both FCEs and Pages rendering.

Template flux part is looking like this -- after some migration progress:
```
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
>
    <f:layout name="Standard"/>

    <f:section name="Configuration">
        <flux:form
            id="startpage"
            options="{
                icon:'EXT:my-layout/Resources/Public/Icons/Page/pageicon_start.png'
            }"
        >
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column colPos="1" colspan="4" name="teasercontent"/>
                </flux:grid.row>
                <flux:grid.row>
                    <flux:grid.column colPos="0" colspan="4" name="maincontent"/>
                </flux:grid.row>
                <flux:grid.row>
                    <flux:grid.column colPos="4" colspan="4" name="additionalcontent" />
                </flux:grid.row>
            </flux:grid>
        </flux:form>
    </f:section>

   <! --- SNIP--->
   Backend preview & FE-templates
   <!---SNAP --->
</div>
```
I can't figure out what's wrong. Is there still something missing for data-migration or is this a bug? I think there's something going wrong here:

Classes/Backend/BackendLayoutDataProvider.php
```php
    public function getBackendLayout($identifier, $pageUid)
    {
        $record = $this->recordService->getSingle('pages', '*', $pageUid);
        if (null === $record) {
            return new BackendLayout($identifier, 'Empty', '');
        }
        $grid = $this->resolveProvider($record)->getGrid($record);
        return $grid->buildBackendLayout(0);
    }
```
https://github.com/FluidTYPO3/flux/blob/ba879b29fd3ab6c03d462536c635ffd3f3c1f922/Classes/Backend/BackendLayoutDataProvider.php#L112

Any help or ideas what's going wrong here? Thanks in advice.

**Comment by typoworx-de** [comment]
I'm doing some research on it. Looks like TYPO3 v9 is already providing it's own BackendLayoutDataProvider (checked via Configuration-Module on TYPO3_CONF_VARS:
![image](https://user-images.githubusercontent.com/1282298/81023106-ac36ad80-8e6f-11ea-9418-c5ccf49ac224.png)

I've been trying to disable it like this in flux ext_localconf.php (right after BackendLayoutDataProvider line):
```php
unset($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['BackendLayoutDataProvider']['pagets']);
```
pagets Provider is gone, but flux backend-layout is still not working (still showing some default/fallback layout).

**Comment by typoworx-de** [comment]
Ok, actually I think it was a fail on my site. Everything looks fine and there doesn't seem to be a bug.

**Comment by typoworx-de** [comment]
Sorry for re-opening, but after some further research and trouble I've noticed flux is loading one of my own flux-grids, but actually its not using the one selected on page-properties! This was leading to some confusion, as initially I thought it was completly ignoring my own grid-definitions!

Currently I'm shure there is something wrong with this class - which seems to be involved in providing backend layout. As far as I actually try to understand flux processing this class should jump once into this code to resolve page-layout, but it's never reaching this point!

FluidTYPO3\Flux\Integration\Overrides\BackendLayoutView
```php
    public function getSelectedBackendLayout($pageId)
    {
        if ($this->addingItemsForContent) {
            // Code will never jump in here for backend showing page-layout
            $pageRecord = $this->loadRecordFromTable('pages', (int)$pageId);
            if (!$pageRecord) {
                return null;
            }
            $pageLevelProvider = $this->resolvePrimaryProviderForRecord('pages', $pageRecord);
            if ($pageLevelProvider instanceof GridProviderInterface) {
                return $pageLevelProvider->getGrid($pageRecord)->buildExtendedBackendLayoutArray(0);
            }
        }
```
https://github.com/FluidTYPO3/flux/blob/ba879b29fd3ab6c03d462536c635ffd3f3c1f922/Classes/Integration/Overrides/BackendLayoutView.php#L67

**Comment by NamelessCoder** [comment]
Are you on most recent dev-development? Do you have any other extension installed which might override `itemsProcFunc` of `tt_content.colPos`?

**Comment by typoworx-de** [comment]
I've figured out what's wrong. Had to manually do some pre-migration for fluidpages to flux:
  ```mysql
  UPDATE `pages`
    SET backend_layout="flux__grid", backend_layout_next_level="flux__grid"
  WHERE
    backend_layout="fluidpages__fluidpages"
    OR backend_layout_next_level="fluidpages__fluidpages"
    AND NOT deleted="1"
  ```
