### ISSUE TITLE
Plug-and-play template structure always created

### ISSUE THREAD

**Issue by DanielHaring** [FluidTYPO3/flux#1781]
With TYPO3 CMS v9 or higher, the plug-and-play template directory structure is always created, regardless of whether the extension configuration option „plugAndPlay“ is set to _TRUE_ or _FALSE_.

This happens because every time the TCA is regenerated (e.g. when flushing the system cache) the FLUX setup is overwritten with the legacy extension configuration array within TCA/Overrides. Thus the complete setup has the value _FALSE_ and the corresponding option „plugAndPlay“ falls back to the default value set in PHP (_TRUE_).

I'll provide a fix in no time.

**Comment by svewap** [comment]
In this context, the problem is that the value of the $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['flux']['setup']['plugAndPlay'] variable is FALSE after the cache flush and the code continues to execute. All other variables are then FALSE as well.

https://github.com/FluidTYPO3/flux/blob/58aeb1013658e474dffb83db13dade97dbdf6e23/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php#L68

The condition should therefore be better inverted.

**Comment by DanielHaring** [comment]
Well, in fact $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['flux']['setup']['plugAndPlay'] is not set at all as $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['flux']['setup'] is _FALSE_ already.

This is because the setup is overwritten with a non-existent array within TCA/Overrides:

https://github.com/FluidTYPO3/flux/blob/58aeb1013658e474dffb83db13dade97dbdf6e23/Configuration/TCA/Overrides/pages.php#L8

https://github.com/FluidTYPO3/flux/blob/58aeb1013658e474dffb83db13dade97dbdf6e23/Configuration/TCA/Overrides/pages_language_overlay.php#L8

https://github.com/FluidTYPO3/flux/blob/58aeb1013658e474dffb83db13dade97dbdf6e23/Configuration/TCA/Overrides/sys_template.php#L8

$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['flux'] simply no longer exists and has been replaced by $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['flux'].

See also: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html

While changing the condition would work around the problem, I still see potential errors if the configuration continues to be read from the wrong array.

**Comment by NamelessCoder** [comment]
Two initial comments from my side:

* The problem described by @DanielHaring does not occur on my dev-master of TYPO3.
* Any change to this must be verified to not break as far back as TYPO3 8.7.

**Comment by typoworx-de** [comment]
I can confirm this annoying problem. And there are a lot of other tickets mentioning this, too:
* https://github.com/FluidTYPO3/flux/issues/1778
* https://github.com/FluidTYPO3/flux/issues/1733
