### ISSUE TITLE
partialRootPaths include Content suffix

### ISSUE THREAD

**Issue by instruccionesaldorso** [FluidTYPO3/flux#1788]
TYPO3 9.5.18 version
EXT:flux dev-development version

I'm trying to use the partials from EXT:fluid_styled_content in my flux content elements:

```
<f:render partial="Media/Type" arguments="{file: file}" />
```

For that purpose, I use in my flux extension provider extension, the next TS settings:

`plugin.tx_vendorextension.view.partialRootPaths < lib.contentElement.partialRootPaths`

However, paths always include a "Content" subfolder.

FE error says:

```
The Fluid template files 
"/var/www/html/public/typo3/sysext/fluid_styled_content/Resources/Private/Partials/Content/Media/Type.html", 
"/var/www/html/public/typo3/sysext/fluid_styled_content/Resources/Private/Partials/Content/Media/Type" could not be loaded.
```

**Comment by NamelessCoder** [comment]
I haven't been able to reproduce this problem, when using the exact same setup as described. When adding the `partialRootPaths` from FSC by referencing the array, the correct paths are always used. I don't know what would cause this but I have to assume there is some customisation or class override in play, which does not come from FSC or Flux, and which either modifies the paths array or overrides it with a version that has the suffixes.

As far as I can tell, the only way to proceed here is for you to debug your setup and determine where the suffix is added and/or where these paths may be overridden (e.g. in TS which modifies the `lib.contentElement.partialRootPaths` setting). Unfortunately I'm not able to help any further.
