### ISSUE TITLE
Flux 7.3.0 PageController is not invoked anymore?!

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1790]
I'm using Flux 7.3.0 "standalone" after TYPO3 Migration using Flux/Fluidpages/Fluidcontent previously. I now noticed a custom site-package PageController for Flux is not invoked anymore!

The PageController looks as follows currently testing it's invoked:
```php
<?php
namespace FooBar\MySitepackage\Controller;

/**
 * Class PageController
 * @package FooBar\MySitepackage\Controller
 * @route off
 */
class PageController extends \FluidTYPO3\Flux\Controller\PageController
{
    public function __construct()
    {
        die(var_dump(__METHOD__));
    }

    public function initializeAction()
    {
        die(var_dump(__METHOD__));
    }
}
```

It's registerted in ext_localconf.php as follows:
```php
<?php
defined('TYPO3_MODE') || die();

call_user_func(
    function($extKey, $vendorName, $packageName)
    {
        $providerExtensionName = $vendorName . '.' . $packageName;

        \FluidTYPO3\Flux\Core::registerProviderExtensionKey(
            $providerExtensionName,
            'Page'
        );
        \FluidTYPO3\Flux\Core::registerProviderExtensionKey(
            $providerExtensionName,
            'Content'
        );
    },
    'foobar_mysitepackage', 'FooBar', 'MySitepackage'
);
```

For testing I also put the Debugging-Statements into my ContenController and those are fired! Putting ``` die(__FILE__)``` before class in PageController is fired! But the Class itself is neither initialized nor there will be anything done in the class.

I am shure this once worked easily like for the ContentController. Why is this not working anymore?

**Comment by NamelessCoder** [comment]
Flux will check for the controller *action* being present on the class, otherwise the class won't be used. Unless your template is called `Initialize.html` that means your controller won't be used - and if your template has this name I'd recommend renaming it, since `initializeAction` is a reserved action name.

So I assume that the reason your class is loaded, but not used, is that the specific method corresponding with your template file name does not exist.

See `\FluidTYPO3\Flux\Controller\AbstractFluxController::hasSubControllerActionOnForeignController`.

**Comment by NamelessCoder** [comment]
@typoworx-de Did you have time to confirm that the controller is used if it contains the corresponding action method?

**Comment by NamelessCoder** [comment]
Closing the issue due to inactivity. If against expecation the tip above doesn't solve the problem then feel free to ping for it to be reopened!

**Comment by typoworx-de** [comment]
@NamelessCoder sorry didn't have this issue on my screen anymore. Well was "working around" this issue somehow but for me it's already present and would help alot knowing how to make it work.

What is the default "Page-Action" I could use to make the PageController being recognised? Could you please give me a hint?

**Comment by typoworx-de** [comment]
Ok just trying to understand your last statement. So there is no "generic" Action-Method I can use, but I would have to make a StartpageAction if the Template is f.e. is named "Startpage.html" - right?

I really would love if it is possible to have more generic overrides without explicitly having to introducte a {TemplateName}Action. Wouldn't this make sense in some cases? This may be could be triggered by Registraction-Method or a PageController property-variable or constant to make the Flux-Core calling the custom-Controller in any way incl. initializeAction() by using parent::initializeAction()
