### ISSUE TITLE
Translated content elements in grids not displayed in backend

### ISSUE THREAD

**Issue by kimchristiansen** [FluidTYPO3/flux#1795]
After the update to flux 9.4.0 I have a strange behaviour with content elements in grids.
When I translate the content elements of a page in translate mode, they are created correctly, assigned to the grids correctly and rendered correctly in the frontend. However, translated content elements in grids are not displayed in the back end.
Only when you edit and save the content element in the original language is the translated content element displayed in the grid.

Setup:
flux 9.4.0
TYPO3 9.5.18
PHP 7.3.9
no fluidpages
ContentDefender

**Comment by NamelessCoder** [comment]
I'm not 100% sure I understood the bug report, but I did find a problem with post-processing of column position when using the "localize" action (as opposed to "copyToLanguage"). If the linked commit doesn't fix your problem, please ping me and if possible, add a screenshot of the problem!

**Comment by kimchristiansen** [comment]
Sorry for the late feedback. Yes, the bug is fixed with flux 9.4.1. Thanks alot!
