### ISSUE TITLE
flux:field.custom renders dummy content in TYPO3 v10

### ISSUE THREAD

**Issue by Gitsko** [FluidTYPO3/flux#1796]
when i want to insert a content field the dummy output always appears.

Example:
```
<flux:field.custom name="settings.description">
   <div class="alert alert-info">
        description
  </div>
</flux:field.custom>
```

**Comment by NamelessCoder** [comment]
@Gitsko what do you mean by "dummy content" in this context?

**Comment by Gitsko** [comment]
@NamelessCoder, yes this output:
![grafik](https://user-images.githubusercontent.com/17161911/84007200-4c508c80-a970-11ea-9ed5-8207f1d51874.png)

**Comment by NamelessCoder** [comment]
Thanks, gives me something to go after :)
