### ISSUE TITLE
v9.4.0 colPos problem

### ISSUE THREAD

**Issue by UNI49** [FluidTYPO3/flux#1797]
Hello

I've got some few problems with : typo3 v9.5.18 & Flux v9.4.0 (from Typo3 Forge) :
- Typo3 forge show me "stable" status, but Github says "beta"
- "colPos" entries are double shown (not all, just some are double)

Is there any explaination ?

Thanks for help

**Comment by NamelessCoder** [comment]
Github development versions are marked as "beta" to distinguish them from released versions (they carry the same version number in metadata but stability is different).

Can you elaborate about the colPos issu - what do you mean by double? Label shown twice in same option or selection options shown twice?

**Comment by UNI49** [comment]
Thanks for details about versioning.

In a "Page content" element, there is a select for "General > Column [colPos]". This select is filled by our TCEform
```
TCEFORM { tt_content { colPos { addItems {
                20 = Colonne Principale
                21 = Colonne Gauche
                22 = Encart haut de page
                23 = Bloc chapô
                24 = Pied de contenu
                25 = Bloc fil d'actu
                26 = Bloc à la une
                27 = Mag + Facebook
            }}}}
```
This is totally functional in v9.3.2, but when we migrate to v9.4.0, the 26, 22 & 20 are shown twice. It's really strange.

**Comment by NamelessCoder** [comment]
Hmm, are these colPos numbers also created as page column colPos numbers in a Flux-registered page template? The pageTSconfig-configured numbers will always be rendered and the numbers from the page template will then be added - so perhaps you need to remove them from pageTSconfig?

**Comment by UNI49** [comment]
They are defined in TCEFORM and in BackendLayouts (tsconfig). But if I remove this, as you said, from tsconfig, I lost all the "page view" from backend… it's annoying.

**Comment by NamelessCoder** [comment]
Did you find a solution that's acceptable? If not then I may be able to prevent duplicates through the hook Flux uses.

**Comment by UNI49** [comment]
Sure, I've just remove this "colPos" from TCEFORM, not even more necessary with Flux v9.4.0, and it's a better UX now, because column/colPos just show the available page template areas.

Not sure it's necessary to prevent duplicates with a hook
