### ISSUE TITLE
[Ask for feature] Hide button for form.object

### ISSUE THREAD

**Issue by UNI49** [FluidTYPO3/flux#1798]
Hello,

I have not find the "hide" for a flux:form.object. Is there any possibilities for activate it, or is this a new feature to ask ?

We can move it and delete the object, but not just "hide" it.

Thanks for help.

**Comment by jpresasicti** [comment]
I second the idea, it would be great to have it.

**Comment by NamelessCoder** [comment]
Unfortunately, TYPO3 doesn't allow a visibility control for FlexForm section objects. While the target XML does support toggles for expand/hide, there is no such support for visiblity. Flux cannot add such capabilities unless they already exist as options in the TYPO3 core.

_I suggest creating this feature request on forge.typo3.org._

A manual implementation is possible but would work slightly different from standard visibility controls. Adding a checkbox inside the FlexForm object's properties, combined with a condition that checks this manual visibility property in all places where you use the FlexForm object, would allow an editor to designate a FlexForm object as "hidden" (meaning "skipped in output but still present in FlexForm data"). Note that not all contexts would support checking this property - for example, accessing FlexForm data from TS would still be able to read the object's properties. And note there are drawbacks, e.g. counting the number of objects has to be done by first filtering out any objects marked as "hidden".
