### ISSUE TITLE
Extension configuration not working

### ISSUE THREAD

**Issue by buepro** [FluidTYPO3/flux#1801]
# Environment
- TYPO3 10.4.4
- FLUX 9.4.0

# Error description
Even though the autoload feature has been disabled in `Extension Configuration - Flux: basic.autoload = 0` the content from page.5 is shown ("Please select a page template in page properties.").

# Findings
When debugging `FluidTYPO3\Flux\Utility\ExtensionConfigurationUtility->getOption` it can be seen that `isset($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['flux'][$optionName])` **allways** results in `false` hence the default configuration is used.

**Comment by NamelessCoder** [comment]
Fixed in https://github.com/FluidTYPO3/flux/commit/3f16340416f8cf016841a0f131bb025824ff38ed, release is pending.

**Comment by buepro** [comment]
Sorry, didn't find that one... Thank you!
