### ISSUE TITLE
Get an error when using "Insert after"

### ISSUE THREAD

**Issue by nielsweb** [FluidTYPO3/flux#1802]
I use **TYPO3 10.4.4** with **flux 9.4.0**
If I copy my own content element and try to paste it with "Paste after" from the context menu, I get an exception.

https://wiki.typo3.org/Exception/CMS/1476107295
#1476107295 TYPO3 \ CMS \ Core \ Error \ Exception
PHP Warning: Cannot unset offset in a non-array variable in /Users/weber/Documents/projects/karstens/www/public/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php line 201

For testing, I completely emptied my element, except for the most necessary values, and still get the same message. Copying via the symbol below the element ("Paste after this record") works.

**Comment by NamelessCoder** [comment]
This issue may already be fixed, if possible please try with `dev-development` and if the error still happens, let me know which line number it happens in (line 201 is moved in `dev-development`).

**Comment by nielsweb** [comment]
I'm sorry, the error still occurs. The affected line `unset ($ value ['update'] ['colPos']);` is also only shifted. I'll check that again tomorrow.

I had tried dev-development and dev-master.
```
"fluidtypo3 / development": "^ 4.0",
"fluidtypo3 / flux": "dev-development",
"fluidtypo3 / vhs": "^ 6.0",
```

**Comment by nielsweb** [comment]
Downgraded to TYPO3 v9 because there are further difficulties with `flux: field.file`.
Thanks for your work. We stay tuned.
