### ISSUE TITLE
Flux Core:  Link Wizard Field

### ISSUE THREAD

**Issue by KevinMcLean** [FluidTYPO3/flux#1804]
Since TYPO3 10 it isn´t possible to use following Tag:

```
<flux:field.input name="link" label="Links">
                    <flux:wizard.link  activeTab="page"/>
                </flux:field.input>
```
In itself it works but the field to select a link is not displayed.

![image](https://user-images.githubusercontent.com/9349611/86000153-6defe180-ba0d-11ea-9dd2-e042e68131f6.png)

Does anybody knew what kind of Problem this is?

**Comment by glucka** [comment]
See: https://github.com/FluidTYPO3/flux/issues/1780

**Comment by KevinMcLean** [comment]
thanks 👍
