### ISSUE TITLE
Missing image metadata and manipulation

### ISSUE THREAD

**Issue by OrangeLeinad** [FluidTYPO3/flux#1806]
In TYPO3 V10.4.4 and Flux V9.4.1 with code as follows

`<flux:field.inline.fal name="settings.image" label="Bilder (max. 1)" required="false" maxItems="1" minItems="0" />`

there aren't image metadata as "Alternative Text [alternative]" and "Link [link]" anymore. Also "Image manipulation [crop]" is not there. 

Those functions should be standard features as you find it in standard content elements "Text & Media [textmedia]".

At the moment I see according attached pictures only:
![flux-missing-metadata-fields-and-crop-20200701](https://user-images.githubusercontent.com/3647459/86223789-4f622580-bb88-11ea-8203-7fd2bd391f47.jpg)

**Comment by hm-tim** [comment]
Can confirm this issue using TYPO3 Version 10.4.4 and latest flux development branch

**Comment by robsonrobi** [comment]
Have the same Problem

**Comment by MediKathi** [comment]
I can also confirm this.

**Comment by robsonrobi** [comment]
@NamelessCoder : Is there any chance to get a quick fix? Would love to go with Flux and TYPO3 10

**Comment by typo3-solution** [comment]
Hey, same Problem here with the 9.4.1. BUT... i have a 9.4.0 Version, that works. But i don't remeber my changes... I also don't know, why this version works and the version from the TER not. 

Maybe... it helps someone?! 


[flux.zip](https://github.com/FluidTYPO3/flux/files/4894773/flux.zip)

**Comment by Cyasi** [comment]
@typo3-solution just downgrade to 9.4.0 don't work. 
But it look like the version you posted work!

You changed following (compared to 9.4.0):
\class.ext_update.php
![grafik](https://user-images.githubusercontent.com/47395292/87134614-34369a80-c299-11ea-95ad-27c711c8de55.png)
line 197
`return [];`

\Classes\Core.php
![grafik](https://user-images.githubusercontent.com/47395292/87134677-4a445b00-c299-11ea-9c1d-37d41e86a45a.png)
after line 18
`TYPO3\CMS\Core\Utility\PathUtility;`
line 322
`if (!PathUtility::isAbsolutePath($templateFilename)) {`

\Classes\Form\Field\Inline\Fal.php
![grafik](https://user-images.githubusercontent.com/47395292/87134983-b6bf5a00-c299-11ea-8e4a-0ccfaf09bde3.png)
function buildConfiguration line 167
`    public function buildConfiguration()
    {
        $configuration = $this->prepareConfiguration('inline');
        $configuration['appearance']['createNewRelationLinkTitle'] = $this->getCreateNewRelationLinkTitle();
        $configuration['overrideChildTca'] = [  
            'columns' => [  
                'uid_local' => $configuration['foreign_selector_fieldTcaOverride']  
            ],  
            'types' => $configuration['foreign_types']  
        ];  
        if (!empty($this->cropVariants)) {  
            $configuration['overrideChildTca']['columns']['crop'] = [  
                'config' => [  
                    'cropVariants' => $this->cropVariants  
                ]  
            ];  
        }  
        return $configuration;
    }`

\Classes\Integration\HookSubscribers\DataHandlerSubscriber.php
![grafik](https://user-images.githubusercontent.com/47395292/87135192-02720380-c29a-11ea-91a2-be340ce19400.png)
line 63
`        if (!empty($fieldArray['l18n_parent'])) {
            // Command was "localize", do not touch colPos.
            return;
        }`

\Classes\Provider\AbstractProvider.php
![grafik](https://user-images.githubusercontent.com/47395292/87135442-57ae1500-c29a-11ea-88b2-eaad5e59dbcf.png)
after line 24
`use TYPO3\CMS\Core\Utility\PathUtility;`
line 484
`if (!PathUtility::isAbsolutePath($templatePathAndFilename)) {`

\Classes\Utility\ExtensionConfigurationUtility.php
![grafik](https://user-images.githubusercontent.com/47395292/87135614-90e68500-c29a-11ea-9926-5319b939f146.png)
line 47
`        return $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['flux']['setup'][$optionName] ?? static::$defaults[$optionName] ?? null;
`

I am still testing if everything else still works. But looks like it work for now.

**Comment by almfisch** [comment]
In TYPO3 10.4 & Flux 9.4.1 for it works with this changes in \Classes\Form\Field\Inline\Fal.php

Line 167:

```
public function buildConfiguration()
    {
        $configuration = $this->prepareConfiguration('inline');
        $configuration['appearance']['createNewRelationLinkTitle'] = $this->getCreateNewRelationLinkTitle();
        
        if (!isset($configuration['overrideChildTca'])) {
            $configuration['overrideChildTca'] = ['columns' => []];
        }
        if (!isset($configuration['overrideChildTca']['columns'])) {
            $configuration['overrideChildTca']['columns'] = [];
        }
        $configuration['overrideChildTca'] = [
            'types' => $configuration['foreign_types']
        ];
        if (!empty($this->cropVariants)) {
            $configuration['overrideChildTca']['columns']['crop'] =
            [
                'config' => [
                    'cropVariants' => $this->cropVariants
                ]
            ];
        }
        
        return $configuration;
}
```

**Comment by X-Tender** [comment]
Looks like that the only thing that is missing is 
```
$configuration['overrideChildTca']['types'] = $configuration['foreign_types'];
```

**Comment by NamelessCoder** [comment]
Fix merged.
