### ISSUE TITLE
Own RTE yaml works for standard element but not for flux:field.text enableRichText = 1

### ISSUE THREAD

**Issue by grischpel** [FluidTYPO3/flux#1808]
This works:
**RTE.default.preset = own** 
But if i try to use my custom yaml for rte for flex items, then it wont:
**RTE.config.tt_content.bodytext.preset = own** 
->
`<flux:field.text name="text" label="Text" required="0" enableRichText="1"/> `

**Comment by X-Tender** [comment]
I've stumbled upon this issue today too.
After some Investigations I could trace it down to this Commit
https://github.com/FluidTYPO3/flux/commit/0003416422bd3ed482dbcc0eebd02293035eba9f?branch=0003416422bd3ed482dbcc0eebd02293035eba9f&diff=split

The ` $root->getOption('record')` call always returns null so it falls back to pageid 0 which lead to no tsconfig and fall backs to "default"

I only noticed it in typo3 10.

**Comment by X-Tender** [comment]
I figured something new out.
I recently refactored my sitepacakge from
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig` in the `ext_localconf.php` to `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerPageTSConfigFile` in the `TCA/Overrides/tt_content.php` because I have two seperate plugins with their own RTE config so I can add the TSConfig in the "Resources" tab of the rootpage.

So what I noticed after I refactored it that the RTE config which is read in the Text.php via `BackendUtility::getPagesTSconfig($pageUid)['RTE.']` is empty. When I change it pack to `addPageTSConfig` its OK (But I cant use it this way because that ways one extension would overwrite the config of the another).

I also tried to put the RTE config Inline in the "Resources" Tab but that didn't worked either.

Maybe this helps to find the reason of this behaviour..

**Comment by grischpel** [comment]
> I figured something new out.
> I recently refactored my sitepacakge from
> `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig` in the `ext_localconf.php` to `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerPageTSConfigFile` in the `TCA/Overrides/tt_content.php` because I have two seperate plugins with their own RTE config so I can add the TSConfig in the "Resources" tab of the rootpage.
> 
> So what I noticed after I refactored it that the RTE config which is read in the Text.php via `BackendUtility::getPagesTSconfig($pageUid)['RTE.']` is empty. When I change it pack to `addPageTSConfig` its OK (But I cant use it this way because that ways one extension would overwrite the config of the another).
> 
> I also tried to put the RTE config Inline in the "Resources" Tab but that didn't worked either.
> 
> Maybe this helps to find the reason of this behaviour..

But this didnt work for me.... i changed to addPageTSConfig but it still dont work

**Comment by grischpel** [comment]
I tried now to override the default like its described on this page: https://docs.typo3.org/c/typo3/cms-rte-ckeditor/master/en-us/Configuration/Concepts.html but this wont work for flex forms..... Only for the standard elements

**Comment by X-Tender** [comment]
Where did you add your RTE preset config?
`RTE.default.preset = myPreset`   Is it in a TSConfig which is included in the Config you added via `addPageTSConfig`?

**Comment by grischpel** [comment]
> Where did you add your RTE preset config?
> `RTE.default.preset = myPreset` Is it in a TSConfig which is included in the Config you added via `addPageTSConfig`?

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::registerPageTSConfigFile('myproviderextension', 'Configuration/TSconfig/page.tsconfig', 'Hbstyle Settings');

i tried several methods:

`RTE {
    default.preset = own
    default.disabled = 0
    config {
      tt_content {
        bodytext {
          13.preset = own
          preset = own
          pi_flexform.preset = own
          13.preset = own
          type {
            textmedia.preset = own
            text.preset = own
            13.preset = own
          }
        }
        pi_flexform.preset = own
      }
      tx_news.teaser.preset = own
    }
}`

**Comment by X-Tender** [comment]
Did you added you preset to the `TYPO3_CONF_VARS`? in the `ext_localconf.php`
When you use `addPageTSConfig` you can do
`$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['own] = 'EXT:myextension/Configuration/RTE/Default.yaml';`
When you use Register you have to override the default one by doing
`$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'myextension/Configuration/RTE/Default.yaml';`
And then set in the TSConfig `RTE.default.preset = default`

**Comment by grischpel** [comment]
> Did you added you preset to the `TYPO3_CONF_VARS`? in the `ext_localconf.php`
> When you use `addPageTSConfig` you can do
> `$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['own] = 'EXT:myextension/Configuration/RTE/Default.yaml';`
> When you use Register you have to override the default one by doing
> `$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'myextension/Configuration/RTE/Default.yaml';`
> And then set in the TSConfig `RTE.default.preset = default`

if (empty($GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['own'])) {
    $GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['own'] = 'EXT:myproviderextension /Configuration/RTE/Own.yaml';
}

**Comment by X-Tender** [comment]
This only works when you use `addPageTSConfig`

**Comment by grischpel** [comment]
> This only works when you use `addPageTSConfig`

I will post the result here

**Comment by X-Tender** [comment]
Hmm thats odd, thats exactly the same setup I use.

**Comment by NamelessCoder** [comment]
I've committed a patch that should ensure the record context exists in the form, which should in turn provide the required context with page UID that gets used when resolving the pageTSconfig. If this doesn't solve the issue let me know!

**Comment by X-Tender** [comment]
It works.
Without the patch the RTE config didn't get applied to custom CEs, with the patch it does.
Thank you very much!

**Comment by NamelessCoder** [comment]
Thanks for the quick feedback :)

**Comment by grischpel** [comment]
It works 😁

**Comment by X-Tender** [comment]
Sorry to comment to the closed bug but I noticed that it only works "half". The tests I made before was tests on already placed CEs, lat week I noticed that when I create a new FLUX-CE that the RTE have the default configuration, after a Quick save the correct configured RTE Configuration gets applied. Should I create a new Issue? Maybe @grischpel could confirm that too.

**Comment by grischpel** [comment]
> Sorry to comment to the closed bug but I noticed that it only works "half". The tests I made before was tests on already placed CEs, lat week I noticed that when I create a new FLUX-CE that the RTE have the default configuration, after a Quick save the correct configured RTE Configuration gets applied. Should I create a new Issue? Maybe @grischpel could confirm that too.

Sorry, i cant confirm this.... for me it works perfect with version 9.4.1 beta

**Comment by X-Tender** [comment]
So when you create a new Flux-CE and it have a RTE in it then it already have the desired RTE configuration from the YAML applied?
