### ISSUE TITLE
History-Rollback on page for tt-content record throwing Flux-Exception from ProviderResolver::resolvePrimaryConfigurationProvider

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1809]
Flux Version: 9.3.2

Tried to rollback deleted tt-content record (plugin content-element) that were deleted accidently before. After executing rollback "single record" this error is thrown:

> (1/1) TypeError
> Argument 3 passed to FluidTYPO3\Flux\Provider\ProviderResolver::resolvePrimaryConfigurationProvider() must be of the type array or null, boolean given, called in /var/www/.../public/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php on line 339

Just in case this may be related:
The deleted plugin content-element was created on TYPO3 v9 and Flux 9.3.2 and was not part of the TYPO3 migration/upgrade that has been done some days ago. So I don't think the error is caused by the migration. The page that is affected by this issue exists before the migration to TYPO3 v9 and Flux 9.3.2 already.

**Comment by NamelessCoder** [comment]
This problem should be solved with Flux 9.4/9.4.1 - visibility restrictions are now ignored in DataHandlerSubscriber.

**Comment by OrangeLeinad** [comment]
I can confirm also, that this issue is solved with Flux V9.4.1. 

I ran into the same problem with TYPO3 V9.5.19 and Flux V9.3.2. After I updated to Flux V9.4.1 the rollback for deleted content elements was working again. Including nested content elements and images.
