### ISSUE TITLE
Missing appending Slash - RequireJS Link in Backend TYPO3 10

### ISSUE THREAD

**Issue by hrdyy** [FluidTYPO3/flux#1813]
The Link is generated without appending slash. So the Browser will generate a link like "/typo3/typo3conf/ext/flux" this results in an 404 for the fluxCollapse JS.

to patch this just add a slash, problem is the TYPO3 8 compatibility.

`         $fullJsPath = '/'. PathUtility::getRelativePath(
                defined('PATH_typo3') ? PATH_typo3 : Environment::getPublicPath(),
                GeneralUtility::getFileAbsFileName('EXT:flux/Resources/Public/js/')
            );`

https://github.com/FluidTYPO3/flux/blob/11732c98eb7909d413ffc572071879f74b208e65/Classes/Integration/HookSubscribers/Preview.php#L78

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/16d8f9b85b5b4b247883d10a9c363d998bf5fe5c
