### ISSUE TITLE
Error after upgrade to 9.4.1: RecursiveDirectoryIterator::__construct(//boot/lost+found): failed to open dir: Permission denied

### ISSUE THREAD

**Issue by marvinhinz** [FluidTYPO3/flux#1814]
After updating to 9.4.1 the following error occurs:

![image](https://user-images.githubusercontent.com/35603466/89303960-2a703f00-d66d-11ea-86eb-f5d0be26eb6a.png)

**Comment by NamelessCoder** [comment]
Hi @marvinhinz - can you provide a more complete stack trace?

Try also disabling the "plug and play" feature in extension configuration if you don't wish to use the global templates directory that Flux creates. Inability to resolve this directory could be the cause of this problem (though I'd expect som other directory than "lost+found" to be used...).

**Comment by marvinhinz** [comment]
[trace.html.txt](https://github.com/FluidTYPO3/flux/files/6930865/trace.html.txt)

Hi, took me a long time but heres a complete error page. Ill try disabling plug and play next

**Comment by NamelessCoder** [comment]
Best I could do here is to guard against empty-ish values of the plug-and-play directory extension setting. You've obviously solved your issue long, long ago - but this new guard should prevent anyone else from running into the same issue.
