### ISSUE TITLE
Using the duplicate button in CE throws PHP warning

### ISSUE THREAD

**Issue by nielsweb** [FluidTYPO3/flux#1816]
**TYPO3 9.5.20**
**EXT: flux 9.4.1**

If I duplicate a CE, the following PHP warning appears:
`PHP Warning: Cannot unset offset in a non-array variable in ... / www / public / typo3conf / ext / flux / Classes / Integration / HookSubscribers / DataHandlerSubscriber.php line 210`

This seems to be the case with all elements, not just with own CE.
Nothing is copied / duplicated.

**Comment by NamelessCoder** [comment]
This particular problem should be solved in `dev-development`. A release is coming.

**Comment by alexstocker** [comment]
**Reproduced with**
TYPO3 9.5.22
EXT: flux 9.4.1

`(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Cannot unset offset in a non-array variable in ... typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php line 210`

**Comment by simare** [comment]
We did a little testing and I could reproduce the error only when pasting using the list module.

TYPO3: 9.5.24
Flux: 9.4.1

**Comment by olegkarun** [comment]
Same for me. Bug just copy from list module
