### ISSUE TITLE
Integration with content_defender?

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#1818]
@NamelessCoder what do you think about this?
https://github.com/IchHabRecht/content_defender/issues/65

**Comment by NamelessCoder** [comment]
Needs a bit of investigation and testing but if I understand it correctly, this would be a viable replacement for a couple of hooks in Flux and we could provide a hook subscriber for content_defender to leverage the allow/disallow functionality from it. Which would be nice, if that works there's no reason for Flux to also provide the same logic.
