### ISSUE TITLE
Copying translated pages does not work properly

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#1819]
When you copy whole page with translations than translated children have wrong colPos.
Test case:
We did extracted test - clean Typo3 9.5.19, on introduction package. Flux 9.4.1, vhs 6.0.3 and test_provider_extension (https://github.com/FluidTYPO3/test_provider_extension/) installed.
Screencast from test https://www.loom.com/share/2a6c7f58cc994e25a25a3c795a7de3d5

**Comment by NamelessCoder** [comment]
The linked commit should take care of this problem - would be great if you can test and confirm!

**Comment by rupasix** [comment]
Yep, seems to be working fine. Thanks!
