### ISSUE TITLE
[TYPO3 10]Uncaught Error: Script error for "FluidTypo3/Flux/FluxCollapse"

### ISSUE THREAD

**Issue by guelzow** [FluidTYPO3/flux#1820]
Hi everyone.

Not sure if this is a core bug . . .

When having the following backend url:
`http://php73.servername.xx/somedirectory/docroot/typo3`
with TYPO3 10.4.6

The backend fails to load the FluxCollapse js.
RequireJs tries the following url:
`http://php73.servername.xx/somedirectory/docroot/typo3/typo3conf/ext/flux/Resources/Public/js/fluxCollapse.js`

The path to the script is assigned here:
https://github.com/FluidTYPO3/flux/blob/9.4.1/Classes/Integration/HookSubscribers/Preview.php#L78

Possible Solutions:
Using the standard `$pageRenderer->loadRequireJsModule();` should work. We use it a lot in BE context.

Tobi

**Comment by NamelessCoder** [comment]
Hey Tobi,

The insertion happens in \FluidTYPO3\Flux\Integration\HookSubscribers\Preview::attachAssets - a pull request would be much appreciated! I'm planning to do a release either today or tomorrow ;)

**Comment by guelzow** [comment]
Hi Claus

I'll see what I can do tomorrow.

Tobi

**Comment by w010** [comment]
Confirmed - the same error here on 10.4.6.
Quick solution:
Classes/Integration/HookSubscribers/Preview.php:84
```
$pageRenderer->addRequireJsConfiguration([
                'paths' => [
                    // 'FluidTypo3/Flux/FluxCollapse' => $fullJsPath . 'fluxCollapse',
// q3i fix - console error in be... wrong path
                    'FluidTypo3/Flux/FluxCollapse' => '/' . $fullJsPath . 'fluxCollapse',
                ],
            ]);
```
