### ISSUE TITLE
flux:wizard.link broken

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/flux#1822]
On TYPO3 10.4.6 and flux 9.4.1 dev branch from github the following code does only generate a plain input field in the CMS with no link wizard, so probably flux:wizard.link is broken right now:

``
<flux:field.input name="link" label="Link">
            <flux:wizard.link />
</flux:field.input>
``

**Comment by shuffgy** [comment]
https://github.com/FluidTYPO3/flux/issues/1780#issuecomment-626071716 fixed it for me

**Comment by NamelessCoder** [comment]
Wizards no longer exist on 10.4 - the only way is to use `renderType` as described by @shuffgy above.
