### ISSUE TITLE
showIconTable doesn't work

### ISSUE THREAD

**Issue by bwasnie1** [FluidTYPO3/flux#1830]
Hi there,

I was working with the new `flux:field` element and configured `showIconTable: '1'` in the `config` attribute:

```
<flux:field type="select" name="header.type" label="flux:field"  config="{
      renderType: 'selectSingle',
      showIconTable: '1',
      items: {
         0:{0:'On the left side',1:'left', 2:'EXT:myext/Resources/Public/Images/BackendLayouts/default.jpg'},
         1:{0:'On the right side',1:'right', 2:'EXT:myext/Resources/Public/Images/BackendLayouts/sidebar.jpg'}
       }
}"/>
```

**Result:**
![image](https://user-images.githubusercontent.com/3907591/93866709-53ee3400-fcc8-11ea-9577-07d457a2280f.png)

When I use the deprecated `flux:field.select` field with `showIconTable="1"` everything works fine:
![image](https://user-images.githubusercontent.com/3907591/93867207-01614780-fcc9-11ea-925e-c1f0b2b37c2c.png)

Did I miss something?

**System:**
TYPO3 10.4.8
Flux: 9.4.1

**Comment by NamelessCoder** [comment]
Hi @bwasnie1,

Flux is merely a wrapper around TCA so it is TCA (on your specific TYPO3 version) which dictates how to achieve a certain rendering. You can find the TCA documentation on https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ - make sure you select the documentation for your specific TYPO3 version.

**Comment by NamelessCoder** [comment]
TCA docs appear to be wrong about this specific option being available (it says it is, but it clearly isn't).

TCA array which works:

```
                'fieldWizard' => [
                    'selectIcons' => [
                        'disabled' => false
                    ]
                ]
```

**Comment by bwasnie1** [comment]
Hi @NamelessCoder,

thank you for your answer!

If anybody else is facing the issue, this solution works:

```
<flux:field type="select" name="header.type" label="flux:field" config="{
        renderType: 'selectSingle',
        showIconTable: '1',
        fieldWizard: {
            selectIcons: {
                 disabled: '0'
             }
         },
         items: {
            0:{0:'On the left side',1:'left', 2:'EXT:myext/Resources/Public/Images/BackendLayouts/default.jpg'},
            1:{0:'On the right side',1:'right', 2:'EXT:myext/Resources/Public/Images/BackendLayouts/sidebar.jpg'}
          }
 }"/>
```
