### ISSUE TITLE
flux:form.field.file -> flux:form.field.inline.fal upgrade wizard

### ISSUE THREAD

**Issue by TrueType** [FluidTYPO3/flux#1831]
going from EXT:flux v8->v9 simple file references need to be moved. Possibly many.

This is an upgrade wizard I used for that purpose:
https://gist.github.com/TrueType/d758efd18a37bdc5bd927764eadb6225

see also: 
TYPO3v9 EXT:install comes with an upgrade wizard to fe_users.image records into sys_file_reference

**Comment by NamelessCoder** [comment]
Published on https://fluidtypo3.org/library/code-examples.html?tx_fluidshare_display%5Baction%5D=display&tx_fluidshare_display%5Bcontroller%5D=Gist&tx_fluidshare_display%5Bgist%5D=39&cHash=a64a74782d1ffa970a45d00d95556a21 - thanks!

**Comment by Chris-shari** [comment]
This belongs into a documentation or ReadMe as this will likely affect many others.
