### ISSUE TITLE
AbstractProvider->getForm crashes, if no flux:form is available

### ISSUE THREAD

**Issue by j0nnybrav079** [FluidTYPO3/flux#1833]
If a flux page/content template does not need/include a form, the method AbstractProvider->getForm crashes, because $form is null/not an object.

As mentioned in https://typo3.slack.com/archives/C46LPB516/p1601305697031800, the solution is, to create an empty form as fallback.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/64fc2daa4034937ffb9616a5fa5e57ec58391e35
