### ISSUE TITLE
Exception "Directory name must not be empty" when design/Templates/Content does not exist

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1835]
This happens with flux 9.4.2 on TYPO3 9.5.9, with "Plug-and-play templates" (basic.plugAndPlay) enabled.

When the directory `$basepath . '/design/Templates/Content` does not exist, I get an exception:

> (1/1) RuntimeException
> Directory name must not be empty.
in /var/www/site/htdocs/typo3_src/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php line 48
> [...]
> in /var/www/site/htdocs/typo3conf/ext/flux/Classes/Content/TypeDefinition/FluidFileBased/DropInContentTypeDefinition.php line 92

(The exception does not happen when `basic.plugAndPlay` is disabled.)

I think that this is a bug because the code in `DropInContentTypeDefinition.php` actually has a `catch(DirectoryNotFoundException)`, but that is circumvented:

```
$contentTypesPath = realpath($basePath . static::TEMPLATES_DIRECTORY . static::CONTENT_DIRECTORY) . '/';
```

`realpath()` returns `false` here, but manually appending the trailing slash makes that a string again, a valid directory: `/`.

Removing the manual trailing slash solves the problem.

**Comment by typo3rel** [comment]
Hi,
This is also a Problem with open_basedir.
I want to use plugAndPlay but i always get 
`open_basedir restriction in effect. File(/) is not within the allowed path(s)`

in line 80 the path returned from GeneralUtility::getFileAbsFileName($basePath) is correct but after $basePath = realpath(GeneralUtility::getFileAbsFileName($basePath)) . '/'; it is only a '/'

**Comment by NamelessCoder** [comment]
> Removing the manual trailing slash solves the problem.

This trailing slash was removed in a recent commit - I noticed that the generated path contained a double `//` so this may have been a contributing factor.
