### ISSUE TITLE
showRecordFieldList inside the section 'interface' is not evaluated anymore

### ISSUE THREAD

**Issue by TrueType** [FluidTYPO3/flux#1839]
Have a nice day... 

.... this is reported in TCA migration wizard in TYPO3v10. 

The 'content_types' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed.

flux/Configuration/TCA/content_types.php

**Comment by NamelessCoder** [comment]
Fixed with https://github.com/FluidTYPO3/flux/commit/d4a987c17ae649bedbcf84014e57ecf270a5117a
