### ISSUE TITLE
A custom ContentController is not found nor used

### ISSUE THREAD

**Issue by dogawaf** [FluidTYPO3/flux#1841]
Hi

We made a mistake while declaring the content provider : 

`\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Site.site', 'Content');`

instead of 

`\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Site.Site', 'Content');` (see the uppercase `S` in the extension name).

The wrong declaration leads Flux to create a class_alias for `Site\site\Controller\Content` which does not exist. `Site\Site\Controller\Content` does exist.
See `\FluidTYPO3\Flux\Integration\ContentTypeBuilder::configureContentTypeFromTemplateFile`.

The symptom is quite hard to debug. Imagine your declare your content controller and create an action for your content `MyTemplate.html`:

```
namespace Site\Site\Controller;

class ContentController extends \FluidTYPO3\Flux\Controller\ContentController {
    public function myTemplateAction()
    {
        return 'Hello world!';
    }
}
```

Your action will never be called, because flux created an alias of `FluidTYPO3\Flux\Controller\ContentController` named `Site\site\Controller\ContentController` and will use it (you tell him to do by your spelling mistake). This alias does not contain `myTemplateAction`.

The same mistake with `\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin` does not produce any error, because Extbase passes the extension name through `ucwords`.
See `\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin`

I create this issue for the records.
But maybe Flux can adopt the same logic than Extbase when parsing the vendor and extension names.

Cheers.

**Comment by NamelessCoder** [comment]
This problem should be fixed (some time ago), through the use of Flux's ExtensionNamingUtility. Each part of the expected FQN is processed by this utility when creating the expected class name - so even if you make a mistake in the upper/lower case of the extension name when registering the provider extension, the resulting class names should be OK.
