### ISSUE TITLE
Where's the viewhelper-Reference gone?

### ISSUE THREAD

**Issue by update-switzerland** [FluidTYPO3/flux#1844]
Sorry, not really an issue with the code, but I was looking for the viewhelper reference and it seems to be gone?

This link: https://fluidtypo3.org/viewhelpers/flux.html shows me a T3-Error page.

Where can I find the viewhelper reference now?

**Comment by mnmleichtweismarco** [comment]
Does the link help you? 
https://viewhelpers.fluidtypo3.org/fluidtypo3/flux/

**Comment by update-switzerland** [comment]
Splendid! Thanks a ton!
