### ISSUE TITLE
Column headlines not shown in translations

### ISSUE THREAD

**Issue by koehnlein** [FluidTYPO3/flux#1850]
Hi,

I'm using flux 9.4.2 in an installation with latest TYPO3 10.4. Unfortunately, the flux column headlines do not show the correct text, but only the value of the colPos field. (orange boxes)

The TYPO3 internal headlines and the flux column headlines in default language are shown correctly (green boxes)

![flux-column-headlines](https://user-images.githubusercontent.com/16088567/99691636-bc1f8300-2a89-11eb-8bb1-463fb2851bc6.png)

**Comment by koehnlein** [comment]
I just saw, this problem already existed and once was fixed in #1620

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/pull/1851
