### ISSUE TITLE
Updated documentation or working sample provider extension 

### ISSUE THREAD

**Issue by luberti** [FluidTYPO3/flux#1852]
Hello, can someone point to updated flux documentation and/or a sample provider extension?
Documentation here 

https://fluidtypo3.org/documentation/templating-manual/introduction.html

seems outdated since refers a EXT:builder extension that doesn't seem to exist on TER and also refers EXT:fluidcontent that has been dismissed.

TIA

**Comment by NamelessCoder** [comment]
Example provider: https://github.com/FluidTYPO3/test_provider_extension

EXT:builder is on TER - https://extensions.typo3.org/extension/builder - but is not yet updated there to reflect fluidpages/fluidcontent being obsolete and is not v10 compatible. I'd suggest installing it from the `dev-development` branch.

**Comment by luberti** [comment]
Thank you for some reason using EM in TYPO3 10 to search TER for 'builder' string didn't retrieve EXT:builde so I assumed it wasn't on TER anymore
