### ISSUE TITLE
Missing CE Group Names

### ISSUE THREAD

**Issue by kledo-34** [FluidTYPO3/flux#1855]
Hey there, 
I just updated to typo3 10 and also to the latest flux version.
In the Backend the Content Elements are still presented inside their correct groups, but the group names got lost somewhere along the way, because they are all set to '-'.
I would be very happy for a little fix ;)
![Screenshot](https://user-images.githubusercontent.com/59743815/101393621-ad2d3300-38c7-11eb-9fb9-e9a4bf6edf1f.png)
I defined the group through <flux:form.option.group value="groupname"/>

**Comment by kledo-34** [comment]
I defined the group through <flux:form.option.group value="groupname"/>

**Comment by kledo-34** [comment]
If it helps something, the $groupName variable in ContentTypeBuilder.php is still correct, but after sprintf(...) the group name seems to be gone for some reason.

**Comment by chriskrj** [comment]
Did you also added something like this to your `locallang.xlf` ?
That worked out for me: (Also used this in TYPO3 9 Projects)

```html
<flux:form.option name="settings.options">
  <flux:form.option.group value="Teaser"/>
</flux:form.option>
```

```xlf
<trans-unit id="flux.newContentWizard.Teaser"><source>Teaser</source></trans-unit>
<trans-unit id="flux.newContentWizard.Develop"><source>Develop</source></trans-unit>
```

**Comment by kledo-34** [comment]
Yeah, thanks a lot, you are right, I had no need to localize until now, but it works and it's easy to add, thanks a lot for the solution.

Apart from that solution, is this wanted behaviour, in versions before everything worked without localization aswell, if it's wanted behaviour we can close this issue.
