### ISSUE TITLE
Flux.field.file Error

### ISSUE THREAD

**Issue by kledo-34** [FluidTYPO3/flux#1856]
Hey there,
after updating to Typo3 10 and the latest flux version I encountered an error for all the flux.field.file elements.
It says that internalType needs to be either db or folder, so if I set internalType="folder", it works again.
But setting it to folder or db breaks the functionality for choosing it.
The fields that are already in the database created by older versions are still rendering correctly in the frontend, so maybe this functionality for choosing files could be brought back.
Nevertheless are there any suggestions for better solutions? I know that field.file is deprecated and FAL should be used more. My current situation is that i have images as well as audio and video chosen by flux:field:file and additionaly I sometimes have those nested inside of sections or objects. Is there any suggestion for a new long lasting solution for those usecases (especially the nested ones, as I don't know a real alternative here except maybe just inserting links and rendering them in the correct place in the frontend)

Additionally, am I correct that everything is going to be shifted to flux:field like the Link wizard did ? Is there a documentation about it's values because I can't find anything over here https://viewhelpers.fluidtypo3.org/fluidtypo3/flux/9.0.1/Wizard/Link.html

Thanks for maintaining this great extension, this is definitely the best typo3 extesnion in my opinion, so keep on going ;)

**Edit**: If someone knows how to access the fieldControl options of flux:field with renderType Link I could go on with that, I would be really happy for that ;)

I tried the following without success:
`<flux:field name="somename" label="somelabel" type="input" config="{renderType: 'inputLink', fieldControl: "{linkPopup: '{options: '{allowedExtensions: \'mp4\', blindLinkOptions: \'file\'}'}'}"}"/>`

**Comment by kledo-34** [comment]
I forgot to mention, that setting it to folder or db breaks the functionality so is there a new suggestion. I know that it is deprecated and FAL should be used more. My current situation is that i have images as well as audio and video chosen by flux:field:file and additionaly I sometimes have those nested inside of sections or objects. Is there any suggestion for a new long lasting solution for those use cases (especially the nested ones, as I don't know a real alternative here)

**Comment by kledo-34** [comment]
I found the correct Syntax 
Nesting can be kind of hard
`config="{renderType: 'inputLink', fieldControl: {linkPopup: {options: {allowedExtensions: 'jpg,png,gif', blindLinkFields: 'class,params,target,title', blindLinkOptions: 'folder,mail,page,spec,telephone,url'}}}}" `

I changed all of my fields to this new flux.field type with the config attribute, hopefully this structure will be maintained. By the way is there a new version for sections and objects or do they stay the way they are?

**Comment by NamelessCoder** [comment]
Copying my reply from #1803 so it can also be found here:

> By the way is there a new version for sections and objects or do they stay the way they are?

These will stay the same, they are not expected in any way to receive new properties by the core. The reason why the fields are migrated to a more generic structure is that there have been (major) TCA changes from 8.7 to 9.5 and again to 10.4 which made it unfeasible to maintain the more specific wrappers. So instead you get the generic version and have to fine-tune the properties to match the target TYPO3 version.
