### ISSUE TITLE
"Available content type" selector didn't work when P&P is disabled and empty

### ISSUE THREAD

**Issue by X-Tender** [FluidTYPO3/flux#1866]
I noticed that the _Available content type_ list in the _Flux Provider_ of the sites Configuration only list my Fluid based Content Elements of my plugin when _Plug & Play_ is enabled and at least one (can be stupid and empty) CE is placed in the `public/design/Templates/Content`.

When I delete the CE or disable P&P then the list is empty.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/ad2bcab291ba87d5451e9b253ff74fc6d7e6a445
