### ISSUE TITLE
flux.form config aren't inherited to child pages in page properties if site root id = 1

### ISSUE THREAD

**Issue by kalypso63** [FluidTYPO3/flux#1872]
Hi,

I have a problem with My instance TYPO3 9.5.35 & Flux 9.4.2. I have 2 pages templates (home & standard). with the following properties:

Home : 

`<f:section name="Configuration">
    <flux:form id="home" label="Homepage">
        <flux:field.input name="settings.title"  />
    </flux:form>
    <flux:grid>
        <flux:grid.row>
            <flux:grid.column colPos="0" name="content" label="Content"/>
        </flux:grid.row>
    </flux:grid>
</f:section>`

Standard : 

`
<f:section name="Configuration">
    <flux:form id="standard" label="Standard">
        <flux:field.select label="Display menu" name="settings.titre" items="{0:'With',1:'Without'}" default="0"/>
    </flux:form>
    <flux:grid>
        <flux:grid.row>
            <flux:grid.column colPos="0" name="content" label="Content"/>
        </flux:grid.row>
    </flux:grid>
</f:section>
`

When I edit my home page which is root the field tx_fed_page_flexform_sub don't get the properties of standard page.

With flux 9.2 all is good.

Don't know if bug or feature.

Thanks in advance.

**Comment by NamelessCoder** [comment]
Closing; inheritance issues are solved in `dev-development`.
