### ISSUE TITLE
Flux 9.4.2 "hybrid mode" using only Content-Elements (No Flux-Pages) seems to be broken?

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1879]
I've upgraded to Flux 9.4.2 in one TYPO3 instance being migrated to TYPO3 v9. The Page-Rendering/Templates are configured for classical TS-Config Page-Grid (pagets) and FLUID.

After upgrading Flux to 9.4.2 the Page Module is broken. Everytime opening the Page Module and selecting a Page to be displayed in backend I'm getting this Exception that looks like Flux is trying to do something, it shouldn't do.

The Page-Templates definetly are not using Flux-Fluid Elements and the Flux-Namespace is removed / not present! So nothing that indicates the Template should have anything to do with Flux making Flux anything here trying to open the Page in backend.

In previous flux versions this was working fine after removing all Flux redundant stuff in Page-Templates and using native page-rendering and grid.

**Comment by typoworx-de** [comment]
Just checked with Flux 9.4.1 it works as expected. So Page rendering is working without any Flux Page-Hooks and FCE's are working as expected.

**Comment by typoworx-de** [comment]
Ok - just noticed on Flux 9.4.1 its only working parital. The good news there is no totally annoying and destroying Exception compared to 9.4.2.

But this is showing up. This should not happen having no Page-Template registered. Or is there anything to explicitly disable Page-Template usage?
![image](https://user-images.githubusercontent.com/1282298/113280986-4fdd4780-92e5-11eb-8a01-9eb9f726ebfd.png)

**Comment by NamelessCoder** [comment]
I've added an extension config toggle that allows you to switch off the entire page integration (the integration will be enabled by default but can be disabled by unchecking the option in extension config of Flux), which is significantly easier than having to clear the `page.5´ TS object and disabling/removing the TCA fields that get added. This should help compatibility with sites that don't want to use the page-related features but still want the content-related features. It will be part of the next release.

Without the new feature toggle it should still be enough to clear the `page.5` TS object to disable the majority of the integration. At least it would stop Flux from attempting to render page in FE which appears to be where your error message happens.
