### ISSUE TITLE
Test with 11.2.0-dev & development branch: some errors

### ISSUE THREAD

**Issue by supercaccia** [FluidTYPO3/flux#1882]
[frontend - t3master- TYPO3 CMS 11.2.0-dev.pdf](https://github.com/FluidTYPO3/flux/files/6371450/frontend.-.t3master-.TYPO3.CMS.11.2.0-dev.pdf)
[backend - t3master- TYPO3 CMS 11.2.0-dev.pdf](https://github.com/FluidTYPO3/flux/files/6371451/backend.-.t3master-.TYPO3.CMS.11.2.0-dev.pdf)

I test the development branch with my extension "theme" based on Flux.
With version 10 everything ok, with version 11.2.0-dev i have encountered the problems reported in the attached pdfs

_The property "extensionStaticsProcessed" on the subject does not exist + Call to a member function getControllerExtensionName() on null_

**Comment by NamelessCoder** [comment]
Solved in current development branch!
