### ISSUE TITLE
flux:grid preview not shown in news extension

### ISSUE THREAD

**Issue by regioadmin** [FluidTYPO3/flux#1886]
Hello - I'm on a step by step upgrade from typo3 7.6 to 8, 9, 10.
At the moment my site is on 8.7.. Flux was upgraded to 9.4.2.
There is an issue whith flux gridelements in NEWS extension in BE under "content elements".
I'm not able to add content to cols, because preview is not working. See  https://pasteboard.co/K0tWcNd.png  (on top "2 Col Grid" in News with missing "+Content" buttons / below working preview on a standard page)
`<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	 xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	 xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	 xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">
 
	<f:layout name="Content"/>
 
	<f:section name="Configuration">
		<flux:form id="gridelementtwocol" localLanguageFileRelativePath="/Resources/Private/Language/locallang_gridelements.xlf">
			
			<flux:form.option name="group" value="Grid-Elemente"/>
			<flux:form.option name="Fluidcontent" value="{sorting: 3}"/>
 
			
			<flux:field.input name="colWidthLeft" default="6"/>
			<flux:field.input name="colWidthRight" default="6"/>
	
 
 
			<flux:grid>
				<flux:grid.row>
					<flux:grid.column name="left" colPos="1" style="width: 50%;"/>
					<flux:grid.column name="right" colPos="2" style="width: 50%;"/>
				</flux:grid.row>
			</flux:grid>
 
		</flux:form>
	</f:section>
 
	<f:section name="Preview">
		<strong>Gridelement 2 Cols</strong><br>
		<div style="width: 100%; border-bottom: 1px solid #000;">			
		</div>
	</f:section>
 
 
	<f:section name="Main">
		<div class="row">
			<div class="col-md-{colWidthLeft}">
				<flux:content.render area="left"/>
			</div>
			<div class="col-md-{colWidthRight}">
				<flux:content.render area="right"/>
			</div>
		</div>
	</f:section>
 
</div>`

**Comment by NamelessCoder** [comment]
This is a limitation of any content type (not just Flux) when rendered inline - this happens outside of a page layout context and the preview is therefore never rendered.

There are two ways to work around this:

1. You can switch to the page module and select the sysfolder where news is stored. Unfortunately this renders all nested content but if you clearly marked the grid container element it should be possible to find it. Nested content can then be inserted as usual.
2. You can emulate an `inline` relation in the Flux form fields and edit the nested content in the same way that News renders its nested content. Add: `<flux:field.inline name="content" table="tt_content" foreignMatchFields="{colPos: '{record.uid}00'}" foreignField="rowDescription"/>`. The example code adds an `inline` field that lets you edit content within the nested column with `colPos="0"` in the Flux grid. The trick here is that:
   * There *must* be a `foreignField` but you can set it to any unused field capable of storing an integer.
   * The specially crafted `foreignMatchField` must be used to ensure that any content you place here is automatically fitted with the right calculated `colPos` value, and when loading the content only the associated content is fetched.
   * You can actually move the nested content between columns of the Flux grid by switching the value in the `colPos` selector. Or you can of course add one `inline` field per nested content column in the grid.
