### ISSUE TITLE
Button to hide/show the grid of a CE is no longer appearing.

### ISSUE THREAD

**Issue by X-Tender** [FluidTYPO3/flux#1887]
I've noticed it in the 10.4.15 version. In 10.4.9 it worked.

During my xdebug journey I noticed that inside the `ContentIcon.php` he always exit the method in the first ìf` statement.
Maybe because the `PageLayoutView` is deprecated

```php
    public function addSubIcon(array $parameters, $caller = null)
    {
        if (!$caller instanceof PageLayoutView) {
            return '';
        }
....
```

Looks like it have something to do with _Fluid based page module_. When I disable the feature the button appear again,

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/pull/1885
