### ISSUE TITLE
Suggest wizard 

### ISSUE THREAD

**Issue by kalypso63** [FluidTYPO3/flux#1888]
Hello guys. I have a problem after migrate my TYPO3 instance to TYPO3 9 and Flux 9.4.2. My wizard suggest return an 500 error.

My field config 

```
<flux:field type="group"
                        name="link2"
                        label="Link2"
                        config="{internal_type: 'db', allowed: 'pages', maxitems: 10, minitems: 0, size: 10, default: 0, suggestOptions: default: {additionalSearchFields: 'nav_title, alias, url', addWhere: 'AND pages.doktype = 1'} }" />
```

Error is Specified path link2 not found in flex form data structure on typo3/sysext/backend/Classes/Controller/Wizard/SuggestWizardController.php line 74

Could you help me ?

Thanks in advance.

**Comment by ogrosko** [comment]
Can confirm same behavior here.
@kalypso63 did you find a solution?

**Comment by cweiske** [comment]
Same here with TYPO3 10.4.17 and flux 9.5.0

**Comment by NamelessCoder** [comment]
TCEForms wrapper is re-introduced in https://github.com/FluidTYPO3/flux/commit/983e5c4c1aaba0e8ab4a05c7179377ee514cc7af
