### ISSUE TITLE
"Clear value" wizard in page config not present any more

### ISSUE THREAD

**Issue by yol** [FluidTYPO3/flux#1894]
Adding wizards via `['config']['wizards']` was removed for TYPO3 8.6: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Deprecation-79440-TcaChanges.html

The "clear value" wizard (rendered when `clearable="1"` on a form field) is still being included with this method: https://github.com/FluidTYPO3/flux/blob/3121e6d/Classes/Form/AbstractFormField.php#L227-L235

As far as I can tell, this should not work any more with any TYPO3 version supported by current vhs. It would have to be replaced with one of the new wizard registration methods.

**Comment by cweiske** [comment]
Flux needs to convert the old "renderClearValueWizardField" into a FieldControl class as described in https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/FormEngine/Rendering/Index.html#node-expansion

(The field tag attribute is `clear="1"`, not "clearable".)

**Comment by NamelessCoder** [comment]
Solved with the PR contributed by @cweiske
