### ISSUE TITLE
Move flux:grid elements with deleted contents results in error message and prevents drag & drop

### ISSUE THREAD

**Issue by mschmitz89** [FluidTYPO3/flux#1896]
Reproduced on 10.4.17 with flux 9.5

When moving a grid content element with flux:grid in which another content element was previously deleted, an error message appears preventing drag & drop. Only after reloading the page the element is at the desired location.

Error is for example this, where tt_content:451 is the previously deleted content element placed inside the grid element.
> 1: Attempt to move record 'test123' (tt_content:451) without having permissions to do so.

If the content element marked as deleted is completely deleted from the database, then drag & drop will work again.

One example from the Configuration section of one of these grid elements:

```
<f:section name="Configuration">
	<flux:form description="LLL:EXT:test_extension/Resources/Private/Language/locallang.xlf:50grid.description" id="Grid50"
		   label="LLL:EXT:test_extension/Resources/Private/Language/locallang.xlf:50grid"
		   options="{group:'grid', icon:'EXT:test_extension/Resources/Public/Icons/Content/50grid.gif'}">
	    <flux:grid>
		<flux:grid.row>
		    <flux:grid.column colPos="0" label="Left" name="left"></flux:grid.column>
		    <flux:grid.column colPos="1" label="Right" name="right"></flux:grid.column>
		</flux:grid.row>
	    </flux:grid>
	</flux:form>
</f:section>
```

Does anybody has a hint or maybe can verify this as a bug?

Thanks!

**Comment by timonkreis** [comment]
I'm pretty sure this is related to #1704. This bug was fixed but then reverted (maybe by accident) in #1745.

**Comment by mschmitz89** [comment]
Will this fix be part of the next minor release of flux?

**Comment by peterreichenbach** [comment]
it is not possible anymore to do anything with restricted (hidden, starttime, endtime, fe_group) content elements.
restriction in getSingleRecordWithRestrictions should be only "deleted".
https://github.com/FluidTYPO3/flux/commit/d0e4db3e957d4a7bccf743ce690f940b0fefcba2#commitcomment-63867229
