### ISSUE TITLE
Inheritance of settings will be overwritten by saving pages

### ISSUE THREAD

**Issue by dkern** [FluidTYPO3/flux#1900]
Hello!

I have encountered a problem that I do not know how to fix of if this is a bug. I have created page templates, and assigned a setting (select box) to them. Now in the backend I can set this setting for _this page_ and all _subpages_. This works so far.

As an example, we assume the following page structure:

```
- Root Page
  - My Subpage
```  

On the `root page`, we assume the value of our setting is `foo`, for both _this page_ and all _subpages_. When I now open the page settings of `my subpage`, I can see that the setting has `foo` pre-selected because of the inheritance.

But here comes the problem. When I _save_ the config of `my subpage` all settings, including the inherited value `foo` will be written to the database. This means, every time I save the settings of a page, the inheritance of all subpage will break on this point.

Is this a bug, or is there any way how I can prevent the settings will be overwritten when I save the settings of pages?

Thank you in advance.

**Comment by NamelessCoder** [comment]
This behavior has now been restored - when you save a page record, Flux will destroy any value in the settings if those values either match the inherited value or is set to a truly empty value (e.g. if the field was cleared by the checkbox added if you set `clear="1"` on the Flux field).
