### ISSUE TITLE
TYPO3 v8.7.32 Could not fetch page data for uid 0

### ISSUE THREAD

**Issue by supercaccia** [FluidTYPO3/flux#1912]
This error appeasrs only with **dev-development branch**, with dev-master branch works correctly.

The error "Could not fetch page data for uid 0" appears in **TYPO3 v8** when you try insert contents into a page (TYPO3 v10 ok)

Possible cause: https://github.com/FluidTYPO3/flux/commit/86220d1072b7a9716358a42768adbbbd75cb1df1

[See attached Stack Trace](https://github.com/FluidTYPO3/flux/files/7659915/v8-rootline.pdf)

It's a core problem, solved in v10:

![core-bug](https://user-images.githubusercontent.com/7404955/145588490-137cb34f-70f5-4ed0-89f4-2c69fe55880d.png)

I propose to add in the file "flux/Classes/Provider/PageProvider.php":

![soluzione](https://user-images.githubusercontent.com/7404955/145591618-fa2d0d40-1f0a-4277-9a25-ea8ef7f3e0ee.png)

Can it work in your opinion?

**Comment by cweiske** [comment]
I confirm this bug exists on TYPO3 v8.7.32 and flux 9.5.0.
The suggested change fixes the problem.

The error occurs when creating a new content element, and when copying pages with content elements.
