### ISSUE TITLE
New Page-Template or Content Template not visible in Backend

### ISSUE THREAD

**Issue by ghwaldo** [FluidTYPO3/flux#1920]
TYPO3 10.4.23
FLUX 9.50

I have used the builder-extnsion to create a new provider extension and installed it. All went right and i can choose the page layout "Example", add some content then output in the frontend is as it should be. The only extension that is also installed is vhs. All via git clone.

I duplicated the Example.html in Resources/Private/Templates/Page and named in Subpage.html.
In this file i only changed <flux:form id="subpage">

After clearing all caches i cannot see the page layout in the dropdown list.

I also duplicated Example.html unter Resources/Private/Templates/Content, renamed it and changed <flux:form id="anything">.

Also this does not appear under available content elements.

Perhaps it is not an issue. Perhaps documentation is not up to date. I also tries to add Foo.html as described in Documentation. But this also does not work.

Kind regards

Additional: i delete Example.html from Content-Layouts. In Backend content wizzard no more fces appear, after renaming my own elemt to Example.html it shows up.
Seems TYPO3 only looks for Example.html, all other template files are ignored.

**Comment by NamelessCoder** [comment]
It's possible that templates generated by EXT:builder have fallen a bit behind in terms of compatibility. For a recent reference about what a currently compatible page template should contain, I suggest https://github.com/FluidTYPO3/test_provider_extension.

I checked the boilerplate templates in EXT:builder but didn't find any obvious issues that should result in an incompatible template being generated. If you still face this issue (with the `dev-development` branch of EXT:builder) then I'd appreciate a bug report on https://github.com/FluidTYPO3/builder/issues :)
