### ISSUE TITLE
Rename cache_runtime

### ISSUE THREAD

**Issue by jonaseberle** [FluidTYPO3/flux#1923]
I am getting deprecation entries
```
component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Accessing a cache with the "cache_" prefix as in "cache_runtime" is not necessary anymore, and should be called without the cache prefix. in /var/www/html/public/typo3/sysext/core/Classes/Cache/CacheManager.php line 150
```

This line uses `cache_runtime`:

https://github.com/FluidTYPO3/flux/blob/3cc50474d8504bbbf2b043410b04110882332b69/Classes/Content/ContentTypeManager.php#L119

References:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-88366-DefaultCachingFrameworkCacheNamesChanged.html
The requirement seems arbitrary but it's also easy to change it.

**Comment by supercaccia** [comment]
It is a good observation but the modification should not be done on flux v9 because it must remain compatible with TYPO3 8.7.

This change should be made on a hypothetical "flux v10 version" :)

**Comment by NamelessCoder** [comment]
Fixed via https://github.com/FluidTYPO3/flux/commit/3c944b576e01745d0c77f49e977df539597b7b81
