### ISSUE TITLE
Bug with area containing numeric with "e" letter

### ISSUE THREAD

**Issue by Vincent-typo3-sp** [FluidTYPO3/flux#1931]
~~if (!is_numeric($columnPosition)) {~~

can be replaced with:

if (!ctype_digit($columnPosition)) {

https://github.com/FluidTYPO3/flux/blob/3cc50474d8504bbbf2b043410b04110882332b69/Classes/ViewHelpers/Content/GetViewHelper.php#L174

**Comment by NamelessCoder** [comment]
Nice catch, @Vincent-typo3-sp!
