### ISSUE TITLE
Class Page does not exist. Reflection failed.

### ISSUE THREAD

**Issue by artur-grigoryan-cgn** [FluidTYPO3/flux#1932]
Hello,
after installing Flux i get the follong exception in TYPO3 11.5.8:
![ksnip_20220326-233104](https://user-images.githubusercontent.com/16120407/160259762-d0ebde34-0c38-401f-a1d1-6e353770289d.png)
Did i do something wrong?
Regards

**Comment by artur-grigoryan-cgn** [comment]
Seems to be fixed in dev-developed.  :)

**Comment by lucmuller** [comment]
We're using the extension in dev-development and composer on TYPO3 11.5.8 we reproduce the error.
imho error still exists.

Any workaround if you say that it's solved ?

**Comment by lucmuller** [comment]
Openend #1940

**Comment by lucmuller** [comment]
Regarding the caches :
we cleared them several times, and rebuild autoload either using composer of native backend functions
regarding the database, everything seems to be ok with the fields regarding flux extension.

**Comment by lucmuller** [comment]
ok, we got it.
The issue is solved in the current development branch, but seems to not be released on packagist at the moment.
the issue on our second instance was related to another problem.
