### ISSUE TITLE
New upgrade wizard for problematic content element "sorting" values breaks upgrade wizard in TYPO3 11

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/flux#1934]
The new upgrade wizard for ` [FEATURE] Upgrade wizard for problematic content element "sorting" values`  breaks the upgrade wizard BE module in TYPO3 11.5.8. Introduced in commit bc93c5f2dee10a89136151cac18ece0a286248de.

Screenshot:

![image](https://user-images.githubusercontent.com/116824/160717722-dc2e5cb8-eb51-4079-b2e4-60d9c18112e1.png)

@cweiske @NamelessCoder

**Comment by cweiske** [comment]
I indeed only tested it on TYPO3 v9.
(It was introduced in #1929 with commit 0c269b0a5bf81727918c66904aa740bc6e4d00d5)

**Comment by NamelessCoder** [comment]
> How should this be fixed? Do we need to drop support for typo3 v8 in flux for this?

I would of course use the new interface and then avoid registering the upgrade for v8 - it won't be very long until v8 support is dropped completely anyway.

**Comment by fnagel** [comment]
This is still an issue in version 9.6.1 (24536535af7cc2f2390906d4641792046b0afbfa).

**Comment by cweiske** [comment]
@fnagel did you try the patch #1935?

**Comment by MohsinQK** [comment]
TYPO3 v10, Flux v9.6.1 problem is still there.

**Comment by cweiske** [comment]
@MohsinQK did you try the patch https://github.com/FluidTYPO3/flux/pull/1935?

**Comment by fnagel** [comment]
@cweiske Sorry for the late response on this one, I've never noticed you created an PR. Sorry for that. 

Please see the PR for my feedback: https://github.com/FluidTYPO3/flux/pull/1935#issuecomment-1117965028

**Comment by MohsinQK** [comment]
> @MohsinQK did you try the patch #1935?

yes @cweiske it worked.

**Comment by fnagel** [comment]
I've tested this in TYPO3 11.5.9 without issues. Thank you :-)
