### ISSUE TITLE
php 7.1 syntax error in \flux\Classes\Utility\ExtensionConfigurationUtility.php

### ISSUE THREAD

**Issue by supercaccia** [FluidTYPO3/flux#1937]
Only with php 7.1, in \flux\Classes\Utility\ExtensionConfigurationUtility.php

the syntax:

```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['flux']['hooks'] ??= [];
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['flux']['hooks'] ??= [];
```
generate syntax error.

We can solve replacing with:

```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['flux']['hooks'] ?? [];
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['flux']['hooks'] ?? [];
```

(by removing the equal symbol at the end)

**Comment by cweiske** [comment]
ext_emconf.php says you need PHP 7.4+
composer.json says you need PHP 7.4+.

This bug is invalid.

**Comment by cweiske** [comment]
@NamelessCoder please close

**Comment by electricretina** [comment]
I was getting this error and I am using TYPO3 10.4.27 with PHP 7.4.28. I have manually edited the file to remove the equals sign.

**Comment by cweiske** [comment]
The modification shown by @supercaccia does not solve the problem.
The null coalescing assignment operator was introduced with php 7.4:
https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.null-coalescing-assignment-operator

So using PHP 7.4 is enough, and the code does not need to be fixed.

**Comment by electricretina** [comment]
I've attached screen captures of the error and the PHP for the site where I receive the error..

Error Screen on the frontend...

![Screenshot 2022-05-17 114951](https://user-images.githubusercontent.com/1200661/168854914-563d90a6-2c7a-47a8-9df2-ee7e665dbebc.png)
.

PHP Environment in the TYPO3 backend...
![Screenshot 2022-05-17 115042](https://user-images.githubusercontent.com/1200661/168855112-47c122ec-23e6-420d-83cf-242ebf9708d3.png)

So, could it be that I'm running fpm version of PHP?

**Comment by NamelessCoder** [comment]
Flux now avoids the null coalesce assign operator - both the original issue and the addition issue from @electricretina should both be solved now.
