### ISSUE TITLE
Delete content element not working if it is hidden

### ISSUE THREAD

**Issue by stoutik** [FluidTYPO3/flux#1939]
TYPO3 11.5.5
flux: dev-development

When I try to delete a hidden content element, I have the following error:

![image](https://user-images.githubusercontent.com/10999921/162787983-d8414248-c867-4a32-8b4b-3185f3b45ebe.png)

The problem comes from this file:

Classes/Integration/HookSubscribers/DataHandlerSubscriber.php

To solve the problem, you could implement the following adjustments:

```
 protected function getSingleRecordWithRestrictions(string $table, int $uid, string $fieldsToSelect): ?array
     {
         $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable($table);
         $queryBuilder->select(...GeneralUtility::trimExplode(',', $fieldsToSelect))
             ->from($table)
             ->where($queryBuilder->expr()->eq('uid', $queryBuilder->createNamedParameter($uid, \PDO::PARAM_INT)));
         return $queryBuilder->execute()->fetch() ?:  [];
     }
```

```
protected function getSingleRecordWithoutRestrictions(string $table, int $uid, string $fieldsToSelect): ?array
    {
        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable($table);
        $queryBuilder->getRestrictions()->removeAll();
        $queryBuilder->select(...GeneralUtility::trimExplode(',', $fieldsToSelect))
            ->from($table)
            ->where($queryBuilder->expr()->eq('uid', $queryBuilder->createNamedParameter($uid, \PDO::PARAM_INT)));
        return $queryBuilder->execute()->fetch() ?: [];
    }
```

**Comment by DanYouCan** [comment]
Hi there
Sorry for rehandle this issue. I use TYPO3 V10.4.28 with Flux V9.6.1. If I remove or delete a hidden flux content element I still got following error:

_Argument 1 passed to FluidTYPO3\Flux\Provider\AbstractProvider::getGrid() must be of the type array, null given, called in /home/webtecha/www/webtech.ch/typo3104/public/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php on line 433_

If I activate that content element and then remove or delete it, it does work. Could you please recheck it and search for a fix?
Thanks in advance for your effort.

**Comment by cweiske** [comment]
This bug has been caused by #1896.

@peterreichenbach correctly wrote there:
> it is not possible anymore to do anything with restricted (hidden, starttime, endtime, fe_group) content elements.
restriction in getSingleRecordWithRestrictions should be only "deleted".

**Comment by DanYouCan** [comment]
@cweiske Thank you for taking your time to find a properly solution.

**Comment by jacobsenj** [comment]
@cweiske Thanks for your patch, it works just fine now.

**Comment by lucmuller** [comment]
Up, any news on this topic. We also face the issue on one of our websites.

**Comment by RKlingler** [comment]
I'm having the same issue, running Flux 9.6.1 on TYPO3 11.5.16.
