### ISSUE TITLE
Hook DynamicFlexForm breaks the flexform from "file storage"

### ISSUE THREAD

**Issue by fabarea** [FluidTYPO3/flux#1944]
**Context:**

Using typo3 v11 and flux dev-development branch

**Problem:**

When opening a sys_file_storage record in the BE the flexform configuration is "gone".

![image](https://user-images.githubusercontent.com/620730/164469615-b5f86f21-8446-4ee2-a9c9-954571231a59.png)

If I comment the DynamicFlexForm from `EXT:flux/ext_localconf.php` it is back to live. I didn't investigate further to find the root cause of the problem. Most presumably the TCA is overridden somewhere.

```
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS'][\TYPO3\CMS\Core\Configuration\FlexForm\FlexFormTools::class]['flexParsing']['flux'] =
            \FluidTYPO3\Flux\Integration\HookSubscribers\DynamicFlexForm::class;
```

![image](https://user-images.githubusercontent.com/620730/164469922-8cd9080d-195b-4bef-bd6e-63d7e7ad2acb.png)

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/31a4c1633ec520d373e394bbf2617566fe89a21a

**Comment by fabarea** [comment]
@NamelessCoder thanks 😄
