### ISSUE TITLE
php 8

### ISSUE THREAD

**Issue by martin-git-kristensen** [FluidTYPO3/flux#1947]
Is there a possibility to upgrade flux to run under php 8?

**Comment by grischpel** [comment]
Also in Class: ContentTypeBuilder

PHP Warning: Undefined array key "class" in /var/www/html/xxx/public/typo3conf/ext/flux/Classes/Integration/ContentTypeBuilder.php line 194

**Comment by NamelessCoder** [comment]
Work is underway to add the necessary checks/null-coalesce statements when array keys may or may not be present. Even so, I would strongly recommend setting the TYPO3 configuration option `exceptionalErrors` to a value that excludes any `E_NOTICE` levels, e.g. `4096`. Not even the TYPO3 core itself is safe from `E_NOTICE` issues, even in version 11.5.

**Comment by Oktopuce** [comment]
Even when excluding `E_NOTICE` there is always some warning, should add this line in `PageProvider.php` method `unsetInheritedValues() ` line 402 (VHS 9.7.2): 

```
+       $values[$name] = ($values[$name] ?? 0);
        $empty = (true === empty($values[$name]) && $values[$name] !== '0' && $values[$name] !== 0);

```
