### ISSUE TITLE
FlexForms from other extensions are no longer displayed

### ISSUE THREAD

**Issue by dennismetz** [FluidTYPO3/flux#1948]
I have the problem that as soon as the extension is active/installed, other FlexForms are no longer displayed.
As an example the one from News (9.4.0 installed)

TYPO3 11.5.9
Flux: 9.6
VHS: 6.1
News: 9.4.0
Composer: yes

![grafik](https://user-images.githubusercontent.com/17856901/166201696-e5fa6280-bf91-4ff3-a53a-13656c338b28.png)

**Comment by dennismetz** [comment]
Unfortunately I noticed the ticket too late, but it seems to be related to this Ticket:
https://github.com/FluidTYPO3/flux/issues/1948

**Comment by dennismetz** [comment]
Unfortunately I noticed the ticket too late, but it seems to be related to this.
https://github.com/FluidTYPO3/flux/issues/1944

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/31a4c1633ec520d373e394bbf2617566fe89a21a
