### ISSUE TITLE
Using "cache_" prefix is deprecated in TYPO3v10

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1953]
flux uses CacheManager to fetch cache instances, e.g. in `ContentTypeManager::getCache()`: https://github.com/FluidTYPO3/flux/blob/ad2bcab291ba87d5451e9b253ff74fc6d7e6a445/Classes/Content/ContentTypeManager.php#L119

In TYPO3 v10, the "cache_" prefix for all the cache names has been removed. Calling `CacheManager::getCache('cache_runtime')` is deprecated since then: https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Deprecation-88366-DefaultCachingFrameworkCacheNamesChanged.html

Using it generates deprecation notices:
> TYPO3 Deprecation Notice: Accessing a cache with the "cache_" prefix as in "cache_runtime" is not necessary anymore, and should be called without the cache prefix. in /var/www/site/htdocs/typo3/sysext/core/Classes/Cache/CacheManager.php line 151

With TYPO3 v12, the fallback will be removed.

How can this be solved, given that flux supports TYPO3 8.7 and 9?
Core version specific code?

**Comment by cweiske** [comment]
Seems to be a duplicate of #1923.

**Comment by NamelessCoder** [comment]
Fixed via https://github.com/FluidTYPO3/flux/commit/3c944b576e01745d0c77f49e977df539597b7b81
