### ISSUE TITLE
TCA: localizeChildrenAtParentLocalization is not supported in TYPO3 v9+

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1958]
Flux uses the TCA setting `localizeChildrenAtParentLocalization` in some places.

This feature has been removed in TYPO3 v9:
https://docs.typo3.org/c/typo3/cms-core/9.5/en-us/Changelog/9.0/Breaking-82709-TCAOptionLocalizeChildrenAtParentLocalizationRemoved.html

We now get a deprecation notice when editing content elements in the backend:
> TYPO3 Deprecation Notice: FormEngine did an on-the-fly migration of a flex form data structure. This is deprecated and will be removed. Merge the following changes into the flex form definition of table "tt_content"" in field "pi_flexform"":
> The TCA setting 'localizeChildrenAtParentLocalization' is deprecated  and should be removed from TCA for dummyTable['columns']['dummyField']['config']['behaviour']['localizeChildrenAtParentLocalization'] in htdocs/typo3/sysext/backend/Classes/Form/FormDataProvider/TcaFlexPrepare.php line 236

flux still supports TYPO3 v8. With v9, this property can completely be removed.
Shall I make a patch that adds version checks to the 7 files, or do we drop v8 support?

**Comment by NamelessCoder** [comment]
> Shall I make a patch that adds version checks to the 7 files, or do we drop v8 support?

Patching it is probably not worth the effort - I expect that v8/v9 support will be dropped in the near future (thanks btw for your other patches and documentation for what to do when that happens!).

**Comment by NamelessCoder** [comment]
Support for v8 and v9 has been dropped in `dev-development` and we can now address this TCA deprecation without concern for backwards compatibility to those versions.
