### ISSUE TITLE
flux 10: Drop support for TYPO3 v8 and v9

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1959]
List of tasks that can be completed when support for TYPO3 v8 and v9 is dropped:

Is hindered by v8 support:
- [ ] https://github.com/FluidTYPO3/flux/issues/1958

Is hindered by v9 support:
- [x] https://github.com/FluidTYPO3/flux/pull/1924 and https://github.com/FluidTYPO3/flux/pull/1954

**Comment by NamelessCoder** [comment]
Support for v9 and below is now dropped! :)
