### ISSUE TITLE
Error while deleting disabled content

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#1962]
Hello,

If I try to delete hidden content from a page I get a 503 error
Typo3 renders

> Argument 1 passed to FluidTYPO3\Flux\Provider\AbstractProvider::getGrid() must be of the type array, null given, called in /aPath/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php on line 433

this is written in the log:

> Core: Exception handler (WEB):  Uncaught TYPO3 Exception: Argument 1 passed to  FluidTYPO3\Flux\Provider\AbstractProvider::getGrid() must be of the type  array, null given, called in  /aPath/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php  on line 433 \| TypeError thrown in file  /aPath/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php  in line 308. Requested URL:  http://aUrl/typo3/record/commit?token=--AnonymizedToken--&cmd[tt_content][856][delete]=1&redirect=%2Ftypo3%2Fmodule%2Fweb%2Flayout%3Ftoken%3D--AnonymizedToken--%26id%3D69

Used Typo3 version: 11.5.10
Used Flux version: current DevVersion

**Comment by NamelessCoder** [comment]
Closed as duplicate - and is fixed in `development`.
