### ISSUE TITLE
urldecode(): Passing null to parameter #1 in ContentIcon.php

### ISSUE THREAD

**Issue by oheinemann** [FluidTYPO3/flux#1967]
After updating from TYPO3 9 to TYPO3 11 I found the following error message in the backend:
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Runtime Deprecation Notice: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/public/typo3conf/ext/flux/Classes/Integration/HookSubscribers/ContentIcon.php line 177
```
After investing a little time in troubleshooting, I noticed that in the function "isRowCollapsed" of the class " FluidTYPO3\Flux\Integration\HookSubscribers\ContentIcon" the line:

```
    /**
     * @param array $row  
     * @return string  
     */  
    protected function isRowCollapsed(array $row)  
    {  
        $collapsed = false;  
        $cookie = $this->getCookie();  
        if (null !== $_COOKIE) {  
            $cookie = json_decode(urldecode($cookie));  
            $collapsed = in_array($row['uid'], (array) $cookie);  
        }  
        return HookHandler::trigger(  
            HookHandler::PREVIEW_GRID_TOGGLE_STATUS_FETCHED,  
            [  
                'collapsed' => $collapsed,  
                'record' => $row,  
                'cookie' => $cookie  
            ]
        )['collapsed'];
    }
```

is responsible for the error! 
Because the variable is null and should not be decoded in this case!
In the variable "$cookie" the value of "fluxCollapseStates" is stored. This value comes from the global array $_COOKIE and is returned by the function getCookie() - or even null:

```
    /**
     * @return string|NULL
     */
    protected function getCookie()
    {
        return true === isset($_COOKIE['fluxCollapseStates']) ? $_COOKIE['fluxCollapseStates'] : null;
    }
```

However, in the surrounding IF condition, it is not the variable $cookie that is checked for null, but the global array $_COOKIE. Of course not only the array element "fluxCollapseStates" to be checked is contained in $_COOKIE, but also e.g. the hash of the logged in backend user!

I think in the IF condition the variable $cookie must be checked for null and not the value of $_COOKIE!

Best regards
Olli

**Comment by NamelessCoder** [comment]
> I think in the IF condition the variable $cookie must be checked for null and not the value of $_COOKIE!

You're completely correct :)
