### ISSUE TITLE
[SUPPORT] Limit allowed types when creating new content elements

### ISSUE THREAD

**Issue by fabarea** [FluidTYPO3/flux#197]
I have been asked whether it is possible to limit allowed content element types upon creating a new content element for instance. I am not aware of such thing. 

I had a look into `EXT:flux/Classes/ViewHelpers/Be/Link/Content/NewViewHelper.php` which renders the "create new" link, hoping to find some parameter for restricting allowed content. 

I also remember the new gridelement2 extension would have such feature. This would be confirmed by [this bug report](http://forge.typo3.org/issues/48410). At the first look, they have their own implementation.

Would you have more info besides that?

**Comment by cweiske** [comment]
@NamelessCoder: Why is this issue closed when the `be_groups` ACL are not implemented yet?
