### ISSUE TITLE
PHP 8: undefined Variable

### ISSUE THREAD

**Issue by HWSebastian** [FluidTYPO3/flux#1972]
i got the Error:

```
PHP Warning: Undefined variable $foreignControllerClass in /var/www/html/public/typo3conf/ext/flux/Classes/Controller/AbstractFluxController.php line 389
```

After looking into the code i saw that the related variable is defined inside the else{} clause, but not in general and it seems like PHP 8 requires that.

**Comment by opus-digital** [comment]
i got the same Error:

TYPO3 11.5.14
Flux 9.6.1
PHP 8.0 and 8.1

`Core: Error handler (FE): PHP Warning: Undefined property: FluidTYPO3\Flux\Controller\ContentController::$response in /var/www/html/typo3conf/ext/flux/Classes/Controller/AbstractFluxController.php line 451`
`Core: Error handler (FE): PHP Warning: Undefined variable $foreignControllerClass in /var/www/html/typo3conf/ext/flux/Classes/Controller/AbstractFluxController.php line 389`

These warnings make the website inaccessible in Debug Mode.

**Comment by Makynou** [comment]
Good Evening,

TYPO3 11.5.17
PHP 8.1
Flux: 9.6.1

I also have the same error.

**Comment by dennismetz** [comment]
+1

**Comment by NamelessCoder** [comment]
Originally reported error is fixed in `dev-development` - it is different from the error described by @opus-digital in comment above; that error will be fixed in https://github.com/FluidTYPO3/flux/pull/1999.
