### ISSUE TITLE
Page configuration for subpages shows same config fields as current page

### ISSUE THREAD

**Issue by stefanoberli** [FluidTYPO3/flux#1973]
Version: TYPO3 11.5.13 (and also 11.5.12)

In the page configuration **tx_fed_page_flexform** and **tx_fed_page_flexform_sub** both show the same fields, 
although **tx_fed_page_controller_action** and **tx_fed_page_controller_action_sub** have a different page template selected (with different field configs each).

It seems that only **tx_fed_page_controller_action** has an influence, and it changes both at the same time.
In the frontend, the correct page template is used for page and subpage.

**Comment by NamelessCoder** [comment]
Solved by recent commits. The field will now show either the form defined by the selected main template, or if no main template is selected, whichever form is inherited from a parent page's sub template selection.
