### ISSUE TITLE
Call to undefined method TYPO3\CMS\Backend\Utility\BackendUtility::getMovePlaceholder()

### ISSUE THREAD

**Issue by guelzow** [FluidTYPO3/flux#1976]
Hi everyone.

**Description**
When using workspaces, the frontend preview is broken with a fatal.

**What is happening in the code**
[Here](https://github.com/FluidTYPO3/flux/blob/9.6.1/Classes/ViewHelpers/Content/GetViewHelper.php#L132) the method `getMovePlaceholder` gets called from the `\TYPO3\CMS\Backend\Utility\BackendUtility`.
Sadly, this method does not exist anymore, resulting in a `Call to undefined method TYPO3\CMS\Backend\Utility\BackendUtility::getMovePlaceholder()`

**Additional info**
This method was removed in TYPO3 11.0.
[Here](https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/backend/Classes/Utility/BackendUtility.php#L3851) it's still available, and marked as `internal`.

Tobi

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/94a832aad86391c1f88fa08583016e5573a94b16

**Comment by guelzow** [comment]
Thanks for fixing.

Tobi
