### ISSUE TITLE
Not possible to disable page integration with PHP 8.1

### ISSUE THREAD

**Issue by derhansen** [FluidTYPO3/flux#1977]
It is not possible to disable page integration when using PHP 8.1, since `ExtensionConfigurationUtility` always returns the default value (`true`) of the extension.

This leads to various PHP 8.1 related errors when editing page properties in TYPO3 backend.

```
Core: Error handler (BE): PHP Warning: Undefined array key "sDEF" in /path/to/website/public/typo3/sysext/backend/Classes/Form/Container/FlexFormNoTabsContainer.php line 58
```

**Comment by derhansen** [comment]
I also created a core patch (see https://review.typo3.org/c/Packages/TYPO3.CMS/+/75448) to prevent the PHP warning, since there is also a problem with content elements that have no FlexForm fields. The patch in PR #1978 is still needed in order to get correct extension configuration.

**Comment by birgitberlin** [comment]
Same problem here with PHP 7.4 - after upgrading from TYPO3 v.9 to v.11. I use EXT:flux for content elments only.
flux overrides the pages TCA and shows a message in frontend: Please select a page template in page properties.

TYPO3 v.11.5.13
flux 9.6.1
php 7.4

LocalConfiguration.php:
'flux' => [
            'autoload' => '0',
            'debugMode' => '0',
            'doktypes' => '',
            'flexFormToIrre' => '0',
            'handleErrors' => '0',
            'pageIntegration' => '0',
            'pagesLanguageConfigurationOverlay' => '0',
            'plugAndPlay' => '0',
            'plugAndPlayDirectory' => 'design',
        ],
