### ISSUE TITLE
Extension configuration not loaded correctly in TYPO3 CMS 10 and above

### ISSUE THREAD

**Issue by thommyhh** [FluidTYPO3/flux#1981]
I noticed, that the page layouts from `design/Template` weren't loaded in TYPO3 CMS 10.4. After debugging I found out, that the `plugAndPlay` setting always evaluated to false.

**Comment by derhansen** [comment]
Note: This is basically the same issue as in https://github.com/FluidTYPO3/flux/pull/1978

**Comment by thommyhh** [comment]
@derhansen Yes, how could I've missed that. I went through issues and PRs before. I'll close it then, as it's duplicate.
