### ISSUE TITLE
Several Hook related PHP warnings with PHP 8.1

### ISSUE THREAD

**Issue by derhansen** [FluidTYPO3/flux#1985]
* PHP Warning: Undefined array key "pid" in `flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php line 127`
* PHP Warning: Undefined array key "uid" in `flux/Classes/Integration/HookSubscribers/DynamicFlexForm.php line 110`
* PHP Warning: Undefined array key 1 in `flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php line 136`
* PHP Warning: Undefined array key "hideUntranslated" flux/Classes/ViewHelpers/Content/GetViewHelper.php line 205

**Comment by dennismetz** [comment]
is there a chance that the fixes will be rolled out soon in a new release?
I have the same errors and even more...
