### ISSUE TITLE
You should not use `f:translate` in the configuration section - instead, use `LLL:EXT...` references which are fully supported by TYPO3 for field labels, select option values and so on.

### ISSUE THREAD

**Issue by kanow** [FluidTYPO3/flux#1988]
You should not use `f:translate` in the configuration section - instead, use `LLL:EXT...` references which are fully supported by TYPO3 for field labels, select option values and so on.

_Originally posted by @NamelessCoder in https://github.com/FluidTYPO3/flux/issues/1746#issuecomment-597014756_

How does it work if I need arguments in the translation?

**Comment by NamelessCoder** [comment]
> How does it work if I need arguments in the translation?

AFAIK this isn't supported with `LLL:EXT:..` references in context of TCA/FormEngine, so you would have to avoid LL keys which require arguments. One way to achieve that would be to create individual LL keys for each value and make part of the LLL reference dynamic, e.g. `LLL:EXT:myext/Resources.../mykey.{dynamicValue}` - although this of course only works if you know in advance the possible values of the `{dynamicValue}` and are able to create all the necessary keys to match the values.

**Comment by kanow** [comment]
OK, thx for your answer. That's what I wanted to avoid :-)

**Comment by kanow** [comment]
Mmh..This effort is probably not worth it.
This is also an older project which we have taken over. Normally we don't use flux in our projects.
Thanks for your help anyway :-)
