### ISSUE TITLE
ColPos update in Typo3 11 not working

### ISSUE THREAD

**Issue by trokohl** [FluidTYPO3/flux#1993]
The "initAfter" signal was removed in Typo3 11.

\FluidTYPO3\Flux\Integration\HookSubscribers\EditDocumentController->requireColumnPositionJavaScript
was not called.
(ext_localconf.php)

Workaround is to add:
```
        if (TYPO3_MODE =="BE" )   {
            $editController = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\FluidTYPO3\Flux\Integration\HookSubscribers\EditDocumentController::class);
            $editController->requireColumnPositionJavaScript();
         }
```
in ext_localconf.php.

**Comment by kraemer-igroup** [comment]
Thank you, this way I could solve my issue #1966!

**Comment by NamelessCoder** [comment]
Fixed with https://github.com/FluidTYPO3/flux/issues/1966

**Comment by kraemer-igroup** [comment]
Hi @NamelessCoder and sorry for the late reply, but this task is not fixed yet.

With the workaround provided by @trokohl I could fix my issue #1966 but there is no solution provided by the flux extension and with flux 9.7.2 this workaround is not working anymore.

As described in #1966 unfortunately I have no idea how to fix this issue. It seems the necessary javascript can not be loaded but is needed for the contentContainer option to work.

**Comment by NamelessCoder** [comment]
> Did you maybe link the wrong ticket when closing this one?

Yes, copy-paste buffer screwup. I adjusted the comment.

The JS inclusion triggers are now migrated to PSR-14 events because the old hooks were removed in TYPO3. Good to hear that it works now without workarounds!

**Comment by kraemer-igroup** [comment]
Thank you for fixing the issue and adjusting your comment!
