### ISSUE TITLE
wizard for input field is not working

### ISSUE THREAD

**Issue by DavidBruchmann** [FluidTYPO3/flux#1997]
Having this code:
```
						<flux:field.input name="target">
							<flux:wizard.link activeTab="Page"/>
						</flux:field.input>
```
a wizard should be shown but a common input field is only shown in TYPO3 v11.

**Comment by luzat** [comment]
The docs should probably contain a notice, but refer to #1780 how to fix this using [`renderType="inputLink"`](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/inputLink.html) in TYPO3 10+.

Also note, that in TYPO3 12+ you should probably switch to using [`type="link"`](https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Link/Index.html).

**Comment by DavidBruchmann** [comment]
thanks, like written in the other issue: hard to find
