### ISSUE TITLE
Undefined property $response 

### ISSUE THREAD

**Issue by Makynou** [FluidTYPO3/flux#2004]
Hello,

I'm using TYPO3 11.5.17 with PHP 8.1
Flux dev-development version

I still have an undefined property into the AbstractFluxController line 398

<img width="1152" alt="Capture d’écran 2022-10-21 à 17 35 34" src="https://user-images.githubusercontent.com/34098047/197234408-2ec7598f-c7cf-48b8-8341-d5f6d32bbc30.png">

**Comment by NamelessCoder** [comment]
Fixed with https://github.com/FluidTYPO3/flux/commit/94a832aad86391c1f88fa08583016e5573a94b16
