### ISSUE TITLE
BE crash : error when deleting a disabled text block 

### ISSUE THREAD

**Issue by olinox14** [FluidTYPO3/flux#2007]
When you create a text-block on a standard page, disable it then try to delete it, the BE crash and the following error is thrown : 

![image](https://user-images.githubusercontent.com/15560057/197491862-996c5b37-c504-4341-8ba4-577041fd95d8.png)

It seems the `$originalRecord` is null in `DataHandlerSubscriber::getParentAndRecordsNestedInGrid`.

To reproduce : 

1. Open the backend, create an empty page and activate it
2. Create a new text block and leave it empty. Save, and return to the page.
3. Disable it
4. Try to delete it

My env : 

- Php 7.4.11
- Typo3 10.4.32
- Flux 9.6.1

**Comment by NamelessCoder** [comment]
Fixed in `dev-development` with https://github.com/FluidTYPO3/flux/commit/35995ce8e579fe5ce5ef096c92a48fea5b3c3d68 - please check status on `dev-development` before filing bug reports :)
