### ISSUE TITLE
Issues in backend with development branch

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/flux#2009]
Hi @NamelessCoder, thanks a lot for the latest merges and changes for PHP 8!

I've been testing the latest development branch (6af7e72709d0ccf3f8e9defaa7a1a08e96bebef1) with TYPO3 11.5.17 and PHP 8.1 and have some issues when using the page module in backend.

Page module for every non root page (is_root field):
![grafik](https://user-images.githubusercontent.com/116824/197737721-d7b338f8-fbd8-49dc-a7e3-f27251ad91c4.png)
This one is fixed by a simple `isset()` check in the `PageProvider` but I'm not sure if the `$row['deleted']` should be empty at all. There are multiple calls to the `getForm()` method, some look like rootline data, missing the deleted field.

Page properties for all pages have following error message in the page module:
![grafik](https://user-images.githubusercontent.com/116824/197738216-81b8e03b-1c24-4ab0-bf0b-77ef49fc48f5.png)

Any idea? Second looks like it could be a configuration issue.

**Comment by NamelessCoder** [comment]
> some look like rootline data, missing the deleted field.

Needs a null-coalesce to assume deleted=0 when deleted isn't passed. I forgot about the root line data only consisting of certain fields (which you must configure). Deleted doesn't need to be among the fields since afaik root line data cannot contain deleted pages.

**Comment by fnagel** [comment]
@NamelessCoder Thanks for the fast fix! Works as expected now.

Any idea what's the issue with the second error? With that `An error occurred trying to process items for field "Page Layout - this page" (PHP Warning: Undefined array key "tx_flux." in typo3conf/ext/flux/Classes/Backend/PageLayoutDataProvider.php line 100).` error.

**Comment by NamelessCoder** [comment]
Second error is also a possibly-null problem, caused by no TS existing for `plugin.tx_flux` (for the record, this *is* a valid use case). Should be fixed now in `dev-development`.

**Comment by fnagel** [comment]
@NamelessCoder Sorry for the late response and thanks for the feedback! I've tested again with dfdbecc4721656f3f607c192ca53b89c531cd67c and everything works as expected now. Thanks a lot!
