### ISSUE TITLE
Plug and play designs not working

### ISSUE THREAD

**Issue by achim71** [FluidTYPO3/flux#2025]
Hello,

I'm in the process to upgrade an typo3 8.7 website using fluidpages to typo3(11.5.18) and flux(@dev). I use an site extension for the templates and classes on 8.7. 
I got stuck at configuring the right templateRootPath search paths in the extension. So I tried the plug and play designs without my extension enabled.
If I enable basic.plugAndPlay i'd expect the design folder to be created in public. But it gets created in public/typo3.
If I then go to page management -> sites the following error occurs and no flux providers are found:
`"Bei dem Versuch, die Elemente für Feld "Available page layouts/templates (empty selection means allow-all)" (The "/usr/www/users/gottind/fot/public/design/Templates/" directory does not exist.) zu verarbeiten, ist ein Fehler aufgetreten."`

So i created the mentioned folder and now there is an page and an content provider selectable.
I can assign the page template "FluidTYPO3.Flux->default" to an page but in the frontend it is rendered as 
`"Please select a page template in page properties.".`
This comes from the Page template in public/typo3conf/ext/flux/Resources/Private/Templates/Page/Default.html.
So the templates under pubil/typo3/design are not picked up.
`The log also shows an error "[ERROR] request="10df8bc7e3e9a" component="FluidTYPO3.Flux.Service.PageService": Section "Configuration" does not exist."`
Seems the template search paths are not working here with the design approach as well.

What is the correct place to define the search paths for the templates. And why does flux create the design folder under public/typo3 and not dircetly under public?

Thanks in advance,
Achim

**Comment by achim71** [comment]
Tried it again with an empty database no own extension. typo3 (11.8.18) flux (@dev).
Still the design folder ends up as public/typo3/design
If I create an page Template in public/design/Templates/Page it is found and can be used.
If i try to add the "Default Flux Content Type" element it searches for an template
public/typo3/design/Template/ContentStandard.html instead of public/typo3/design/Template/Content/Standard.html
Adding an template as public/design/Template/ContentStandard.html does not work. 
Creating public/typo3/design/Template/ContentStandard.html works.
All abit confusing.

**Comment by janhelke** [comment]
From my point of view, this is not an "a bit confusing" configuration issue, but a regression, introduced somewhere on the way from Version 9.6.1 (were is works) to 9.7.1 (were the error occured). I guess at some point the slash, that separates Content from Standard in "Template/Content/Standard.html" went AWOL. Downgrading flux to version 9.6.1 fixed the error for me. 

So I would like to see this issue reopend and fixed.

For reference, my configuration: 
TYPO3-Version	9.5.39
Webserver	Apache/2.4.54 (Debian)
PHP-Version	7.4.33
Datenbank (Default)	MySQL 5.5.5-10.3.37-MariaDB-1:10.3.37+maria~ubu2004-log

**Comment by m3nt0r** [comment]
I still have this issue with v10.0.9
