### ISSUE TITLE
Page flexform breaks fe/be with EXT:flux v9.7.1

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#2036]
Typo3: 11.5.19,
Flux: 9.7.1,
Composer mode: Yes,

When you edit page in backend or use {flux:form.data(table:'pages',field:'tx_fed_page_flexform',uid:123) in fluid template for fe you'll  see error:
![image](https://user-images.githubusercontent.com/9860558/203557261-3c8bd7db-0c5c-4193-9c41-65a11d589f0a.png)

**Comment by Skywalker-11** [comment]
Changing this line
https://github.com/FluidTYPO3/flux/blob/a6b3dba43a0b4399797e6fe8155459baf46d7ecf/Classes/Provider/PageProvider.php#L402
to  this seems to fix it
```$empty = !isset($values[$name]) || (true === empty($values[$name]) && $values[$name] !== '0' && $values[$name] !== 0);```
