### ISSUE TITLE
FluidTYPO3\Flux\Utility\ColumnNumberUtility::calculateParentUid(): Argument #1 ($colPos) must be of type int, string given, called in /var/www/.../public/typo3conf/ext/flux/Classes/Integration/Overrides/BackendLayoutView.php on line 119

### ISSUE THREAD

**Issue by lucmuller** [FluidTYPO3/flux#2045]
Parameter colPos should be cast as an integer

**Comment by lucmuller** [comment]
Should be fixed by : #2046

**Comment by grischpel** [comment]
#2055

**Comment by huckels** [comment]
Are there any updates?

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/3c944b576e01745d0c77f49e977df539597b7b81#diff-89545df00ad17f687303f6717cebcce3ceac29681e98d0cbed63fa9c21fdb0f1
