### ISSUE TITLE
[BUG] - transform repository DI

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/flux#2048]
Hello,

With a latest version of `dev-development` branch `transform` attribute doesn't work. It fails on repository instantiation [here](https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/Transformation/FormDataTransformer.php#L157).

transform attribute looks like this:
`transform="TYPO3\CMS\Extbase\Persistence\ObjectStorage<Vendor\ExtName\Domain\Model\Address>"`

Typo3 v 11.5.18
flux v 9.7.2 (dev-development)

**Comment by NamelessCoder** [comment]
Did you make sure that the Repository associated with your record type, is registered as `public: true` in `Services.yaml`? If it is not registered this way, it cannot be instanced via `makeInstance` (constructor DI fails with message about missing required constructor arguments).

**Comment by NamelessCoder** [comment]
Closing due to lack of feedback and near-certainty that missing registration of the Repository as `public` in DI config is the cause.
