### ISSUE TITLE
[BUG] Not working D&D

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#2051]
Composer mode
Typo3 11.5.21
PHP 8.1.13
Flux: 9.7.2

On attempt to drag&drop on T3 backend, xhr respond with error:
![image](https://user-images.githubusercontent.com/9860558/209665897-bb3ca4d6-62de-45b2-98bf-c74d88447e8b.png)

**Comment by maximaexchen** [comment]
Confirm same Problem

None composer
Typo3 11.5.22
Flux 9.7.2 
php-8.1.14

@kraemer-igroup fix works

**Comment by dreadfulgate** [comment]
Confirm the confirmation. Thanks! This has been vexing me for a week!

**Comment by NamelessCoder** [comment]
Would one of you mind trying this with `dev-development` branch? The mentioned code places have been changed to add the third array entry (as an empty array).

**Comment by kraemer-igroup** [comment]
I can confirm it is working with the `dev-development` branch. Thank you @NamelessCoder!

**Comment by NamelessCoder** [comment]
Thanks @kraemer-igroup - closing as solved :)
