### ISSUE TITLE
[BUG] An error occurred trying to process items for field in BE with TYPO3 V11

### ISSUE THREAD

**Issue by Oktopuce** [FluidTYPO3/flux#2053]
1. Define some page layout in an own extension
2. In TYPO3 BE, edit a page
3. Close the page

Then you have this message :

> An error occurred trying to process items for field "Page Layout - this page" (PHP Warning: Undefined variable $_EXTKEY in /var/www/html/web/typo3conf/ext/my_ext/ext_emconf.php line 3).

TYPO3 version : 11.5.21
Flux version : 9.7.2
PHP : V8

**Comment by NamelessCoder** [comment]
Quick fix: avoid `$_EXTKEY` in your `ext_emconf.php` - hardcode the extension key instead. This is good advise for any extension, not just Flux provider extensions.

**Comment by Oktopuce** [comment]
Don't agree with your fix because in the official TYPO3 documentation, it's written this : 

> However, due to limitations in the TYPO3 Extension Repository, the $_EXTKEY option must be kept within an extension's [ext_emconf.php](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ExtEmconf.html#extension-declaration) file.

See : https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/BestPractises/ConfigurationFiles.html

**Comment by NamelessCoder** [comment]
Regardless what it says in the documentation (which may just be outdated), it doesn't cause any problems to use the hardcoded extension key. Both Flux and VHS has been doing this for nearly a year with no adverse effects. Even if it did, it only applies to extensions that you upload to TER so IMHO the quick solution I proposed is still valid, tried and tested.

**Comment by georgringer** [comment]
fixed with https://github.com/FluidTYPO3/flux/commit/900415e7bf970f7e32fd27f223b9af230bee1661

**Comment by NamelessCoder** [comment]
Closing as solved.
