### ISSUE TITLE
Missing "Show or hide the grid" button

### ISSUE THREAD

**Issue by r3h6** [FluidTYPO3/flux#2058]
TYPO3 v11 with flux v9.7.2 does not show the "Show or hide the grid" button in page module.

In previous versions there was a button for collase "container" elements:
![flux-gridToggle](https://user-images.githubusercontent.com/4550541/213994932-fba14788-e947-4371-b1e0-a2623b15546d.jpg)

**Comment by NamelessCoder** [comment]
Duplicate of https://github.com/FluidTYPO3/flux/issues/2056, please follow status there.
