### ISSUE TITLE
Bug PHP V8 if TCA fiedl 'useColumnsForDefaultValues' is not set

### ISSUE THREAD

**Issue by Oktopuce** [FluidTYPO3/flux#2059]
If the TCA field 'useColumnsForDefaultValues' is not set there is a bug with PHP V8 :

PHP Warning: Undefined array key "useColumnsForDefaultValues" in /var/www/html/web/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DynamicFlexForm.php line 123

**Comment by NamelessCoder** [comment]
Solved with https://github.com/FluidTYPO3/flux/commit/886f584e3a2e7ed895460e913095f70774853953
