### ISSUE TITLE
Inheritance page configuration problem

### ISSUE THREAD

**Issue by MaxGTR** [FluidTYPO3/flux#2060]
It's missing an `array_reverse` before the return of the method **loadRecordTreeFromDatabase** in the file **Classes/Provider/PageProvider.php**, so the inheritance comes from top instead of nearest parent.

Bug appears since version 9.6.0

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/79dce7ff2439a90a210002139e338a1e4561adc2 - thanks for reporting!
