### ISSUE TITLE
Sub-controller execution broken in AbstractFluxController (at least since 9.7.0 in TYPO3 v10)

### ISSUE THREAD

**Issue by rkleo** [FluidTYPO3/flux#2066]
Hello,

I think there is a bug introduced in version 9.7.0 in `AbstractFluxController`.
The `$response` object is passed by reference and should seemingly be updated by the called `processRequest($request, $response)` method. The Extbase `ActionController` does not seem to return the value, at least in TYPO3 v10 (where I encountered the problem). So effectively the `$response` variable will always be overwritten with `NULL`.

Flux 9.7.2:
https://github.com/FluidTYPO3/flux/blob/9eb903f7dbc45306ee774258e043576f143c3c8d/Classes/Controller/AbstractFluxController.php#L475

Previously in Flux 9.6.0, there was a version switch, seems like it was mixed up while merging the two cases:
https://github.com/FluidTYPO3/flux/blob/a4ba6fe1716cf46fede81fec22c75e86572db048/Classes/Controller/AbstractFluxController.php#L458-L462

9.7.2 is still marked as compatible with TYPO3 v10 – but see `processRequest()` implementation:

https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php#L384-L428

**Comment by renemaas** [comment]
I can confirm this problem.  
Results in `Call to a member function getBody() on null`.

Broke my production upon update, luckily I had a backup.

**Comment by NamelessCoder** [comment]
Hotfix released as 9.7.3.
