### ISSUE TITLE
Backend Problems with "dev-development" - Branch

### ISSUE THREAD

**Issue by devtroll** [FluidTYPO3/flux#2071]
When I use the "dev-development" - Branch I have problems with opening some modules within the backend.
currently the modules "backend users"  and "log" from TYPO3 not working. Additonal the plugin "sgalisnki/cookie-opt-in" has the same error. When I switch to a tagged version, all is okay.

Error-Message (all modules have the same):

`(1/1) #1316104317 TYPO3\CMS\Extbase\Mvc\Exception
The default controller for extension "Belog" and plugin "system_BelogLog" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.`

I need to use "dev-development" branch for random bugfixes.

so u can fix this very quickly?

Thanks!

TYPO3 v11, PHP 8.1

**Comment by nabossha** [comment]
same here using 11.5.25 and dev-development branch.
disabling "FluidTYPO3\Flux\Core::registerProviderExtensionKey('extKey',"ControllerName") in my ext_localconf.php solves the backend-problem but that does not really help

**Comment by nabossha** [comment]
it seems this got fixed with 572d9765271198a2823f701b10a17fc10de101ff for me, thanks a lot!
