### ISSUE TITLE
Preview images in Backend

### ISSUE THREAD

**Issue by mrwhy-orig** [FluidTYPO3/flux#2074]
I'm trying to display preview Images in the backend. But nothing is showing. Is it supported ? {img.url} is null in Preview section. I'm still on Typo3 9.5 but want to do an upgrade soon.

```
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">

    <f:layout name="Content"/>

    <f:section name="Configuration">
        <flux:form id="VideoItem" options="{group: 'FCE'}">
            <flux:field.input label="Video Bezeichnung (nur im Backend sichtbar)" name="settings.name" required="1"/>
            <flux:field.inline.fal label="Video" name="settings.video" required="1" maxItems="1" minItems="1"
                                   allowedExtensions="mp4"/>
            <flux:field.inline.fal label="Poster" name="settings.poster" required="1" maxItems="1" minItems="1"/>
        </flux:form>
    </f:section>

    <f:section name="Preview">
       {v:content.resources.fal(field: 'settings.poster')
        -> v:iterator.first()
        -> v:variable.set(name: 'img')}
        Video: {settings.name}
       <img src="{img.url}"/> 
    </f:section>

    <f:section name="Main">
        {v:content.resources.fal(field: 'settings.video')
        -> v:iterator.first()
        -> v:variable.set(name: 'vid')}
        {v:content.resources.fal(field: 'settings.poster')
        -> v:iterator.first()
        -> v:variable.set(name: 'img')}
        <div class="video_preview" style="display: flex; align-content: center;">
            <video poster="{img.url}"
                   style=""
                   preload="auto"
                   muted="1"
            >
                <source src="{vid.url}" type="{vid.mimetype}">
            </video>
        </div>
    </f:section>
</div>
```

**Comment by NamelessCoder** [comment]
@mrwhy-orig This *might* work if you change `v:content.resources.fal(field: 'settings.poster')` in the Preview section, to 'v:content.resources.fal(field: 'settings.poster', record: record)`. When this ViewHelper is used in a backend context, the normal resolving of the currently active content record is not possible to automate and you'll have to explicitly tell it the record, which is available in the `{record}` variable that Flux assigns when rendering the section.
This can also be done, but isn't required, in the Main section that's rendered in frontend context.

**Comment by NamelessCoder** [comment]
The described solution passing `record` explicitly, but in the next version of Flux a much, much more convenient method becomes possible:

```xml
<f:section name="Configuration">
    <flux:form id="myelement">
        <flux:field.inline.fal label="Poster" name="settings.poster" transform="filereference" />
    </flux:form>
</f:section>

<f:section name="Preview">
    <f:image image="{settings.poster}" maxHeight="200" />
</f:section>

<f:section name="Main">
    <f:image image="{settings.poster}" />
</f:section>
```

The `transform` prioperty now allows you to use either `file`, `files`, `filereference` or `filereferences` to declare what type of FAL resource the field's value should be converted to - and Flux takes care of the conversion in all contexts, turning the assigned template variable into a single or array of File/FileReference ready to use with various ViewHelpers.

**Comment by kraemer-igroup** [comment]
Hi @NamelessCoder, I was very exited to just read about this possiblity and tested it with TYPO 12.4.10 + flux 10.0.9.
It works great in the frontend, but it's not working in the backend. `filereferences` resolve to an empty array and `filereference` to NULL.

Should this work already?

```html
<f:section name="Configuration">
    <flux:form id="myelement">
        <flux:field.inline.fal label="Poster" name="poster" transform="filereference" />
        <flux:field.inline.fal label="Poster" name="posters" transform="filereferences" />
    </flux:form>
</f:section>

<f:section name="Preview">
    <f:debug>{poster}</f:debug> => NULL
    <f:debug>{posters}</f:debug> => array(empty)
</f:section>

<f:section name="Main">
    <f:debug>{poster}</f:debug> => TYPO3\CMS\Core\Resource\FileReference
    <f:debug>{posters}</f:debug> => array(1 item)
</f:section>
```

**Comment by NamelessCoder** [comment]
@kraemer-igroup There's a catch when using this in backend mode: TYPO3 tries to resolve the images in a different way than FE, because it has to support workspaces. Unfortunately, some of the methods that TYPO3 use make the assumption that the field is a root-level TCA field and therefore simply doesn't support the flexform-based usage.

There are two ways to work around that:

1. Use a Flux field name that is *also* a root-level TCA field of type `inline` - for example, `image` is such a name. Despite the name, it does support multiple images.
2. Stick with the `transform` approach for FE, but in BE use `v:resources.record.fal` (with `table` and `field` and either `record` or `uid` arguments) to extract the references. This works because this ViewHelper does not use the same method as the core to resolve the references and doesn't make the assumption that the field is a root-level TCA field. Extract it to a variable (`f:variable()`) first if you need to have a condition since you can't check on any property of the parent record.

**Comment by kraemer-igroup** [comment]
@NamelessCoder Thanks for looking into this! We have some templates with just one field `image` - this works great in FE and BE.
And we have some templates with multiple files, in this case the workaround with `v:resources.record.fal` also works fine for the backend (even without the `table` argument, but always with the `record` argument). The `v:resources.record.fal` viewhelper already creates a variable via the `as` argument, so I guess also using `f:variable()` is superfluous?

Anyway, I very like this change and using "normal" file reference for the frontend! 👍

**Comment by NamelessCoder** [comment]
@kraemer-igroup You're totally right, I forgot that the ViewHelper has the `as` argument. That is of course better.

Happy to hear you like the feature!
