### ISSUE TITLE
The default controller for extension "x" and plugin "y" can not be determined (follow up to #1991)

### ISSUE THREAD

**Issue by sdelcroix** [FluidTYPO3/flux#2076]
Hi,

this is a follow up to #1991 
It may be a TYPO3 core bug but I redeclare it here as well in case it's not.

As @MrMooky said in #1991, sometimes TYPO3 creates a redirect to a page itself (for example when a page "A" is renamed to "B" then back to "A").
This behaviour has been handled by core team to avoid infinite loops but, in that particular case, an error occurs for Flux content elements.

`The default controller for extension "Rvvnfluidcolumns" and plugin "Example" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php., in file typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php:217 ` 

Deleting the problematic redirect solves the problem but we cannot ask our users to do this every time this happens ;)

**Comment by sdelcroix** [comment]
I "re-open" this issue because it becomes really problematic as we cannot use the actual Flux development version, that fixes it, in production.

Today, one of our editors has simply moved a page (containing an Extbase plugin) to the wrong location then replaced it at its initial location in page tree.
2 redirects that loop each other have been created by TYPO3.
And when visiting this page in frontend, exception occurs : 
```
#1316104317 TYPO3\CMS\Extbase\Mvc\Exception
The default controller for extension "News" and plugin "Pi1" can not be determined. 
Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php
```

@NamelessCoder do you manage to reproduce the issue ? 
TYPO3 11.5.29 + flux 9.7.4
Create a page "Page A", rename it "Page B", then back to "Page A".
Put any extbase frontend plugin as "news" on this page.
Display the page in frontend.

**Comment by NamelessCoder** [comment]
I have tried the steps you descibed - and also tried moving the page instead of renaming it. I am still not able to reproduce the problem.

Are you absolutely certain that:

* You don't have any third-party middlewhare that involves a ConfigurationManager instance?
* You are using the most recent `dev-development` of Flux (updated 6 hours ago)?

**Comment by sdelcroix** [comment]
Thanks for your quick test. 
The issue occurs with the master version not the dev one ;)
And as I said, we cannot use the dev one in production as it’s not stable :(
