### ISSUE TITLE
Missing array key "pid" on Form Field Text element while using RTE (PHP8 error?)

### ISSUE THREAD

**Issue by ako-3004** [FluidTYPO3/flux#2078]
used <flux:field.text name="settings.text" enableRichText="true" /> with enabledRichText, causes error:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "pid" in typo3conf/ext/flux/Classes/Form/Field/Text.php line 238

error is in lines

```
            $record = $root->getOption('record');
            if ($record !== null) {
                $pageUid = (integer) $record['pid'];
            }

```
where $record[pid] is not set (did a var_dump). I have PHP8 and warnings enabled. Guess PHP8 is the reason for having this error message now. Did not have this error with php7. Code has not been changed on update to php8.

**Comment by ako-3004** [comment]
fixed for my by doing this:

```
            $record = $root->getOption('record');
            if ($record !== null) {
                if (isset($record['pid'])) {
                    $pageUid = (integer) $record['pid'] ?? 0;
                }
            }

```

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/pull/2087
