### ISSUE TITLE
Another PHP8 undefined array key warning in DataHandlerSubscriber

### ISSUE THREAD

**Issue by ako-3004** [FluidTYPO3/flux#2079]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key 2 in /var/www/fohhn/www-dev/typo3conf/ext/flux/Classes/Integration/HookSubscribers/DataHandlerSubscriber.php line 410

caused when moving content elements by drag-and-drop in the TYPO3 backend (ajax request)

Line:
`[, $recordsToProcess, $bannedColumnNumbers] = $this->getParentAndRecordsNestedInGrid(`

**Comment by NamelessCoder** [comment]
Solved via https://github.com/FluidTYPO3/flux/issues/2051
