### ISSUE TITLE
Toggle buttons for grids are missing again.

### ISSUE THREAD

**Issue by n-meissner** [FluidTYPO3/flux#2086]
The toggle buttons fixed by this commit are missing again.

https://github.com/FluidTYPO3/flux/commit/877f51500262f3e20a0b15e8816e844dac22d390

` if ($cachedIconIdentifier !== false) {
`

The original issue can be found here:
https://github.com/FluidTYPO3/flux/issues/1616

This is the commit which breaks the toggle button again:
https://github.com/FluidTYPO3/flux/commit/e77db9433d4e6d459944ec67bf8736a36950ac21

**Comment by NamelessCoder** [comment]
The good news is that this is now fixed in `dev-development` for v10 and v11.

The bad news is that because TYPO3 chose to remove a hook that triggered in both list- and page-module, with an event that only triggers in list-module, there is no way to implement this feature for TYPO3v12 and beyond.
