### ISSUE TITLE
TYPO3 12.4.2 errror during registerProviderExtensionKey

### ISSUE THREAD

**Issue by develth** [FluidTYPO3/flux#2091]
On registerProviderExtensionKey i get following Error (see screenshot)

If i comment RenderingContextBuilder.php::62 

    $templatePaths->fillDefaultsByPackageName($extensionKey);

It seems to work.

Any ideas?

![Bildschirmfoto 2023-06-30 um 19 25 04](https://github.com/FluidTYPO3/flux/assets/3374563/da8bfb9d-b185-4974-9ea4-91e8e604442b)

**Comment by NamelessCoder** [comment]
@develth Can you try this again with a fresh pull from `dev-development`? I'm pretty sure this was solved with a commit I made yesterday.

**Comment by develth** [comment]
@NamelessCoder Seems to be fixed. Thx!
