### ISSUE TITLE
"Identifier could not be decoded to an array." - Copying a record not possible

### ISSUE THREAD

**Issue by steffen-hph** [FluidTYPO3/flux#2099]
When I try to copy a simple text-tt_content-record, I get the following error. So it is not possible to copy a record.

TYPO3 12.4.2
Flux: Latest from 2023-07-11

![Bildschirmfoto 2023-07-11 um 11 25 58](https://github.com/FluidTYPO3/flux/assets/78363413/55616195-f4e1-414c-9657-ab9198c17b4a)

**Comment by steffen-hph** [comment]
Sorry i forgot my solution: We check the identifier before calling setIdentifier to get null on getIdentifier if the element is not a FluxContentElement to generate the default identifier needed for the core elements.

https://github.com/FluidTYPO3/flux/pull/2093/commits/356b312f52c054079b19bc4179425f7aa71080e7

**Comment by deerfish** [comment]
Same happens if I translate a content element. Your fix also works in this context. Thanks a lot for this.

TYPO3 12.4.4
Flux: Latest from 2023-07-25
