### ISSUE TITLE
"Unused elements" in column element

### ISSUE THREAD

**Issue by steffen-hph** [FluidTYPO3/flux#2100]
When I use multiple column elements on a page, each record is displayed correctly (in BE and FE). 
But all of the following records are also displayed under "unused.

TYPO3 12.4.2
Flux: Latest from 2023-07-11

![Bildschirmfoto 2023-07-11 um 12 03 40](https://github.com/FluidTYPO3/flux/assets/78363413/ae401c65-c6d0-4618-8bff-49fb122aff96)

**Comment by fiedomedia** [comment]
I can confirm the issue.
The error occurs when multiple multi column elements are used on the same page.

![image](https://github.com/FluidTYPO3/flux/assets/2965516/39fb4165-8b67-4ed8-bd20-940c3baf8ffc)

If there is only one grid element on the page then it works. Even nesting is fine:

![image](https://github.com/FluidTYPO3/flux/assets/2965516/9bfc89dd-6f9b-4bf8-a0ea-2ee819a55d7d)

**Comment by steffen-hph** [comment]
Sorry i forgot my solution. There is one core function parameter available: https://github.com/FluidTYPO3/flux/pull/2093/commits/1a6f83cdebf1b780f1f6c86a3e54f16d4894c996
