### ISSUE TITLE
Frontend error after update from flux 9.7.2 to 9.7.3 on a TYPO3 11.5 composer website project.

### ISSUE THREAD

**Issue by eckonator** [FluidTYPO3/flux#2101]
`Argument 1 passed to TYPO3\CMS\Extbase\Mvc\Controller\ActionController::processRequest() must implement interface TYPO3\CMS\Extbase\Mvc\RequestInterface, null given, called in /var/www/public/typo3conf/ext/flux/Classes/Controller/AbstractFluxController.php on line 475`

Can someone help?

**Comment by jonakieling** [comment]
Same with TYPO3 10.4.37

This fix works locally for me: https://github.com/jonakieling/flux/commit/555b3cbf9422736c95ae670968de3e7f7bb408b0

**Comment by eckonator** [comment]
Thank you! If I had looked into the file, I would have noticed that directly.

**Comment by NamelessCoder** [comment]
Solved with 9.7.4 released yesterday. Sorry about the inconvenience; the code I ported used a variable that was created in a different commit that does not yet exist on `master`.
