### ISSUE TITLE
Workspace > try to publish a deleted Page > Broken rootline. Could not resolve page 

### ISSUE THREAD

**Issue by typo3rel** [FluidTYPO3/flux#2108]
Hi,

Deleted pages can no longer be published in the workspace.

versions
flux 9.7.2 and 9.7.4
typo3 9.5.30

```
503
Oops, an error occurred!

Broken rootline. Could not resolve page with uid 23242.
```

first flux error in the trace:

```
at TYPO3\CMS\Core\Utility\RootlineUtility->get()
in /var/www/*******/public/typo3conf/ext/flux/Classes/Service/PageService.php line 127

        $rootLineUtility = $this->getRootLineUtility($pageUid);

        // Initialize with possibly-empty values and loop root line
        // to fill values as they are detected.
        foreach ($rootLineUtility->get() as $page) {
            $resolvedMainTemplateIdentity = is_array($page['tx_fed_page_controller_action'] ?? null)
                ? $page['tx_fed_page_controller_action'][0]
                : $page['tx_fed_page_controller_action'] ?? null;
            $resolvedSubTemplateIdentity = is_array($page['tx_fed_page_controller_action_sub'] ?? null)
```
without the flux extension everything runs fine

**Comment by NamelessCoder** [comment]
TYPO3 9.5 will no longer be supported in the next release of Flux. There will be no fix for this issue - sorry.

The issue does not appear to exist in more recent versions of TYPO3.

**Comment by typo3rel** [comment]
Sorry, but I meant v11.5.30.
I don't know why I wrote 9.

**Comment by NamelessCoder** [comment]
Ah okay :)

In any case: the problem doesn't seem to exist anymore in `dev-development`.

**Comment by typo3rel** [comment]
I have just tried it. Unfortunately, the same problem.

**Comment by typo3rel** [comment]
Okay, I have deactivated basic.pageIntegration and it works for now.
