### ISSUE TITLE
Create new content element wizard in TYPO3 v12

### ISSUE THREAD

**Issue by rolfd** [FluidTYPO3/flux#2112]
The "Create new content element" wizard shows all available content elements, ignoring the "allowedContentTypes" or "deniedContentTypes" Flux variables.

It seems the "wizardItemsHook" is not executed anymore:
https://github.com/FluidTYPO3/flux/blob/c59608d2b33d8bd59a51cc58ffa98d7909327b9e/ext_localconf.php#L94

More information is available here:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97201-PSR-14EventForModifyingNewContentElementWizardItems.html

Branch: development
TYPO3: 12.4.4

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/fb459365b53d7ea7f76895d1d1fbcc9b459b429f
