### ISSUE TITLE
FlexForms of extension plugins missing in templates

### ISSUE THREAD

**Issue by steffen-hph** [FluidTYPO3/flux#2115]
The FlexForms of e.g. News plugins are missing in the templates while Flux is installed and active. It is possible that this does not only apply to the News extension.
While Flux is disabled, everything works fine, so it seems that Flux changes something about how the core loads FlexForms.

TYPO3 12.4.4
Flux: Latest from today (2023-08-08)
News: Latest from today (2023-08-08)

**Comment by NamelessCoder** [comment]
@steffen-hph Can you elaborate, for example what do you mean by "missing in the templates"? I have EXT:news installed and I see the expected News plugin flexforms.

**Comment by steffen-hph** [comment]
We set the "detailPid" for example in the News plugin and the settings array that we got in the Fluid template was missing all the options from the FlexForm. But without Flux all the settings where available. We also checked the settings inside the NewsController at the start of the listAction but we only got the TypoScript options in the settings array.

**Comment by steffen-hph** [comment]
The FlexForms are working now, thanks for that.

But somehow the News Detail plugin still doesn't work when Flux is active because the record can't be found. But once we disable Flux, it works.

You can test it by adding a news list view on one page and the detail plugin on another page. Set the configuration in the plugins so that the links point to the correct pages.
With Flux it won't work to link from the list to the detail page without getting a "News record not found" error, but without Flux it should work.

**Comment by NamelessCoder** [comment]
@steffen-hph Can you try again with the most recent linked commit checked out? It solves the issue on my end.

I think it has to do with either EXT:news' xclass of ExtensionService or how ExtensionService is instanced in general. For whatever reason, ExtensionService received a vanilla configuration manager which lacked the ability to resolve the right framework configuration so EXT:news couldn't dynamically switch the plugin name scope and read request parameters from the shared `tx_news_pi1` scope. The result was that controller arguments were always empty.

**Comment by r12r** [comment]
I can confirm that this problem also happened with powermail and has been fixed with the latest commit. Thank you!

**Comment by steffen-hph** [comment]
Works fine for us now too! Perfect thank you
