### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Result::fetchColumn()

### ISSUE THREAD

**Issue by Amine1414** [FluidTYPO3/flux#2124]
Hello,
When i run upgrade wizard under Typo3 12 i get this error.
![image](https://github.com/FluidTYPO3/flux/assets/12212836/3e352e75-a814-4916-8282-29dfb9862b99)
Thank you.

**Comment by steffen-hph** [comment]
@Amine1414 Fixed in the newest version. Or only this fix is here: https://github.com/FluidTYPO3/flux/pull/2093/commits/d4d688fd0d83ef2d7d02bdbc7bab93572a8e4a24

**Comment by Amine1414** [comment]
@steffen-hph thank you so much for your fix and answer

**Comment by NamelessCoder** [comment]
Closing as solved, thanks @steffen-hph :)
