### ISSUE TITLE
An exception occurred while executing a query: Table 'typo3_v12.cache_flux' doesn't exist

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#2127]
Hello,

I'm just trying to upgrade from typo3 v11 LTS to v12 LTS.

Aswell from Flux 9.7.2 to 10.0.3

I got the newest version of FLUX from the TER and I got this message:

```An exception occurred while executing a query: Table 'typo3_v12.cache_flux' doesn't exist```
This is immediately shown as soon I use this line in the ext_localconf.php
```\FluidTYPO3\Flux\Core::registerProviderExtensionKey('MyVendor.MyExt', 'Content');```

**Comment by xellos866** [comment]
we run in a similar issue and it may be possible that your loading order of the extensions is not correct. Did you require the extension in your local extension?

**Comment by MediKathi** [comment]
> Did you require the extension in your local extension?

what do you mean with this?

The setup used to workl with typo3 v11 and flux9

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/commit/843526a2e4722d002254ea6e8be367d04e1e0e27
