### ISSUE TITLE
Undefined array key "native" & "position" in AbstractFieldViewHelper - TYPO3 v12

### ISSUE THREAD

**Issue by Apen** [FluidTYPO3/flux#2128]
Hi, 

I have 2 warnings on the last "development" version with the last TYPO3 v12 version.

```
PHP Warning: Undefined array key "native" in fluidtypo3/flux/Classes/ViewHelpers/Field/AbstractFieldViewHelper.php line 165
PHP Warning: Undefined array key "position" in fluidtypo3/flux/Classes/ViewHelpers/Field/AbstractFieldViewHelper.php line 166
```

**Comment by Apen** [comment]
I cannot reproduce the bug... So its good for me.
Thanks again Claus 👍

**Comment by olegkarun** [comment]
- flux:field.text 
- flux:field.inline.fal

If add 
native=""  warning despaired
TYPO3 11.5.31, FLUX 10.0.0-10.0.6
