### ISSUE TITLE
Empty {settings} from other Extensions in Frontend

### ISSUE THREAD

**Issue by webdev-pw** [FluidTYPO3/flux#2129]
Hello,

I am currently updating a TYPO3 from v9 to v11 that uses flux. From TYPO3 v11 the extension Flux overwrites all settings of other extensions in the frontend.
As soon as I deactivate the flux templates, the other extensions work again.

**Comment by sdelcroix** [comment]
What version of Flux do you use ?

Do the other extensions inject ConfigurationManager ?

**Comment by webdev-pw** [comment]
Hey @sdelcroix,

i am using Flux 10.0.3.
Yes, the other extensions inject ConfigurationManager e.g. cart & cookieman

**Comment by sdelcroix** [comment]
Can you try this to confirm that is the same issue I’ve opened few days ago ( #2126  ) ? :

replace ConfigurationManager by ConfigurationManagerInterface where it’s injected

**Comment by Konafets** [comment]
@sdelcroix 

> replace ConfigurationManager by ConfigurationManagerInterface where it’s injected

This works. Tested with Powermail.

**Comment by NamelessCoder** [comment]
Duplicate of https://github.com/FluidTYPO3/flux/issues/2126, please follow that issue for status.

**Comment by sdelcroix** [comment]
@Konafets @webdev-pw Could you test the last development version and confirm that it fixes your issue ?

**Comment by webdev-pw** [comment]
@sdelcroix 
Sorry for the late reply. I'm currently on vacation and will test it from September 18th.
