### ISSUE TITLE
Fatal Error in combination with EXT:mask and/or itemsProcFuncs

### ISSUE THREAD

**Issue by rfuehricht** [FluidTYPO3/flux#2132]
Hi!

I am currently upgrading a legacy project to TYPO3 v12 and noticed that EXT:flux and EXT:mask do not work together.

Mask adds some itemsProcFuncs to TCA. Flux breaks because it seems that it expects the Classes used to implement the FormDataProviderInterface of the core.

See Classes/Integration/MultipleItemsProcFunc.php:

`public function execute(array &$parameters, FormDataProviderInterface $formDataProvider): void`

Why those classes must implement FormDataProviderInterface? AFAIK, this is not expected by TYPO3 Core, at least the examples here do not state that: 

https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/CommonProperties/ItemsProcFunc.html#tca-property-itemsprocfunc

Kind regards,
Reinhard

**Comment by rfuehricht** [comment]
Your explanation is totally correct.

I will ask for a fix in EXT:mask then.

Thank you very much for the quick answer.

**Comment by NamelessCoder** [comment]
Fixed in EXT:mask.
