### ISSUE TITLE
Bug: Creating New Page generating error because the Flux Provider 'Page' was not registered correctly

### ISSUE THREAD

**Issue by Sofatraining** [FluidTYPO3/flux#2135]
**I have checked that the bug exists in the `dev-development` branch**
_Yes_

**I have checked that there are no already open issues or recently closed issues about this bug**
_Yes_

**Describe the bug**
Creating New Page generating error.
`FluidTYPO3\Flux\Service\PageService::getPageTemplateConfiguration(): Argument #1 ($pageUid) must be of type int, null given, called in /www/htdocs/.../typo3conf/ext/flux/Classes/Provider/PageProvider.php on line 87`
TYPO3 12.4.6
Probably because the Flux Provider 'Page' was not registered correctly
![flux-provider](https://github.com/FluidTYPO3/flux/assets/47626641/31761945-15fd-4497-94bb-c9f302b6cedf)
Flux Provider 'Content' was registered correctly

Also you can see there are no entries in page properties under 'Page Layouts':
![page-properties](https://github.com/FluidTYPO3/flux/assets/47626641/a69f6135-b124-4fa5-9b5c-efbae245e60b)

Entries in ext_localconf.php:
`\FluidTYPO3\Flux\Core::registerProviderExtensionKey('myextensionkey', 'Content');`
`\FluidTYPO3\Flux\Core::registerProviderExtensionKey('myextensionkey', 'Page');`
'myextensionkey' was of course replaced with the correct key.

**To Reproduce**
1. Go to Page 
2. Click on 'Create New' Wizard
3. Click on 'Insert Page'

**Comment by wrock** [comment]
Same error in TYPO3 11.5.31 with flux 10.0.6

**Comment by xellos866** [comment]
we patched it as followed:
(this is related to: #2138 )

`Classes/Service/PageService.php`:
```php
@@ -59,7 +59,7 @@
- public function getPageTemplateConfiguration(int $pageUid): ?array
+ public function getPageTemplateConfiguration(?int $pageUid): ?array
```

`Classes/Provider/PageProvider.php`
```php
@@ -84,7 +84,7 @@
-        $pageTemplateConfiguration = $this->pageService->getPageTemplateConfiguration($row['uid']);
+        $pageTemplateConfiguration = $this->pageService->getPageTemplateConfiguration((int)$row['uid']);
```
