### ISSUE TITLE
BUG: no tt_content fileds from TCA Overrides after update to 10.0.x and dev 

### ISSUE THREAD

**Issue by olegkarun** [FluidTYPO3/flux#2142]
**I have checked that the bug exists in the `dev-development` branch**
Yes

**I have checked that there are no already open issues or recently closed issues about this bug**
Yes

**Describe the bug**
myext/Configuration/TCA/Overrides/contenet_ext.php additional fields dispirited after update to any 10.0.x version. Works after downgrade to 9.7.2-9.7.4

**Expected behavior**
Get additional fields with new FLUX version

**Additional context**
TYPO3 11.5.32-33
FLUX 10.0.x + dev

**Comment by NamelessCoder** [comment]
Override files for Flux-enabled content types need to be in `Configuration/TCA/Flux/` - the override files must follow the same approach as a standard TCA override file. Alternatively, you can define a replacement default `showitem` that gets used as basis for all Flux-enabled content types, by adding to your `ext_localconf.php` file of your extension (any extension which depends on Flux will work):

```
    \FluidTYPO3\Flux\Utility\CompatibilityRegistry::register(
        \FluidTYPO3\Flux\Builder\ContentTypeBuilder::DEFAULT_SHOWITEM,
        [
            '10.4.0' => '
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:general,
                --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.general;general,
                --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.headers;headers,
                pi_flexform,
            --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,
                --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames;frames,
                --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.appearanceLinks;appearanceLinks,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language,
                --palette--;;language,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access,
                --palette--;;hidden,
                --palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.access;access,
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:categories,
                categories, 
            --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:notes,
                rowDescription'
        ]
    );
```

Modify the long string as needed. The format is documented on https://docs.typo3.org/m/typo3/reference-tca/main/en-us/Types/Properties/Showitem.html.

The reason for needing different files to make TCA overrides compared to earlier versions is a fundamental change made in TYPO3v12 which makes it impossible to trigger the Flux integration at a point where it would be able to register the necessary configuration _and_ happen before TCA overrides are applied. This has forced Flux to use a separate overrides file location which can be loaded at the right time. Note that the Flux-specific overrides _can_ contain also overrides for non-Flux elements, but _should_ contain only overrides for Flux-specific elements.

**Comment by engineintern** [comment]
@NamelessCoder I have two palettes defined in my _Configuration/TCA/Overrides/tt_content.php_ 

 Here is my example code:
 `$tempColumns = [
        'custom_breadcrumb' => [
            'label' => 'Custom breadcrumb',
            'description' => 'Set custom breadcrumb',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectMultipleSideBySide',
                'foreign_table' => 'tx_mytemplateext_domain_model_breadcrumb',
                'foreign_table_where' => 'AND {#tx_mytemplateext_domain_model_breadcrumb}.{#hidden}=0 AND {#tx_mytemplateext_domain_model_breadcrumb}.{#deleted}=0 AND {#tx_mytemplateext_domain_model_breadcrumb}.{#sys_language_uid} IN (-1,0)',
                'fieldControl' => [
                    'editPopup' => [
                        'disabled' => false,
                    ],
                    'addRecord' => [
                        'disabled' => false,
                    ],
                    'listModule' => [
                        'disabled' => false,
                    ],
                ],
                'maxitems' => 1,
            ],
        ],
    ];

    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns(
        'tt_content',
        $tempColumns
    );

    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addFieldsToPalette(
        'tt_content',
        'custom_breadcrumb_settings',
        implode(',', array_keys($tempColumns)),
    );

    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
        'tt_content',
        '--palette--;custom breadcrumb;custom_breadcrumb_settings',
        '',
        'after:linkToTop'
    );

    unset($tempColumns);`

I already added the file as you metioned hier: https://github.com/FluidTYPO3/flux/issues/2142#issuecomment-1840678514

But I am struggling to add it correctly. 
My goal is: All default field and additionally my two palettes in the appearance tab.

Please help me!

**Comment by Oktopuce** [comment]
Does this change use `Configuration/TCA/Flux/` to configure the TCA is documented somewhere ? In flux documentation or in change log ?
I see nothing about that except in this issue.
