### ISSUE TITLE
Incompatibility with 12.4.9 at translated content

### ISSUE THREAD

**Issue by svewap** [FluidTYPO3/flux#2143]
The error occurs as soon as I want to edit a translation.

```
Uncaught TYPO3 Exception: FluidTYPO3\Flux\Integration\MultipleItemsProcFunc::execute(): Argument #2 ($formDataProvider) must be of type TYPO3\CMS\Core\DataHandling\ItemProcessingService, TYPO3\CMS\Backend\Form\FormDataProvider\TcaSelectItems given | TypeError thrown in file /var/www/html/vendor/fluidtypo3/flux/Classes/Integration/MultipleItemsProcFunc.php in line 36
```

I fixed it by modifying MultipleItemsProcFunc and adding ItemProcessingService:

```
    public function execute(array &$parameters, FormDataProviderInterface|ItemProcessingService $formDataProvider): void
    {
```

**Comment by tobiasgraeber** [comment]
@NamelessCoder We also just ran into this and debugged already a bit. 

We think the reason tracks down to this changes here:

- https://github.com/TYPO3/typo3/commit/1c2b6a80101866451719c99af607192aac82c491

To be more specific in that function here: 

- https://github.com/TYPO3/typo3/commit/1c2b6a80101866451719c99af607192aac82c491#diff-83b6e1dbbf02a43046bc231ce4b936bf1bf15ea866eed93b58c208b74f14d826L1272

Around line 1335 - 1340 (old Version) the if-clause changed.

And now, we are not running into the return at https://github.com/TYPO3/typo3/commit/1c2b6a80101866451719c99af607192aac82c491#diff-83b6e1dbbf02a43046bc231ce4b936bf1bf15ea866eed93b58c208b74f14d826L1272 anymore 

We also thought about the same solution like suggested by @svewap
