### ISSUE TITLE
Empty element browser with flux:field.file

### ISSUE THREAD

**Issue by infodry** [FluidTYPO3/flux#2147]
When I use 
```
<flux:field.file name="image" label="Image" useFalRelation="1" allowed="jpg,svg,eps,png,tif,jpeg" /> 
```

it opens an empty element browser with no folder trees. 
I also tried to set config="{renderType: 'file'}" which shows the folder tree but when I select an image the element browser closes and the file is not in set in the form. I just get "Error undefined".

TYPO3 12.4.9, flux 10.0.9, PHP 8.2

PS: I can not use flux:field.inline.fal in this case because I use flux:form.object. But flux:field.file also does not work out side form.object.

**Comment by NamelessCoder** [comment]
I have bad news for you - `flux:field.file` also does not work inside section objects on TYPO3v12. This version of TYPO3 has completely destroyed any option for having a FAL relation within a section object. You have no choice but to find an alternative. One alternative is to convert your section objects into content types and use the content type that currently has the flexform with sections, to a container element. Then iterate over the child content and either render the element (`flux:content.render`) or use the properties of the element (`flux:content.get`) to extract the image, header, etc.

**Comment by infodry** [comment]
Hello Claus, yes that's pretty bad. But thank you very much for your answer and your suggestions.

**Comment by NamelessCoder** [comment]
Closing the issue as there is no solution except to use a different type of field and/or content structure.
