### ISSUE TITLE
BUG: After upgrading from flux 9.7.4 to 10.0.9 ArgumentCountError in ContentTypeManager

### ISSUE THREAD

**Issue by infastra** [FluidTYPO3/flux#2148]
System Environment:
Typo3 v11.5.34

**Describe the bug**
After Updating the flux extension, I get the following error: Too few arguments by instancing ContentTypeManager. The constructor method expected an argument for the CacheService. But in the class Core.php the Utility makes a call without any more arguments.

In my extension I make the following method call:
`\FluidTypo3\Flux\Core::registerProviderExtensionKey('My.Extension', 'Content');`

After comparing the version 10.0.9 with the current development branch the error still exists.

<img width="1186" alt="Bildschirmfoto 2024-01-17 um 09 44 23" src="https://github.com/FluidTYPO3/flux/assets/3442346/3230aaf7-704e-4e8b-b3f8-c9c7c993a981">

**Comment by NamelessCoder** [comment]
@infastra Did you remember to flush the DI caches, using the "Maintenance" module of the backend with a user that is admin and systems administrator? Alternatively, delete all files in `var/cache/code/di`. The dependency injection container has to be rebuilt to register the required arguments.

**Comment by infastra** [comment]
Thank you for your response. After my first try I couldn't call the maintenance modul in my browser, so I did a call in terminal and get the same error. Now after deleting the di-folder I get another error where the code is missing a placeholder. So I think this is an error in my configuration. I will report more in the next week.

**Comment by infastra** [comment]
It was a caching problem, so I close the ticket.
