### ISSUE TITLE
How to migrate wizard.suggest

### ISSUE THREAD

**Issue by infastra** [FluidTYPO3/flux#2149]
This is not a bug, but I looked everywhere and couldn't find a solution. How can I migrate flux:wizard.suggest?

`
<flux:field.multiRelation name="tour" label="Tour" size="1" table="tableName" minItems="0" maxItems="1" required="false">
  <flux:wizard.suggest />
</flux:field.multiRelation>
`

**Comment by magicsunday** [comment]
```
<flux:field type="group"
    name="tour"
    label="Tour"
    config="{allowed: 'tableName', size: 1, minitems: 0, maxitems: 1, required: 1}"
/>
```

Seems like that's the suggest-wizard is not explicitly required anymore. To add any "suggestOptions" pass it to the "config"-Array. https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Group/Properties/SuggestOptions.html

**Comment by NamelessCoder** [comment]
Closing, @magicsunday is right about the new method! By the way this is true for every wizard - the concept of wizards no longer exists as such, it's replaced by field options and you'll need to look up the TCA field type to see which options to use.
