### ISSUE TITLE
TYPO3 12.4.10 - Multilingual - Undefined array key "colPos"

### ISSUE THREAD

**Issue by Apen** [FluidTYPO3/flux#2151]
I have a large website with a lot of languages.
Sometimes, when i edit a content, i have the following error message

```
(PHP Warning: Undefined array key "colPos" in xxx/Classes/Integration/Overrides/BackendLayoutView.php line 118
```

It happen when "BackendLayoutView->colPosListItemProcFunc" is called by the core with a "row" with only uid/pid.
Could it be possible to add a default value to this line (BackendLayoutView.php line 118) :

```php
$parentRecordUid = ColumnNumberUtility::calculateParentUid((integer) $this->record['colPos']);
```

like 

```php
$parentRecordUid = ColumnNumberUtility::calculateParentUid((integer) ($this->record['colPos'] ?? 0));
```

Except that, everything works fine in backend/frontend.

Thanks

**Comment by Apen** [comment]
PR here https://github.com/FluidTYPO3/flux/pull/2156

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/pull/2156
