### ISSUE TITLE
Error message "Tried resolving a template file for controller action "Content->standard" in format ".html"" after update

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#2154]
TYPO3 10.4.28
flux 9.7.4

After upgrading flux from 9.4.0 to 9.7.4 is get the following error message in BE on every page:

`Tried resolving a template file for controller action "Content->standard" in format ".html", but none of the paths contained the expected template file (/html/typo3/typo3_src-10.4.28/typo3/design/Templates/ContentStandard.html). The following paths were checked: /home/www/p/html/typo3/typo3conf/ext/flux/Resources/Private/Templates/, /home/www/p/html/typo3/design/Templates/`

In the content element wizard i have a strange empty new element "content-flux_standard", see screen

Anybody an idea what the reason for this could be?

![Bildschirmfoto 2024-03-10 um 15 51 30](https://github.com/FluidTYPO3/flux/assets/5647051/677999f6-b1ca-4210-a9d6-2e023395c1a9)

**Comment by blueamerican** [comment]
![Uploading Bildschirmfoto 2024-03-10 um 13.14.47.png…]()

**Comment by blueamerican** [comment]
This is the strange new content element.. no idea where it comes from

![Bildschirmfoto 2024-03-10 um 16 39 29](https://github.com/FluidTYPO3/flux/assets/5647051/f98d38ce-d40f-4e40-b5de-fba2abbb2cc2)

**Comment by blueamerican** [comment]
in this ticket a related issue is discussed

https://github.com/FluidTYPO3/flux/issues/2025

**Comment by NamelessCoder** [comment]
This issue should be solved in the most recent release. There were a couple of problems resolving files in the special `design` folder that could have resulted in a wrong template file being used.

**Comment by blueamerican** [comment]
is solved this issue with deleting this file:

typo3/design/Templates/Page/Standard.html
