### ISSUE TITLE
BUG: TYPO3 12 flux:field.file Record Selector dont work

### ISSUE THREAD

**Issue by ms-wa** [FluidTYPO3/flux#2157]
**I have checked that the bug exists in the `dev-development` branch**
_Yes._
If you're about to answer "no" here, it is your responsibility to check `dev-development` **before** opening a bug report!

**Describe the bug**
typo3 flux field file record selector dont work, i tested it with php 8.1 abd 8.2 with different typo3 12 versions

**To Reproduce**
1. create a flux content element with flux field file
2. click on directory item to select file from file list
3. Record selector dont work
4. See white modal

**Expected behavior**

<img width="1080" alt="image" src="https://github.com/FluidTYPO3/flux/assets/100279082/db80c42a-472a-442b-85d5-842884bb0bcd">

**Additional context**
It does not work on a empty typo3 too. 

I use the flux 10.9.0 from development branch.

**Comment by DavidBruchmann** [comment]
see #2139

**Comment by ms-wa** [comment]
@DavidBruchmann thank you four your comment! 
Is there a relatively easy way to migrate flux:field.file to flux.inline fal?

**Comment by DavidBruchmann** [comment]
@ms-wa  well, actually those kind of issues are one reason for me to avoid flux.

**Comment by NamelessCoder** [comment]
Closing the issue, cannot do anything more to change the situation.
