### ISSUE TITLE
BUG: PHP Warning: Undefined array key "colPos" in /flux/Classes/Integration/Overrides/BackendLayoutView.php line 118)

### ISSUE THREAD

**Issue by eckonator** [FluidTYPO3/flux#2159]
**I have checked that the bug exists in the `dev-development` branch**
Yes

**I have checked that there are no already open issues or recently closed issues about this bug**
Yes

**Describe the bug**

- TYPO3 v12.4.14
- Flux v10.0.9
- PHP 8.2.17 / Nginx 1.25.2

**I got for each contentelement in listview this error:**
PHP Warning: Undefined array key "colPos" in /flux/Classes/Integration/Overrides/BackendLayoutView.php line 118)

**Screenshots**
![undefined_array_key_colpos](https://github.com/FluidTYPO3/flux/assets/13748683/dfe7927a-79cb-4d01-ad4f-46621f824263)

**Additional context**
This fixed the wrong behavior for me:

Original Code
`
$parentRecordUid = ColumnNumberUtility::calculateParentUid((integer) $this->record['colPos']);
`

Changed Code
`
$parentRecordUid = ColumnNumberUtility::calculateParentUid((int) ($this->record['colPos'] ?? 0));
`

Please merge it to next patch-level.

**Comment by kraemer-igroup** [comment]
I ran into the same issue, it is already fixed (development branch): issue https://github.com/FluidTYPO3/flux/issues/2151 / pull request https://github.com/FluidTYPO3/flux/pull/2156

**Comment by NamelessCoder** [comment]
Flux 10.0.10 has been released which contains the mentioned fix.
