### ISSUE TITLE
BUG: PHP Warning: Undefined array key "native" in /var/www/html/public/typo3conf/ext/flux/Classes/ViewHelpers/Field/AbstractFieldViewHelper.php line 165

### ISSUE THREAD

**Issue by linawolf** [FluidTYPO3/flux#2181]
After upgrading to TYPO3 v11.5, PHP 8.2 and flux 10.0.10 I get the following errors in Both frontend and backend:

PHP Warning: Undefined array key "native" in /var/www/html/public/typo3conf/ext/flux/Classes/ViewHelpers/Field/AbstractFieldViewHelper.php line 165

**Comment by NamelessCoder** [comment]
Make sure you flush system caches, in particular, flush the Fluid template cache. You may need to do so manually by deleting `var/cache/*` (or `typo3temp/* if your previous TYPO3 was that old). The only context I've seen this error in is when the Fluid template cache isn't flushed and the compiled templates call ViewHelper methods with an incomplete set of arguments. This may happen for any ViewHelper which adds new arguments so it isn't specific to Flux.

**Comment by linawolf** [comment]
Deleting the cache folder does not work. I can neither call the backend nor the cache folders.

```
lina@WCO-LIWO24:~/projects/xxx/xxx$ rm -rf var/cache/
lina@WCO-LIWO24:~/projects/xxx/xxx$ rm -rf public/typo3temp/
lina@WCO-LIWO24:~/projects/xxx/xxx$ ddev typo3 cache:flush

Uncaught TYPO3 Exception FluidTYPO3\Flux\Form\Field\Input::setPlaceholder(): Argument #1 ($placeholder) must be of type ?string, float given, called in /var/www/html/public/typo3conf/ext/flux/Classes/ViewHelpers/Field/InputViewHelper.php on line 50
thrown in file /var/www/html/public/typo3conf/ext/flux/Classes/Form/Field/Input.php
in line 78
```

There seems to be indeed no sanity check weather the $arguments array contains the correct types and the keys are set:

InputViewHelper line 50:

```
        $input->setPlaceholder($arguments['placeholder']);
```

The last version for which this worked for me was TYPO3 11.5, PHP 8.2 and  fluidtypo3/flux 9.7.4

**Comment by NamelessCoder** [comment]
One step further though, the undefined array key thing is solved.

The other error appears to be from not considering that Fluid will pass integer/float for numeric node values and "placeholder" values may of course be integers/floats, a case that was overlooked when strict types were added to setter methods.

This will need to be fixed with an added check for `is_string()` or `=== null` and if both are false, cast the value to string where the `setPlaceholder` method is called.

**Comment by linawolf** [comment]
So I should patch the code of flux?

**Comment by NamelessCoder** [comment]
I would appreciate if you have the time, create a pull request with that change (and other similar cases you may encounter, the solution is always the same for that kind of error). I can pretty much guarantee an instant merge and new release before the end of this week, I'm just stuck on other tasks and can't take care of it myself right now.
