### ISSUE TITLE
BUG: TYPO3 Backend and CLI Cache Clear Fail After Upgrading Flux from V10.0.10 to V10.1.0

### ISSUE THREAD

**Issue by HimanshuRamavat07** [FluidTYPO3/flux#2202]
**I have checked that the bug exists in the `dev-development` branch**
Yes

**I have checked that there are no already open issues or recently closed issues about this bug**
_Yes or no._
Yes

**Describe the bug**
I have upgraded the flux version from V10.0.10 to V10.1.0. Now, when I try to cache clear through the command line, the error below is displayed. Also, the TYPO3 backend is not working. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade Version.
2. Try to cache flush using the Command line.
3. See error.

**Expected behaviour**
The cache must be clear and backed must be accessible. 

**Screenshots**
![image](https://github.com/user-attachments/assets/465776e0-68b7-43a6-b0e6-842851f98c9b)

**Additional context**
TYPO3 Version: 12.4.20 [Composer mode]
PHP version: 8.3

**Comment by rtfirst** [comment]
After I removed the var/cache folder i can exec the typo3 cache:flush command in cli console.

**Comment by HimanshuRamavat07** [comment]
Thanks @rtfirst
