### ISSUE TITLE
argument table in field.wizard.suggest has no effect

### ISSUE THREAD

**Issue by joneppie** [FluidTYPO3/flux#283]
I write `<flux:flexform.field.wizard.suggest table="pages"/>` in the template but the parameter for table in the post-request is tt-content

**Comment by pixelplant** [comment]
Is there any up-to-date documentation on this issue?
The "input" field still points to tt_content and I understand it's not supported, but what is the proper syntax to use it with a select? A select requires the "items" property to be defined, so I'm setting it as empty so far...
This is the code that I call but I get no pages displayed from the search (latest version of flux with T3 v.6.15) and the table passed to the query still points to tt_content
```
	<flux:field.select name="link" items="" label="LLL:EXT:hdv/Resources/Private/Language/locallang.xlf:flux.swiperRelated.fields.link">
		<flux:wizard.suggest table="pages" searchCondition="doktype = 1"/>
	</flux:field.select>
```
