### ISSUE TITLE
[BUG] Rich text editor (RTE) support broken for <flux:flexform.field.text> in the introduction package

### ISSUE THREAD

**Issue by jkphl** [FluidTYPO3/flux#339]
Hi,

I'm working with the latest versions of the vhs, flux, fluidpages, fluidcontent and fluidcontent_bootstrap extensions (from the Git master branch) and TYPO3 CMS 6.1.5.

In a custom fluid content element, I want to have a text field with RTE features. As far as I understood, I shouldn't have to do more than

``` xml
<flux:flexform.field.text name="bodytext" enableRichText="TRUE"/>
```

to achieve this, right? Unfortunately this doesn't work for me – the field just renders as a textarea without RTE controls.

Also, in an unmodified **introduction package** install, the **bootstrap carousel content element** doesn't show an RTE field as well (but it should, as far as I read from the sources, right?).

However, a quick check of the configuration compiled for my text field in `Tx_Flux_Form_Field_Text` looks just fine:

``` php
Array
(
    [type] => text
    [transform] => 
    [default] => 
    [rows] => 10
    [cols] => 85
    [defaultExtras] => richtext[*]:rte_transform[mode=ts_css]
)
```

BTW, the RTE **does work** in regular (non-fluid) text content elements, so it's not a browser problem whatsoever ... Am I missing something? Any help appreciated!

**Comment by samowitsch** [comment]
I have the same problem here. No RTE in BE?
```xml
<flux:field.text label="Text" name="text" enableRichText="TRUE" defaultExtras="richtext[*]:rte_transform[mode=ts_css]"/>
````

I am using TYPO3 v6.2.9 and all needed extensions from Github.

Cheers
