### ISSUE TITLE
flux:field.inline.fal inside flux:form.object

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [FluidTYPO3/flux#478]
I try to put a `flux:field.inline.fal` inside `flux:form.object` on TYPO3 6.2, flux and fluidcontent (all GIT master) like this:

```
<flux:form.object name="element">
    <flux:field.inline.fal name="image" />
</flux:form.object>
```

The form is correctly rendered in the BE but as the name of the object is used as reference in table `sys_file_reference` (field `fieldname`) for all elements the correlation element<>image is lost. If I add three elements and assign one image per element all elemets have all three images after saving.

So how do I get a correct element<>image correlation? I thought of dynamically adding an index or the element-id to the object (image.0, image.1 etc.) but don't really know where to start.

As a workaround I use `flux:field.file` inside `flux:form.object`. But as FAL offers so much more features I'd like to use it if it's possible.

**Comment by kraftb** [comment]
I have a solution for this problem:
https://github.com/FluidTYPO3/flux/pull/815

But simply applying this patch would break existing contents of normal non-section FAL fields in flux elements.
