### ISSUE TITLE
Backend Stylesheet not loaded

### ISSUE THREAD

**Issue by mpeu** [FluidTYPO3/flux#499]
Hello,
we've setup a fresh TYPO3 6.2 with latest stable version of vhs,flux,fluidpages,fluidcontent.

Within page module the stylesheet is not loaded correctly. 
In \flux\Classes\Backend\Preview.php:159

$doc->getPageRenderer()->addCssFile(ExtensionManagementUtility::extRelPath('flux') . 'Resources/Public/css/grid.css');

Results in following line in backend -> page module  which results in a 404 (as we are in this path /typo3/sysext/cms/layout/db_layout.php) 
../typo3conf/ext/flux/Resources/Public/css/grid.css

It works within this path:
../../../../typo3conf/ext/flux/Resources/Public/css/grid.css

I've tried all possible Combinations for extension paths by ExtensionManagementUtility but cannot find any working method for extension path in this case. Maybe someone finds a better way than adding this path hardcoded before  "../../../".

**Comment by dmitryd** [comment]
Still does not work (TYPO3 6.2.26). The code we see:

```php
	/**
	 * @return void
	 */
	protected function attachAssets() {
		if (FALSE === self::$assetsIncluded) {
			$doc = GeneralUtility::makeInstance('TYPO3\\CMS\\Backend\\Template\\DocumentTemplate');
			$doc->backPath = $GLOBALS['BACK_PATH'];

			$doc->getPageRenderer()->addCssFile($doc->backPath . ExtensionManagementUtility::extRelPath('flux') . 'Resources/Public/css/grid.css');
			$doc->getPageRenderer()->addJsFile($doc->backPath . ExtensionManagementUtility::extRelPath('flux') . 'Resources/Public/js/fluxCollapse.js');
			self::$assetsIncluded = TRUE;
		}
	}
```

The error we see in logs:
```
2016/09/22 07:28:05 [error] 22422#0: *4387219 open() "/home/***/www/typo3/sysext/cms/typo3conf/ext/flux/Resources/Public/css/grid.css" failed (2: No such file or directory), client: 212.98.33.178, server: ***.ch, request: "GET /typo3/sysext/cms/typo3conf/ext/flux/Resources/Public/css/grid.css HTTP/1.1", host: "***.ch", referrer: "https://***.ch/typo3/sysext/cms/layout/db_layout.php?id=168"
```

I checked, we do not have any other references to `grid.css` that can cause this.
