### ISSUE TITLE
BE Style in flux:grid.column

### ISSUE THREAD

**Issue by misterboe** [FluidTYPO3/flux#553]
Since typo3 6.2.1 the BE styling does not work

in 6.2.0 this elements shows a border in BE; it's ignored in 6.2.1

```
<flux:grid.column style="width: 50%;border-right: 1px dotted #999;">
</flux:grid.column>
```

6.2.0
![bildschirmfoto 2014-05-09 um 08 52 19](https://cloud.githubusercontent.com/assets/6050140/2925231/7292abbe-d747-11e3-8cdc-b46ce370be22.jpg)

6.2.1
![bildschirmfoto 2014-05-09 um 09 00 01](https://cloud.githubusercontent.com/assets/6050140/2925236/95f384d4-d747-11e3-9182-be3109a8c530.png)

**Comment by typo3ua** [comment]
I have the flux 7.3.0 and TYPO3 7.6.4 but my styling does not work in backend layout.

**Comment by cedricziel** [comment]
A 2 years old ticket? 

Please.

Open up a new one if you're stuck.
