### ISSUE TITLE
Content affiliation in BE Colums of FCE Elements

### ISSUE THREAD

**Issue by misterboe** [FluidTYPO3/flux#554]
I have a flux:form.section with an object:

```
<flux:form.section name="Section" label="Section">
   <flux:form.object name="Object" label="Object">                       
   </flux:form.object>
</flux:form.section>
```

and i create BE Colums for each Section

```
 <flux:grid>
   <f:for each="{Section}" as="item" iteration="iteration">
      <flux:grid.row>
         <flux:grid.column>
           <flux:form.content name="Colum.{iteration.index}">
           </flux:form.content>
         </flux:grid.column>
      </flux:grid.row>
   </f:for>
</flux:grid>
```

Now i put some simple Contentelement in there (Text)

and now to the Problem:

When i switch the sorting of the Objects inside the FCE, the Colums in the Pageview gets switcht, but the Content is an his old position.

Here Some Screenshots:

Before the switch:

![l6vcc](https://cloud.githubusercontent.com/assets/6050140/2928167/83731e88-d778-11e3-94d4-0dd303430ffe.png)
![nzvte](https://cloud.githubusercontent.com/assets/6050140/2928168/8681f5c2-d778-11e3-8cac-f6d8bc164fb6.png)
![oa88z](https://cloud.githubusercontent.com/assets/6050140/2928172/88d08c12-d778-11e3-856e-19ad40de70f3.png)

After switching the Objects per d&d

![gxhbv](https://cloud.githubusercontent.com/assets/6050140/2928178/abb31be6-d778-11e3-804b-877f211e2e5a.png)
![x5tg1](https://cloud.githubusercontent.com/assets/6050140/2928179/af197d48-d778-11e3-9233-557e37468878.png)
![2j2uu](https://cloud.githubusercontent.com/assets/6050140/2928180/b1f10a5e-d778-11e3-8cc4-4d9354b90ed6.png)

My FCE File: 
https://gist.github.com/misterboe/761a0fa3cd24791a1ab6

The problem is also in this File (which is from @NamelessCoder )
https://github.com/bootstraptheme-for-typo3/fluidbootstraptheme/blob/master/Resources/Private/Templates/Content/Tabs.html

Typo3 6.2.1
FT3 Ext latest dev from 29.Apr

**Comment by bauermar** [comment]
The problem stil exists!!! Somebody a fix?

**Comment by NamelessCoder** [comment]
@bauermar Please read my last comment, it tells you how to fix the issue. This is not a problem caused by Flux, it's caused by the way you use the iteration to identify your sections (and it would be a problem with any FlexForm source used the same way). We provide the convenience `id` property for your objects. Please use it ;)

**Comment by NamelessCoder** [comment]
Locked, nearly two years old.
