### ISSUE TITLE
[BUG] create copy of element 

### ISSUE THREAD

**Issue by misterboe** [FluidTYPO3/flux#615]
if you copy a "text" element inside a FCE and paste after the original the element is not shown in BE. You can see the "copy1" in list module. 

The problem seems that tx_flux_column and tx_flux_parent is not taken from the origninal element. If i set these values manual its woking. 

latest flux 8c1f7174227fc6c4013aca92c5d452ace206155a

**Comment by NamelessCoder** [comment]
Seems to be long gone but if it pops up again for any combination of column/area/language please add info to #573 ;)
