### ISSUE TITLE
[FEATURE] flux:form icon to show in page module

### ISSUE THREAD

**Issue by Idleworks** [FluidTYPO3/flux#672]
In TYPO3 6.2 only icons of the content elements are displayed (names are hidden). Content elements of Flux always shows the TYPO3 icon, although in flux: form an icon was specified. 
Is it possible to show that icon in list/page module instead of default icon?

![ce-icon](https://cloud.githubusercontent.com/assets/6685173/4683882/f56bcafe-562a-11e4-8495-408e698027eb.jpg)

**Comment by NamelessCoder** [comment]
Pull request with this feature is currently being processed - closing the issue.
