### ISSUE TITLE
Usage of query in flux:field.select

### ISSUE THREAD

**Issue by shredding** [FluidTYPO3/flux#679]
I try to use the documented feature of using a query in flux field select.

There is absolutely nothing i can do to make this work, and i waded through the entire code.

Could you please specify an example or look if it's featured at all?

Thank you very much.

**Comment by MisatoTremor** [comment]
@shredding Could you please provide an example of how you achieved it?
As of now the current argument for this seems to be items and it accepts "array / CSV / Traversable / Query". Query seems to be the correct one but I don't now how to get create a query in the template. (Maybe @NamelessCoder could explain that)

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin am Freitag, 20. November 2015 abwesend und gerne am Montag, 23. November 2015 wieder für Sie da. 
 
Die Nachricht wird nicht weiter geleitet! In ganz dringenden Fällen bin ich auf dem Mobile zeitweise erreichbar.


Einen guten Tag wünscht

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by NamelessCoder** [comment]
@MisatoTremor Query instances are normally created via a Repository, which means that you create it from a controller and assign it to a template (or extract it from a QueryResult, which also contains a reference to the Query that yielded the result).
