### ISSUE TITLE
[BUG] style for columns is not longer applied

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#685]
Style is not longer applied to Page Layout <flux:grid.column style="background:red;" />

**Comment by NamelessCoder** [comment]
Unable to accommodate this when it concerns *page* columns, but can implement (if currently missing) in all Flux content areas. The page layout view requires an XCLASS for this and such a class cannot be made compatible with both 6.2 and 7.x.

`PreviewView` should be checked if it applies the style - if it does, this issue can be closed. If not, it should be a fairly simple matter to render it.

**Comment by NamelessCoder** [comment]
Already supported in content templates - cannot support in page templates.
