### ISSUE TITLE
Inhertitance of settings - empty XML value breaks it

### ISSUE THREAD

**Issue by githubrsys** [FluidTYPO3/flux#712]
## Summary

While this problem is with pages I think the problem itself relies in flux.

I want to give editors the opportunitiy to define where the mainmenu shall begin. I have a constant for this and a setting in the flux page-configuration form of the page settings. 

For somplicity I've got 2 pages. id=3 and id=7. id=7 is a child of id=3. As soon I set something in Page Configuration - subpages of id=3 the expected value is set in FE as expected and inherited by id=7 in FE. 
* If I now open the page settings of id=7 I see a value inherited from id=3 (BTW: inherited values should be marked visible as inherited). 
* If I now hit save button without changing anything a xml value is written to pages:tx_fed_page_flexform
shortened: ```<field index="settings.mainMenuRootPageUid">
                    <value index="vDEF">3</value>
                </field>``` of id=7
* If I now change the value to something different in id=7 it works as expected and the menu gets rendered from a different source
* If I remove the value from the field and hit save the db entry changes to: ```<field index="settings.mainMenuRootPageUid">
                    <value index="vDEF"></value>
                </field>```
* But now the inheritance from id=3 is broken. Which IMHO should not be the case. settings.mainMenuRootPageUid is empty in FE but should be inherited from id=3 or from the constant
* The clear attribute seems to have no impact of anything at all - no matter if used or not

##### If I truncate the  pages:tx_fed_page_flexform field in DB of id=7 the inheritance is working again

And If I do not use the flux but constants at all it also works as expected but granting editors access to the constants seems to me not the real deal.

### The sheet looks like this
```
<flux:form.sheet name="menusettings" label="Menü">
            <flux:field.input size="4"  clear="true" inheritEmpty="false" name="settings.mainMenuRootPageUid" label="foo">
                <flux:wizard.link label="Auswählen" activeTab="pagetree"></flux:wizard.link>
            </flux:field.input>
        </flux:form.sheet>
```

### FE Template looks like this
```
<ul id="mainMenu" class="rp{settings.mainMenuRootPageUid}" role="menu">
                <v:page.menu accesskey="m" as="menu" classFirst="first" classLast="last" classActive="active" classCurrent="current" classHasSubpages="hasSub" expandAll="true" levels="5" useShortcutData="true" pageUid="{settings.mainMenuRootPageUid}">
 </v:page.menu>
            </ul>
```

**Comment by NamelessCoder** [comment]
Related to https://github.com/FluidTYPO3/flux/issues/727
