### ISSUE TITLE
FAL: IRRE instead of Object

### ISSUE THREAD

**Issue by GuidoJansen** [FluidTYPO3/flux#713]
I know that this is not possible

    <flux:form.section name="sec" label="Section">
      <flux:form.object name="obj" label="Object">
        <flux:field.inline.fal name="image" />
      </flux:form.object>
    </flux:form.section>

So I thought of using IRRE inside the Configuration section of the template file (within a provider extension). I thought `<flux:field.inline>` would be the right thing to use instead of the `section`/`object` thing. But I don't know how to handle this.
I want another Template from my provider extension

I have 

    <flux:field.inline name="object-irre"
                       table="tt_content"
                       foreignField="tx_flux_parent"
                       />

But what then? I somehow need to add the `CType` and the `tx_fed_fcefile`.

CType --> fluidcontent_content
tx_fe_fcefile --> &lt;myExt>:&lt;Template>.html

**Comment by NamelessCoder** [comment]
@GuidoJansen Have you found an answer to this question on IRC for example? Your goal:

> I want another Template from my provider extension

Is not clear to me. Are you sure that for example an `flux:field.select` with `size` set to a reasonably high number isn't preferable to this section/irre? Would it make more sense to make this one a content field that you can insert "Image" elements into? You can limit the allowed content types in content columns you create using Flux and you can edit them through the parent element as well.

**Comment by NamelessCoder** [comment]
I'll take the liberty of closing this one, with a few final hints:

* Child objects can already be edited using the "Relations" tab - and it looks like this is what you're trying to do.
* The IRRE as well as relation and (in dev currently) multiRelation fields support a condition which allows you to insert variables from the record as well as hardcoded conditions for `CType` value etc. - so you *could* use that, but I'm not sure you would get the right result when *creating* new relations.
* Perhaps what you are looking for is to restrict the allowed types of elements you can place into a proper Flux content area - those options work in both page and content columns and allow you to limit the types of content elements you can insert, to any number of types - including a single type.

**Comment by GuidoJansen** [comment]
The issue I have:
I don't know how two handle the `<flux:field.inline>`
How does this work?

**Comment by NamelessCoder** [comment]
We support the same parameters as described on http://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Inline/Index.html - exactly *how* you configure the IRRE in each case completely depends on your desired results (which aren't clear to me yet), but I have to warn you that it may not handle elements in a sensible way if you use it with the `tt_content` table which it appears is what you are trying to do.

You should consider if a content area with rules about allowed child content types (you can target both `CType`s and fluid content types), or a `flux:field.multiRelation` is what you need.
