### ISSUE TITLE
Including flux:form element partials from other extensions breaks automatic labels

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/flux#722]
Flux has the very useful feature to automatically generate LLL references for labels of forms, sections elements etc.
However, the LLL reference always points to the locallang file inside the extension currently rendering the fluid template. This makes it impossible to include form partials across extensions, as the reference to the active extension is not changed by fluid automatically. All generated LLL references then point to the locallang file of the wrong extension, which means there will be no labels in the backend at all. The only workaround known to me is copying all (relevant) labels from the referenced extension to my own extension's locallang file.

As a consequence, it is currently not feasible to use the standard forms provided by fluidcontent_core for custom CE variants, see FluidTYPO3/fluidcontent_core#110.

**Comment by NamelessCoder** [comment]
Feature introduced by https://github.com/FluidTYPO3/flux/commit/a9ec0b14c54f770f47b0cb30e6992090fa0684e1 - thanks for requesting!

**Comment by pkerling** [comment]
Thank _you_ for implementing it!
