### ISSUE TITLE
content element icon has wrong path

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#724]
```
<flux:form id="mycontent" options="{icon: 'Icons/Content/Example.gif', group: 'mysite'}">
```

creates:

```
<img alt="" src="../../../Icons/Content/Example.gif">
```

the file is existant, but the path seems to be wrong

**Comment by rathgeber2** [comment]
its back again, but different :).

Typo3 Version 6.2, Flux 7.2.1, vhs 2.3.3, fluidcontent 4.3.1, fluidpages 3.3.1
Typo3 Version 7.4, Flux 7.2.1, vhs 2.3.3, fluidcontent 4.3.1, fluidpages 3.3.1

happens in fuidbootstraptheme Content Element and Custom Content Elements

 <flux:form id="grid3" options="{useTypoScript: 0, group: 'Grid', Fluidcontent: {sorting: 100}, icon: '{f:uri.resource(path: \'Icons/Content/ThreeColumn.png\')}'}">

results in 
6.2
<img src="../../..//var/www/html/sfz-chemnitz.de/cms/typo3conf/ext/fluidbootstraptheme/Resources/Public/Icons/Content/ThreeColumn.png" alt="">

7.4
<img src="../../typo3temp/pics/4c5bd83fd5.png" alt="">
