### ISSUE TITLE
includeRecordsWithoutDefaultTranslation not working

### ISSUE THREAD

**Issue by camuco** [FluidTYPO3/flux#725]
Hi, inside a flux grid the option styles.content.get.select.includeRecordsWithoutDefaultTranslation = 1 seems not to work. I want to display translated elements without parents in the default language in a setting with:
config.sys_language_overlay = hideNonTranslated
config.sys_language_mode = strict
This works for TYPO3 content elements, but not inside a grid. Any ideas?

**Comment by NamelessCoder** [comment]
`styles.content.get.select.includeRecordsWithoutDefaultTranslation` appears to be a `css_styled_content` specific behavior related to rendering content by markers; e.g. copying the `styles.content.get` and setting the condition that selects content. Flux renders elements by ID and selects the list of IDs to render in (approximately) the same way as a standard `RECORDS` cObject would.

Flux does not support this particular `css_styled_content` option - but Flux **does** (or should I rather say, should) support both of the language overlay and language mode toggles in the `config.` scope.

Are the `config.` toggles not working as expected?

**Comment by NamelessCoder** [comment]
Hi @camuco - any updates on this? I need to confirm if the TS options are working - the `config.sys_language_mode = strict` instruction should also apply to content rendered by Flux, but the CSC-specific TS is (by design) not considered.

**Comment by camuco** [comment]
I couldn't make it work. The workaround I've found, is using two separate container elements, one in the default language, one in the translated language, with no mapping between them. The inner elements are then shown without a default translation. This doesn't work with translated container elements, which are mapped to an element in the default language.

**Comment by NamelessCoder** [comment]
Backend-related issues with translation and containers either fixed or can now be affected using translation toggles on `flux:form` (see https://github.com/FluidTYPO3/flux/issues/852#issuecomment-128860963). Frontend-related issues are described closer, in a non-`css_styled_content` context, on https://github.com/FluidTYPO3/vhs/issues/761.
