### ISSUE TITLE
Fatal error: Cannot use string offset as an array

### ISSUE THREAD

**Issue by avenit** [FluidTYPO3/flux#727]
When using a flux based flexform like in fluidpages, the flexform data is modified by FluidTYPO3\Flux\Provider\AbstractProvider::postProcessRecord. More precisely, it removes fields from data xml. This may lead to empty sheet tags which itself leads to the fatal error:
"Fatal error: Cannot use string offset as an array in [...]/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php on line 223"

I suggest to remove empty sheets after removing the fields like this (in the method mentioned above):

    foreach ($dom->getElementsByTagName('sheet') as $sheetNode) {
      $fieldsInSheet=$sheetNode->getElementsByTagName('field');
      if(!$fieldsInSheet->length)
        $sheetNode->parentNode->removeChild($sheetNode);
    }

Edit: typo3 version is 6.2.9

**Comment by NamelessCoder** [comment]
Confirmed: the trimming of values needs a bit of love.

**Comment by NamelessCoder** [comment]
Implemented in https://github.com/FluidTYPO3/flux/commit/50d57d997684d39a4f8fd42df9e5105bc6093e62
