### ISSUE TITLE
[FEATURE] Option to use complete custom ``templateRootPath`` path

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/flux#730]
Currently i have this folder structure.
I want to have it this way so that i have a complete theme with all templates nicely structured in one extension.
```
ext/bdm_theme/Resources/Private
└── Templates
    ├── Content
    │   ├── Columns2-50Pc-50Pc.html
    │   ├── Columns3-25Pc-50Pc-25Pc.html
    │   ├── ...
    │   ├── Layouts
    │   └── Partials
    ├── CoreContent
    │   ├── Bullets.html
    │   ├── Default.html
    │   ├── Div.html
    │   ├── ...
    │   ├── Layouts
    │   └── Partials
    ├── Page
    │   ├── PageLayoutDefault.html
    │   ├── ...
    │   ├── Layouts
    │   └── Partials
    └── TxNews
        └── News
            ├── Detail.html
            └── List.html

```
The typoscript configuration for this is:
```typoscript
plugin.tx_fluidcontent.collections.bdm_theme {
	templateRootPath = EXT:bdm_theme/Resources/Private/Templates/
	partialRootPath = EXT:bdm_theme/Resources/Private/Templates/Content/Partials/
	layoutRootPath = EXT:bdm_theme/Resources/Private/Templates/Content/Layouts/
}
```
Now flux automatically adds the current controller (eg. ``Content``) name as a folder to the end of the ``templateRootPath``.
 So ``EXT:bdm_theme/Resources/Private/Templates/```
---->
becomes ``EXT:bdm_theme/Resources/Private/Templates/Content/``

This prevents me from using a custom subfolder for the templates like:
```
.
└── Templates
    ├── Content
    │   ├── Layouts
    │   ├── Partials
    │   └── Templates
    │       ├── Columns2-50Pc-50Pc.html
    │       ├── Columns3-25Pc-50Pc-25Pc.html
    │       ├── ...
    ├── CoreContent
    │   ├── Layouts
    │   ├── Partials
    │   └── Templates
    │       ├── Bullets.html
    │       ├── Default.html
    │       ├── Div.html
    │       ├── ...
    ├── Page
    │   ├── Layouts
    │   ├── Partials
    │   └── Templates
    │       └── PageLayoutDefault.html
    └── TxNews
        └── News
            ├── Detail.html
            └── List.html
```

Is there a way to do this?
Which way should/could such a feature be implemented?

**Comment by BenjaminBeck** [comment]
Hi NamelessCoder,

thank you for the great description. It helped me to understand & remember some points i didn´t before.

> The folder structure you suggest would not be possible [...] The usual way of dealing with this problem (which is: shipping templates for X number of third-party  extensions) is to create one templateRootPath per extension and to not nest this additional templateRootPath inside the default Templates folder unless absolutely required. 

I changed the directory structure. As i understand, this does no break the template paths convention:
```
.typo3conf/ext/bdm_theme_bootstrap/Resources/Private
├── Templates
├── TxFluidcontent
│   ├── Layouts
│   ├── Partials
│   └── Templates
│       └── Content
│           ├── Columns2-50Pc-50Pc.html
│           ├── Columns3-25Pc-50Pc-25Pc.html
│           [...]
├── TxFluidcontentcore
│   ├── Layouts
│   ├── Partials
│   └── Templates
│       └── CoreContent
│           ├── Bullets.html
│           ├── Default.html
│           ├── [ ... ]
├── TxFluidpages
│   ├── Layouts
│   ├── Partials
│   └── Templates
│       └── Page
│           ├── PageLayoutDefault.html
│           ├── [ ... ]
└── TxNews
```

I registered the fluidpages templates with TS because the ``\FluidTYPO3\Flux\Core::registerProviderExtensionKey`` has no option to provide a path:
```ts
plugin.tx_fluidpages.collections.bdm_theme_bootstrap {
	templateRootPath = EXT:bdm_theme_bootstrap/Resources/Private/TxFluidpages/Templates/
}
```
But with this it had problems to find the controller class (``BDM\BdmThemeBootstrap\Controller\PageController``).

As a workaround i manually included that controller class in ext_localconf and extended it as (``BdmThemeBootstrap\Controller\PageController``).

Is it right/known, that vendor prefixes are not supported for controller classes if the templates are defined with typoscript?

**Comment by NamelessCoder** [comment]
> Is it right/known, that vendor prefixes are not supported for controller classes if the templates are defined with typoscript?

Yes, that is correct. Defining your templates this way is considered legacy and is there mainly to support very old unmigrated installs where templates reside in `fileadmin`. You *might* be able to get the right result by doing:

```
plugin.tx_fluidpages.collections.bdm_theme_bootstrap.extensionKey = BDM.BdmThemeBootstrap
```

...but that solution comes completely without warranty and is still considered legacy. I fear some parts of Flux might reject this because not all code enforces conversion of the input to the expected type which in this case would be a `underscored_lowercase` style extension key.

Although it isn't always pretty, the ideal solution is to use one `templateRootPath` (and await our adjustments to support `templateRootPaths` instead) and rely on the controller name to separate the templates into purpose groups.

Flux will be migrating to `templateRootPaths` which will allow you to *additively* override templates, partials and layouts which will help a lot. Basically, it will do what the current `overlays` method does, but be entirely based on TYPO3's native behavior as per 6.2.

**Comment by NamelessCoder** [comment]
I'll take the liberty of closing this one. If anybody comes up with a solution involving the `subPackage` of view paths without breaking compatibility with current setups then I'd be happy to accept that patch!
