### ISSUE TITLE
getParent() / setParent() in \FluidTYPO3\Flux\Form\WizardInterface

### ISSUE THREAD

**Issue by bucha** [FluidTYPO3/flux#731]
As `\FluidTYPO3\Flux\Form\WizardInterface` inherits from `\FluidTYPO3\Flux\Form\FormInterface`, the methods `getParent()` and `setParent()` in the WizardInterface are obsolete. In my case I even receive an error such as follows:

PHP Fatal error:  Can't inherit abstract function FluidTYPO3\\Flux\\Form\\FormInterface::setParent() (previously declared abstract in FluidTYPO3\\Flux\\Form\\WizardInterface) in /var/www/…/htdocs/typo3conf/ext/flux/Classes/Form/WizardInterface.php on line 31

**Comment by NamelessCoder** [comment]
Thanks @bucha :)
