### ISSUE TITLE
[TASK] Add fa icon in v7 for reference a element

### ISSUE THREAD

**Issue by xf-** [FluidTYPO3/flux#736]
Right now in v7 we use the old colored icon and not a fa icon.
Icon maybe fa-link or any of fa-share or share-alt icons.

And the collapse button should also be replaced.

**Comment by NamelessCoder** [comment]
We should try to approach the new style used by TYPO3, offsetting the paste icons to the right and only displaying the paste-after-element ones as clickmenu items.
