### ISSUE TITLE
flux field input default value

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#738]
for me the default value is always empty if i use:
```
<flux:field.input name="class" default="myclass" label="Class"/>
```
any suggestions?

**Comment by githubrsys** [comment]
Cannot confirm. Works always as expected here. Prehaps you have an error elsewhere so this might be a regression then. You can test your syntax with ext:builder

**Comment by blueamerican** [comment]
sorry, you're right. maybe it was a cache issue
