### ISSUE TITLE
flux:wizard.slider initialisation on load

### ISSUE THREAD

**Issue by githubrsys** [FluidTYPO3/flux#739]
If I create a new content object which has some global settings in a sheet I do not see any wizard.slider at all. 
* If I hit "save" - the slider appears - but without the default value from the input field set
* I have to hit "save" once again to get the default value of the input field getting applied to the wizard.slider.

ext:builder says all is well

**Comment by NamelessCoder** [comment]
I'm afraid this one is a long-time bug in TYPO3 itself. The bug causes slider initialisation to not use the default value when the slider is attached to a field inside a flexform and would be caused in any flexform with or without flux. It appears to be an issue with the JS.

I suggest reporting this one to the TYPO3 core bug tracker.

**Comment by githubrsys** [comment]
Would you give advice how to discribe the issue correct for forge?

**Comment by NamelessCoder** [comment]
Sure. I'd describe it alone the lines of "If a TCA slider wizard is used in a field with a default value and the field is placed inside a flexform field, the slider is not initialised with the correct value. If the same slider wizard is used on a field that is not inside a flexform field, the slider initialisation works correctly. Suspected cause is the different nesting and naming that applies when the slider wizard is used inside a nested structure. Potentially also an issue for IRRE fields."
