### ISSUE TITLE
Links inserted via flux:field.text, RTE enabled, are not rendered by realUrl

### ISSUE THREAD

**Issue by jazzica** [FluidTYPO3/flux#740]
Hi,

I have several content elements with a flux:field.text, RTE enabled. Unfortunately links I add via the mentioned fields do not get rendered by realUrl. RealUrl is working fine for the rest of my page so I'm guessing it's a problem with the flux:field.text? 

flux 7.1.2
fluidcontent 4.1.1
realUrl 1.12.8 
Typo3 6.2.9 multi-domain installation

Thanks for the help!

**Comment by githubrsys** [comment]
If the links are not rendered at all, then you have to use :
### In ``<f:section name="Configuration">``
``
<flux:field.text name="Text" label="Whatever" enableRichText="1"></flux:field.text>
``
### In ``<f:section name="Main">``
``
<f:format.html>{Text}</f:format.html>
``

If they are rendered but not realurl'ed then the fault relies somwhere else.

**Comment by jazzica** [comment]
I'm using <f:format.html> for output, so that's not the problem. Links are rendered but not realurl'ed.

**Comment by githubrsys** [comment]
Nontheless I've to say: Here it works everytime I use realURL or CoolURI. No Problem ever had. So I can only give the advice to upgrade to the most recent git:master versions of flux, fluidcontent and realurl.

PS: be sure not to have disabled realurl somewhere in the pagetree.

**Comment by bjo3rnf** [comment]
Been there. Use ``defaultExtras="richtext:rte_transform[flag=rte_enabled|mode=ts_css]"`` which is - I think - the new default in an upcoming release of flux.

**Comment by jazzica** [comment]
yes, problem solved. Thanks a lot!
