### ISSUE TITLE
fluidtypo3.org is down

### ISSUE THREAD

**Issue by GuidoJansen** [FluidTYPO3/flux#741]
This message appears on https://fluidtypo3.org/
1301648945: Database Error: The current username, password or host was not accepted when the connection to the database was attempted to be established!

Seems, your DB creadentials have changed.

**Comment by NamelessCoder** [comment]
Fixed, see https://github.com/FluidTYPO3/fluidtypo3org/issues/26

**Comment by GuidoJansen** [comment]
Very nice.
