### ISSUE TITLE
Unset templates for a specific tree branch

### ISSUE THREAD

**Issue by InvisibleKind** [FluidTYPO3/flux#747]
Hi,

A possibility to disable custom CEs for a specific branch is needed.

I've tried 2 cases: disable for a sub-branch and disable for a root-page.

Sub-branch disabling was useless. I've created a TS template record on a sub-branch, where I've disabled complete `view` section of my provider extension by `plugin.tx_myext.view >` and ensured with `TypoScript Object Browser`, that view is no longer set, but still page and content templates were there.

So, I've tried to create different tree root with different root TS template (which didn't include any TS from my provider extension) and it worked for page templates, but still content templates were on a "New CE Wizard Tab".

flux 7.1.2
fluidpages 3.1.2
fluidcontent 4.1.1

The reference to this issue is a [StackOverflow comment](http://stackoverflow.com/questions/27400964/disable-fluidtypo3-page-template-and-or-content-elements/27657857#comment43734001_27657857).

Migrated from https://github.com/FluidTYPO3/fluidcontent/issues/204

**Comment by NamelessCoder** [comment]
Solved - and then some, via https://github.com/FluidTYPO3/flux/commit/8fe7e6efd1e60e81f5281e65d77343c7edf177d1

**Comment by InvisibleKind** [comment]
Nice feature in provided commit! Many thanks)
