### ISSUE TITLE
ViewHelper Content\GetViewHelper missies record pid in SELECT's WHERE clause

### ISSUE THREAD

**Issue by GuidoJansen** [FluidTYPO3/flux#749]
Our system somehow managed to stall at the copying of pages/content made with fluidcontent and fluidpages. Therefore we had many CE's that where child content of a fluidcontent element made with <flux:grid.row>. This may be a different issue, but is just a prerequisite to this issue.

Those scattered other CE's shouldn't be displayed in the frontend, because they are on different pages (and could only be deleted directly in the database BTW). The SELECT doesn't have a pid in the WHERE CLAUSE

Salvation:
File EXT:flux/Classes/ViewHelpers/Content/GetViewHelper.php
Line: 118
Current:
`$conditions = "((tx_flux_column = '" . $area . ':' . $id . "')`
Fix
`$conditions = "(pid = " . $record['pid'] . ") AND ((tx_flux_column = '" . $area . ':' . $id . "')`

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/78d9f8fef2511f7e25c270d099086b8c3dfa4b47
