### ISSUE TITLE
controllerActions VH: problem resolving '* '-prefixed LLL keys

### ISSUE THREAD

**Issue by wikipeter** [FluidTYPO3/flux#751]
If controllerAction ViewHelper is used, actions which have a required argument in it's signature become prefixed by prefixLabel(). The LLL key is stored within an array for resulting options of the selectbox, including the '* ' prefix. When buildItemsForActions() tries to resolve the key, it fails due to the prefix.

**Comment by NamelessCoder** [comment]
Fixed; forgot to close this one.
