### ISSUE TITLE
Section object preview with a RTE enabled text field is strange.

### ISSUE THREAD

**Issue by Ishikawakun** [FluidTYPO3/flux#752]
I have a flux configuration like this:

    <flux:form id="headerSlider" label="LLL:fcc.headerSlider.title" icon="Icons/Page.gif">
        <flux:form.section name="headerSlider.slideCollection">
            <flux:form.object name="slideElement" label="Slidelement">
                <flux:field.inline.fal name="image" multiple="TRUE" maxItems="1" minItems="0" newRecordLinkAddTitle="Bild hinzufügen" label="Bild" collapseAll="TRUE" />
                <flux:field.input name="header" label="Überschrift" />
                <flux:field.text name="bodytext" label="Text" enableRichText="TRUE">
                </flux:field.text>
                <flux:field.input name="linkText" label="Linktext" default="" />
                <flux:field.input name="linkTarget" label="Linkziel" default="">
                    <flux:wizard.link />
                </flux:field.input>
            </flux:form.object>
        </flux:form.section>
    </flux:form>

Works really well with one exception:
![screenshot-flux](https://cloud.githubusercontent.com/assets/4943488/5875541/8fca8970-a30e-11e4-983f-5d5a9505d0e2.gif)

Displaying part of the RTE in the section object preview text is probably a bug in my opinion. Or did i miss any issue with my Configuration?

**Comment by Ishikawakun** [comment]
Forgot: TYPO3 CMS 6.2.9 and Flux 7.1.2

**Comment by NamelessCoder** [comment]
Hi Sven,

Yes, that's unfortunately how the TYPO3 core renders the preview text when an RTE field is used. I'm not sure why, but it has been that way for as long as I can remember.

I suggest reporting this to the core bug tracker: https://forge.typo3.org/projects/typo3cms-core/issues
