### ISSUE TITLE
Copy and Paste of a content element in multi language site

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#755]
I am having a site with three languages. When i copy a Content Element and paste it in one language, it is automatically pasted in the other languages. There it is hidden, but why is it placed there?

Maybe someone can help me.

**Comment by robsonrobi** [comment]
Additionally, TYPO3 seems to make really crazy stuff. The following tests we made:

1. We have a site with 2 languages. Adding f.e. a TEXT element into the section results in the button in the second language "copy default values". That is great. But adding a TEXT element inside a 50-50 container made with Flux, the copy option does not appear. That not good. Additionally modifying a FCE in the default langauge, that uses objects, f.e. a slider adding a new slide, the result is although not recognized in the seocond language. Meaning, adding a slide in sys_language = 0 gets lost in sys_language=1. You have to remove all elements first and then copy. :-(

2. Inserting a element at the bottom of the section at sys_language=0 gets copied and pasted in sys_language = 1 somewhere else, f.e. in the middle

3. Sometimes it happens that an element copied and pasted gets pasted twice in the translated language

**Comment by beda** [comment]
Any news on this issue? Any tricks to circumvent this problem. I'm having the same issues with a multilanguage site and contentelements within flux container elements.

My solution to translate a page was this:
1. Drag and drop the content elements out of the container element.
2. "Copy default values"
3. Using Drag and drop reinsert the elements into the container elements in both language views.

**Comment by NamelessCoder** [comment]
Fixed, but see https://github.com/FluidTYPO3/flux/issues/790 for partial still unsolved issue.
