### ISSUE TITLE
[BUG] Missing variable $paths in FluxService

### ISSUE THREAD

**Issue by cedricziel** [FluidTYPO3/flux#770]
https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/FluxService.php#L198 the variable ``$paths`` is undefined

**Comment by NamelessCoder** [comment]
Ah yes... I *think* we no longer require the providerPaths since overlays are in full effect via the new TS handling :) mind investigating?

**Comment by cedricziel** [comment]
Not at all, will debug down the rabbit hole.. ;)

**Comment by cedricziel** [comment]
Obsolete due to Spring cleaning.
