### ISSUE TITLE
blindLinkFields="JSopenParams" OR blindLinkFields="popup_width,popup_height"

### ISSUE THREAD

**Issue by VancD** [FluidTYPO3/flux#778]
Hi @ all,

could somebody help me solve this problem pls?

I want to hide the popup_width and the popup_width in the Link-Wizard. I tried the following Code:
```
<flux:field.input name="link">
  <flux:wizard.link activeTab="page" blindLinkOptions="page,folder" blindLinkFields="JSopenParams" />
</flux:field.input>
```
and 
```
<flux:field.input name="link">
  <flux:wizard.link activeTab="page" blindLinkOptions="page,folder" blindLinkFields="popup_width,popup_height" />
</flux:field.input>
```
cheers!

**Comment by NamelessCoder** [comment]
Hi @VancD - you can set both "width" and "height" on the wizard which will affect the popup size, but you can't in the current version *remove* these parameters. However: setting these to `0` I think should make the window open with the last used size / size of parent window.
