### ISSUE TITLE
[BUGFIX] When Icon is not set it is not shown in selector

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#780]
According to https://fluidtypo3.org/blog/news/coming-changes-in-flux-72.html and based on "Convention-based icons for templates" $form->getOption(Form::OPTION_ICON) on ContentSelector should return the proper icon when icon is not set as property

![bugfix icon](https://cloud.githubusercontent.com/assets/2902073/6651870/6beff992-ca58-11e4-93ec-456b69ddba5a.png)

**Comment by NamelessCoder** [comment]
Implemented resolving by convention for this icon as well.
