### ISSUE TITLE
Feature-Request: Make output of FluidTYPO3\Flux\View\PreviewViewHelper modifiable by provider extensions

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/flux#783]
This was possible in up to version 7.1.2 by modifying the templates for the f:widget.grid viewhelper. It helped greatly to make the backend more user friendly, if you e.g. have elements which have different widths in the frontend (big screens).

An example how we used the templates is appended.

**Comment by JostBaron** [comment]
![backend-preview](https://cloud.githubusercontent.com/assets/2916594/6749214/515c8cae-ceee-11e4-92fa-db7ed1822987.png)

**Comment by NamelessCoder** [comment]
Hi Jost,

The Grid widget was replaced with a View implementation for performance reasons - few users would actually overrule the template, but the Widget would significantly impact the BE performance for all users. So we chose to deprecate it in favour of straight PHP. It's one part of why Flux 7.2 is so much faster than Flux 7.1 especially in the backend - even considering we removed a significant amount of L1 caches.

The documentation section is still not updated but will be as soon as possible:

https://fluidtypo3.org/documentation/templating-manual/templating/previews/the-preview-section.html

The issue that calls for this change if you would like to monitor it:

https://github.com/FluidTYPO3/documentation/issues/40

To briefly describe your current options: the following new `flux:form.option`s have been added which control the preview:

* `mode` which can be either `append` or `prepend`.
* `toggle` which can be either `TRUE` or `FALSE`.

You define these as `<flux:form options="{Preview: {mode: 'append', toggle: 1)}">` or `<flux:form.option name="Preview" value="{mode: 'append', toggle: 1)}" />`. The `mode` switch controls if the grid is inserted before or after the contents of your `Preview` section. The `toggle` determines whether or not the area is collapsible (the small minus icon that's shown top right on hover).

In addition to this, you can apply a `style` attribute to `flux:grid.column` which will be inserted inline - but which only works in content grids. The page grid is still rendered by the core's native grid view which unfortunately doesn't support this attribute. To control the flow of columns you can set the `colspan` and `rowspan` attributes of `flux:grid.column` (in your case, obviously, you have two `flux:grid.row` with the top one having two `flux:grid.column` **without** colspan and the bottom row having one `flux:grid.column` **with** colspan of `2`.

Together these options (still) let you control a lot of the rendering but obviously not as much as before. If you absolutely must modify the HTML that is generated (which we advise you don't - you **do** still have the option of injecting some CSS and even JS to further manipulate the rendering), I'm afraid your only remaining option is to XCLASS (see current docs for how to do this - the method has changed) the PreviewView of Flux to create your own.

Hope this explains the whole situation. Until the doc chapters are written ;)
