### ISSUE TITLE
wizard.link does not create wizard

### ISSUE THREAD

**Issue by hirnschmalz** [FluidTYPO3/flux#787]
I'm working with the current stable flux version with TYPO3 CMS 7.1.

The code

```
	<f:section name="Configuration">
		<flux:form id="cGoogleMap">
            <flux:field.input name="link">
                <flux:wizard.link activeTab="page"/>
            </flux:field.input>
		</flux:form>
	</f:section>
```

does create a simple input field but without the possibility to open the link wizard.

Markus

**Comment by netzloesungen** [comment]
Same issue here. I am also using TYPO3 7.1 and flux 7.2.0

**Comment by NamelessCoder** [comment]
Under review: https://github.com/FluidTYPO3/flux/pull/804
