### ISSUE TITLE
Rich Text Editor - Download links for custom content elements are not parsed.

### ISSUE THREAD

**Issue by andrij2012** [FluidTYPO3/flux#788]
I use TYPO3 version of 6.2.9
I've created a custom content element with RTE text field. And in edit area of this field I created a link to the file.

Code of created content element with RTE text field.

```
<f:section name="Configuration">
  <flux:form id="exampleModule" options="{group: 'FCE'}">
    <flux:field.text name="text" enableRichText="TRUE" />
  </flux:form>
</f:section>
```

In html view of RTE field there is something like this:

```
<a href="http://example.com/?file:3" target="_blank" class="download">
```
But on frontend the URL of this link is not parsed. I just get the same result:
```
<a href="http://example.com/?file:3" target="_blank" class="download">
````
Looks like lib.parseFunc_RTE doesn't have effect on this kind of field. Or maybe I'm wrong with my suggestion.

**Comment by NamelessCoder** [comment]
Are you using `<f:format.html>` when you output the RTE content? That's a must ;)

**Comment by andrij2012** [comment]
@NamelessCoder, yes I use it :)

**Comment by bjo3rnf** [comment]
Might be related to #740

**Comment by andrij2012** [comment]
Thank you very much @bjo3rnf, I tried your solution and it works. :+1: 
Issue is closed.
