### ISSUE TITLE
With update from 7.1.2 to 7.2 no Page Layouts are found

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/flux#789]
I updated flux, fluidpages and fluidcontent today. Suddenly no Layouts are shown in the backend. In the frontend I get `#1225709595: Template could not be loaded. I tried ""`.
But i think this is only a result of no selected Page Layout in the backend. Maybe it is an error in fluidpages but i assume it is a result of the cleanup in flux.
Any hint, why the layouts are not found? Someone have the same problems?

**Comment by andrij2012** [comment]
@MoppieMop, you need to be sure that you have included flux in namespaces.
```
{namespace flux=FluidTYPO3\Flux\ViewHelpers}
```

**Comment by cedricziel** [comment]
Can you please Post an example Layout please?

**Comment by andrij2012** [comment]
Yup, here it is.
```
{namespace flux=FluidTYPO3\Flux\ViewHelpers}
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
<f:layout name="Page" />

<f:section name="Configuration">
  <flux:form id="onecolumn" options="{icon: '{v:extension.path.resources(path: \'Icons/Page/Standard.gif\')}'}">
    <flux:grid>
      <flux:grid.row>
        <flux:grid.column colPos="0" name="main" />
      </flux:grid.row>
    </flux:grid>
  </flux:form>
</f:section>

<f:section name="Main">
  <main>
    <v:content.render column="0" />
  </main>
</f:section>
```

**Comment by cedricziel** [comment]
Where did you save it? Relative path from the website root please :)

**Comment by andrij2012** [comment]
website_root/typo3conf/ext/your_providerextension/Resources/Private/Templates/Page/Onecolumn.html

**Comment by MoppieMop** [comment]
My setup is similiar to that of andrij2012. I have in every template that uses flux `{namespace flux=FluidTYPO3\Flux\ViewHelpers}`. But I can not select a page layout in the backend.

**Comment by NamelessCoder** [comment]
Should be remedied by recent change in TemplatePaths to merge default paths rather than only add defaults if no paths at all were defined.
