### ISSUE TITLE
Translation - localization won't work in page view

### ISSUE THREAD

**Issue by mkoehler2911** [FluidTYPO3/flux#796]
Hi!
I'm trying to localize contents from a flux:grid.column container.
Default language = english, language to localize = german.
If I create a container (EN) for the first time an insert some fluid elements everything works fine on localization (to DE). But if I change something inside of my container (EN) I couldn't localize again (only works in list view).
This affects only elements inside of my flux container. 
How could I tell the container sth changed inside and needs to refresh again?

Any solutions for me? 
Thanks!

**Comment by blueamerican** [comment]
I don't understand your problem.
> But if I change something inside of my container (EN) I couldn't localize again (only works in list view).

I couldn't localize again? What does this mean?

**Comment by mkoehler2911** [comment]
If I change sth inside of my default lang container I need to copy default content elements again for my other language

**Comment by blueamerican** [comment]
ah... you add another element to your container and do not get it copied to the container of your language...

**Comment by blueamerican** [comment]
if i localize an element in an container in list view, the new localized element appears in the wrong language..

**Comment by mkoehler2911** [comment]
That's the next issue.
But I thought this bug would be fixed in next update

**Comment by NamelessCoder** [comment]
Fixed.
