### ISSUE TITLE
Delivering default page-Template for non logged in users

### ISSUE THREAD

**Issue by MK-42** [FluidTYPO3/flux#799]
This issue is mostly hidden by Cache delivering the page generated for the backendUser creating and reviewing content.
see FluidTYPO3/fluidpages#243

to determine fluidpages-template
`FluidTYPO3\Flux\Service\WorkspacesAwareRecordService::getWorkspaceVersionOfRecordOrRecordItself()`
is calling 
`BackendUtility::workspaceOL($table, $copy);`
which is in turn checking for
`$wsid = $GLOBALS['BE_USER']->workspace;`
which is **`null`** if no user is logged in and is only checked against `!== 0`

I don't know if this is a core bug - not checking against `$wsid !== null` or a Flux Bug calling `BackendUtility::workspaceOL` from frontend.

Changing `typo3/sysext/backend/Classes/Utility/BackendUtility.php:3821` (in typo3-6.2.11) to
`if ($wsid !== 0 && $wsid !== null && is_array($row)) {`
**fixes this issue**

should I file a core bug or will flux change the call to `BackendUtility::workspaceOL($table, $copy);`?

**Comment by NamelessCoder** [comment]
See also https://github.com/FluidTYPO3/fluidpages/issues/243
