### ISSUE TITLE
flux:form.data - error with nested custom content elements after updating flux to 7.2

### ISSUE THREAD

**Issue by jenses** [FluidTYPO3/flux#801]
In my provider extension [fluidfoundationtheme](https://github.com/jenses/Fluid-Foundation-Theme) there are some grid elements and many custom content elements (*cce*).  
In some *cce'*s I fetch the settings of the parent grid element with:  

    <f:if condition="{record.tx_flux_parent}">  
    	<f:then>  
    		<flux:form.data field="pi_flexform" table="tt_content" uid="{record.tx_flux_parent}"
    								as="fluxParentData">  
    			<f:if condition="{fluxParentData.settings.equalize}">  
    				<f:then>  
    					<v:variable.set name="parentEqualize" value='true'/>  
    				</f:then>  
    				<f:else>  
    					<v:variable.set name="parentEqualize" value='false'/>  
    				</f:else>  
    			</f:if>  
    		</flux:form.data>  
    	</f:then>  
    </f:if>  

After updating flux, fluidpages, fluidcontent etc. to the newest versions I get on pages, which contains a grid element with a nested *cce* like described,
a TYPO3 error message:  
# Oops, an error occurred!

## "" is not a valid template resource URI."

In previous versions all worked fine.  

If I change for testing purposes in flux:form.data the fieldname from **pi_flexform** to f.ex. **content_options**, I get no error message.

**Comment by jenses** [comment]
added error backtrace table on:
https://github.com/jenses/Fluid-Foundation-Theme/blob/master/Documentation/TYPO3%20Exception.html

**Comment by f000** [comment]
I've got the same problem "#1257246929: "" is not a valid template resource URI. "...

Error is triggered by flux:form.data:
```
 <flux:form.data table="tt_content" field="pi_flexform" uid="{pageElement.uid}" as="elementData">
    ...{elementData.settings.xxx}
 </flux:form.data>
```

even with existing uid:

```
 <flux:form.data table="tt_content" field="pi_flexform" uid="1" as="elementData">
    ...{elementData.settings.xxx}
 </flux:form.data>
```

**Comment by f000** [comment]
workaround is to use record parameter instead of uid parameter:
```
<f:for each="{v:content.get(column: 0, render: 0, pageUid: item.uid)}" as="pageElement">
        <flux:form.data table="tt_content" field="pi_flexform" record="{pageElement}" as="elementData">
            ...{elementData.settings.xxx}...
        </flux:form.data>
 </f:for>
```

**Comment by jenses** [comment]
Thanks for the workaround, works for me, for now.
But it would be nice, if we could get back a correct working flux:form.data viewhelper.

**Comment by xf-** [comment]
{flux:form.data(uid: menuPage.uid, table: 'pages', field: 'tx_fed_page_flexform')-> v:variable.set(name: 'pageSettings')}
i use it on pages and it works fine.

btw. thx for providing a foundation setup. we will test it.

**Comment by NamelessCoder** [comment]
Should be solved thanks to recent efforts by @xf- and @jmverges. If not, let us know and we'll reopen.
