### ISSUE TITLE
Buttons "paste here" / "paste here as reference"

### ISSUE THREAD

**Issue by grintsch-sb** [FluidTYPO3/flux#805]
These buttons "paste here" / "paste here as reference" should be enabled by default, if i've got something in my clipboard.
But i can't see these Buttons while having my clipboard filled with a contentelement.
They are positioned next to "Add new record" before/after each extisting contentelement.
![icons](https://cloud.githubusercontent.com/assets/11944076/7138105/5ab6ed4c-e2be-11e4-9c23-cdfc1340454c.png)
I saw these buttons enabled in an "old" project, but the colleague doesn't work here anymore.

Current setup without buttons:
Typo3 6.2.10
VHS: Fluid ViewHelpers 2.2.0 
Flux: Fluid FlexForms 7.2.0
Fluid Pages Engine 3.2.0
Fluid Content Engine 4.2.1 

"Old" setup with buttons:
Typo3 6.2.9
VHS: Fluid ViewHelpers 2.0.1
Flux: Fluid FlexForms 7.1.0
Fluid Pages Engine 3.1.0
Fluid Content Engine 4.1.0

Do i have do downgrade to make these buttons work or is there another possibility.

**Comment by DenisMir** [comment]
I can see this error as well. Sometimes they do show up sometimes they don't. Pretty random at the moment.

**Comment by hkarvasonis** [comment]
I noticed that on flux 7.2 paste and paste as reference are shown only inside a fluidcontent content element and not inside the template's content areas and between normal content elements.
This was working correctly on flux 7.1.

It would be nice if this functionality was brought back as before, since "Paste as reference" on any content area is a very useful feature for editors.

**Comment by DenisMir** [comment]
I can confirm what @hkarvasonis mentions. The functionality would be very useful. But first it would be nice if pasting as a reference would work correctly which it does not. (the bug is described right here: #818)

**Comment by jmverges** [comment]
Hi there, 

here is the code involved in the creation of the create new element buttons in the PageLayoutView https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/backend/Classes/View/PageLayoutView.php#L1096

**Comment by NamelessCoder** [comment]
We currently do not have this option and unfortunately cannot add the support. A TYPO3 core patch to enable a hook/signal when rendering "content column icons" (top and bottom) would allow this, but currently the only way to achieve this is a large chunk of overrides of core code. We had that earlier and it just causes problems. Furthermore: a nested content solution is expected from the core at which point Flux will remove its implementation and instead provide supports for using Flux content areas via the core's implementation.
