### ISSUE TITLE
Template path resolving is not compatible to core fluid

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/flux#808]
`FluidTYPO3\Flux\Service\FluxService::getViewConfigurationForExtensionName` provides the template paths e.g. for rendering `fluidcontent_core` variants. It is however not compatible to core fluid in at least one respect: Usually, if no custom template paths are configured for an extension in TypoScript e.g. at `plugin.tx_abcdef.view`, fluid uses the default paths (`EXT:abcdef/Resources/Private/...`). flux does this too. However, if  _anything_ under `plugin.tx_abcdef.view` is set, the default paths will _not_ get set with flux (see the `0 === count(...)` check in the function), but they will with fluid. So just adding `plugin.tx_abcdef.view.a = b` to the TypoScript will cause a "#1225709595: Template could not be loaded" exception. If you just want to change the `partialRootPaths` setting without touching the `templateRootPath`, you will be greeted by this error. I'm aware that this can be solved by adding all three (`templateRootPaths`, `partialRootPaths`, `layoutRootPaths`) to the TypoScript view configuration explicitly, but I really think that it should not be necessary.

**Comment by NamelessCoder** [comment]
The `TemplatePaths` class can be used as intermediary step here - if the `plugin.tx_ext.view` array is passed as constructor and `$paths->toArray()` is called, the class should internally build a complete set of paths regardless of how the input looks.

**Comment by pkerling** [comment]
I don't think it will, since you can provide `TemplatePaths` with _either_ an extension name or a TypoScript array, i.e. it also will not add default paths if the constructor gets an array.

**Comment by NamelessCoder** [comment]
Applied in https://github.com/FluidTYPO3/flux/commit/aacefc04b99ce2ff5cb95cd9e76535263e176207 (right about TemplatePaths - besides; TemplatePaths instances are constructed using the return value of this function so it would be kind of ass backwards in my suggestion).

**Comment by pkerling** [comment]
I'm not sure this is the right way to fix this: Now the default path is _always_ fixed at position 10 in the array, even when `templateRootPaths` and such is explicitly set. I guess it should be done the same fluid does it: Use the default only if and only if no user configuration is given _in a category_.
