### ISSUE TITLE
Copy of page - colPos 18181 gets lost

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/flux#811]
I recognized a weird bug that I don't understand. 

I have got the following setup: flux@7.1.2, vhs@2.2.0, fluidpages@3.1.2, fluidcontent@4.1.1, typo3@6.2.9. I'm using fluidpages for backend layout and exclusively fluidcontent content elements on the pages. I got _wrapper elements_, _wrapper elements that are inside another wrapper_, and _child elements_. 

When copying some pages with non admin rights the colPos of some _wrapper elements that are inside another wrapper_ which should be _18181_ gets lost and is set to 0 which messes up the whole page in backend and frontend rendering.

I'm not quite sure which permissions could be missing for the user because it only happens to some pages. On other pages which got a similar content element copying works fine.

I took some screenshots of `tt_contents` for a working copying process and a failed one. It is interesting that the fields `tx_flux_column` and `tx_flux_parent` are set correctly.

Working process: 

_Original content elements for the page_
![working_original_page](https://cloud.githubusercontent.com/assets/157281/7268931/a6747252-e8ce-11e4-951e-81a419f2fe5f.png)

_Copied content elements for the page_
![working_copied_page](https://cloud.githubusercontent.com/assets/157281/7268932/a676c0b6-e8ce-11e4-9ee1-a7a766f5b892.png)

Failed process:

_Original content elements for the page_
![failed_original_page](https://cloud.githubusercontent.com/assets/157281/7268947/d0c09a04-e8ce-11e4-9258-c0cc994aecea.png)

_Copied content elements for the page_
![failed_copied_page](https://cloud.githubusercontent.com/assets/157281/7268946/d0bc33a6-e8ce-11e4-9200-10f827bbf534.png)

If you got some ideas why this could happen it would be great. As an admin users I can not reproduce the problem.

**Comment by Idleworks** [comment]
Did you copy your elements through page or list module?

**Comment by DenisMir** [comment]
@Idleworks I have copied the whole page through the page tree.

**Comment by xf-** [comment]
needs testing

**Comment by jmverges** [comment]
I can not reproduce.
Tested on 6.2 LTS and master with latest versions of FT3.
