### ISSUE TITLE
TYPO3 CMS 7.1 editing page properties

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#813]
Everything works great, but when trying to edit the page properties i get the error

```
Could not analyse class:FluidTYPO3\Flux\ViewHelpers\Flexform\Grid\RowViewHelper maybe not loaded or no autoloader?
```

**Comment by robsonrobi** [comment]
Works now, may be the current development versions are not stable?

**Comment by NamelessCoder** [comment]
Somewhere you have a `flux:flexform.grid.row` which is invalid. Change to `flux:grid.row`.
