### ISSUE TITLE
Path on Windows System are incorrect.

### ISSUE THREAD

**Issue by sdewald** [FluidTYPO3/flux#814]
On a Windows System i got the following Exception:

    Uncaught TYPO3 Exception
    #1: PHP Warning: file_get_contents(): Filename cannot be empty in D:\apache\htdocs\typo3.7\typo3\sysext\fluid\Classes\View\TemplateView.php line 317 (More information)

    TYPO3\CMS\Core\Error\Exception thrown in file
    D:\apache\htdocs\typo3.7\typo3\sysext\core\Classes\Error\ErrorHandler.php in line 102.

    39 TYPO3\CMS\Core\Error\ErrorHandler::handleError(2, "file_get_contents(): Filename cannot be empty", "D:\apache\htdocs\typo3.7\typo3\sysext\fluid\Classes\View\TemplateView.php", 317, array)

    38 file_get_contents("")

**Comment by sdewald** [comment]
here is the patch to fix this:



    From 1473d596c0cac436f9500269fc4c01e685d97015 Mon Sep 17 00:00:00 2001
    From: Sascha Dewald <sascha.dewald@gmail.com>
    Date: Tue, 28 Apr 2015 14:33:52 +0200
    Subject: [PATCH] * Fix resolveFileNamePath in ExposedTemplateView for Windows

    ---
     Classes/View/ExposedTemplateView.php | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)
    
    diff --git a/Classes/View/ExposedTemplateView.php b/Classes/View/ExposedTemplateView.php
    index 0484656..f544328 100755
    --- a/Classes/View/ExposedTemplateView.php
    +++ b/Classes/View/ExposedTemplateView.php
    @@ -178,6 +178,6 @@ class ExposedTemplateView extends TemplateView implements ViewInterface {
     	 * @return string absolute pathAndFilename
     	 */
     	protected function resolveFileNamePath($pathAndFilename) {
    -		return '/' !== $pathAndFilename{0} ?     GeneralUtility::getFileAbsFileName($pathAndFilename) : $pathAndFilename;
    +		return '/' !== $pathAndFilename{0} ?         GeneralUtility::getFileAbsFileName(GeneralUtility::fixWindowsFilePath($pathAndFilename)) :     $pathAndFilename;
     	}
     }
     -- 
    1.9.4.msysgit.2

**Comment by xf-** [comment]
@NamelessCoder do we support windows? i can't test it.
Most web server run on *NIX systems and LAMP stack can easily replaced by Vagrant or/and other visualization option.

(Sry, i think we have no windows user in core team.)

**Comment by NamelessCoder** [comment]
We should support Windows paths but only to the extent that PHP itself supports them. The crazy thing here is why TYPO3 doesn't use `GeneralUtility::fixWindowsFilePath` on paths internally instead of requiring each and every place of implementation to do so.

@xf- if you take this one: we'd need this implemented in our TemplatePaths object at this time, I think. There should no longer be any filename resolving happening in the View itself.

**Comment by NamelessCoder** [comment]
See explanation in https://github.com/FluidTYPO3/fluidcontent/issues/246
