### ISSUE TITLE
Flux controllers' views are unaware of correct request

### ISSUE THREAD

**Issue by Cash2m** [FluidTYPO3/flux#819]
I tried to use `<f:widget.paginate />` in fluidcontent and it's not possible to get beyond the first page.

The view created by `\FluidTYPO3\Flux\Service\FluxService->getPreparedExposedTemplateView` in [`AbstractFluxController:181`](https://github.com/FluidTYPO3/flux/blob/development/Classes/Controller/AbstractFluxController.php#L181) has no knowledge of the original request and it's parameters. This is why the controller context used by the widget does not contain the required parameters.

My idea would be allowing to pass an optional `$request` parameter to `->getPreparedExposedTemplateView` so there's no need for creating a fresh Request instance.

**Comment by xf-** [comment]
@NamelessCoder can you provide some insides?

**Comment by NamelessCoder** [comment]
We need to investigate this one but I think we maybe aren't passing the original request to our specialised sub-request; or the controller is for some reason using our manipulated request when it should be using the controller's.

**Comment by NamelessCoder** [comment]
Solved:

* ViewContext now either stores or creates the Request used by ExposedTemplateView and FluxService.
* Provider now creates the ViewContext that gets used; based on record and original request.
* Provider will by default pass the original request when in FE and an emulated request when in BE.
* Provider can be extended to use a fixed ViewContext which will increase performance.

https://github.com/FluidTYPO3/flux/commit/c3d4939cbc462c946f179191f550ee05c3d78b7c

Usage:

```php
// inside Controller which is the place where we have the Request
$this->provider->getViewContext($record, $this->request);
```

Called by default by the `initializeViewObject` method.
