### ISSUE TITLE
Paste into fluidcontent area: ``FluidTYPO3\Flux\Provider\ContentProvider`` is only been triggered when fluidcontent_core ist installed

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/flux#820]
Pasting a element without fluidcontent_core has a bug as described in #573. After some tracing this is my assumption:
When fluidcontent_core is installed ``FluidTYPO3\FluidcontentCore\Provider\CoreContentProvider`` triggers when pasting a element. Because of that ``FluidTYPO3\Flux\Provider\ContentProvider::postProcessCommand`` gets executed which results in correct pasting.

If fluidcontent_core is not installed, ``FluidTYPO3\Flux\Provider\ContentProvider`` is not triggered (by ``FluidTYPO3\Flux\Provider\AbstractProvider::trigger``) and so ``FluidTYPO3\Flux\Service\ContentService::pasteAfter`` does not fix the record..

Sadly i don´t have much more time for debugging this right now..

**Comment by andreaswolf** [comment]
I’ve got the same problem, installing fluidcontent_core did not fix it for me – at least not in the functional tests I wrote for flux. I’m currently discussing possible solutions for this over at #573, in case you’re interested.

**Comment by NamelessCoder** [comment]
https://github.com/FluidTYPO3/flux/pull/866 should solve this. Please test and if you discover it doesn't trigger the ContentProvider as expected, let me know and I will reopen this issue!

It is indeed related to the issue mentioned by Andreas!

**Comment by andreaswolf** [comment]
This indeed fixes the issue, thanks! Should also fix quite a few problems with pasting content now, at least according to my tests…

**Comment by xf-** [comment]
THX for testing @andreaswolf :)
