### ISSUE TITLE
Impossible to move FCE inside another FCE in TYPO3 CMS 7.2

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#822]
I just installed TYPO3 CMS 7.2. Everything looks great with the dev versions of fluidpages, flux and fluidcontent. But i am not able to move a nested content element. Trying to grab f.e. a content element inside a left column to put it in the right column, move the complete container CE|CE, not just the element inside.

Moving Content Elements up and down does not work either.

Any help would be great!

**Comment by robsonrobi** [comment]
Is there any progress? I really love to use FLUX in TYPO3 7.2 :-)

**Comment by georg-tiefenbrunn** [comment]
Same here using TYPO3 7.3-dev (TYPO3 and FluidTYPO3 dev using composer).

@robsonrobi: Using cut/paste you can achieve your goal:

1. You have your container FCE1 and create (or choose) a FCE2 outside (after) the container
3. create a new FCE3 *inside* the container FCE1
4. cut FCE2 and paste it *after* FCE3
5. delete FCE3

But you have to be very careful:

* pasting a FCE inside another FCE at first position does not work (the FCE keeps its position)
* pasting a FCE from inside a FCE to outside the FCE (into a column) does not work (no icon "Paste in this position" is displayed for columns)
* pasting a FCE from inside a FCE into another FCE at first position does not work; the FCE is unlinked (youl'll have to correct fields ``tt_content.tx_flux_column`` and ``tt_content.tx_flux_parent`` in DB)
* moving records down doesn't seem problematic. But moving a FCE to position 1 using "Move record up" will unlink the FCE.

@NamelessCoder: Should these TYPO3 7.2/7.3 specific issues also be added to #573 or should we wait until the new PreviewView (sub)class mentioned in https://github.com/FluidTYPO3/flux/pull/823#issuecomment-100647141 is ready?

**Comment by robsonrobi** [comment]
@georg-tiefenbrunn : Thanks for your answer. Me as a programmer it is okay doing that workaround, but for the rest it is not possible to use it in that way. Looking really really forward to a stable fix in the next version. :-)

Thumbs up for FLUX!

**Comment by NamelessCoder** [comment]
@georg-tiefenbrunn Please wait for the reworked preview-view class for 7.2+, that's likely to remove some of the problem(s) - and feel free to coordinate with @monosize if perhaps you've got more time to implement something like that!

**Comment by robsonrobi** [comment]
Is there date you plan to finish it?

**Comment by NamelessCoder** [comment]
I'm not working on it - @monosize is. So I assume the Q was for him ;)

**Comment by robsonrobi** [comment]
@monosize : Is there any progress? It would be great to get it working.

**Comment by grimmcreative** [comment]
The Fix works. Would be nice if it gets merged. Only the reaction when draging is sometimes curious.

**Comment by NamelessCoder** [comment]
Under review - https://github.com/FluidTYPO3/flux/pull/823

**Comment by Outdoorsman** [comment]
Hi @NamelessCoder. Just curious why this issue was closed as it seems that discussion #823 has not been resolved and I don't see a code merge anywhere.

Was the @monosize fix merged somewhere and I missed it? Did you just decide to scrap the @monosize solution? I was asking @smichaelsen and he didn't know what was going on with this either. I was just wanting to know if I can use the Flux Dev branch here yet for copy/paste.

**Comment by NamelessCoder** [comment]
Hi @Outdoorsman - we close issues when they are replaced with pull requests and instead link to the pull request. Nothing ominous, just a way to limit the number of open issues ;)

The fix by @monosize requires a bit of consideration (you can check the technical stuff in the pull request, #823). Our main concern is to make it maintainable - the fix works, we just would like to limit how much it currently has to override. And you'll be happy to know that we've also been offered manpower/contributions to fix these exact issues, with the mentioned pull requests as starting point.

Sorry about the time this is taking but from experience those two aspects of large JS overrides of vital functionality plus multiple versions of PHP classes are the most likely to cause problems with future updates in TYPO3 itself. Given TYPO3's new faster release schedule we're even more cautious about this. But please rest assured it is being handled and is now given high priority!

**Comment by ervaude** [comment]
@NamelessCoder Thank you for clearify this.

**Comment by Outdoorsman** [comment]
Thank you from me as well :)
