### ISSUE TITLE
No protection against inserting a content element as its own child

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/flux#824]
It is somehow possible (don't know why, and can't reproduce it, but an editor did it) to insert a content element as its own child. Doing this has the effect that the page module can't be opened any longer for that page because of an infinite recursion. 

This could be mitigated by adding two checks:

 1. If a content element has children, and a child has the same ID than the element itself, don't render it (in previews and in the frontend). Maybe print a warning instead, or silently ignore it.
 2. If a content element is pasted into another element, and both uids are the same, don't do it and show a warning.

**Comment by JostBaron** [comment]
This happend with TYPO3 6.2.12, flux 7.2.0 and fluidcontent 4.2.1

**Comment by NamelessCoder** [comment]
Under review: https://github.com/FluidTYPO3/flux/pull/833
