### ISSUE TITLE
db error in backend

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#825]
hi,

after upgrading from flux 7.1.2 to 7.2 i get the following error in the backend:

caller 	TYPO3\CMS\Core\Database\DatabaseConnection::exec_INSERTquery
ERROR 	Table 'db57507.cf_flux' doesn't exist
lastBuiltQuery 	INSERT INTO cf_flux (identifier,expires,content) VALUES ('tt_content350f73a7cf19d1fe9c4e086d605217eb3ba','1431352131','N;')
debug_backtrace 	TYPO3\CMS\Backend\Controller\PageLayoutController->main#128 // TYPO3\CMS\Backend\Controller\PageLayoutController->renderListContent#536 // TYPO3\CMS\Recordlist\RecordList\AbstractDatabaseRecordList->generateList#930 // TYPO3\CMS\Backend\View\PageLayoutView->getTable#439 // TYPO3\CMS\Backend\View\PageLayoutView->getTable_tt_content#202 // TYPO3\CMS\Backend\View\PageLayoutView->tt_content_drawHeader#502 // TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction#1400 // call_user_func_array#4232 // FluidTYPO3\Flux\Hooks\ContentIconHookSubscriber->addSubIcon# // TYPO3\CMS\Core\Cache\Frontend\VariableFrontend->set#119 // TYPO3\CMS\Core\Cache\Backend\Typo3DatabaseBackend->set#79 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_INSERTquery#147 // TYPO3\CMS\Core\Database\DatabaseConnection->debug#202

the database analyser suggests the following actions:
CREATE TABLE cf_flux ( id int(11) unsigned NOT NULL auto_increment, identifier varchar(250) NOT NULL default '', expires int(11) unsigned NOT NULL default '0', content mediumblob, PRIMARY KEY (id), KEY cache_id (identifier,expires) ) ENGINE=InnoDB;
CREATE TABLE cf_flux_tags ( id int(11) unsigned NOT NULL auto_increment, identifier varchar(250) NOT NULL default '', tag varchar(250) NOT NULL default '', PRIMARY KEY (id), KEY cache_id (identifier), KEY cache_tag (tag) ) ENGINE=InnoDB;

what does that mean?

best regards
m

**Comment by JostBaron** [comment]
It means that the extension has introduced a two new database tables (caching tables in this case), but these tables were not created during the extension update.

Just create the tables using the database analyser, then you should be fine.

**Comment by blueamerican** [comment]
ok thx

**Comment by Kitzberger** [comment]
Had the same issue with version 7.3.0 and TYPO3 7 LTS.

The table cf_flux only reappeared after de- and re-installing the extension. Rerunning the update script wouldn't solve anything.

The install tool wasn't offering to recreate the tables but offered to rename and then to drop them when the tables were present again. Maybe there's something wrong with the registration of the caching tables in ext_localconf.php? I'm just guessing here ;-)

Same goes for cf_fluidcontent btw.
