### ISSUE TITLE
Nesting of sections/objects results in a non-nested backend form

### ISSUE THREAD

**Issue by arnekolja** [FluidTYPO3/flux#827]
When nesting sections and objects, the resulting backend form renders them as non-nested. I'm experiencing this with two FCEs now, and cannot find an error in my code.

Example:

```xml
  <f:section name="Configuration">
    <flux:form id="timeliner" label="Timeliner" description="Historische Timeline" options="{group: 'Sonstiges'}" >
      <flux:form.section name="major" label="Hauptzweige">
        <flux:form.object name="majorelement" label="Hauptzweig">
          <flux:field.input name="title" label="Titel" />
          <flux:form.section name="minor" label="Unterzweige">
            <flux:form.object name="minorelement" label="Unterzweig">
              <flux:field.input name="title" label="Titel" />
            </flux:form.object>
          </flux:form.section>
        </flux:form.object>
      </flux:form.section>
    </flux:form>
  </f:section>
```

Results in a form with "Hauptzweige" and "Unterzweige" on the same level. Screenshot:

![Imgur](http://i.imgur.com/zB8RrHI.png)

Is this a bug, or am I missing something?

Setup:

* PHP 5.3.29
* TYPO3 6.2.12
* flux 7.2.0
* fluidcontent 4.2.1
* fluidpages 3.2.0
* vhs 2.2.0

**Comment by arnekolja** [comment]
I have to correct myself. It seems to work when adding "Hauptzweig" items. The error seems to be, that there's a trailing "Unterzweige" that is just a zombie somehow (see screenshot).

**Comment by coding46** [comment]
Can confirm this issue.

**Comment by rastocs2** [comment]
Also can confirm this issue.
![img1](https://cloud.githubusercontent.com/assets/5691082/8107520/25b9878a-104a-11e5-8b3b-866ed2952743.png)
![img2](https://cloud.githubusercontent.com/assets/5691082/8107521/25bc0672-104a-11e5-8b36-e1a469a01db3.png)

**Comment by NamelessCoder** [comment]
Pesticide applied.

**Comment by sepclaas** [comment]
{namespace flux=FluidTYPO3\Flux\ViewHelpers}
{namespace v=FluidTYPO3\Vhs\ViewHelpers}

<f:layout name="Content"/>

<div xmlns="http://www.w3.org/1999/xhtml" xmlns:flux="http://fedext.net/ns/flux/ViewHelpers" xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

    <f:section name="Configuration">
        <flux:form wizardTab="table" id="test" label="Test" description="{f:translate(id: 'flux.fce.imagetiling-description')}">

                <flux:form.section name="cols" label="cols">
                    <flux:form.object name="column" label="column">
                        <flux:field.input name="ladder-position" label="{f:translate(id: 'flux.fce.image')}"/>
                        <flux:form.section name="params" label="Slides">
                            <flux:form.object name="parameter" label="{f:translate(id: 'flux.fce.quote')}">
                                <flux:field.input name="name" label="{f:translate(id: 'flux.fce.headline')}"/>
                                <flux:field.input name="height" label="{f:translate(id: 'flux.fce.text')}"/>
                            </flux:form.object>
                        </flux:form.section>
                    </flux:form.object>
                </flux:form.section>

        </flux:form>
    </f:section>

</div>
I created this FCE with the code given above, and this is the TYPO3 Exception that i get:
#1458745712: Invalid flex form data structure on field name "pi_flexform" with element "params" in section container "column": Nesting sections in container elements sections is not allowed.

**Comment by NamelessCoder** [comment]
Sections in sections or sections in container is, as you see from the TYPO3 exception being thrown, no longer supported. This is outside our control and not a decision we made. We do, however, respect that the decision was made - because using such structures results in side effects for some use cases and was never explicitly intended.
