### ISSUE TITLE
Template fallback quit working at this commit

### ISSUE THREAD

**Issue by Outdoorsman** [FluidTYPO3/flux#831]
When I updated to the most recent verion of Flux I found that my template fallback just stopped working. I have isolated it to this @NamelessCoder commit in Flux where it quit working:
https://github.com/FluidTYPO3/flux/commit/7a541dd5777a2db7a11347034a438594ecf3e0f0

Here is the way that I'm implementing fallback...

My provider_extension has this in setup.txt
```
plugin.tx_fluidbootstraptheme.view {
    templateRootPaths.1 = {$plugin.tx_providerextension.view.templateRootPaths.0}
    partialRootPaths.1 = {$plugin.tx_providerextension.view.partialRootPaths.0}
    layoutRootPaths.1 = {$plugin.tx_providerextension.view.layoutRootPaths.0}
}
```

fluidbootstraptheme (v2.0 branch, compatible with TYPO3 7.x) has this in setup.txt
```
plugin.tx_fluidbootstraptheme.view {
    templateRootPaths.0 = {$plugin.tx_fluidbootstraptheme.view.templateRootPaths.0}
    partialRootPaths.0 = {$plugin.tx_fluidbootstraptheme.view.partialRootPaths.0}
    layoutRootPaths.0 = {$plugin.tx_fluidbootstraptheme.view.layoutRootPaths.0}
}
```

**Comment by doerler** [comment]
I think, this happens because since this commit: aacefc0 the default view configuration is added with the array key 10. Later on all configuration paths are sorted by key: [TemplatePaths.php](../blob/7.2.1/Classes/View/TemplatePaths.php#L337).

This means that all overlay paths with a key below 10 are overriden by this new default path.

**Comment by Outdoorsman** [comment]
@doerler you are correct. As soon as I changed from 1 to 11 (or anything larger than 10), it works. I believe that Flux should be changed from 10 to 0 though since it is the base template. I noticed that this is the way that the news extension does it and I have adopted it elsewhere because it really makes sense.
```
plugin.tx_fluidbootstraptheme.view {
    templateRootPaths.11 = {$plugin.tx_providerextension.view.templateRootPaths.0}
    partialRootPaths.11 = {$plugin.tx_providerextension.view.partialRootPaths.0}
    layoutRootPaths.11 = {$plugin.tx_providerextension.view.layoutRootPaths.0}
}
```
