### ISSUE TITLE
Copy paste problems with flux grids

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/flux#838]
There are some problems with copy paste. I use TYPO3 6.2.12 with flux, fluidcontent, fluidpages and vhs from the development branch of today (had the same problems with different versions of the last days an with the TER versions before too). 

For example if I copy a tx_news plugin an try to paste it into a gridelement built with flux it fails. I only can see the plugin in the listview not in the pageview. 

Second prob is that if I copy a normal CE (maybe "text") from a gridelement built with flux and try to paste it in another grid at the same page it comes on a wrong position: it comes at the location I copied it from. 

I guess I know some of this behaviour from older flux-versions but in the last month it seems to be fixed. But now it is back again :-(

**Comment by xf-** [comment]
We fixed a lot of stuff and i can't reproduce the problems.

**Comment by xf-** [comment]
I tested because of other bugs (similar) even more. I can't reproduce it on development branch. Please comment, if this is still an issue.
