### ISSUE TITLE
Default view configuration in FluxService prevents using multiple separated template collections with static TS includes

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [FluidTYPO3/flux#839]
As written in the [templating manual](https://fluidtypo3.org/documentation/templating-manual/templating/provider-extension/configuration-files.html#option-1-standard-static-typoscript) using static TypoScript is ideal for multi-domain sites using multiple template collections. But [FluxService::getViewConfigurationForExtensionName()](https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/FluxService.php#L304) always returns at least the default template paths for a provider extension and thus every page template (page layout) is available on every page in page tree whether or not the static TypoScript of a provider extension is included or not.

**Comment by georg-tiefenbrunn** [comment]
As a workaround you can use always-included false defaults and set the paths to an extension which doesn't provide templates for fluidcontent/fluidpages like flux: 
~~~~
// ext_localconf.php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScript($_EXTKEY, 'setup', '
	plugin.tx_myprovider.view {
		templateRootPaths.10 = EXT:flux/Resources/Private/Templates/
		partialRootPaths.10 = EXT:flux/Resources/Private/Partials/
		layoutRootPaths.10 = EXT:flux/Resources/Private/Layouts/
	}
');
~~~~
To overwrite the default values generated in [FluxService->getDefaultViewConfigurationForExtensionKey()](https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/FluxService.php#L287) you have to use the same index ``.10`` both in ``myprovider/ext_localconf.php`` and in your static TS (``myprovider/Configuration/TypoScript/setup.txt``).

**Comment by NamelessCoder** [comment]
Merged a while back - thanks Georg!

**Comment by blueamerican** [comment]
i tested georgs workaround above but it does't really work for me.
