### ISSUE TITLE
flux:form.object don't work in Page Configuration with Typo3 7.2

### ISSUE THREAD

**Issue by hhjse** [FluidTYPO3/flux#841]
I tried to use flux:form.object in the Page Configuration with Typo3 7.2, but it dosen't work. I can add a new Item, but when I save the Page Configuration, the item will not be saved.

```
...
<flux:form id="col1" label="1 Spalten">
    <flux:form.sheet name="icm" label="Icon Menu">
        <flux:field.input name="class" label="Class"/>
        <flux:form.section name="columns">
            <flux:form.object name="column">
                <flux:field.input label="Title" name="title"/>
                <flux:field.select name="open" label="Open" items="{1:'No', in:'Yes'}"/>
            </flux:form.object>
        </flux:form.section>
    </flux:form.sheet>
 </flux:form>
...
```

**Comment by SvenDeKa** [comment]
doesn't work in 6.2.12 either, for me.

**Comment by NamelessCoder** [comment]
Setting `inherit="0"` on the section, object and any fields in the object should exempt the object and all properties of it from being processed by inheritance. If you can please confirm that this does in fact solve the problem, I'll be happy to consider if perhaps it is time to set the default value of this `inherit` property to `FALSE` as default on all containers and form objects created inside containers which would not affect content but would prevent this issue when used in pages.

**Comment by lars85** [comment]
@NamelessCoder, its just possible to set  inherite="0" for fields... 

for sections and objects it says:
#1237823695: Argument "inherite" was not registered.

Setting it just to the fields does not solve the problem of this issue...

**Comment by NamelessCoder** [comment]
Attribute name is `inherit` - watch out for the typo ;)

**Comment by lars85** [comment]
sorry for the typo - but its still the same with "inherit"

**Comment by NamelessCoder** [comment]
In that case I think we simply lack this attribute on the ViewHelper (and passing it from the ViewHelper to the created Form component instance).

**Comment by lars85** [comment]
sorry, did not work..

What I did:

typo3conf/ext/fiessler_site/Resources/Private/Templates/Page/Default.html
```php
        <flux:form.section name="slides" label="Slides" inherit="0">
            <flux:form.object name="slide" label="Slide" inherit="0">
                <flux:field.file name="file" label="Bild" allowed="jpg, png" maxItems="1" showThumbnails="1" required="1" inherit="0" />
                <flux:field.input name="link" label="Ziel" inherit="0">
                    <flux:wizard.link activeTab="page" />
                </flux:field.input>
            </flux:form.object>
        </flux:form.section>
```

typo3conf/ext/flux/Classes/ViewHelpers/Form/ObjectViewHelper.php->initializeArguments
typo3conf/ext/flux/Classes/ViewHelpers/Form/SectionViewHelper.php->initializeArguments
```php
		$this->registerArgument('inherit', 'boolean', 'If TRUE, the value for this particular field is inherited - if inheritance is enabled by the ConfigurationProvider', FALSE, TRUE);
		$this->registerArgument('inheritEmpty', 'boolean', 'If TRUE, allows empty values (specifically excluding the number zero!) to be inherited - if inheritance is enabled by the ConfigurationProvider', FALSE, TRUE);
```

typo3conf/ext/flux/Classes/ViewHelpers/Form/ObjectViewHelper.php->render
```php
		$object->setInherit($this->arguments['inherit']);
		$object->setInheritEmpty($this->arguments['inheritEmpty']);
```

typo3conf/ext/flux/Classes/ViewHelpers/Form/SectionViewHelper.php->render
```php
		$section->setInherit($this->arguments['inherit']);
		$section->setInheritEmpty($this->arguments['inheritEmpty']);
```

Versions:
TYPO3 CMS: 6.2.14
Flux: 7.2.1
Fludpages: 3.2.3

**Comment by jmverges** [comment]
Thank you @lars85

**Comment by dogawaf** [comment]
I have just encountered this issue. inherit=0 on both section and object resolved my problem.
