### ISSUE TITLE
Copy and Pase, Drag 'n' Drop not working with TYPO3 7.2

### ISSUE THREAD

**Issue by tranimani** [FluidTYPO3/flux#843]
I've tried to setup a 7.2 with actual flux (v 7.2.1) and I can't move any content elements.

Dragging moves the parent flux element with all child elements.
Copying content elements into the flux element wont work neither, sometimes they even disappear in the backend.

**Comment by erredeco** [comment]
do you see them in list view?

**Comment by orangenpresse** [comment]
https://github.com/FluidTYPO3/flux/issues/822
Already fixed

**Comment by tranimani** [comment]
Thanks, the patch worked fine for me on 7.3.

https://github.com/FluidTYPO3/flux/pull/823/files#r31531194
