### ISSUE TITLE
Support for MM_match_fields

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/flux#844]
When you want to store mm relations (e.g. to `sys_category`) in multiple fields you need TCA's `MM_match_fields` which seems not supported by flux at the moment.

**Comment by xf-** [comment]
No high priority. This only helps to put m,ore comp[lex stuff in it (logic) that should be in a extension. In some cases useful of course.

PR are welcome.

**Comment by NamelessCoder** [comment]
I think we should begin considering moving some of the more esoteric TCA options into the "options" attribute of each `flux:form.*` component. We should obviously allow a looooong deprecation or introduce a drop-in compatibility layer.

In the foreseeable future it will become possible to decouple certain parts of Flux and ridding out the TCA-specific options would be a required step on that path.

We may as well start with this one, unless there are objections? We need to establish the procedure and starting with a single option would make that easier.

**Comment by NamelessCoder** [comment]
Added, but is expected to be moved to "options" in the next major/minor of Flux (and deprecated on the component itself).
