### ISSUE TITLE
Workspaces - nested FCE with content container areas doesn't work

### ISSUE THREAD

**Issue by tjungebluth** [FluidTYPO3/flux#846]
Hi everyone,
I'm not sure if I'm addressing the repository right with my bug, since it's the first bug-issue that i have created on Github :) 
I found a bug in workspaces (of course not the live workspace) with flux. 

When I add a fluid content element (FCE) with flux grids as content container and add a second FCE with also grids as container, then I'm not able to add other content elements inside the second FCE. Moved content elements (e.g. via drag&drop) into the second inner FCE, move back to their old position after refreshing the browser, so that doesn't work either.

**Comment by xf-** [comment]
needs testing

**Comment by NamelessCoder** [comment]
Fixed by @thomas-clio - thanks for reporting!
