### ISSUE TITLE
Workspaces - images of copied or translated content deleted after publishing

### ISSUE THREAD

**Issue by tjungebluth** [FluidTYPO3/flux#847]
Hey everybody,
I found a bug in workspaces with images added to fluid content elements (FCE).
I've added an image to a FCE with the viewhelper flux:field:file in a none live workspace. After copying and pasting this FCE, everything is fine in the workspace preview. After publishing the copied FCE, the related image to the flux:field:file is removed from the disc.

**Comment by xf-** [comment]
needs testing

**Comment by NamelessCoder** [comment]
Any feedback on this would be very much appreciated. Suggestions for fixing even more so! For eternal glory, submit a valid pull request ;)

**Comment by NamelessCoder** [comment]
Please report this one to the TYPO3 core bug tracker. It seems to be an issue in general with non-live records being referenced from any type of field in any type of flexform - as such, it's not isolated to nor can it be correctly fixed in Flux (sorry!).

**Comment by cweiske** [comment]
Probably the same as #1171.
