### ISSUE TITLE
FCE can not be created under an existing element

### ISSUE THREAD

**Issue by loco8878** [FluidTYPO3/flux#850]
TYPO3 Setup:
T3 6.2.12
flux 7.2.1 after upgarade from 7.1.2
fluidpages 3.2.3 after upgarade from 3.1.2 
fluidcontent 4.2.2 after upgarade from 4.1.1 

If you put several FCE's on one side, only works the first.

**Comment by bjo3rnf** [comment]
Maybe related to #849

**Comment by xf-** [comment]
works on development.
If you still have an issue, please comment again.

**Comment by xf-** [comment]
Maybe https://github.com/FluidTYPO3/flux/issues/849 - nothing in description
