### ISSUE TITLE
_TRANSFORM_vDEF.vDEFbase - absolute links

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/flux#851]
Could someone tell what `_TRANSFORM_vDEF.vDEFbase` is for and why it saves RTE internal links as absolute links?

**Comment by NamelessCoder** [comment]
...haven't got the foggiest idea; never even seen that before just now. Anyone else?

**Comment by DenisMir** [comment]
Another example from the RTE. I have configured `b` to be remapped to `strong`. This leads to the following content in the database: 

```
    <value index="vDEF">&lt;strong&gt;Bold text&lt;/strong&gt;</value>
   <value index="_TRANSFORM_vDEF.vDEFbase">&lt;b&gt;Bold text&lt;/b&gt;</value>
```

**Comment by jmverges** [comment]
@DenisMir is this Flux related?

**Comment by DenisMir** [comment]
@jmverges To be honest I don't know. If you are sure that it is not flux related feel free to close the issue.

**Comment by jmverges** [comment]
@DenisMir I think it is not related. 

It looks like something related with you RTE configuration. There are plenty of RTE configurations on Internet, you could change your configuration for other and see the results. 

You can take also a look to this: http://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#absrefprefix

If you found what it is, let us know.

**Comment by DenisMir** [comment]
@jmverges Yeah I will let you know.
