### ISSUE TITLE
Styling for icons in list mode for 7 >

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#857]
This is not a bit deal but currently we can see
![currentbehaviouratmaster](https://cloud.githubusercontent.com/assets/2902073/8880474/60122070-3239-11e5-9304-e1a711fe92a3.png)
and we should see
![fix](https://cloud.githubusercontent.com/assets/2902073/8880486/750379ac-3239-11e5-8f9d-472040d77c54.png)

**Comment by xf-** [comment]
i prefer it on front - better usability

**Comment by jmverges** [comment]
Me too. However it is into a btn-group class and there is a rule for round corners and last element:
.btn-group > .btn:last-child:not(:first-child), .btn-group > .dropdown-toggle:not(:first-child) {
    border-bottom-left-radius: 0;
    border-top-left-radius: 0;
}
So we should add to much css for a simple thing. The result just adding float left: 
![metoo](https://cloud.githubusercontent.com/assets/2902073/8880728/14c987a0-323b-11e5-8423-bb78994aa7be.png)
We will not be able btn btn-default and round corners for last element of the group will not be applied.
