### ISSUE TITLE
Inline FAL Field does not work with Workspaces

### ISSUE THREAD

**Issue by Marc-Bauer** [FluidTYPO3/flux#870]
Hi,
if I use:

     <flux:field.inline.fal name="images" multiple="TRUE" maxItems="1" label="LABEL" />

there is a problem with the relation in workspaces. I think (not testet) there is not set the workspaces flag in database. Problem is on creating a new relation.

**Comment by coding46** [comment]
Can't reproduce.

CMS 6.2.14 / 7.4
