### ISSUE TITLE
FCE not sorted in backend dropdown list

### ISSUE THREAD

**Issue by anfuet** [FluidTYPO3/flux#877]
With ``` value="{sorting: 10030}"``` I can sort the FCE. That works fine.
But if a user in the backend form want to change the Fluid Content type there is no sorting for the FCEs.

**Comment by NamelessCoder** [comment]
Confirmed - sorting currently only applies in the new content element wizard. If someone takes this, we are looking at implementing an additional sorting step in both `fluidcontent` and `fluidpages` - in `fluidcontent` we need the elements sorted from the itemsProcFunc that is used. In `fluidpages` we need the templates sorted in he custom user function that renders both of the template selector.

Thanks for reporting, @anfuet! We'll take care of it.

**Comment by xf-** [comment]
We need to add sub-optionGroups, Wizard tab is "missing" and sorting can be applied multiple times.

**Comment by xf-** [comment]
Extensions will be removed and select will be presented like Wizard.

**Comment by NamelessCoder** [comment]
Patch is coming in a few moments.
