### ISSUE TITLE
Bug in BackendConfigurationManager > getPageIdFromRecord… returns wrong page ID

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/flux#884]
flux/Classes/Configuration/BackendConfigurationManager.php, line 110
getPageIdFromRecordIdentifiedInEditUrlArgument

I don't know exactly what the condition should do (the comparison with 0), therefore I submit no patch/pull request,
but I debugged my problem (TYPO3 returned not all of the Typoscript) to this point.
Arguments where:
table: tt_content
id: -40006
command: new
(simple text element added after another content element)
and I got a page ID(!) of 40006 that's simply wrong (the abs value of the content element id).
To fix this I changed the condition to:
```php
(('pages' === $table && 'new' === $command) || 0 === $id)
```
here's the original code:
```php
	protected function getPageIdFromRecordIdentifiedInEditUrlArgument() {
		list ($table, $id, $command) = $this->getEditArguments();
		// if TYPO3 wants to insert a new page, URL argument is already the PID value.
		// if any non-page record is being edited, load it and return the PID value.
		return ('pages' === $table || 'new' === $command || 0 === $id) ? $id : $this->getPageIdFromRecordUid($table, $id);
	}
```

**Comment by NamelessCoder** [comment]
Thanks for the detailed report, Wolfgang. We'll look into this - in your described use case we do want to have `getPageIdFromRecordUid` get called since you are creating content, not pages. And that means we want the condition to evaluate to FALSE when given your inputs!

**Comment by NamelessCoder** [comment]
Hi Wolfgang,

I'll push a patch for this right away so you can check if it works on the `development` branch of Flux when you read this message. If it doesn't fix it (which I expect it will) then please drop a message here and I will reopen the issue ;)

**Comment by yeldiRium** [comment]
This fix turns the problem around for me. Now I can't insert a new content element as the first element on a page, since then the page id is returned as the uid of a not existing previous content element.

My fix is rather amateurish, i suppose. i reverted the fix and found another way.

flux/Classes/Configuration/BackendConfigurationManager.php, line 138
getEditArguments
```php
- $id = (integer) (0 > $id && 'tt_content' === $table) ? $id = -$id : $id;
+ if(0 > $id && 'tt_content' === $table){
+     return array($table, -$id, 'newafter');
+ }
```
flux/Classes/Configuration/BackendConfigurationManager.php, line 114
getPageIdFromRecordIdentifiedInEditUrlArgument
```php
- return ('pages' === $table || 'new' === $command || 0 === $id) ? $id : $this->getPageIdFromRecordUid($table, $id);
+ if('newafter' === $command && 'tt_content' === $table) {
+     return $this->getPageIdFromRecordUid($table, $id);
+ }
+ return ('pages' === $table || 'new' === $command || 0 === $id) ? $id : $this->getPageIdFromRecordUid($table, $id);
```
