### ISSUE TITLE
Edit Icons of custom fce's are missing 

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#885]
Using TYPO3 7.4 all custom elements do not have the edit pen, trash, visible icon in the right top corner. Normal TYPO3 text elements have these options. 

![icons_missing](https://cloud.githubusercontent.com/assets/3888860/9194198/d73767bc-4019-11e5-8098-1dbe4fa4798d.png)

**Comment by robsonrobi** [comment]
May be it is more a fluidcontent problem. Inside the dom , there is a div with a class "fluidcontent-hack". Inside that container, the icons exist, but the div is invisible...

**Comment by robsonrobi** [comment]
Sorry, TYPO3 version was 7.1, in 7.4 everything is fine.

**Comment by xf-** [comment]
:)
