### ISSUE TITLE
Inheritance of settings does not work in backend

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/flux#892]
When I set a checkbox
```
	<flux:field.checkbox label="Something" name="settings.something" />
```
for a page in Page Configuration/Page Configuration - subpages
{settings.something} is available
on this very page, but not on sub pages.
This works in the frontend, but not in the backend.

I would like to show a flux:grid.column based on the checkbox value.

**Comment by DenisMir** [comment]
I can confirm this bug.

**Comment by NamelessCoder** [comment]
You don't mention how you are trying to consume the variables (which section and context) but I assume you are in the same context as described here: https://github.com/FluidTYPO3/fluidpages/issues/276

See my response there for an explanation and alternatives.
