### ISSUE TITLE
content element icon has wrong path similar to #724

### ISSUE THREAD

**Issue by rathgeber2** [FluidTYPO3/flux#897]
its back again, but different :).

Typo3 Version 6.2, Flux 7.2.1, vhs 2.3.3, fluidcontent 4.3.1, fluidpages 3.3.1
Typo3 Version 7.4, Flux 7.2.1, vhs 2.3.3, fluidcontent 4.3.1, fluidpages 3.3.1

happens in fuidbootstraptheme Content Element and Custom Content Elements

```html
<flux:form id="grid3" options="{useTypoScript: 0, group: 'Grid', Fluidcontent: {sorting: 100}, icon: '{f:uri.resource(path: \'Icons/Content/ThreeColumn.png\')}'}">
```

results in 

6.2
```html
<img src="../../..//var/www/html/sfz-chemnitz.de/cms/typo3conf/ext/fluidbootstraptheme/Resources/Public/Icons/Content/ThreeColumn.png" alt="">
```

7.4
```html
    <img src="../../typo3temp/pics/4c5bd83fd5.png" alt="">
```

i tried whit typoscript on 7.4  baseURL = https://xxx/sfz-chemnitz.de/cms7/ but no good results

**Comment by rathgeber2** [comment]
dont know what changed but now it works as expected on 6.2

**Comment by erredeco** [comment]
I'm having this issue in 6.2.15 :S I cleared cache from Install Tool, but without luck

**Comment by andyhausmann** [comment]
I am having this issue as well. Exactly as described above.

**Comment by TrueType** [comment]
The problem stays with 6.2.15. For the form elements preview flux renders the form in a special context unaware of paths or the extension name. At other places the part with uri.resource is rendered in normal TYPO3 environment and it works. It's hard to get around. With version 8 the IconUtility will be dropped. It's deprecated already with v7.x. This may resolve in changes of how flux deals with icons and things may become better.

**Comment by BSelke** [comment]
We've fixed the issue by creating a symlink in the typo3 folder: "ln -s ../../typo3conf ."
And kept the path simple in the template: icon="typo3conf/ext/your_ext/Resources/Public/......"
