### ISSUE TITLE
Translation workflow - Manual copy to a new language - nested elements set to default language

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/flux#899]
I have recognized another error with the translation workflow in combination with flux and its nested elements. The following setup: flux@developement or last release, vhs/fluidcontent/fluidpages @ release version, Typo3 6.2.14 LTS. 

When you got two languages (default and english) and copy a wrapper element (that includes a child element) from the default to the new language manually you get the wrapper element set correctly to the new language but the child element (nested one) stays at the default language. (`sys_language_uid` column is set to 0) 

If you got only one nested child element you can change the language manually but for a lot of nested content this is no practical solution. 

I could use the default button to copy the default content, but I don't want to since it connects the content element from the default language with the content element from the new language via `l18n_parent` which is a behavior I don't want to have.
I want to be able to delete content from the default language without having to worry about the content from the other languages. (the content should not change)

**Comment by NamelessCoder** [comment]
Should be fixed now (plus, you've now got individual localize buttons). If you try this on development branch of Flux (or wait for tomorrow's TER release) and this still fails and you see no solution queued here:

https://github.com/FluidTYPO3/flux/pull/921

Then please let me know and I'll reopen the issue.
