### ISSUE TITLE
flux:grid.column attribute class for backend-grid styling?

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#900]
It would be great to support the class attribute on the viewhelper "flux:grid.column" instead of only supporting static styles using the styles-attribute.

**Comment by xf-** [comment]
You need also inject a CSS in Pagelayout, i think this is far way from our goal.
Also T3 usually adds a lot of classes and we would need to extend them. Feature like drag and drop could end in ugly effects and class changes/bugreports.

@NamelessCoder i would close this issue.

**Comment by NamelessCoder** [comment]
We would like to, but we cannot (with the current implementation of TYPO3's grid feature). We are able to partially support the `style` attribute on columns but it only works for nested content containers, not the page module. Future solutions for the page module may allow setting a class, but we cannot support this until it becomes a core feature (pageTSconfig option in grid configuration, basically) and at that time we will immediately begin supporting it.
