### ISSUE TITLE
Flux virtual Sections adding unattempted new, blank items?!

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#902]
I tried to build a custom FCE with flux/fluid that contains custom image/text-fields for a special layout.

I came up with this code for the flux-section:

```
	<f:section name="Configuration">
		<flux:form
			id="lehrwerke"
			label="Lehrwerke"
			options="{useTypoScript: 0, group: 'Flexible Content', icon: '{f:uri.resource(path: \'Icons/bootstrap/glyphicons_113_justify.png\')}'}"
		>

		<flux:form.sheet name="panel" label="Lehrwerk">
			<flux:field.checkbox name="disabled" label="Disabled" />
			<flux:field.input name="title" label="Title" required="1" />
			<flux:field.input name="subtitle" label="Subtitle" />
			
			<flux:field.inline.fal
				name="image"
				label="Book Cover"
				multiple="FALSE"
				collapseAll="TRUE"
				allowedExtensions="gif,jpg,jpeg,png,pdf"
				showThumbs="1"
				required="1"
			/>

			<flux:field.text
				name="description"
				label="Description"
				enableRichText="TRUE"
			/>
			<flux:field.input name="linkUrl" label="Link">
				<flux:wizard.link />
			</flux:field.input>
			<flux:field.input name="linkText" label="Link Text"/>
			</flux:form.sheet>
		</flux:form>
	</f:section>
```

The result looks fine in first attempt. But poking around with testing and filling in some content-sections I noticed that this always ends up by creating new elements (blank and sometimes partly filled with content like images of other elements) after saving the Content.

**Comment by NamelessCoder** [comment]
Make sure you wipe your DB records' XML definitions in dev setup when you "poke around". When you change names of fields in the Flux structure, the corresponding value is not automatically removed from the database.

If you face issues with FAL relations being duplicated there are other issues currently open dealing exclusively with that and if you find more info that's not already in those issues then we'd appreciate it if you could add it to them ;)
