### ISSUE TITLE
export/import nested CE

### ISSUE THREAD

**Issue by braguzz** [FluidTYPO3/flux#903]
If I try to import a page with nested CEs, for example
Page ----> CE1 (CE2 (content))
(an accordion inside another accordion for example)
content loose his Parent element (tx_flux_parent)	while importing

it shows 
Parent element (tx_flux_parent)	2459 0
(2459 was the old uid of parent)

even if I check  'Force ALL UIDs values'

**Comment by NamelessCoder** [comment]
It's correct that you have to "force all UID values" but you *also* have to "import all relations statically" *and* make sure you exported the elements with those relations statically ;)
