### ISSUE TITLE
Copy & Paste of nested standard typo3 elements - tx_flux_parent not updated

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/flux#904]
We found another bug in the copy & paste process. 

Here is the setup for the initial error:

**Page A**
* Custom Container Element (a)
* One nested standard typo3 table element (b)

**Page B**
* Custom Container Element (c)

Here is what I do: 

* Copy (b)
* Paste (b) in (c)

Result: 

The pasted element (d) does not appear in the page view. If you look in the `tt_content` table you can find element (d) but with an incorrect `tx_flux_parent` value which is set to the `uid` of element (a). (correct would be the `uid` of element (c))

If the editor does not recognize this error and tries to fix the "lost" element you get a followup error: 

* Copy (a)
* Paste (a) in a new Page C

Result:

You get the pasted element (f) with two nested table elements. The reason for the second table element is the "lost" element with its incorrect `tx_flux_parent` which lies around in `tt_content` with a totally different `pid`. This error gets even worse if you got a lot of zombie elements flying around. You paste a container element with one nested content element and the result is a container element with a bunch of child elements which does not make sense in the first place.

These bugs do not happen with custom elements only with the standard typo3 ones and only while pasting in a container element.

These bugs happen with Typo3 6.2 LTS (lastest patch release), flux (@7.2.1), vhs/fluidcontent/fluidpages @latest release.

**Comment by NamelessCoder** [comment]
Fixed in flux @ development. Will be included in next TER release!

**Comment by DenisMir** [comment]
Perfect I will be testing this asap.
