### ISSUE TITLE
drag and drop does not work in upward direction

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/flux#905]
You can't drag and drop elements from flux grid if you do this in upward direction.

![screenshot from 2015-08-28 06 40 18](https://cloud.githubusercontent.com/assets/6602365/9539290/fca0421a-4d4f-11e5-9421-e228ac0ece01.png)

Downward works!

![screenshot from 2015-08-28 06 40 32](https://cloud.githubusercontent.com/assets/6602365/9539295/044cfb2a-4d50-11e5-96bb-825825c33c25.png)

Typo3 6.2.15-dev
Typo3 7.4
Latest FluidTYPO3 development branch

**Comment by smichaelsen** [comment]
I'm also experiencing these difficulties when dragging content around.
