### ISSUE TITLE
registerFluidFlexFormTable not working? 

### ISSUE THREAD

**Issue by janviehweger** [FluidTYPO3/flux#907]
Don't know if it's a bug or just a mistake by myself. I did not found any example for using the `registerFluidFlexFormTable`, so i tried to adopt it from the way i use `registerFluidFlexFormPlugin`.

For my extbase extension `myext` i'm trying to register a table `tx_myext_domain_model_mymodel` like this in `ext_tables.php`:

```
\FluidTYPO3\Flux\Core::registerFluidFlexFormTable(
	'tx_myext_domain_model_mymodel',
	'pi_flexform',
	'EXT:myext/Resources/Private/Templates/Mymodel/Index.html',
	array(),
	'Configuration',
	array(
		'templateRootPath' => 'EXT:myext/Resources/Private/Templates/',
		'partialRootPath' => 'EXT:myext/Resources/Private/Partials/',
		'layoutRootPath' => 'EXT:myext/Resources/Private/Layouts/',
	)
); 
```
in the `columns` section of `typo3conf/ext/myext/Configuration/TCA/tx_myext_domain_model_mymodel.php` i defined the `name` field like this:
```
'name' => array(
			'exclude' => 1,
			'label' => 'Name',
			'config' => array(
				'type' => 'flex',
			),
		),
```
the flux template `ddd` looks like this:
```
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	  xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	  xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">
<head>
	<title>Templates/Mymodel/Index.html</title>
</head>
<body>
<f:layout name="Default" />

<f:section name="Configuration">
	<flux:flexform id="myext.mymodel">
		<flux:flexform.field.input name="name" label="The Name:" clear="true"/>
	</flux:flexform>
</f:section>
</body>
</html>
```
If i now try to create a new record of type `mymodel`in typo3 backend, i get a blank form displaying the error `Data Structure ERROR: No proper configuration!`. ^^ 

Any Ideas?

**Comment by NamelessCoder** [comment]
Everything looks correct except maybe a few things:

* `templateRootPath` etc. are deprecated, use `templateRootPaths = array($path1, $path2)`.
* The "clear" attribute may not be supported; I haven't checked. But it will generate an extra field that is probably not in your schema.
* `flux:form` should have a label or the automatic LLL reference should be filled out. I've observed some strange behaviors when TCA configurations either have no label or use a hardcoded label (but no label is worse).
* The "id" of the form should, if I remember this correctly, always be the name of your SQL table.

I'm pretty sure one or more of these will solve your issue but if not, let me know and I'll reopen!
