### ISSUE TITLE
Get rid of ExtJS in favor of jQuery

### ISSUE THREAD

**Issue by InvisibleKind** [FluidTYPO3/flux#914]
Since TYPO3 version 7.something there is no more ExtJS in BE (in fact it still persists somewhere, but devs cleaning it up), but all is done in jQuery.

From time to time I'm getting this error in console: `Uncaught ReferenceError: Ext is not defined`, which is triggered by [namespace declaration](https://github.com/FluidTYPO3/flux/blob/development/Resources/Public/js/fluxCollapse.js#L10).
Maybe, there are more such places.

In fact the view is not corrupted, but JS error is JS error, which may lead to some not-nice consequences.

TYPO3 7.4
Flux 7.2.1

**Comment by NamelessCoder** [comment]
Confirmed; when 7.x becomes our LTS we can remove all ExtJS resources in one swoop with no negative impact :)

**Comment by NamelessCoder** [comment]
This will come all on it's own and we won't need an issue to remind us. It will be done as part of a larger operation to remove legacy code when we no longer support 6.2 in any way - so that means when the next LTS comes out :)

**Comment by DenisMir** [comment]
@NamelessCoder It would be great if you could write something in the blog (https://fluidtypo3.org/blog.html) about the future roadmap in terms of 6.2 LTS and 7 LTS support of flux. I know that we will have some projects that won't go up to 7 LTS directly and some information would be greatly appreciated. Thank you very much. :+1:
