### ISSUE TITLE
Asset path issue

### ISSUE THREAD

**Issue by xf-** [FluidTYPO3/flux#931]
Error since path change:
Asset "/var/www/typo3conf/ext/fluidpages/Resources/Public/Css/Styles.css" does not exist.

inserted via (inside a partial)
<v:asset.style name="style" path="{f:uri.resource(path: 'Css/Styles.css')}"/>

BTW: Adding extensionName in uri works. Since change uri path is not in your provider.

**Comment by DenisMir** [comment]
I can confirm this issue for 7.2.2. 

I got something like:

```
<v:page.header.link additionalAttributes="{sizes: '152x152'}" rel="apple-touch-icon-precomposed" href="{f:uri.resource(path: 'Favicons/apple-touch-icon-152x152.png')}" />
```

This results in a link like:

`/typo3conf/ext/fluidpages/Resources/Public/Favicons/apple-touch-icon-152x152.png`

**Comment by mrk131324** [comment]
I can confirm the issue and the workaround

**Comment by DenisMir** [comment]
It does also include the custom icons for the custom content elements.

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/dcd6132042e5f8b670f443e6b74398ae8c4db6b6
