### ISSUE TITLE
Link Wizard does trigger field update in TYPO3 7.4

### ISSUE THREAD

**Issue by mrk131324** [FluidTYPO3/flux#933]
Using the link wizard (flux:wizard.link) inside an flux:form.input tag word on the outside, but the link configuration set correctly to the field is not send to the database when saving the record (in my case a page record). It appear that a JS event is missing that happens only if the value in the field in typed by the user not set by JS.

```html
<flux:field.input name="settings.actionButton1.text" label="Button 1 Text" clear="true"/>
<flux:field.input name="settings.actionButton1.link" label="Button 1 Link">
	<flux:wizard.link activeTab="page"/>
</flux:field.input>
```

**Comment by NamelessCoder** [comment]
Hi Martin - that's definitely one for the core's own bug tracker. It would affect any wizard anywhere, not just the ones based on TCEforms arrays created via Flux.

https://forge.typo3.org/projects/typo3cms-core

**Comment by mrk131324** [comment]
I got your point. But the link wizards configured with TCA do work. I suppose that there is a callback necessary for an input field now (in TYPO3 7.4) that the link wizard from flux does not have implemented. 

Furthermore: There is a difference between a TCA field an a field from a flexform (like flux fields). I'm not into the BE JS changes for TYPO3 7.X so I'm not entitled to debug this on my own. 

I know this is an annoying bug, but please at least try to verify it.
