### ISSUE TITLE
Backend broken on Windows after upgrading Flux

### ISSUE THREAD

**Issue by phth** [FluidTYPO3/flux#935]
We use flux 7.2.2 and experienced an exception in TYPO3 (7.4.0) backend and frontend after installing on windows with our usual provider extension and completly new generated provider extensions fresh from EXT:builder:

> #1257246929: "" is not a valid template resource URI. 

This is caused by the generation of the New Content Element Wizard. It hands over a absolute template root path to\FluidTYPO3\Flux\View\ExposedTemplateView->resolveFileNamePath() in the format

> C:/htdocs/**DOCUMENT_ROOT**/typo3conf/ext/**extensionname**/Resources/Private/Templates//Content/**ContentelementName**.html

As the condition in resolveFileNamePath checks for a trailing slash, but as an absolute Windows path starts with the drive name, this check fails and the absolute path will be handed over to GeneralUtility::getFileAbsFileName() wich isn't capable resolving it either without getting it fixed by GeneralUtility::fixWindowsFilePath().
So a possible solution could look like this:

```php
protected function resolveFileNamePath($pathAndFilename) {
	$fixedPathAndFilename = GeneralUtility::fixWindowsFilePath($pathAndFilename);
	return '/' !== $fixedPathAndFilename{0}  ? GeneralUtility::getFileAbsFileName($fixedPathAndFilename) : $pathAndFilename;
}
```

**Comment by Cash2m** [comment]
There is a similar issue with `AbstractProvider::getViewContext()`: When creating a new instance of `TemplatePaths` the returned value of `AbstractProvider::getTemplatePaths()` is used, which are paths with backslashes on Windows. Within `TemplatePaths` they will be thrown into `GeneralUtility::getFileAbsFileName()` again and finally result in one or multiple empty paths.  

I think the main problem is `PathUtility`:

1. when receiving an array with two levels (templateRootPaths, partialRootPaths, layoutRootPaths) the function fails on the first recursion (`in_array($key, self::$knownPathNames)` called with numerical keys)
2. if a directory exists `realpath()` is called and will return paths with backslashes

Time for a Windows patch I guess; I'll try to come up with something on the weekend if nobody beats me to it.

**Comment by NamelessCoder** [comment]
@Cash2m basically did all the work for me. Bonus: we saved 15 lines of code by fixing this...

**Comment by Cash2m** [comment]
Well, that was fast. :+1: Thank you!!
