### ISSUE TITLE
<f:translate> extensionName broken after update to 7.2.2

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/flux#937]
I debugged the Fluid Translate View Helper and as the `extensionName` now I get `Fluidpages` and not my extension name. Should I do something special with version 7.2.2?

On 7.2.1 everything was fine.

Thanks in advance.

**Comment by NamelessCoder** [comment]
@julianxhokaxhiu which context are you using `f:translate` in? I'm assuming the `Main` section of a page template but I need to make sure.

**Comment by julianxhokaxhiu** [comment]
Yes, the Main section :)

**Comment by julianxhokaxhiu** [comment]
Thank you!

**Comment by NamelessCoder** [comment]
Flux 7.2.3 is out - get it while it's hot! ^^
