### ISSUE TITLE
f:translate viewHelper doesn't work in fluidcontent template after updating flux to 7.2.2

### ISSUE THREAD

**Issue by eckonator** [FluidTYPO3/flux#939]
I have updated flux from 7.2.1 to 7.2.2. It's the TER version.

After this update, my translations are no longer displayed in the frontend. For testing, i downgraded flux to 7.2.1 and there it works flawlessly. Is this a bug or do I have to change something in the locallang.xlf file?

**Comment by NamelessCoder** [comment]
Fixed in https://github.com/FluidTYPO3/flux/commit/dcd6132042e5f8b670f443e6b74398ae8c4db6b6 and will be in next TER release. You can roll back to 7.2.2 or use the development branch until then.

**Comment by eckonator** [comment]
Thanks a lot, i use now the development branch and the translations are back again :)

**Comment by NamelessCoder** [comment]
Flux 7.2.3 is out - get it while it's hot! ^^
