### ISSUE TITLE
fluidcontent icons not shown in new CE Wizard after update to flux 7.2.2 / 7.2.3

### ISSUE THREAD

**Issue by eckonator** [FluidTYPO3/flux#943]
I define my Icons as follows:

<pre><code>
options="{
            useTypoScript: 0, 
            group: '{f:translate(key: \'flux.accordion\')}', 
            icon: '{f:uri.resource(path: \'Icons/icon-accordion.gif\')}', 
            Fluidcontent: {sorting: 10}
}"
</code></pre>

But the Icons is not shown after update. Have i anything to change?

**Comment by webdev2027** [comment]
Same problem .. I wrote an stackoverflow-post: http://stackoverflow.com/questions/32851230/typo3-fluidtypo3-missed-flux-icons-for-content-elements-at-typo3-backend

![0ueog](https://cloud.githubusercontent.com/assets/5501876/10231784/f5784546-6884-11e5-80d6-e3b3de49c0ba.gif)

**Comment by derhansen** [comment]
Same problem here. Seems to be a bug in the latest release.

**Comment by braguzz** [comment]
same here..

**Comment by DenisMir** [comment]
I got the same error. Even when not setting a custom icon it fails. The default goes to `typo3/typo3conf/ext/fluidcontent/Resources/Public/Icons/Plugin.svg` which is incorrect.

**Comment by webdev2027** [comment]
Issue solved .. fluidcontent 4.3.3
https://github.com/FluidTYPO3/fluidcontent/pull/290
https://github.com/FluidTYPO3/fluidcontent/blob/development/CHANGELOG.md

**Comment by eckonator** [comment]
I have updated my fluidcontent extension to 4.3.3 and yeah, the icons in the new ce wizard are shown again. Thanks a lot! But there is still a small bug with the path on flux content elements:

If i write the path like this, the icons are shown in new ce wizard, but not in global page overview, where the content elements has a small preview icon, too:

```
<flux:form id="grid2" options="icon: '{f:uri.resource(path: \'Icons/Content/TwoColumn.png\')}'}">
```
If i add a Slash before `{f:uri.resource(path: \'Icons/Content/TwoColumn.png\')}'` i get back the icons in the page overview in Backend, but not in ce wizard anymore.

```
<flux:form id="grid2" options="icon: '/{f:uri.resource(path: \'Icons/Content/TwoColumn.png\')}'}">
```
Can you fix this? Thanks for your great work :)

**Comment by DenisMir** [comment]
The icons are still not shown in Typo3 6.2 LTS with all the latest fluid extensions installed. 

Now the link goes to `../../../../..`. A bit more care with the updates would be great. At the moment every update breaks something different.

**Comment by InvisibleKind** [comment]
After upgrade of TYPO3 from 7.4 to 7.5 icons are not there again.
Reason is in deprecated way of New CE wizard icon registration: [Deprecation: #69057](https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.5/Deprecation-69057-DeprecateIconUtilityAndMoveMethodsIntoIconFactory.html)

> For content element wizard register your icon in IconRegistry::registerIcon() and use the new setting: mod.wizards.newContentElement.wizardItems.*.elements.*.iconIdentifier

Some inspiration can be taken from [css_styled_content revision](https://forge.typo3.org/projects/typo3cms-core/repository/revisions/9bfe22bc32770e4d3099cecb0c95f922954b40d4).

**Comment by NamelessCoder** [comment]
> For content element wizard register your icon in IconRegistry::registerIcon() and use the new setting: mod.wizards.newContentElement.wizardItems.*.elements.*.iconIdentifier

I have a hunch this means we can no longer support custom content icons...

**Comment by InvisibleKind** [comment]
What about such version of `ConfigurationService::buildWizardTabItem()`:
```php
protected function buildWizardTabItem($tabId, $id, $form, $templateFileIdentity) {
	if (TRUE === method_exists('FluidTYPO3\\Flux\\Utility\\MiscellaneousUtility', 'getIconForTemplate')) {
		$icon = MiscellaneousUtility::getIconForTemplate($form);
		$icon = ($icon ? $icon : $this->defaultIcon);
	} else {
		$icon = $this->defaultIcon;
	}
	$description = $form->getDescription();

	$iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Imaging\IconRegistry::class);
	$iconIdentifier = 'fluidcontent-' . $form->getId();
	$iconRegistry->registerIcon($iconIdentifier, \TYPO3\CMS\Core\Imaging\IconProvider\BitmapIconProvider::class, ['source' => $icon]);

	return sprintf('
		mod.wizards.newContentElement.wizardItems.%s.elements.%s {
			iconIdentifier = %s
			title = %s
			description = %s
			tt_content_defValues {
				CType = fluidcontent_content
				tx_fed_fcefile = %s
			}
		}
		',
		$tabId,
		$id,
		$iconIdentifier,
		$form->getLabel(),
		$description,
		$templateFileIdentity
	);
}
```
So, basically registering an icon just before generating PageTS. As an addition some service/method can be added, which detects the appropriate IconProvider: Bitmap or Svg.

**Comment by ervaude** [comment]
@InvisibleKind: You are correct, thats how it needs to be done in 7.5 and later versions of TYPO3.
@NamelessCoder: Custom content icons should be possible nevertheless.

I would also add support for already registered iconIdentifiers and only register new ones if necessary.

**Comment by ervaude** [comment]
For reference:

https://github.com/FluidTYPO3/fluidcontent/issues/295
https://github.com/FluidTYPO3/fluidcontent/issues/296

**Comment by MarvinRudolph** [comment]
Same issue in TYPO3 7.6. The default icon and the automatic loaded icon for this content element don't get rendered. I also overwrote the path with

    options="{icon: '{f:uri.resource(path: \'Icons/Content/Box.svg\')}'}"

The path seems correct because a wrong path shows an red "image-not-found" icon.

**Comment by DenisMir** [comment]
Please add this to the legacy issues! It does not work with Typo3 6.2 LTS as well.

**Comment by fnagel** [comment]
It seems I'm having similar issues. Strange thing is: in my local (Vagrant based VM) it just works as expected, but on the live system there are no icons shown in the new element wizard but some (not all) in the default page module view. 

On the live system the the icon path is prefixed with the absolute path like:
`/html/typo3/typo3conf/ext/my_ext/Resources/Public/Icons/Backend/TwoColumn.png` but `/html/typo3/` shouldn't be there.

TYPO3 7.6.2 (and 7.6.3).

**Comment by kimchristiansen** [comment]
Same here. Working fine on local Server but not on Live Server. Also here it takes the absolute path. 
My Setup: TYPO3 7.6.3, flux 7.3.0, fluidpages: 3.4.0, fluidcontent: 4.4.0.

**Comment by DenisMir** [comment]
Is there some hotfix that allows me to patch flux@7.2.3 (latest 6.2 compatible version) to show at least the default icon? At the moment I am defining no icon at all at `flux:form` and the icon is still broken with the path going to `../../../../..` in the CE wizard. I am working here with the current 6.2.19 LTS release.

**Comment by fnagel** [comment]
@DenisMir You did realize this reference? https://github.com/FluidTYPO3/fluidcontent/pull/334

**Comment by DenisMir** [comment]
@fnagel If you talk about the fix looking like `$icon = PATH_site . ltrim($icon, '/');` - this doesn't work for me either on fluidpages 3.3.1 @ 6.2 LTS (latest patch release).

**Comment by NamelessCoder** [comment]
Fixed by commits to `development` branch about a week ago - thanks everyone for your patience!

**Comment by enr-beck** [comment]
Hi,

i have the same issue with TYPO3 7.6.9 and flux 7.4.0. On my local development machine everything works as expected, but on live server the icon url contains the absolute path of the TYPO3 installation. is the before mentioned fix already contained in the 7.4.0 release or will it be released later?

**Comment by enr-beck** [comment]
Do you have an estimated time for the release of this fix?

**Comment by r12r** [comment]
Hi everyone, 

I have had exact the same problem. Local (vagrant) every thinks works fine, but one the staging/live machines (Hosted at Mittwald), the icons are missed.

My dirty little workaround:

Add the following line at the end of the .htaccess file:
Redirect 301 /html/typo3/typo3conf/ /typo3conf/

Best - Bastian

**Comment by adick** [comment]
Same here, TYPO3 7.6 and I get '/html/typo3/' prepended to the icon path (alos on Mittwald). Seems like the DOCUMENT_ROOT is prepended here for some reason.

**Comment by codemonkey1988** [comment]
In my case (TYPO3 7.6.11 and fluidcontent 4.4.1) the problem was a symlinked document root.

The Icon path for the wizard got generated in \FluidTYPO3\Fluidcontent\Service\ConfigurationService::buildWizardTabItem 
In Line 428, the Path is generated via the realpath-Method. Realpath follows the symlink and returns the real path ^^
I think when TYPO3 tries to render the icon, it removes the absolute path of the icon by comparing it to its PATH_site. But because of the symlink and realpath, the absolute part will stay because the paths are not equal.

When I change the realpath line to `$icon = PATH_site . ltrim($icon, '/');` it worked for me.

I don't know if my change breaks something else, but it works for me :)
In the changelog I found, that the realpath was added in 4.3.3 relating to that ticket https://github.com/FluidTYPO3/fluidcontent/pull/290

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin am Mittwoch, 12. Oktober 2016 unterwegs und nicht in Büro erreichbar.
 
Die Nachricht wird nicht weiter geleitet! In dringenden Angelegenheiten erreichen Sie mich auf dem Mobile oder wenden Sie sich bitte an Hugo Stalder, hugo.stalder@appline.ch. Vielen Dank!

Sonnige Grüsse

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by NamelessCoder** [comment]
Conversation locked; this issue was solved six months ago.
