### ISSUE TITLE
Broken data structure on field name pi_flexform. section without type or vice versa is not allowed

### ISSUE THREAD

**Issue by samowitsch** [FluidTYPO3/flux#944]
Hi. Since TYPO3 7.5 (it was a test :-) this exception "Broken data structure on field name pi_flexform. section without type or vice versa is not allowed" appears in background when editing an fluidcontent element.
There exists also an ticket on typo3 forge (https://forge.typo3.org/issues/70197).

Regards

**Comment by Taskrider** [comment]
Same with flux

if I have a fluidcontent with the "flux.form.section" segment, typo3 give this errormessage. If I remove this from the fluidcontent template, it's working fine, but without the fields I will have.

**Comment by Taskrider** [comment]
I find a little workaround, I hope so.

in flux/Classes/Form/Container/Section.php on line 57;

```
/**
	 * @return array
	 */
	public function build() {
		$structureArray = array(
			'type' => 'array',
			'title' => $this->getLabel(),
			'section' => 1,
			'el' => $this->buildChildren($this->children)
		);
		return $structureArray;
	}
```
Change section => 1

```
/**
	 * @return array
	 */
	public function build() {
		$structureArray = array(
			'type' => 'array',
			'title' => $this->getLabel(),
			'section' => '1',
			'el' => $this->buildChildren($this->children)
		);
		return $structureArray;
	}
```

**Comment by samowitsch** [comment]
I have tried your suggestion and the exception is gone. The backend seems to work normally again.
It seems the TYPO3 core FormHandler is under heavy development ;-) [https://github.com/TYPO3/TYPO3.CMS/commit/b524fc860c96077eabe6adb6fc9d0eab197aea9e]

**Comment by samowitsch** [comment]
https://forge.typo3.org/issues/70197
