### ISSUE TITLE
Text field with RTE doesn't have individual RTE classes

### ISSUE THREAD

**Issue by int-digital** [FluidTYPO3/flux#945]
Adding one RTE field allows me to select individually added RTE classes.
When having multiple RTE fields in one form only the last RTE field has the individual classes.

Typo3 7.4.0, Flux 7.2.1

![2015-10-04 at 11 57](https://cloud.githubusercontent.com/assets/14962396/10267295/29ad9094-6a8f-11e5-9087-1cded5d19847.png)

![2015-10-04 at 11 53](https://cloud.githubusercontent.com/assets/14962396/10267274/9a6ef724-6a8e-11e5-8044-21acffbf36d0.png)

**Comment by xf-** [comment]
no uptodate flux ant TYPO3 (with release of 7.5 we work to fix issues 7.5).

About the issue:
We only everything around and don't touch the RTE. You can pass some simple configurations to RTE and setup RTE in TSConfig.

**Comment by int-digital** [comment]
The RTE configration with individual classes is up and working, but is only added to the last RTE field in the Flux form. The previous fields are configured the same way, but the RTE configuration with individual classes is ignored. Same problem with 7.2.3
