### ISSUE TITLE
Page link wizard does not save selected page id

### ISSUE THREAD

**Issue by jenka13all** [FluidTYPO3/flux#948]
With T3 7.4 and Flux 7.2.3

`<flux:field.input name="linkToPage" label="Link to page"><flux:wizard.link activeTab="page"/></flux:field.input>`

An input field with a page wizard link seems to work when using it in the backend, but, the selected page id does not get saved. In tt_content in the pi_flexform field, the snippet looks like this:

`<field index="linkToPage"><value index="vDEF"/></field>`

However, when in the backend you enter in the page id by hand into the input field and save, the page id gets saved, and it looks like this in tt_content:

`<field index="linkToPage"><value index="vDEF"/>13</value</field>`

This value then naturally shows up in the front end correctly.

**Comment by jmverges** [comment]
Hi @jenka13all,

I can confirm this is happening also in 7.5 version. I'm going to try with master. However I think this is a issue related with TYPO3 Core and not with Flux. I'll keep you informed.

**Comment by mkoehler2911** [comment]
Any solution for that?

**Comment by robsonrobi** [comment]
It is a TYPO3 7 Core bug.

The hidden input value is not updated when using the wizard.
I made a litte fix in the class

typo3/sysext/recordlist/Classes/Browser/ElementBrowser.php

Just add after line 631 the following snipper:
//Fix for updating hidden input field when using wizard
var hiddenInputFieldName = field.getAttribute("name").replace("_hr", ""),
hiddenField =  window.opener.document.' . $this->P['formName'] . '[hiddenInputFieldName];

if (hiddenField) {
  hiddenField.value = input;
 }

Hope it helps you.

**Comment by jenka13all** [comment]
this fix works! Will it be added to TYPO3 Core?

2015-10-07 13:36 GMT+02:00 robsonrobi <notifications@github.com>:

**Comment by NamelessCoder** [comment]
Thanks for reporting the solution, @robsonrobi! I'm afraid I have to ask you or one of the other people involved here, to take this one to the TYPO3 core bug tracker (with or without a contributed fix). Personally I just don't have the time currently to drive another core patch home.

Closed as unrelated to FluidTYPO3, but thank you guys all the same for reporting and solving!

**Comment by cweiske** [comment]
It's TYPO3 core bug [Bug #70602: Page link wizard does not save selected page uid](https://forge.typo3.org/issues/70602) and was fixed in [Bug #69047: Returned value from "form field wizard" in flexform is not stored in database](https://forge.typo3.org/issues/69047), which will be in 7.6 LTS but is not yet in TYPO3 7.5.
