### ISSUE TITLE
flux:field.select is rendering Unknown type

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/flux#955]
TYPO3 master, FluidTYPO3 development

flux:field.select is returning this:
![image](https://cloud.githubusercontent.com/assets/2902073/10349908/5367279c-6d41-11e5-8f88-6146c5a51bd2.png)

Am I crazy or can anyone confirm it?

I also see the same behaviour in FCC for Heading
![image](https://cloud.githubusercontent.com/assets/2902073/10350216/ff84572e-6d42-11e5-9fce-b5c311d7a693.png)

**Comment by jmverges** [comment]
I can confirm Core 86f42bc500afc966c84bcfeddd0a723e109c5cb7 commit broke this

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/43912a3eeb3119bd1387266887b7bc998727a086, caused by FormEngine suddenly changing behavior regarding the secondary configuration option `renderMode` and throwing a rather misleading error message.
