### ISSUE TITLE
Insert record does not work anymore with flux 7.2.3

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/flux#958]
After updateing from flux 7.2.1 to 7.2.3 all "insert record"-entry are not visible in Frontend.
When I reset to flux 7.2.1 the inserted records are visible again.
On my live-system i got in backend a got a message like "no fluid content type selected", but there were no fluid-contents just insert record which inserted text elements.
On my test-system there is no message in backend, unfortunately.
TYPO3 6.2.15 all fluid extension are up to date from TER.

UPDATE: In flux 7.2.2 the insert records are not visible too.

**Comment by flotschn** [comment]
I am having the same issue. Since I am using "Insert Records" the first time, I can not confirm that this was working in a previous version of Flux.

 - Typo3 6.2.15
 - Fluid	6.2.0
 - VHS 2.3.3
 - Flux 7.2.3
 - Fluidpages	3.3.1
 - Fluidcontent	4.3.2
 - fluidbootstraptheme 2.0.0

**Comment by coding46** [comment]
Cannot reproduce this issue.

**Comment by NamelessCoder** [comment]
Restored a while ago - thanks for reporting!
