### ISSUE TITLE
Flux loses element if moved in workspaces

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/flux#961]
In the sequence flux loses content elements:
1. There are two content element types: A container element having a grid for children, and "normal" elements.
2. In LIVE workspace, create a container element, and one child for it.
3. Switch to a draft workspace
4. Create a second container element
5. Move the child of the first container to the second one (either drag & drop or copy & paste)
6. The child is gone (if you used drag & drop you need to reload the view).

Here is a simple provider extension to reproduce this:

https://github.com/JostBaron/fluxworkspacestest

I have some time assigned to check this stuff out - can you tell me where stuff like this is handled?

**Comment by JostBaron** [comment]
There seem to be two parts to this problem.

**First:** The command that is executed in this case is `'version'`. Neither the hook subscriber [here][1] nor the one in the superclass handles that command.

**Second:** Even if one adds the `'version'` command to the `$pasteCommands`, it does not work.In the [`moveRecord()`-method][2], no move placeholder is created, and there is no preexisting one, because the record was not previously versioned.

So it seems there are two things that need to be done here:

 1. Handle `'version'` commands
 2. Make sure that placeholder records are created before they are updated. Not sure whose responsibility this is, but probably the one of EXT:workspaces.

 [1]: https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/ContentProvider.php#L129
 [2]: https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/ContentService.php#L200

**Comment by JostBaron** [comment]
Ok, here is the text from pull request #962, so I can close that:

One problem is, that provider methods are not always executed, because of the caching mechanism that tracks the method calls and limits them to 1 call/request. The problem is that this mechanism only tracks method calls based on these things:

 * method name
 * ID of the modified record
 * Class name of the provider.

But when using workspaces, multiple commands can be issued per request that create the same cache identifier. E.g. in the case described in #961 there are two commands issued:

 * One with `'version'` as command. The provider method of `FluidTYPO3\Flux\Provider\ContentProvider` does nothing for this one, except tracking the method call, in two places: `FluidTYPO3\Flux\Provider\ContentProvider->postProcessCommand`, and also in `FluidTYPO3\Flux\Backend\TceMain->executeConfigurationProviderMethod`.
 * One with `'move'` as command. The provider method should do something on this command, but because the method call has been tracked, nothing happens here.

The pull request prevents tracking of the method call, but this is probably the wrong solution. A proper solution would fix the tracking of method calls.

It seems to work if the command is appended to the cache identifier.

**Comment by JostBaron** [comment]
Another problem is in the [WorkspacesAwareRecordService](https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/WorkspacesAwareRecordService.php#L87-L94):

TYPO3 does not know about the fields introduced by flux that determine a records position, i.e. about `tx_flux_parent` and `tx_flux_column`. So when overlaying a moved content element, these fields are not correctly set in the row. This needs to be fixed, in the function linked above, it needs to check if the overlayed record is a `MOVE_POINTER`, and if so, retrieve the corresponding `MOVE_PLACEHOLDER`-element and overlay those two fields.

I'll make see if I can find the time to make a pull request for this.

**Comment by JostBaron** [comment]
This pull request partly fixes the problem, but changes the provider interface :/

However, the following still doesn't work:

 1. Start with a container element containing two children, all created in live workspace.
 2. Switch to a workspace
 3. Create a new container element besides the first one.
 4. Move one of the children over to the new container. This works after the patch.
 5. Move the second child over to the new container.

**Behaviour**:

 1. If the second child is placed in the first position of the new container, everything is fine.
 2. If it is placed after the first child, it will remain in the old container (maybe refresh view to see that).
 3. If the second child is placed in the first position of the new container, and then moved again after the child element that was first moved, everything is fine again.

The problem in the second case seems to be the combination of negative `$relativeTo` value and the element referenced in `$relativeTo` being a move placeholder. In that case the `tx_flux_parent` and `tx_flux_column` are probably not set correctly.

In the third case, the first move operation seems to set both columns correctly.

I'm now out of time for this, would be nice if someone could continue here.

**Comment by JostBaron** [comment]
I'd like this to stay open, since the pull request only partially fixes the problem.

**Comment by dneuge** [comment]
Disappearance of content elements may be related to #1125. However, I can't currently test workspaces for that issue; if this issue should still be open after fixing #1125, it may be worth re-checking if `WorkspacesAwareRecordService` works correctly.

**Comment by NamelessCoder** [comment]
Solved by recent patches to workspaces compatibility.
