### ISSUE TITLE
plugin.xxx.forms.xxx.enabled =0 doesn't work on different root templates

### ISSUE THREAD

**Issue by joneppie** [FluidTYPO3/flux#966]
If you use plugin.xxx.forms.xxx.enabled =0 with different setting in different root templates, it doesn't work, because the pageId for used typoscript isn't found right. It is a new version of #794. Patch is coming soon.

**Comment by neufeind** [comment]
@joneppie Is that bugfix-branch working for you? Can you then send a pull-request for it?

**Comment by joneppie** [comment]
@neufeind  See https://github.com/FluidTYPO3/flux/pull/967
