### ISSUE TITLE
Page Configuration lost after saving meta data in Typo3 7.4.0

### ISSUE THREAD

**Issue by mkoehler2911** [FluidTYPO3/flux#968]
Typo3 7.4.0
flux 7.2.3 stable
fluidpages 3.3.1 stable
fluidcontent 4.3.2 stable 

I've an image in my page configuration (in use as header image)
```
<f:section name="Configuration">
        <flux:form id="page" label="page">
            <flux:form.option name="icon" value="" />
            <flux:form.option name="group" value="pageContainer" />
            <flux:field.file name="headerImage" label="headerimage" />
            <flux:field.input name="additionalCssClass" label="additionalCssClass" />
        </flux:form>
        <flux:grid>
            <flux:grid.row>
                <flux:grid.column colPos="0" name="Content" label="Content"/>
            </flux:grid.row>
        </flux:grid>
</f:section>
```

I selected and saved an image in my page configuration and my image is available.
In table `pages` xml `tx_fed_page_flexform` looks like
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                
                <field index="headerImage">
                    <value index="vDEF">fileadmin/user_upload/Header_Images/13.jpg</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```

**Now, the bug**:
I wrote some meta tags in my page settings and saved these changes.
My header images disappeared after saving.

Table `pages` xml `tx_fed_page_flexform` after saving:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                
                 <field index="additionalCssClass">
                    <value index="vDEF"/>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```

Any solutions for this?

**Comment by mkoehler2911** [comment]
Update:
There's a difference between the button "save" and "save & close". 
The "save" button will save my content while my content get lost on "save & close".

More strange behavior:
I've 2 elements in my page configuration "headerimage" and "additionalCssClass".
I tried to fill both and save but one of them always get lost after saving (random which one). 
No chance having a page configuration with both elements filled.

Before saving:
![bildschirmfoto 2015-10-16 um 10 41 15](https://cloud.githubusercontent.com/assets/6328720/10537518/a2a63548-73f2-11e5-9f20-ad32879f5fa9.png)

After saving (clicked only "save" button):
![bildschirmfoto 2015-10-16 um 10 42 32](https://cloud.githubusercontent.com/assets/6328720/10537522/a6cdc4ec-73f2-11e5-84dd-3a80cc53e3dd.png)

**Comment by robsonrobi** [comment]
Is there any progress?

**Comment by MajPay** [comment]
Same problem here, but running TYPO3 7.5.0
flux, fluidpages, fluidcontent all at development

Its not possible to save values, everytime something gets lost - maybe thru some broken validation?

**Comment by robsonrobi** [comment]
Saving without changing something ends in loosing all configurations set before.

**Comment by neufeind** [comment]
I couldn't reproduce the problem. Could you maybe retry with current development-branch of the extensions as well as current core-master?

**Comment by xf-** [comment]
This could be somehow to many core changes.
Please try it in LTS release and reopen/comment is necessary.

**Comment by robsonrobi** [comment]
The problem gets solved, when deactivating FLUX SHEET COMPACTING.
