### ISSUE TITLE
[ FAL ] Multiple <flux:field.inline.fal> declaration brings up only ONE "select & upload files"

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/flux#969]
Hi,

I have a strange issue on a FCE that I've done with Flux. Actually I have the backend side divided through <flux:form.sheet> and in anyone of them I have a <flux:field.inline.fal> inside.

```html
<flux:form.sheet name="teaser1" label="Teaser 1">
  <flux:field.inline.fal name="background1" label="Bild" allowedExtensions="gif,jpg,jpeg,png" minItems="0" maxItems="1" />
</flux:form.sheet>
<flux:form.sheet name="teaser2" label="Teaser 2">
  <flux:field.inline.fal name="background2" label="Bild" allowedExtensions="gif,jpg,jpeg,png" minItems="0" maxItems="1" />
</flux:form.sheet>
<flux:form.sheet name="teaser3" label="Teaser 3">
  <flux:field.inline.fal name="background3" label="Bild" allowedExtensions="gif,jpg,jpeg,png" minItems="0" maxItems="1" />
</flux:form.sheet>
```

Actually this brings out that only the first FAL inside the first sheet is going to have the "select & upload files" button, the other two no. Why? Is this a bug? Any suggestion?

Thanks in advance,
Julian

---

![t1](https://cloud.githubusercontent.com/assets/1237070/10542606/9767e72c-7419-11e5-9c16-82d26ca176b8.png)
![t2](https://cloud.githubusercontent.com/assets/1237070/10542605/9766a196-7419-11e5-828d-42ec0f5ef09b.png)
![t3](https://cloud.githubusercontent.com/assets/1237070/10542607/97691cbe-7419-11e5-9d1c-c71ea5c915fa.png)

**Comment by julianxhokaxhiu** [comment]
It would be nice to have a flag also to control if we want to show this button or not also :)

[Proposed fix](https://github.com/FluidTYPO3/flux/blob/master/Classes/ViewHelpers/Field/Inline/FalViewHelper.php#L80):
```php
$component->setForeignSelectorFieldTcaOverride(array(
  'config' => array(
    'appearance' => array(
      'elementBrowserType' => 'file',
      'elementBrowserAllowed' => $allowedExtensions,
      'fileUploadAllowed' => $this->arguments['fileUploadAllowed'] // Nice to have :)
    )
  )
));
```

**Comment by julianxhokaxhiu** [comment]
@NamelessCoder can you help me?

**Comment by NamelessCoder** [comment]
This is a core bug. You can find more information here:

https://github.com/FluidTYPO3/flux/issues/759

PS: regarding proposed feature to support fileUploadAllowed please create a new issue or submit a pull request!
