### ISSUE TITLE
[BUG] flux:grid.column Elements not shown in Module List

### ISSUE THREAD

**Issue by grimmcreative** [FluidTYPO3/flux#970]
I am using flux:grid.column and flux:content.render for several Content Elements so i can put new Content Elements inside of it just like Accordion or Tabs.

But the Content Elements inside of the FCE dont show up in the List Module.
Localisation fails too because of this.

TYPO3 6.2.15
flux latest dev
vhs, fluidcontent, fluidpages = latest TER

**Comment by MichiBeck** [comment]
Same problem with TYPO3 7.5
flux, vhs, fulidcontent and fluidpages latest TER

**Comment by grimmcreative** [comment]
As i see, all the relations are not shown in module list if flux:grid.column is used in FCEs.
Is there any Workaround to get this shown up.

**Comment by grimmcreative** [comment]
Rolling back to FLUX 7.1.2 solves it
Same Problem as in https://github.com/FluidTYPO3/flux/issues/963

**Comment by DenisMir** [comment]
I can confirm this issue. I'm not sure if this is working now as intended.

**Comment by InvisibleKind** [comment]
afaik, this is intended to be so. Check this commit: https://github.com/FluidTYPO3/flux/commit/c0864b4f02ccd7382146e6f15737bf3576d2ed0e
> This class removes all elements with colPos=18181 from db list view to avoid trouble with sorting
containers into child elements.

**Comment by DenisMir** [comment]
But this makes it impossible to use the `insert record` content type with elements from the `18181` col since they are not selectable which is not that nice.

**Comment by NamelessCoder** [comment]
Hi guys,

The newest release of Flux has an extension configuration toggle to enable display of the nested content elements - it also affects the element selection. As the initial commit says, be careful if you enable this - it will re-introduce sorting issues if you use the arrow icons to sort elements.

Thanks for your patience and sorry that it took a while to introduce that feature flag!
