### ISSUE TITLE
Fatal error in cached fluid template

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/flux#971]
After updating flux to current master I get the following fatal: `Parse error: syntax error, unexpected ')' in /var/www/projects/schaefer/ticketshop/typo3temp/Cache/Code/fluid_template/ThemeMinimal_Standard_action_index_f3a40ac4e8f2c108711ff825173ce40e41e2f22e.php on line 62`

Here's the complete cached template file: https://gist.github.com/smichaelsen/eb4efd15cfd6fc569c1e

You can see two syntax problems in line 62 (unmatching brackets) and in line 63 (assignment without right hand value).

Any ideas?

**Comment by robsonrobi** [comment]
We have the same problem, is there any help coming? Would be great.
