### ISSUE TITLE
Wrong column width in backend page-templates

### ISSUE THREAD

**Issue by MarvinRudolph** [FluidTYPO3/flux#972]
Hey,

I created a page-template with the option under "Page Configuration" to choose the position of the sidebar (left/right). It should be rendered with the content in the backend with the ratio of 3:9 (in a 12 columns layout). So the sidebar should be 3 columns and the content 9.
Under the two columns there should be a wide column over all 12 columns for additional content.

My flux.grid looks like this:
```
<flux:grid>
				<flux:grid.row>
					<f:if condition="{PageSettingsSidebarPosition} == 'right'">
						<f:then>
							<flux:grid.column colPos="1" colspan="9" name="Content" label="{f:translate(key: 'content')}" />
							<flux:grid.column colPos="2" colspan="3" name="Sidebar" label="{f:translate(key: 'sidebar')}" />							
						</f:then>
						<f:else>
							<flux:grid.column colPos="2" colspan="3" name="Sidebar" label="{f:translate(key: 'sidebar')}" />
							<flux:grid.column colPos="1" colspan="9" name="Content" label="{f:translate(key: 'content')}" />
						</f:else>
					</f:if>	
				</flux:grid.row>
				<flux:grid.row>
					<flux:grid.column colPos="0" colspan="12" name="ContentLarge" label="{f:translate(key: 'content')}" />
				</flux:grid.row>
			</flux:grid>
```

But it doesn't render like this. The two columns have a ratio of 6/6 (50% each).
I think the style attribute doesn't work for this? I don't know if I misunderstand something with the colspan attribute. When I change the colspan with the developer tools of google chrome then the sizes of the columns are correct.

Thanks in advance!

**Comment by bjo3rnf** [comment]
Hi,

try adding ``style="width: 33.3333%"`` and ``style="width: 66.6666%"`` which works for me.

Cheers
Björn

**Comment by MarvinRudolph** [comment]
Hmm that didn't work for me.

I forgot to say that I am using TYPO3 6.2.13 with the latest version of flux and fluidpages.
Does it only work in TYPO3 7.x?

Thanks.

**Comment by NamelessCoder** [comment]
Setting `style` only works for nested content, for page columns you are supposed to use `colspan` and `rowspan` as the example correctly does.

If this is no longer parsed correctly by the core, then there's a breaking change in the backend layout mechanisms that I'm not aware of (obviously, it's easy to support those even if they are legacy, turning them into the desired bootstrap CSS class). Or it could simply be a bug in the core that for some reason, `rowspan` and `colspan` are no longer respected.

In either case: please report this to the TYPO3 core to learn what got changed and whether or not it can be fixed. It seems a bit excessive to just drop those when they're so easy to support, with or without deprecation warnings...

**Comment by MarvinRudolph** [comment]
The HTML code of these columns in the backend gets rendered correctly I think.

There is the `<colgroup>` with the correct amount (12) of `<col>` and it's width.
The `colspan` of the columns has the amount (3/9) I defined in the template. These columns also have the "t3-gridCell-width[amount]" class.

So I don't think that it is deprecated or something like that but the HTML/CSS doesn't seem to work.
I couldn't find the same problem or any information about that problem. It is a little bit weird.

Maybe the problem is anywhere in the whole template?
Below you can see my "Subpage.html" template. Is there any mistake?

	
	<f:layout name="Page/Standard" />

	
	<f:section name="Configuration">
		<flux:form id="PageSubpage" label="{f:translate(key: 'page.subpage')}" description="{f:translate(key: 'page.subpage.description')}">
			<flux:field.checkbox name="PageSettingsRenderSubmenu" label="{f:translate(key: 'page.settings.renderSubmenu')}" default="1" />

			<flux:field.select name="PageSettingsSidebarPosition" label="{f:translate(key: 'sidebar.position')}" items="{
				0: {0: \"{f:translate(key: 'sidebar.position.left')}\", 1: 'left'},
				1: {0: \"{f:translate(key: 'sidebar.position.right')}\", 1: 'right'}
			}" maxItems="1" />

			<flux:grid>
				<flux:grid.row>
					<f:if condition="{PageSettingsSidebarPosition} == 'right'">
						<f:then>
							<flux:grid.column colPos="1" colspan="9" name="Content" label="{f:translate(key: 'content')}" style="width: 66.6666%" />
							<flux:grid.column colPos="2" colspan="3" name="Sidebar" label="{f:translate(key: 'sidebar')}" style="width: 33.3333%" />							
						</f:then>
						<f:else>
							<flux:grid.column colPos="2" colspan="3" name="Sidebar" label="{f:translate(key: 'sidebar')}" style="width: 33.3333%" />
							<flux:grid.column colPos="1" colspan="9" name="Content" label="{f:translate(key: 'content')}" style="width: 66.6666%" />
						</f:else>
					</f:if>	
				</flux:grid.row>
				<flux:grid.row>
					<flux:grid.column colPos="0" colspan="12" name="ContentLarge" label="{f:translate(key: 'content')}" />
				</flux:grid.row>
			</flux:grid>
		</flux:form>
	</f:section>

	
	<f:section name="Main">
		<section class="main">
			<div class="row">		
				<f:if condition="{PageSettingsSidebarPosition} == 'right'">
					<f:then>
						<div class="columns large-9 medium-9 small-12">
							<v:content.render column="1" />
						</div>
						<div class="columns large-3 medium-3 small-12 hide-for-small-only">
							<f:if condition="{PageSettingsRenderSubmenu}">
								<f:then>
									<f:cObject typoscriptObjectPath="lib.menuSub" />
								</f:then>
							</f:if>
							<v:content.render column="2" />
						</div>
					</f:then>
					<f:else>
						<f:if condition="{PageSettingsSidebarPosition} == 'left'">
							<f:then>
								<div class="columns large-3 medium-3 small-12 hide-for-small-only">
									<f:if condition="{PageSettingsRenderSubmenu}">
										<f:then>
											<f:cObject typoscriptObjectPath="lib.menuSub" />
										</f:then>
									</f:if>
									<v:content.render column="2" />
								</div>
								<div class="columns large-9 medium-9 small-12">
									<v:content.render column="1" />
								</div>
							</f:then>
						</f:if>
					</f:else>
				</f:if>
			</div>
		</section>
		<v:content.render column="0" />
	</f:section>
</div>

Thanks in advance!

**Comment by coding46** [comment]
Can confirm the issue for webkit based browsers. For firefox it works as intended.

**Comment by MarvinRudolph** [comment]
@coding46 Oh wow! Thought it could be the browser but forgot to test it. Thanks! 
So I think it should be reported to the TYPO3 team or is it fixed in 7.x? Someone tested it already?

**Comment by coding46** [comment]
@MarvinRudolph Nope, for now it's not an issue of cms 7 as the rendering for standard backendlayout works right. We're currently investigating the issue.

**Comment by MarvinRudolph** [comment]
@coding46 Sounds good. Thanks!

**Comment by coding46** [comment]
@MarvinRudolph After some more investigation we've found that it's actually a TYPO3 core issue. It's get triggered if the colspan attribute of more than one column is set.

In the last message, I tried 2:1 ratio which caused only one colspan to be set - the 1 got ignored, but I interpreted it wrong as it seemed to be okay.

(It's an webkit browser issue)
