### ISSUE TITLE
Separating templates on two PID-Rootlines

### ISSUE THREAD

**Issue by RobinKemna** [FluidTYPO3/flux#978]
@NamelessCoder 
Hello Claus,

i need to separate 2 templateRootPaths in the same TYPO3[v.6.2.15] System (Fluidcontent[4.3.3], Fluidpages[3.3.1], Flux[7.2.3], VHS[2.2.0] and our own provider extension).

I’ve created the Extension tx_provider with following Configuration:

Configuration/TypoScript/Set1/setup.txt

plugin.tx_provider.view{
	templateRootPaths.10 = Provider/Set1/FlexForms/
	layoutRootPaths.10 = Provider/Set1/Layouts/
	partialRootPaths.10 = Provider/Set1/Partials/
}

Configuration/TypoScript/Set2/setup.txt

plugin.tx_provider.view{
	templateRootPaths.10 = Provider/Set2/FlexForms/
	layoutRootPaths.10 = Provider/Set2/Layouts/
	partialRootPaths.10 = Provider/Set2/Partials/
}

After including the TypoScripts in separated pages, the second configuration gets ignored and the first one is used for both rootlines.

When i use 

Configuration/TypoScript/Set2/setup.txt

plugin.tx_provider.view{
	templateRootPaths.20 = Provider/Set2/FlexForms/
	layoutRootPaths.20 = Provider/Set2/Layouts/
	partialRootPaths.20 = Provider/Set2/Partials/
}

both configurations gets used in the rootlines.

Furthermore i tried out two Extensions and two registered providers, as well as „plugin.x_provider.forms.set2FormID.enable = 0.
However i tried, the extension doesn’t separate the two configurations, both rootlines gets either the first setup, or both setups.

So my question: Is there any possibility at all to solve my problem?

greetings Robin

**Comment by jmverges** [comment]
Hi @RobinKemna,

I can confirm your issue. I will take a look into it.
