### ISSUE TITLE
RTE loses configuration

### ISSUE THREAD

**Issue by Marc-Bauer** [FluidTYPO3/flux#979]
When you insert a new content item as text and purpose "content" the first button used. Does the RTE configuration as it should. However, to use one of the other buttons in the Content column as the RTE configuration is not loaded.

I use TYPO3 7.5 with the latest version of FLUX.

**Comment by NamelessCoder** [comment]
Closing this one since I highly doubt it's relevant anymore. If you still have the problem on more recent versions of TYPO3/Flux feel free to open another issue (and perhaps add a screenshot or two to demonstrate what you mean).
