### ISSUE TITLE
flux TER version not compatible with TYPO3 7.5

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#982]
The latest `flux` version available in TER http://typo3.org/extensions/repository/view/flux is 7.2.3, which is not compatible with TYPO3 7.5.

There should be a TER release of a compatible one since 7.5 has been released already.

(same for `fluidpages`)

**Comment by bwasnie1** [comment]
+1
 I get this error. Even when I download the latest version from git: 
#1257246929: "" is not a valid template resource URI.

**Comment by xf-** [comment]
i close that one - we work for LTS TYPO3 release in sprint this weekend. We will provide a release for 7.6 LTS.

**Comment by NamelessCoder** [comment]
@bwasnie1 Make sure you read all the blog posts about how to upgrade - depending on how old your versions were. Your error should not be related to the TYPO3 core version you use so I have to assume one or more steps were missed during the upgrade.

And please stop by the support channel if you need some more real-time help with it!

**Comment by bwasnie1** [comment]
Thanks, I fixed my problem by cloning the latest releases of fluidcontent, fluidpages, flux and vhs to my typo3 project :)
