### ISSUE TITLE
Add script to update .xsd file

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#987]
It'd be nice if the repository contained a script that I just have to run to get the `Resources/Private/Schemas/Flux.xsd` file updated, using `FluidTYPO3/schemaker`.

Figuring it out all yourself isn't that nice, and having a script assisting is much easier.

**Comment by xf-** [comment]
master should have the current XSD. 
We will not ship a php, sh or bat script to update it.
It is possible to use schemalocation as attribute and your IDE downloads the XSD.

**Comment by cweiske** [comment]
@xf- : I do not mean a script to download new versions of the `.xsd` file, but a script to regenerate the `.xsd` schema file that developers can use after changing the view helper classes.

With such a script I could commit an updated `.xsd` file with my pull requests.

**Comment by NamelessCoder** [comment]
There actually is such a script - but it requires the "schemaker" extension installed in TYPO3. If you install your development extension (vhs or whichever) in a TYPO3 site alongside "schemaker" you can run:

```
./typo3/cli_dispatch.phpsh extbase schema:generate FluidTYPO3.Vhs > typo3conf/ext/vhs/Resources/Private/Schemas/Vhs.xsd
```

Which then regenerates the schema (recreates everything from scratch). When you do this make sure you're cleared the reflection cache which will store the class reflections that include doc comment headers.

This script is "easy enough" - famous last words, I know ;) - that I think we don't need a helper script to do it. The main hinge about it is that it must be installed as a TYPO3 extension but that too is going to change - along with standalone fluid comes a way to regenerate these schemas by adding a composer dependency to any package and using a shipped "bin" command. So it's okay (not great) currently but is going to improve tremendously, quite soon.

If you wish to help with that decoupled schema generation command that's certainly also appreciated - you can see the current working state at https://github.com/NamelessCoder/TYPO3.Fluid.SchemaGenerator - which is currently bound to NamelessCoder/Fluid and not the proper TYPO3Fluid/Fluid that's going to be the future base of TYPO3 Fluid.

**Comment by NamelessCoder** [comment]
NB: if you use a shell variant of emacs etc. you may even be able to use backtick operators to source the XSD directly, e.g. `--schema \`./typo3/cli_dispatch.phpsh extbase schema:generate FluidTYPO3.Vhs\`` or similar (forgive the pseudo, not an emacs user!)

**Comment by cweiske** [comment]
@NamelessCoder: Yes, if I know about schemaker I can use it once I figure out all the parameters, but simply having a build script within the extension would be so much easier for people that do not day-by-day development of the flux extension.

Apart from this, the files generated by schemaker seem to be missing newlines; the diff is about 20k lines. This can't be right, so I thought there is more to do than simply running schemaker.

**Comment by xf-** [comment]
its simply schemaker for a basic file. Some options for older versions exists, but shouldn't be touched.

**Comment by NamelessCoder** [comment]
@cweiske The end goal is to have these schema files be regenerated by a bot that always uses the same method and same settings. I've thought about doing this via gizzle (https://github.com/NamelessCoder/gizzle) and just making a privileged (ssh-authenticated) host that receives a signal when commits are made, then checks if any ViewHelper files were touched, then regenerates and commits+pushes the updated schema.

That's one of the reasons why we currently don't insist that XSD files get updated by users and submitted in pull requests - it's nice when it does get done, but we're perfectly okay regenerating these files manually for a while still.

Regarding the formatting issues there's maybe some different behaviors in the XML library on various platforms or PHP versions - I couldn't tell you which it is. If, like your file does, the output looks suspicious, I would just give up quickly and say "sorry, can't regenerate the XSD for you". However: files that you generate for *local* use don't necessarily have to be well whitespace formatted; it should work all the same - but of course we prefer merging only XSDs that use the same formatting as the originals.

**Comment by cweiske** [comment]
Ok, so we'll wait for the bot.

**Comment by NamelessCoder** [comment]
Yes, I think that's more practical than trying to iron out various PHP/XML client issues. Hopefully there's time for those semi-hobby projects during my winter break!
