### ISSUE TITLE
Broken data structure on field name pi_flexform. section without type or vice versa is not allowed

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#992]
This is the same issue as #944, but a month later with TYPO3 7.5 and current git version of flux and fluidcontent.

I get an error when using a `<flux:form.container>` to group some fields:

>  #1440685208: Broken data structure on field name pi_flexform. section without type or vice versa is not allowed

Example fluidcontent element:

```
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers">

  <f:layout name="Content" />

  <!-- backend form -->
  <f:section name="Configuration">
    <flux:form id="example" options="{group: 'FCE'}">
      <flux:form.container name="settings.name" label="Name">
        <flux:field.input name="firstname" label="First name"/>
      </flux:form.container>

    </flux:form>
  </f:section>

  <!-- frontend output -->
  <f:section name="Main">
    <h2>{settings.name.firstname}</h2>
  </f:section>
</html>
```

**Comment by jmverges** [comment]
Hi @cweiske,

I'm able to reproduce this. We will let you more about this.

**Comment by MarvinRudolph** [comment]
Is there any update?

**Comment by cweiske** [comment]
Still happens with flux `development` branch @02c93e0.

**Comment by NamelessCoder** [comment]
Is this still an issue? As far as I can tell from the source code, each and every "container" type component in Flux is already producing the `'type' => 'array'` TCEforms instruction...

It could possibly also be fixed/prevented by this commit: https://github.com/FluidTYPO3/flux/commit/0aaa843287c175cf506c7693974a633c2e71bd58 - but I'm far from certain that the updated nesting structure is the only cause. Please verify if you can :)

**Comment by NamelessCoder** [comment]
The specific issue with `type=array` missing from the structures is solved. Regression described in https://github.com/FluidTYPO3/flux/issues/1013 is not solved - but not related to this detail.

**Comment by cweiske** [comment]
Yes, this is still a problem and reproducible with the content element code above, TYPO3 7.6.2, flux 7.3.0 and fluidcontent 4.4.0

**Comment by cweiske** [comment]
Also happens with `flux` git branch `development`.

**Comment by manuelbachl** [comment]
@NamelessCoder (finally found the right related Issue) Is this really resolved? For me (just updated to 7.6.5 right now) an error still gets thrown... But it's an other error:

> Broken data structure on field name pi_flexform. section without type or vice versa is not allowed

my (simplyfied) code:

```
<f:section name="Configuration">
    <flux:form
            id="CallToActionBoxes"
            label="Call to action Boxen (nebeneinander)"
            description="Call to actions (Links zu Unterseiten)"
            options="{
                icon: '{f:uri.resource(path: \'Icons/Content/CallToActionBoxes.svg\')}',
                group: 'Globale Elemente',
                Fluidcontent: {
                    sorting: 200
                }
            }"
    >
        <flux:form.container name="cta.first" label="Erste Box">
            <flux:field.input name="title" label="Titel" required="1" />
        </flux:form.container>
        <flux:form.container name="cta.second" label="Zweite Box">
            <flux:field.input name="title" label="Titel" required="1" />
        </flux:form.container>
        <flux:form.container name="cta.third" label="Dritte Box">
            <flux:field.input name="title" label="Titel" required="1" />
        </flux:form.container>
    </flux:form>
</f:section>
```

**Comment by eugine-carmichael-iii** [comment]
I'm still getting an error with code as simple as
```
<flux:form.container name="settings" label="Name">
    <flux:field.input name="firstname" label="First name"/>
    <flux:field.input name="lastname" label="Last name"/>
</flux:form.container>
```
Without the bugfix the error is
```
#1440685208: Broken data structure on field name pi_flexform. section without type or vice versa is not allowed
```
and with the bugfix the error is
```
#1: PHP Warning: Invalid argument supplied for foreach() in /somepath/typo3_src-7.6.5/typo3/sysext/backend/Classes/Form/Container/FlexFormElementContainer.php line 48
```

My setup is:
TYPO3: 7.6.5
flux: 7.3.0
fluidcontent: 4.4.1

Don't know if it's an error on my side or if the issue was not resolved...

**Comment by NamelessCoder** [comment]
Manually picked and merged via https://github.com/FluidTYPO3/flux/pull/1105
